### ISSUE TITLE
GetParticipants

### ISSUE THREAD

**Issue by XaGrid** [pyrogram/pyrogram#100]
When I use in function GetParticipants filter ChannelParticipantsKicked I cant get more then 1000 participants.

```
limit = 200
offset = 0
users = set()
query = [""] + [str(i) for i in range(10)] + list(ascii_lowercase)

for q in query:
	while 1:
		c = app.resolve_peer(channel)
		p = app.send(functions.channels.GetParticipants(c , types.ChannelParticipantsKicked(q) , offset , limit , 0))
		for user in p.users:
			users.add(user.id)
		offset += len(p.users)
		if not p.users:
			break

```

**Comment by delivrance** [comment]
@XaGrid Is it exactly 1000? If so, that means is a server side limitation. I don't have any group with more than 1000 banned users to test this on, but I guess you want to unban them. In that case, just unban the first 1000 first, then the next 1000 will show up.
