### ISSUE TITLE
Support For replying with Thumbnail of documents or video

### ISSUE THREAD

**Issue by pr13260** [pyrogram/pyrogram#1000]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

It would be awesome if we could download or send back thumbnail from a picture/Document or video 
I tried using 
message.reply_document(thumbnail_file_id)
 and 
message.reply_photo(thumbnail_file_id)
But none seem to work

**Comment by delivrance** [comment]
To send thumbnails as photos you have to download them first.

**Comment by pr13260** [comment]
Download just thumbnail or whole video / documents??
