### ISSUE TITLE
get_chat_member() not accepting user ids

### ISSUE THREAD

**Issue by NaziYeeter** [pyrogram/pyrogram#1001]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

[get_chat_member(chat_id,user_id)](https://docs.pyrogram.org/api/methods/get_chat_member#get-chat-member)

get chat member is not fetching user ids 

### Steps to reproduce

get chat member not accepting user ids but works with usernames

### Code example

```python
user_id = 1010101
app.get_chat_member(target, 'GojouSats') #returns a fetched data
app.get_chat_member(target, int(user_id)) # raises an error
```

### Logs

```shell
**context:**

raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: 1339564157'

[400 PEER_ID_INVALID] - The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it 
```
```

**Comment by NaziYeeter** [comment]
```
add_chat_members() #doesnt accept user id only str usernames

check_password() #doesnt accept pure int password
```

**Comment by delivrance** [comment]
> [400 PEER_ID_INVALID] - The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it

See https://docs.pyrogram.org/faq/peer-id-invalid-error.
