### ISSUE TITLE
The latest version does not support Python 3.6.8?

### ISSUE THREAD

**Issue by anylayer** [pyrogram/pyrogram#1002]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

![image](https://user-images.githubusercontent.com/46556817/170214241-0c810649-02e1-4568-abaf-132a11e8469d.png)

### Steps to reproduce

```bash
pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip
pip install pyrogram==pyrogram==2.0.24
pip install git+https://github.com/pyrogram/pyrogram.git
```

**Comment by delivrance** [comment]
This is expected and therefore not an issue. New changes, additions and requirements can be found at https://docs.pyrogram.org/releases/v2.0.
