### ISSUE TITLE
[400 MSG_ID_INVALID] when replying to a channel's message using app.get_discussion_message() 

### ISSUE THREAD

**Issue by Spiffical** [pyrogram/pyrogram#1006]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I wrote a program that polls for new messages from a specific public channel. When certain conditions are met, it should reply to the channel's message. 

My program successfully retrieves the message, the channel ID, and the message ID, and the only part that seems to be an issue is that the message ID it finds isn't valid when trying to send a message with app.get_discussion_message() . The specific error message I get is:

Telegram says: [400 MSG_ID_INVALID] - The message ID used in the peer was invalid (caused by "messages.GetDiscussionMessage")

### Steps to reproduce

1. Set up a message handler to wait for new messages from a specific channel
2. When new message arrives, retrieve message ID and reply to channel's message.

### Code example

```python
from pyrogram import Client
from pyrogram.handlers import MessageHandler

app = Client('my_account', api_id, api_hash)

async def newMessageListener(client, event):
    # Get message event
    new_message_id = event.id
    channel_id = event.chat.id

    m = await client.get_discussion_message(channel_id, new_message_id)
    await m.reply("comment")

test_channel_ids = [-1001704482400, -1001642109073]  # test channels i made
my_handler = MessageHandler(newMessageListener, filters.chat(test_channel_ids))
app.add_handler(my_handler)
app.run()
```

### Logs

```shell
pyrogram.errors.exceptions.bad_request_400.MsgIdInvalid: Telegram says: [400 MSG_ID_INVALID] - The message ID used in the peer was invalid (caused by "
messages.GetDiscussionMessage")
```

**Comment by Spiffical** [comment]
@dedonnodev Jeez, easy solution. Many thanks!

**Comment by kanewi11** [comment]
> Hey there!
> Are you sure that your channel has a discussion group?

Hi, do you happen to know how to check if a group has a group for discussion?
