### ISSUE TITLE
Reconnection does not work properly after upgrading to version 2.0

### ISSUE THREAD

**Issue by vellrya** [pyrogram/pyrogram#1008]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [ ] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Hello, I periodically encounter errors which are logged below.
The server may be losing internet at this time, but I would like to be able to reconnect automatically until the connection is restored. Maybe there are some configuration options for Pyrogram in this case? I believe in version 1.0 reconnection attempts were not limited.
Pyrogram version: 2.0.24 (I checked git, there are no changes in versions .25 and .26 regarding interaction with the network)
Here the similar issue (https://github.com/pyrogram/pyrogram/issues/848) that was closed as completed, but the error is repeated in new versions.

### Steps to reproduce

Probably some networks error

### Logs

```shell
Unable to connect due to network issues: timed out
Unable to connect due to network issues: [WinError 10061] No connection could be made because the target machine actively refused it
Unable to connect due to network issues: [WinError 10061] No connection could be made because the target machine actively refused it
Unable to connect due to network issues: [WinError 10061] No connection could be made because the target machine actively refused it
Unable to connect due to network issues: [WinError 10061] No connection could be made because the target machine actively refused it

// That's all, no more attempts to reconnect.
```

**Comment by delivrance** [comment]
> Unable to connect due to network issues: timed out

> Unable to connect due to network issues: [WinError 10061] No connection could be made because the target machine actively refused it

The error message is self-explanatory; it's clearly a network/server issue, not a library issue.

**Comment by vellrya** [comment]
> > Unable to connect due to network issues: timed out
> 
> > Unable to connect due to network issues: [WinError 10061] No connection could be made because the target machine actively refused it
> 
> The error message is self-explanatory; it's clearly a network/server issue, not a library issue.

Yes, I know that, but how can I deal with this situation? Now I have to manually restart the script, which is why I'm asking if it's possible to configure the number of connection retries in the library.
I think on older versions the connection was restored automatically when the network came up.

**Comment by rayanfer32** [comment]
Pyrogram library stops the program after network retries, how do i catch this and know if my thread died, basically its a critical thread that check for new blocks and sends notification when huge transactions amount is being transferred
source : https://github.com/rayanfer32/nexus-alert-bot

**Comment by Deathcrash** [comment]
и как это решать?

**Comment by vellrya** [comment]
> и как это решать?

Seems like original problem was fixed as part of this issue: https://github.com/pyrogram/pyrogram/issues/1135
Make sure you are using the latest version of Pyrogram, in my case reconnections are now made until the connection is restored. 
`pip install --upgrade pyrogram`
