### ISSUE TITLE
offset_date paramater on get_chat_history() does not work

### ISSUE THREAD

**Issue by satrio-yudhoatmojo** [pyrogram/pyrogram#1017]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

The issue started from running the get_chat_history() that didn't actually get all the messages.  I compared the result with the messages on Telegram App and there were some missing messages.  Therefore, I tried to use the offset_date parameter to retrieve the rest of the missing messages, but it seems the get_chat_history() ignores the offset_date and work the same way as without the offset_date.

Any idea how to solve this?

### Steps to reproduce

1. add offset_date to the get_chat_history()
2. run get_chat_history()

### Code example

```python
from pyrogram import Client

app = Client("message_collector", api_id=api_id, api_hash=api_hash, session_string=session_string)

async def main(channel_name, offset_date):
  await app.start()
  async for message in app.get_chat_history(channel_name, offset_date=offset_date):
    print(message)
  await app.stop()
```

**Comment by delivrance** [comment]
You need to provide an actual [minimal and reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by karaposu** [comment]
> You need to provide an actual [minimal and reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

that example is quite reproducible.
