### ISSUE TITLE
Login succeeded but was immediately banned

### ISSUE THREAD

**Issue by Corray** [pyrogram/pyrogram#102]
I use the following code for test:

#!/usr/bin/python3
#encoding:utf-8
from pyrogram import Client

def phone_code_callback(phone_number):
    code = input("Enter your code:")
    return code  # e.g., "12345"

phone_number = input('Enter your phone:')
app = Client(
    session_name=phone_number,
    phone_number=phone_number,
    phone_code=phone_code_callback,  
    first_name=phone_number,
)

app.start()

print(app.get_me())

app.stop()

and i can login success, but when i try to login on the web,i got this error:

Method: auth.sendCode
Result: {"_":"rpc_error","error_code":400,"error_message":"PHONE_NUMBER_BANNED"}

my phone was banned by telegram.

If there some precautions to use pyrogram?

Please help!

**Comment by Corray** [comment]
Yes ,I got this error.But I don't know the reason, I tried several times and both the numbers banned

**Comment by moelius** [comment]
@Corray Tried with proxy - success. No ban/deactivate/delete. I think this is not a program bug.

**Comment by Corray** [comment]
I had proxy. Now I change my appid and apphash and it works. I logined and  the acc can work. So I think the problem is the appid.@moelius

**Comment by moelius** [comment]
I think it combination of all this things. I tried without proxy new app_id/hash and telegram banned numbers. Now with proxy registered 5 sessions with one id/hash and it's work good.

**Comment by Corray** [comment]
Maybe proxy and appid/hash are both the influence factor。

**Comment by delivrance** [comment]
As @moelius said, there's no bug in the library that makes your accounts immediately vanished. People should understand that Telegram has anti-spam protection systems running to prevent flood and spam, and of course we can't know how do they work exactly.

What we know is that everything we share with Telegram can be used to detect a possible source of spam: virtual/cheap phone numbers, IP addresses (from countries where telegram sees there's a lot of traffic) as well as leaked third-party API keys.

**Comment by asadullokhn** [comment]
The same thing!

**Comment by ColinShark** [comment]
@asadullokhn If you still experience issues, please make a new thread instead of reviving this old thread. It's over TWO YEARS old.

Besides that, please [see what Dan suggested here](https://github.com/pyrogram/pyrogram/issues/102#issuecomment-459982723).
