### ISSUE TITLE
telegram premium Can't upload files bigger than 2000 MiB

### ISSUE THREAD

**Issue by alamia442** [pyrogram/pyrogram#1023]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

1. I have update to latest pyrogram Version: 2.0.29
2. I have  change my telegram upload limit to 4194302000

### Steps to reproduce

Can't upload files bigger than 2000 MiB

**Comment by alamia442** [comment]
I am using bot

**Comment by delivrance** [comment]
Telegram premium benefits currently apply to users only. Premium owners' bots are still regular bots
