### ISSUE TITLE
send_reaction() Not working

### ISSUE THREAD

**Issue by BlackC1over** [pyrogram/pyrogram#1028]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Не ставит реакцию при вызове метода

### Steps to reproduce

Попробуйте проставить реакцию на новое сообщение через декоратор app.on_message и вызов метода send_reaction

### Code example

```python
app.send_reaction(chat_id=message.chat.id, message_id=message.message_id, emoji="🔥")
```

### Logs

```shell
no error
```

**Comment by bezumnui** [comment]
working.

**Comment by BlackC1over** [comment]
> 

mb y show?

**Comment by BlackC1over** [comment]
Sorry, rly working
