### ISSUE TITLE
Handlers does not work when use compose function

### ISSUE THREAD

**Issue by Dolfik1** [pyrogram/pyrogram#1043]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

The message handlers are not working with compose function (even if only one client is used)

### Steps to reproduce

1. Create client
2. Add handler
3. Run client by calling `compose` function.

### Code example

Simple repro:

```python
from pyrogram import Client, compose
from pyrogram.handlers import MessageHandler
import asyncio
import logging

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

apps = [
    Client("acc_bot")
]

async def dump(client, message):
    print(message)

async def main():
    app = apps[0]
    app.add_handler(MessageHandler(dump))

    await compose(apps)

asyncio.run(main())
```

At the same time this code working as expected:
```python
from pyrogram import Client, compose
import pyrogram
from pyrogram.handlers import MessageHandler
import asyncio
import logging

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

apps = [
    Client("acc_bot")
]

async def dump(client, message):
    print(message)

def main():
    app = apps[0]
    app.add_handler(MessageHandler(dump))

    app.run()

main()


```

### Logs

**Comment by delivrance** [comment]
This is not a problem with the library, see https://docs.pyrogram.org/start/invoking#using-asyncio-run.
