### ISSUE TITLE
Total filesize is 0 in download progress function

### ISSUE THREAD

**Issue by ali-safapour** [pyrogram/pyrogram#1048]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I tried to add a queue for downloading files using download_media method, but when I set a progress function and print the current and total sizes, the current downloaded size is shown but the total size is zero. Obviously I can pass the file size to the progress function as an argument but I am curious about the reason of this problem.

![image](https://user-images.githubusercontent.com/91371249/180773845-4445ae47-478a-4831-9595-2a245c91d8ff.png)
![image](https://user-images.githubusercontent.com/91371249/180773686-657db011-3392-4e48-91c8-37b521588e87.png)

### Steps to reproduce

1. create a queue containing the file_id, file_name and user_id.
2. create a downloader coroutine and run it on the current event loop for checking the state of the queue. if the queue is not empty, this coroutine gets the information about the front file in the queue and calls the download_media with the gathered information.

**Comment by delivrance** [comment]
This is expected, because the file_id has no information about the file size.
You can work with message objects instead, that is: `app.download_media(message)`.
