### ISSUE TITLE
Pyrogram has no attribute edited

### ISSUE THREAD

**Issue by Shad0wGlitch** [pyrogram/pyrogram#1049]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

'pyrogram.filters' has no attribute 'edited'
Gives error only in admin plugin handler. 

### Steps to reproduce

Just on the bot.on_message using filters.edited gives error.

### Code example

```python
from pyrogram.raw import functions, types
from pyrogram.types import Message, ChatPermissions
from pyrogram import filters, Client, ContinuePropagation

@Client.on_message(filters.group & ~filters.edited & ~filters.me)
async def admintool_handler(_, message: Message):
    if message.sender_chat:
        if (
            message.sender_chat.type == "supergroup"
            or message.sender_chat.id == db_cache.get(f"linked{message.chat.id}", 0)
        ):
            raise ContinuePropagation
```

### Logs

```shell
plugin.admintool: AttributeError: module 'pyrogram.filters' has no attribute 'edited'
```

**Comment by Clinton-Abraham** [comment]
> ### Checklist
> * [x]  I am sure the error is coming from Pyrogram's code and not elsewhere
> * [x]  I have searched in the issue tracker for similar bug reports, including closed ones
> * [x]  I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version
> 
> ### Description
> 'pyrogram.filters' has no attribute 'edited' Gives error only in admin plugin handler.
> 
> ### Steps to reproduce
> Just on the bot.on_message using filters.edited gives error.
> 
> ### Code example
> ```python
> from pyrogram.raw import functions, types
> from pyrogram.types import Message, ChatPermissions
> from pyrogram import filters, Client, ContinuePropagation
> 
> @Client.on_message(filters.group & ~filters.edited & ~filters.me)
> async def admintool_handler(_, message: Message):
>     if message.sender_chat:
>         if (
>             message.sender_chat.type == "supergroup"
>             or message.sender_chat.id == db_cache.get(f"linked{message.chat.id}", 0)
>         ):
>             raise ContinuePropagation
> ```
> 
> ### Logs
> ```shell
> plugin.admintool: AttributeError: module 'pyrogram.filters' has no attribute 'edited'
> ```

Read this bro.... https://docs.pyrogram.org/releases/v2.0
