### ISSUE TITLE
why am I having trouble uploading a video

### ISSUE THREAD

**Issue by lycorisor** [pyrogram/pyrogram#1053]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I am trying to upload a 200MB video file, and it seems that the upload stops after the progress reaches 6.4%, and the final file is not displayed in the chat

### Steps to reproduce

1.Find a video file about 200MB in size
2.try uploading with the `app.send_video()`

**Comment by lycorisor** [comment]
[5] Retrying "upload.SaveBigFilePart" due to TimeoutError()
[5] Retrying "upload.SaveBigFilePart" due to TimeoutError()
[5] Retrying "upload.SaveBigFilePart" due to Connection lost
[5] Retrying "upload.SaveBigFilePart" due to Connection lost
[5] Retrying "upload.SaveBigFilePart" due to Connection lost
[5] Retrying "upload.SaveBigFilePart" due to Connection lost
[5] Retrying "upload.SaveBigFilePart" due to TimeoutError()
[5] Retrying "upload.SaveBigFilePart" due to TimeoutError()
[5] Retrying "upload.SaveBigFilePart" due to TimeoutError()
[5] Retrying "upload.SaveBigFilePart" due to TimeoutError()
[5] Retrying "upload.SaveBigFilePart" due to Connection lost
[5] Retrying "upload.SaveBigFilePart" due to Connection lost

**Comment by GojouSats** [comment]
Its your connection/internet problems

**Comment by retiolus** [comment]
Hi, I'm having the same issue, and I don't have "internet problems"
![image](https://user-images.githubusercontent.com/65604466/197910412-e3f6a7ca-efe9-461d-915b-cbb0d1e7dbd9.png)

**Comment by buave** [comment]
![screen-gif](https://media.tenor.com/Vv8Z4J0XmzUAAAAC/popopo.gif)

**Comment by AnonymousProDev** [comment]
@retiolus Same issue. Got any solution?

**Comment by lycorisor** [comment]
I achieved this by using the telethon library instead
[Telethon](https://github.com/LonamiWebs/Telethon)

**Comment by lycorisor** [comment]
example
`import asyncio
from telethon.sync import TelegramClient, events

with TelegramClient("my_account", , "") as client:
   client.send_message('me', 'Hello, myself!')
   print(client.download_profile_photo('me'))

   @client.on(events.NewMessage(pattern='(?i).*Hello'))
   async def handler(event):
      print(event.original_update.user_id)
      a = await client.send_file(event.original_update.user_id, path, supports_streaming=True, )
      print(a)

   client.run_until_disconnected()`

**Comment by TorhamDev** [comment]
I have the same issue. and I don't have an internet problem(I ran it on VPS and had the same issue with local). stop upload in 79.2%.

( god I knew that I should use telethon)

**Comment by kxzen-x** [comment]
try to update that msg upload at same time
 i want to uplod 2 gb video how to?
