### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1: unexpected end of data

### ISSUE THREAD

**Issue by moelius** [pyrogram/pyrogram#106]
Hi, check method GetHistory on `vseon` channel.
I have error TimeoutError. And pyrogram error logs `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 202: unexpected end of data`

**Comment by moelius** [comment]
If I change api.core.primitives.string.py it works fine.
```
class String(Bytes):
    @staticmethod
    def read(b: BytesIO, *args) -> str:
        return super(String, String).read(b).decode(errors='replace')

    def __new__(cls, value: str) -> bytes:
        return super().__new__(cls, value.encode())
```

**Comment by moelius** [comment]
strange support of the project =(
For somebody having this issue this monkey patch works:
```
from io import BytesIO

from pyrogram.api.core.primitives.string import String


def read(b: BytesIO, *args) -> str:
    return super(String, String).read(b).decode(errors='replace')


String.read = read
```

**Comment by delivrance** [comment]
Hi, sorry for the late reply but I've been on vacation. I'm going to check this right now.

**Comment by moelius** [comment]
Hi @delivrance, ok, I'l do it tomorrow. There is no time today unfortunately :-(

**Comment by moelius** [comment]
Hi, pull request: https://github.com/pyrogram/pyrogram/pull/114

**Comment by delivrance** [comment]
Merged.
