### ISSUE TITLE
get_chat_members() limits

### ISSUE THREAD

**Issue by TrixiS** [pyrogram/pyrogram#1072]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

get_chat_members() does not return more than 200 members for **a channel** . Is it server-side limitation?

### Steps to reproduce

1. Run the code below

### Code example

```python
import asyncio

from pyrogram.client import Client

SESSION_NAME = "bot"
API_ID = ""
API_HASH = ""

CHAT = "@chat"


async def main():
    async with Client(SESSION_NAME, API_ID, API_HASH) as client:
        members_generator = client.get_chat_members(CHAT)

        count = 0

        async for member in members_generator:  # type: ignore
            count += 1
            print(member.user.username, member.joined_date)

        print(count) # ony 200 members in a channel with more than 4k


asyncio.run(main())
```

### Logs

```shell
200
```

**Comment by delivrance** [comment]
> Is it server-side limitation?

Yes.
