### ISSUE TITLE
Auto restart my sever when using pyrogram v2 client with run

### ISSUE THREAD

**Issue by Mhdrzn** [pyrogram/pyrogram#1079]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Auto restart my server when using pyrogram client method run with a forwarding bot. But in pyrogram v1.4.16 there is no such like this if there any solution to it will close all my process. Please give any answer 

### Steps to reproduce

1 i started my app with pyrogram client.run
2 after bot will run perfectly
3 some time after my bot will restart 

### Code example

```python
from pyrogram import Client

class Bot(Client):
    def __init__(self):
        super().__init__(
            name=**,
            api_id=**,
            api_hash=**,
            bot_token=**,
        )
    
    async def start(self):
       await super().start()
    
    async def stop(self):
        await super().stop()

Bot().run()
```

### Logs

```shell
only see app is restart after 

frequently restart with 3 hours
```

**Comment by Mhdrzn** [comment]
I noticed this issue in others bots

**Comment by delivrance** [comment]
Reconnections are normal and can happen at any time for any reason, but mostly because the server decided so.

**Comment by Mhdrzn** [comment]
Ok i found my own way
