### ISSUE TITLE
can I send telegram code before app.start()

### ISSUE THREAD

**Issue by m3r3lin** [pyrogram/pyrogram#108]
HI 
can I send telegram code before app.start()?

i need  GUI for telegram app and get telegram code from textbox

What should I do?

**Comment by delivrance** [comment]
> can I send telegram code before app.start()?

No you can't. Currently, for new authorizations, `app.start()` takes care of everything (the python code that makes telegram send you the sms code is inside that method). Can you explain more in detail what you need and why `app.start()` can't work for you?
