### ISSUE TITLE
How to check user is already logged in ?

### ISSUE THREAD

**Issue by jakbin** [pyrogram/pyrogram#1096]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

How to check user is already logged in ?

While user try to do something , if user is already logged in , user is good to go else user have to log in.

**Comment by delivrance** [comment]
This kind of questions are better asked on [StackOverflow](https://stackoverflow.com/questions/ask?tags=pyrogram).

**Comment by jakbin** [comment]
@delivrance There is no method in pyrogram to check user is already logged in.

telethon have a method `client.is_authorised()` .
