### ISSUE TITLE
idle() breaks keyboard interrupts

### ISSUE THREAD

**Issue by kitten934** [pyrogram/pyrogram#1098]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Program stops receiving keyboard interrupts after calling idle() and stopping it with an interrupt signal

### Steps to reproduce

1. Call idle()
2. Press ^C
3. You get out of idle() but ^C stops working everywhere else in the program

### Code example

```python
from pyrogram import Client, idle

app = Client("my_account")

app.start()

print("Idle")
idle()
print("\nInterrupt is recieved")

app.stop()

while True:
    try:
        pass
    except KeyboardInterrupt:
        print("Exiting!")
        break
```

### Logs

```shell
python3 main.py
Idle
^C
Interrupt is recieved
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

**Comment by delivrance** [comment]
This is completely unrelated.
