### ISSUE TITLE
continue from incoming updates while bot is off

### ISSUE THREAD

**Issue by Eikosa** [pyrogram/pyrogram#1104]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

When the bot is closed, it ignores all incoming user messages and continues updates after it is turned on, especially when uploading updates to my bot I frequently reset and my users are badly affected

**Comment by evgfilim1** [comment]
Bots doesn't have message history, so they don't get any updates while the connection to telegram servers is closed. Official telegram bot API stores the updates temporarily inside in-app cache to provide this feature. If you want this to be implemented via Pyrogram, there are two ways:
- write something like proxy (like official bot API) which allows you to store and get updates
- update the bot without turning it off (may be too hard, updates may be duplicated, etc.)
- use official bot API (not really a Pyrogram-based solution)

**Comment by Danstiv** [comment]
> Bots doesn't have message history, so they don't get any updates while the connection to telegram servers is closed. Official telegram bot API stores the updates temporarily inside in-app cache to provide this feature.

Yes, bots don't have the ability to get history, but they do have the ability to get missed updates.

My experiment with the local server described [here](https://github.com/pyrogram/pyrogram/issues/263#issuecomment-1025174273) proves that this is possible.

**Comment by clot27** [comment]
> > Bots doesn't have message history, so they don't get any updates while the connection to telegram servers is closed. Official telegram bot API stores the updates temporarily inside in-app cache to provide this feature.
> 
> Yes, bots don't have the ability to get history, but they do have the ability to get missed updates.
> 
> My experiment with the local server described [here](https://github.com/pyrogram/pyrogram/issues/263#issuecomment-1025174273) proves that this is possible.

The thing is, that caching of updates is from bot api side and pyrogram is based on MTProto, so you have to find a manual approach. Also consider closing this as a duplicate of #263

**Comment by Danstiv** [comment]
> The thing is, that caching of updates is from bot api side

The point is that the bot API is a wrapper over MTProto, and you can use the free cloud wrapper from telegram by using api.telegram.org, or you can run this wrapper (local bot server) on your own server.

In both cases, MTProto will eventually be used, and using a local server it's fairly easy to make sure that no caching is happening (the server can't cache anything if it's off, but that doesn't prevent clients from getting missed updates).

**Comment by Eikosa** [comment]
Any suggestions on how I can do this?

**Comment by Danstiv** [comment]
@Eikosa, look here:

[1](https://github.com/pyrogram/pyrogram/pull/580)

[2](https://github.com/pyrogram/pyrogram/pull/731)

[3](https://github.com/Danstiv/cm-assistant/blob/pyrogram-client-state-management/tgbot/pyrogram_client_state_management.py)

**Comment by Eikosa** [comment]
> @Eikosa, look here:
> 
> [1](https://github.com/pyrogram/pyrogram/pull/580)
> 
> [2](https://github.com/pyrogram/pyrogram/pull/731)
> 
> [3](https://github.com/Danstiv/cm-assistant/blob/pyrogram-client-state-management/tgbot/pyrogram_client_state_management.py)

It looks very complicated, what should I do?

**Comment by Danstiv** [comment]
> It looks very complicated, what should I do?

There is currently no working solution, otherwise these issues would be closed 🙂

You probably need to experiment and write some code to handle missed updates.

For small downtimes of a few seconds (for example, restarting the bot), my terrible solution (third link in the comment above) will do.

To handle updates missed for a longer period of time, most likely you need to do something like #580 or #731.

**Comment by clot27** [comment]
> > The thing is, that caching of updates is from bot api side
> 
> The point is that the bot API is a wrapper over MTProto, and you can use the free cloud wrapper from telegram by using api.telegram.org, or you can run this wrapper (local bot server) on your own server.
> 
> In both cases, MTProto will eventually be used, and using a local server it's fairly easy to make sure that no caching is happening (the server can't cache anything if it's off, but that doesn't prevent clients from getting missed updates).

Alright, so you can close this as a duplicate of #263

**Comment by Danstiv** [comment]
I don't have permission to close the issue, someone else should do it.

**Comment by evgfilim1** [comment]
> I don't have permission to close the issue, someone else should do it.

@Eikosa?

**Comment by Eikosa** [comment]
Duplicate of #263
