### ISSUE TITLE
`download` directory should not be created when in_memory=True

### ISSUE THREAD

**Issue by rand-byte** [pyrogram/pyrogram#1105]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

In client.py, function handle_download, the code calls `os.makedirs(directory, exist_ok=True)` even when `in_memory=True`. This breaks when the client has not permissions to create directories.

Proposed fix: Call the path creation only for `in_memory=False`

### Steps to reproduce

1. Download media with in_memory=True under a user that has no permissions to create directories.

**Comment by delivrance** [comment]
Fixed.
