### ISSUE TITLE
Sign Up - [400 PHONE_CODE_INVALID]

### ISSUE THREAD

**Issue by kthenurseone** [pyrogram/pyrogram#1110]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

pyrogram.errors.exceptions.bad_request_400.PhoneCodeInvalid: Telegram says: [400 PHONE_CODE_INVALID] - The confirmation code is invalid (caused by "auth.SignUp")

############# CODE ##############

app = Client(name=number, api_id=api_id, api_hash=api_pass, phone_number=number)

app.connect()

sent_code = app.send_code(phone_number=number)

app.sign_up(phone_number=number, phone_code_hash=sent_code.phone_code_hash, first_name = "dsadadsad", last_name = "asdadsa")

### Steps to reproduce

I followed everything in the website (https://docs.pyrogram.org/api/methods/sign_up?highlight=sign+up#pyrogram.Client.sign_up)
I searched this everywhere but couldn't find any answer and I typed on the telegram group and none answered.

### Code example

```python
app = Client(name=number, api_id=api_id, api_hash=api_pass, phone_number=number)

app.connect()

sent_code = app.send_code(phone_number=number)


app.sign_up(phone_number=number, phone_code_hash=sent_code.phone_code_hash, first_name = "dsadadsad", last_name = "asdadsa")
```

### Logs

```shell
C:\pyrogram>sign_up.py




Code:
Traceback (most recent call last):
  File "C:\pyrogram\sign_up.py", line 37, in <module>
    app.sign_up(phone_number=number, phone_code_hash=app.send_code(phone_number=number).phone_code_hash, first_name = "test", last_name = "223213sad")
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\methods\auth\sign_up.py", line 59, in sign_up
    r = await self.invoke(
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\session\session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\session\session.py", line 331, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.PhoneCodeInvalid: Telegram says: [400 PHONE_CODE_INVALID] - The confirmation code is invalid (caused by "auth.SignUp")
```

**Comment by delivrance** [comment]
Hi. The issue section on GitHub is for issues with the library. This is not an issue with the library, but rather an issue with your usage. If you want to ask Pyrogram related questions you can do so on [StackOverflow](https://stackoverflow.com/questions/ask?tags=pyrogram).

**Comment by kthenurseone** [comment]
> Hi. The issue section on GitHub is for issues with the library. This is not an issue with the library, but rather an issue with your usage. If you want to ask Pyrogram related questions you can do so on [StackOverflow](https://stackoverflow.com/questions/ask?tags=pyrogram).

What do you mean ? It's for errors. If I can't find this error anywhere how can I solve this..

**Comment by mokeLiu** [comment]
> ### Checklist
> * [x]  I am sure the error is coming from Pyrogram's code and not elsewhere
> * [x]  I have searched in the issue tracker for similar bug reports, including closed ones
> * [x]  I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version
> 
> ### Description
> pyrogram.errors.exceptions.bad_request_400.PhoneCodeInvalid: Telegram says: [400 PHONE_CODE_INVALID] - The confirmation code is invalid (caused by "auth.SignUp")
> 
> ############# CODE ##############
> 
> app = Client(name=number, api_id=api_id, api_hash=api_pass, phone_number=number)
> 
> app.connect()
> 
> sent_code = app.send_code(phone_number=number)
> 
> app.sign_up(phone_number=number, phone_code_hash=sent_code.phone_code_hash, first_name = "dsadadsad", last_name = "asdadsa")
> 
> ############# CODE ##############
> 
> ### Steps to reproduce
> I followed everything in the website (https://docs.pyrogram.org/api/methods/sign_up?highlight=sign+up#pyrogram.Client.sign_up) I searched this everywhere but couldn't find any answer and I typed on the telegram group and none answered.
> 
> ### Code example
> ```python
> app = Client(name=number, api_id=api_id, api_hash=api_pass, phone_number=number)
> 
> app.connect()
> 
> sent_code = app.send_code(phone_number=number)
> 
> 
> app.sign_up(phone_number=number, phone_code_hash=sent_code.phone_code_hash, first_name = "dsadadsad", last_name = "asdadsa")
> ```
> 
> ### Logs
> ```shell
> C:\pyrogram>sign_up.py
> 
> 
> 
> 
> Code:
> Traceback (most recent call last):
>   File "C:\pyrogram\sign_up.py", line 37, in <module>
>     app.sign_up(phone_number=number, phone_code_hash=app.send_code(phone_number=number).phone_code_hash, first_name = "test", last_name = "223213sad")
>   File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
>     return loop.run_until_complete(coroutine)
>   File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
>     return future.result()
>   File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\methods\auth\sign_up.py", line 59, in sign_up
>     r = await self.invoke(
>   File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 77, in invoke
>     r = await self.session.invoke(
>   File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\session\session.py", line 361, in invoke
>     return await self.send(query, timeout=timeout)
>   File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\session\session.py", line 331, in send
>     RPCError.raise_it(result, type(data))
>   File "C:\Users\Kerim\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
>     raise getattr(
> pyrogram.errors.exceptions.bad_request_400.PhoneCodeInvalid: Telegram says: [400 PHONE_CODE_INVALID] - The confirmation code is invalid (caused by "auth.SignUp")
> ```

Have you found a way to solve it? I have the same error as yours.

**Comment by mokeLiu** [comment]
> Hi. The issue section on GitHub is for issues with the library. This is not an issue with the library, but rather an issue with your usage. If you want to ask Pyrogram related questions you can do so on [StackOverflow](https://stackoverflow.com/questions/ask?tags=pyrogram).

but there is no answer about it, can you give me a direction about it please?
