### ISSUE TITLE
Adding a feature which will take the user respones

### ISSUE THREAD

**Issue by iamgojoof6eyes** [pyrogram/pyrogram#1112]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

Add a function that when called will make the bot stationary until the user gives it a reply like `bot.ask()` or `bot.get_reply()` something like this like there is one in telethon `get_reply()`.

**Comment by EDM115** [comment]
[PyroMod](https://github.com/usernein/pyromod) is a package that have exactly what you need

**Comment by iamgojoof6eyes** [comment]
Thank you :heart:
