### ISSUE TITLE
I can't use pyrogram with async flask

### ISSUE THREAD

**Issue by Eikosa** [pyrogram/pyrogram#1114]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

it gives this error
Task cb=[run_until_complete..done_cb()]> got Future ._call_check_cancel() at /usr/lib/python3.8/asyncio/futures.py:360]> attached to a different loop

### Steps to reproduce

use pyrogram functions inside flask function and see error
like:
await app.get_messages(chat_id, msg_id)

im using flask[async]

### Code example

```python
@app.route("/")
async def asdfasdfsdaf(chat_id, msg_id):
    return str(await epp.get_messages(chat_id, msg_id))
```

**Comment by prtolem** [comment]
please attach a minimal produced example that can simply be inserted and run with minimal changes.
