### ISSUE TITLE
Markup submodule support

### ISSUE THREAD

**Issue by SKY-ALIN** [pyrogram/pyrogram#1116]
Hello! I want to table a proposal to add a special submodule to generate Telegram-specific markup easily.

## Motivation

A common markdown format that every programmer uses is really simple and doesn’t require special utils for that, but MarkdownV2 and HTML which let include spoiler, strikethrough and other telegram innovations are different. For example, MarkdownV2 also requires to escape 18 characters, and if it’s not, reject the request. This may make the task of designing markup generation for bots that include business logic complicated enough and I suppose it’s better to have a ready-made out-of-the-box solution for this.

### General explanation

I have recently worked on a related challenge and I’m writing this to propose to re-use my solution. It’s the [`telegram-text`](https://github.com/SKY-ALIN/telegram-text) module. The general structure in the context of the `pyrogram` module I propose to implement is the following:

- Add [`telegram-text`](https://github.com/SKY-ALIN/telegram-text) as a dependency (maybe even optional)
- Add support for message objects rendering depending on format mode (Markdown / MarkdownV2 / HTML) inside the message sending function
- Add imports into the `pyrogram` module core to import styles and other needed classes as `from pyrogram import ...`. Or it’s quite pretty to add a separated file (`text.py` or `markup.py` for example) to import as `from pyrogram.text import ...`

### Why [`telegram-text`](https://github.com/SKY-ALIN/telegram-text) module?

- Include all rules for all markup modes
- Almost entirely covered by tests
- Fully documented
- Open to contribute
- Has a few presets and is easily expandable to add new

Example of the module:

```python
from telegram_text import Bold, Italic, Underline

text = Underline(Bold("Bold") + "and" + Italic("italic") + "with underline.")
```

<p align="center">
  <img 
    width="600"
    src="https://telegram-text.alinsky.tech/_images/basic_example_result.jpg"
  />
</p>

### Usage example in the `pyrogram` context

```python
from pyrogram import Client, filters
from pyrogram.text import Spoiler

app = Client("my_account")


@app.on_message(filters.private)
async def hello(client, message):
    await message.reply(Spoiler("Hello from Pyrogram!"))
```

**Comment by delivrance** [comment]
Hi. Thanks for the proposal, but I'm not going to add this.
