### ISSUE TITLE
`@app.on_chat_join_request(filters.chat(TARGET))`  cannot handle the message of people requesting to join the group 

### ISSUE THREAD

**Issue by FANJANDA** [pyrogram/pyrogram#1120]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

After multiple tests, this decorator cannot handle the function of new users requesting to join a group
`@app.on_chat_join_request(filters.chat(TARGET))`

pyrogram.__version__
'2.0.59'

### Steps to reproduce

I want to find out how many people can be invited to join the internal group robot. During the implementation process, many tests have found that this decorator cannot handle the message of people requesting to join the group `@app.on_chat_join_request(filters.chat(TARGET))` 
I also used the method of non decorator, which can't be realized

### Code example

```python
from pyrogram import Client, filters



TARGET = -100123456789
app = Client("my_account")

@app.on_chat_join_request(filters.chat(TARGET))
async def chat_join_request(client, chat_join_request):
    await app.send_message("me", "received a chat_join_request")


app.run()  # Automatically start() and idle()
```

### Logs

```shell
nothing
```

**Comment by delivrance** [comment]
`filters.chat` is currently meant to be used with `on_message` only.

**Comment by Egorrko** [comment]
@delivrance Is that handler works?
I can't call it, when someone make request to join.
But function `app.get_chat_join_requests` works.
