### ISSUE TITLE
MessageEmpty error when sending particular strings

### ISSUE THREAD

**Issue by User087** [pyrogram/pyrogram#1124]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I find that when I try to send a message which is just a text message with nothing but `--------` as text, i.e. it's just a series of hyphens, I get the following error:
```
pyrogram.errors.exceptions.bad_request_400.MessageEmpty: Telegram says: [400 MESSAGE_EMPTY] - The message sent is empty or contains invalid characters (caused by "messages.SendMessage")
```
I found that I was able to send such a message with Telethon and it didn't return that error.
I think an extension of this issue is when I 'get' a `--------` message like the above from another channel, then add some text onto the end of it, then send that newly modified message into a chat, all that appears is the text I added onto the end, not the original `--------` at the beginning. Again, Telethon doesn't produce this problem.
(pointing out Telethon to emphasise it's not just an unresolvable server-side issue)
It's apparent that strings like these are different in some way, e.g. when I try to enter `--------` into the Search bar of the official Telegram app, no results appear. But I can still send such strings as messages in the official app. So what can be done to enable this in Pyrogram?

### Steps to reproduce

Try to send a string of hyphens in a chat

### Code example

```python
from pyrogram import Client

Client.send_message(-1000000000000,'--------')
```

### Logs

```shell
File "C:\...\app.py", line #, in <module>
    Client.send_message(-1000000000000,'--------')
File "C:\...\lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\...python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\...\lib\site-packages\pyrogram\methods\messages\send_message.py", line 126, in send_message
    r = await self.invoke(
  File "C:\...\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "C:\...\lib\site-packages\pyrogram\session\session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "C:\...\lib\site-packages\pyrogram\session\session.py", line 331, in send
    RPCError.raise_it(result, type(data))
  File "C:\...\lib\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageEmpty: Telegram says: [400 MESSAGE_EMPTY] - The message sent is empty or contains invalid characters (caused by "messages.SendMessage")
```

**Comment by User087** [comment]
I think the issue is with the Markdown.parse() method (https://github.com/pyrogram/pyrogram/blob/ef92389ed029ddc4d95e2d234cf3d302774c7e7d/pyrogram/parser/markdown.py#L62). I found that by moving `return await self.html.parse(text)` to the beginning of the definition (line 63) and commenting out the rest of it, the message `--------` would successfully be sent.

**Comment by delivrance** [comment]
This is not an issue, you are using markdown delimiters without text. See https://docs.pyrogram.org/topics/text-formatting.
