### ISSUE TITLE
MessageEmpty error when copying particular strings

### ISSUE THREAD

**Issue by User087** [pyrogram/pyrogram#1125]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Regarding #1124 it may be fair to have to change the `parse_mode` argument when sending such strings, but the issues still remains when copying such a message using `Client.copy_message(...)` or `msg = Client.get_message(...)` and `msg.copy(...)`. I get the MessageEmpty error regardless of what I put for the `parse_mode` argument, even with `parse_mode=enums.ParseMode.DISABLED`. You can try by just sending '--------' in a chat from the app, then copying it with Pyrogram. What's the resolution to that? Preferably copying messages accurately shouldn't require modifying the `parse_mode` anyway.
I'm also finding variable behaviour in this regard. When the message is 'blah --------', copying it to another chat just results in 'blah' without the '--------'. When the message is '**blah** --------', with 'blah' in bold, it does copy in full as '**blah** --------'. This is all with the default parse_mode (haven't tried the others for this variation).

(P.S. for future reference, when we think you've closed an issue prematurely, should we make a comment on the closed issue or open a new one?)

### Steps to reproduce

1. Send '--------' in a chat using the official Telegram app
2. Try copying that message using Pyrogram

### Code example

```python
from pyrogram import Client

#choose a message with text '--------'

#then either
Client.copy_message(...)

#or
msg = Client.get_message(...)
#print(msg)
msg.copy(...)
```

**Comment by User087** [comment]
Maybe the issue is that in the definition of `message.copy()` [here](https://github.com/pyrogram/pyrogram/blob/master/pyrogram/types/messages_and_media/message.py#L2964), the parse_mode argument is read [here ](https://github.com/pyrogram/pyrogram/blob/master/pyrogram/types/messages_and_media/message.py#L2968)but not passed on subsequently when sending a text message [here](https://github.com/pyrogram/pyrogram/blob/master/pyrogram/types/messages_and_media/message.py#L3050). How about just adding `parse_mode=parse_mode` there and in the other instances of `send_message`? Then the problem should be solved when the user passes the argument `parse_mode=enums.ParseMode.DISABLED` to `copy_message()`.

Although, it's not clear what the point of the `parse_mode` argument in `copy_message()` and `message.copy()` is anyway, as if it's copying a message that already exists, then the bold and italic etc formatting is already contained in `Message.entities`, so doesn't that indicate that any apparent formatting syntax remaining in `Message.text` is actually supposed to be part of the message and remain unparsed?

**Comment by delivrance** [comment]
Hi. Thanks for reporting this issue which should now be fixed. You can update and try again.
About the `parse_mode` parameter of both copy methods, this parameter does indeed look unnecessary and will likely be removed in a future release.
