### ISSUE TITLE
Tag v2.0.61 missing on GitHub

### ISSUE THREAD

**Issue by dotlambda** [pyrogram/pyrogram#1141]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

Version 2.0.61 exists on https://pypi.org/project/Pyrogram/#history but not on https://github.com/pyrogram/pyrogram/tags.

**Comment by delivrance** [comment]
Tag added. I should automate the process somehow.
