### ISSUE TITLE
request bot with start parameter

### ISSUE THREAD

**Issue by mokeLiu** [pyrogram/pyrogram#1146]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

I wonder if there is a way I can request a bot by the link like 'https://t.me/bot_name?start=XXX', and get the bot's answer? I've searched for it for a long time, but found no way.to solve it.

I've tried sending to the bot a '/start=XXX' message, but it returns a different answer from the manual operation.

**Comment by mokeLiu** [comment]
If anyone ever find a solution to it, help me please😭.

**Comment by delivrance** [comment]
Hi. The issue section on GitHub is for issues with the library. This is not an issue with the library, but rather a question. If you want to ask Pyrogram related questions you can do so on [StackOverflow](https://stackoverflow.com/questions/ask?tags=pyrogram).
