### ISSUE TITLE
is there anyways to get direct download 'link' in pyrogram 

### ISSUE THREAD

**Issue by CYCNO** [pyrogram/pyrogram#1148]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

is there anyways to get direct download 'link' in pyrogram or any way to get direct download link for telegram files

**Comment by delivrance** [comment]
> is there anyways to get direct download 'link' in pyrogram or any way to get direct download link for telegram files

HTTP links for media messages are not a thing in the protocol.
