### ISSUE TITLE
Invite Link

### ISSUE THREAD

**Issue by mehranj73** [pyrogram/pyrogram#115]
Is there a way that my app can identify a link in a message from other messages and returns it to me?
and how can I use it?

**Comment by zeroone2numeral2** [comment]
Message links are contained in the `entity` attribute of a `Message` object

```py
def return_urls(client, message):
  links = []

  for entity in message.etities:
    if entity.type == 'text_link':
      # inline links, Telegram tells you the actual url
      links.append(entity.url)
    elif entity.type == 'url':
      # normal links, you need to substring the text based on the entity offsets
      link = text[entity.offset:entity.offset + entity.length]
      links.append(url)
  
  message.reply('Found {} urls:\n{}'.format(lens(links), '\n'.join(links)))
```

**Comment by delivrance** [comment]
@mehranj73 @zeroone2numeral2 That's just a typo! "etities" should be "e**n**tities"

**Comment by mehranj73** [comment]
Now I get this error. NameError: name 'text' is not defined

**Comment by zeroone2numeral2** [comment]
@mehranj73 I corrected my example snippet. Anyway all the errors you are getting are something you can fix through basic debugging, I suggest you to try to `print(message)` and see what it contains so you can get an idea of what to do when some exception gets raised. That's more basic python debugging than something related to pyrogram

**Comment by delivrance** [comment]
@mehranj73 If you need more help feel free to join [PyrogramChat](https://t.me/pyrogramchat).
