### ISSUE TITLE
Pyrogram mock-testing incl. load-testing

### ISSUE THREAD

**Issue by JeffreRash** [pyrogram/pyrogram#1152]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

It would be cool to make functionality/tools for testing a bot written with Pyrogram, because this framework gives a huge number of possibilities and bots written in it would be good to check properly

**Comment by delivrance** [comment]
This looks like something a separate library should be doing.
