### ISSUE TITLE
Add the ability to pre-upload a file and send it using high-level methods

### ISSUE THREAD

**Issue by tshipenchko** [pyrogram/pyrogram#1159]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

```python
file = client.upload("FilePath")  # or something other
for chat_id in chat_ids:
    client.send_document(chat_id, file)
```
I mean, without sending document to anywhere.
It was implemented in [telethon](https://docs.telethon.dev/en/stable/modules/client.html#telethon.client.uploads.UploadMethods.upload_file). Look at Example section. 

This feature will be useful in code of send_document, send_audio and etc. In the source code of these methods, most of the code is completely the same.

**Comment by delivrance** [comment]
This already exists, see https://docs.pyrogram.org/api/methods/save_file.
Why do you need it to be in the high-level API instead? Sounds like a XY problem.
