### ISSUE TITLE
TESTED PROXY NOT CONNECTING

### ISSUE THREAD

**Issue by reddere** [pyrogram/pyrogram#1160]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Hello, I am trying to connect my Client() with my rotating proxies. In case this might be helpful, basically how this works is that "inside" of IP and port there are a pool of proxies that rotate at each request. still, it cannot even login to the client because of some authentication error. Read more below.

I am setting my proxy with this pattern:

```
 proxy = {
     "scheme": "http", 
     "hostname": "11.22.33.44",
     "port": 1234,
     "username": "username",
     "password": "password"
 }

app = Client("my_account", proxy=proxy)
```

the problem is that even if I tested the proxy in many projects and requests, Pyrogram still returns me:

`Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required`

The fact is the authentication is prefectly fine, I triple-checked to have written it right and tested it multiple times. Still no way to get it working. Updated to latest version, still not fixed. Thanks to whoever will reply and help

### Steps to reproduce

Client

### Code example

```python
from pyrogram import Client

proxy = {
     "scheme": "http", 
     "hostname": "11.22.33.44",
     "port": 1234,
     "username": "username",
     "password": "password"
}

app = Client("my_account", proxy=proxy)
```

### Logs

```shell
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required
```

**Comment by delivrance** [comment]
The library used underneath is rather finicky about HTTP proxies and only supports CONNECT-based HTTP proxies.
The issue you are having is likely due to this.

**Comment by reddere** [comment]
> The library used underneath is rather finicky about HTTP proxies and only supports CONNECT-based HTTP proxies. The issue you are having is likely due to this.

can you explain a way to fix this? thank you in advance @delivrance !

**Comment by ItzmeSwapy** [comment]
any updates on this?
I am facing the same issue

**Comment by reddere** [comment]
> any updates on this? I am facing the same issue

nah lmao he just decided to not reply/help further. proxies work absolutely fine but they dont just with pyrogram.
