### ISSUE TITLE
Non receiving any messages in groups

### ISSUE THREAD

**Issue by Remerd** [pyrogram/pyrogram#1173]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

No message handlers recived any messages in groups, but in private chat all works.

### Steps to reproduce

1. Start bot
2. Try to handle message in a group
3. Nothing

### Code example

import asyncio
from pyrogram import Client, filters
from pyrogram.handlers import MessageHandler

api_id = 
api_hash = ""

app = Client("my_account_2", api_id, api_hash)

@app.on_message(filters.command(["start"]))
async def help(client, message):
    print(1)
    await message.reply("test1")

async def test(client, message):
    print(1)
    await message.reply("test1")

app.add_handler(MessageHandler(test, filters.command(["check"])))

app.run()

### Logs

```shell

```

**Comment by delivrance** [comment]
Not a Pyrogram issue. It's likely a misconfigured bot, check BotFather.
