### ISSUE TITLE
Redundant calls `Client.fetch_peers`

### ISSUE THREAD

**Issue by kai3341** [pyrogram/pyrogram#1174]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

PR is coming. I see it happens twice and pattern is the same.
Before starting: `Client.fetch_peers` is already [calls](https://github.com/pyrogram/pyrogram/blob/master/pyrogram/methods/advanced/invoke.py#L86) by `Invoke.invoke` and it looks normal

# 1 `GetChat.get_chat`

[This](https://github.com/pyrogram/pyrogram/blob/master/pyrogram/methods/chats/get_chat.py#L70) place looks strange. Variable `r` is got from `invoke`

# 2 `ResolvePeer.resolve_peer`

[This](https://github.com/pyrogram/pyrogram/blob/master/pyrogram/methods/advanced/resolve_peer.py#L92) place looks really strange -- of course it fetches data got from `invoke`, but the most strange that implementation is [asymmetric](https://github.com/pyrogram/pyrogram/blob/master/pyrogram/methods/advanced/resolve_peer.py#L105)

### Steps to reproduce

None

**Comment by delivrance** [comment]
There's no redundant call. `.invoke`'s calls are made specifically on the `users` and `chats` attributes of a response (when available), other places call `fetch_peers` with other arguments (when applicable).

**Comment by kai3341** [comment]
@delivrance and again. There is an `invoke` implementation (all fine here):
```
        r = await self.session.invoke(
            query, retries, timeout,
            (sleep_threshold
             if sleep_threshold is not None
             else self.sleep_threshold)
        )

        await self.fetch_peers(getattr(r, "users", []))
        await self.fetch_peers(getattr(r, "chats", []))

        return r
```

I see `fetch_peers` call just before return
It means calling `fetch_peers` on data returned from `invoke` is redundant

Now looks the PR again

**Comment by delivrance** [comment]
I'll rephrase https://github.com/pyrogram/pyrogram/issues/1174#issuecomment-1358632321: those `fetch_peers` calls outside of `invoke` are not redundant because some responses don't have `chats` or `users` attributes for `invoke`'s `fetch_peers` to execute on. `fetch_peers` is called in those other places with different arguments depending on the response type.

**Comment by kai3341** [comment]
Omg. I see, I agree. Oh, it's too dynamic. Thank you for description.
Maybe it's good idea to add a comment? For example, [asymmetric](https://github.com/pyrogram/pyrogram/blob/master/pyrogram/methods/advanced/resolve_peer.py#L105) implementation looks __very__ strange
Also I tried to ask you in tg chat about it but you did not answer
