### ISSUE TITLE
Passing custom `ainput` as `Client` argument?

### ISSUE THREAD

**Issue by kai3341** [pyrogram/pyrogram#1177]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

Right not `ainput` is uses directly via import. It's OK when you are creating CLI app but not OK when it's GUI app
@delivrance if OK, I'll create the PR

**Comment by delivrance** [comment]
There exist dedicated methods for the login part one should use in case the built-in auth process is not suitable and handle the flow step-by-step. See https://docs.pyrogram.org/api/methods/#authorization.
