### ISSUE TITLE
bot crashes randomly when running

### ISSUE THREAD

**Issue by Eikosa** [pyrogram/pyrogram#1179]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I don't know how, but my bots suddenly stop after working for a long time, I don't know how it happened but I'm sure it's not from my codes, does anyone have this problem? The bad part is, I can't see any error logs.

### Steps to reproduce

1. I do not know.

**Comment by delivrance** [comment]
Low effort issue report with no useful information whatsoever.
