### ISSUE TITLE
Read channel messages (increment "views" counter)

### ISSUE THREAD

**Issue by HIMix** [pyrogram/pyrogram#118]
Hi,
My app (based on pyrogram) is receiving and reading messages from a channels.
I already tried to use different methods such as:
`app.get_history`
`app.get_messages`
also I tried to use raw method `api.functions.channels.ReadMessageContents`

But the views counter in messages do not increments. Why?

**Q: How I can read message from channel so it will count as message view (and increment "views" counter on that message)?**

**Comment by HIMix** [comment]
Very strange...
I already tried this func before but had no results.
But now... hmmm... looks like it works as it should.
Maybe I missed something before.

Anyway, thanks a lot for your answer 👍

**Comment by delivrance** [comment]
> I already tried this func before but had no results.

You probably already viewed the message using an official client sometime before you tried to call the method. Official clients do that automatically as soon as you open a channel or scroll through messages, but is the server that decides whether to actually increase the view or not.

**Comment by Rhetice** [comment]
Hi I have the same problem, what should I do? here is my code: import os
from pyrogram import Client
from pyrogram.raw import functions

API_ID = 123456
API_HASH = 'b0bbb3d8f8bdc96b07502467363350980U9'  
PYROGRAM_SESSIONS_FOLDER = 'Pyrogram' 
CHANNEL_LINK = '@moncanal'  


message_ids = [3]  

pyrogram_sessions = [f for f in os.listdir(PYROGRAM_SESSIONS_FOLDER) if f.endswith('.session')]

for pyrogram_session in pyrogram_sessions:
    session_path = os.path.join(PYROGRAM_SESSIONS_FOLDER, pyrogram_session.replace('.session', ''))

    with Client(session_path, api_id=API_ID, api_hash=API_HASH) as app:
     
        for message_id in message_ids:
            get_views_request = functions.messages.GetMessagesViews(peer=CHANNEL_LINK, id=[message_id], increment=True)
            app.send(get_views_request)
