### ISSUE TITLE
Markdown is not working properly

### ISSUE THREAD

**Issue by Mahesh0253** [pyrogram/pyrogram#1181]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When I'm trying to send below text with markdown formatting, I'm getting `Unclosed tags: <pre>` warning and some part text is missing in sent message.

**Original text -** 
```
**EVAL**: ```from config import API_ID

print(API_ID)```

**OUTPUT**:
```1234```
```

**Sent message -**

**EVAL:** 

```print(API_ID)```

**OUTPUT:**

### Steps to reproduce

Please run below given code to reproduce the issue.

### Code example

```python
import asyncio
from pyrogram import Client, enums


text = """**EVAL**: ```from config import API_ID

print(API_ID)```

**OUTPUT**:
```1234```"""

async def main():
    async with Client("my_account") as app:
        await app.send_message("me", text, parse_mode=enums.ParseMode.MARKDOWN)


asyncio.run(main())
```

### Logs

```shell
10:41:01 AM - 134 - pyrogram.parser.html - html - WARNING - Unclosed tags: <pre> (x1)
```

**Comment by delivrance** [comment]
This is expected behavior.
Three backticks are for multi-line texts and the first line is for the code language, which is not part of the content.

Either use it this way (first line empty):
<pre>
```
pre-formatted
  fixed-width
   code block
```
</pre>

or:

<pre>
```python
pre-formatted
  fixed-width
   code block
with language
```
</pre>

or use single backticks for single lines: `` `line` ``.

More info at https://docs.pyrogram.org/topics/text-formatting.
