### ISSUE TITLE
"on_deleted_messages" handler does not work in groups/channels

### ISSUE THREAD

**Issue by JailSeed** [pyrogram/pyrogram#1188]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Hello! [Pyrogram's documentation](https://docs.pyrogram.org/api/handlers#pyrogram.handlers.DeletedMessagesHandler) says that this handler can handle deleted messages coming from any chat (private, group, channel), but it's not actually true. It works only for private. 

Sorry for the opened issue if I have misunderstood something :)

### Steps to reproduce

1. Invite a bot to a group/channel and grant admin privileges to it
2. Send a message to the group/channel
3. Delete the message from the group/channel

### Code example

```python
from pyrogram import Client

Bot = Client(NAME, APP_ID, APP_HASH, bot_token=BOT_TOKEN)


@Bot.on_deleted_messages()
async def received_msg(bot, m):
    for msg in m:
        print(f'Message with ID {msg.id} was deleted')


@Bot.on_message()
async def deleted_msg(bot, m):
    print(f'Received new message with ID {m.id}')


Bot.run()
```

### Logs

```shell
Output in case chat is private:

Received new message with ID 1
Message with ID 1 was deleted

Output in case chat is group/channel:

Received new message with ID 1
```

**Comment by delivrance** [comment]
Message deleted updates could be not sent when irrelevant for the client, this is a server behavior.
