### ISSUE TITLE
get sent messages after given date

### ISSUE THREAD

**Issue by Pranav108** [pyrogram/pyrogram#1189]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

I didn't find any way to get messages which are sent after a given date with `get_chat_history`.

As an example ,how can get chat history of all the message sent in last two days?

I am searching for a feature which works opposite of `offset_date` in `get_chat_history`.

**Comment by delivrance** [comment]
The API only supports getting messages before an offset date, not after.
You could probably get newer messages than the offset date by fiddling with the other offset arguments.
