### ISSUE TITLE
Auth key creation failed. Let's try again: KeyError(225735525,)

### ISSUE THREAD

**Issue by deadkrolik** [pyrogram/pyrogram#12]
I've got this error when run the code:

```python
from pyrogram import Client

client = Client(session_name="example")
client.start()
```

I also have config.ini with correct api_id and api_hash from telegram site.

It's the log:

```
Auth key creation failed. Let's try again: KeyError(225735525,)
Auth key creation failed. Let's try again: KeyError(225735525,)
Auth key creation failed. Let's try again: KeyError(225735525,)
Auth key creation failed. Let's try again: KeyError(225735525,)
Auth key creation failed. Let's try again: KeyError(225735525,)
Traceback (most recent call last):
  File "/home/.../tgtg/venv/lib/python3.5/site-packages/pyrogram/client/client.py", line 314, in load_session
    with open("{}.session".format(session_name), encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'example.session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.../tgtg/go.py", line 4, in <module>
    client.start()
  File "/home/.../tgtg/venv/lib/python3.5/site-packages/pyrogram/client/client.py", line 104, in start
    self.load_session(self.session_name)
  File "/home/.../tgtg/venv/lib/python3.5/site-packages/pyrogram/client/client.py", line 318, in load_session
    self.auth_key = Auth(self.dc_id, self.test_mode, self.proxy).create()
  File "/home/.../tgtg/venv/lib/python3.5/site-packages/pyrogram/session/auth.py", line 252, in create
    raise e
  File "/home/.../tgtg/venv/lib/python3.5/site-packages/pyrogram/session/auth.py", line 94, in create
    res_pq = self.send(functions.ReqPq(nonce))
  File "/home/.../tgtg/venv/lib/python3.5/site-packages/pyrogram/session/auth.py", line 74, in send
    return self.unpack(response)
  File "/home/.../tgtg/venv/lib/python3.5/site-packages/pyrogram/session/auth.py", line 67, in unpack
    return Object.read(b)
  File "/home/.../tgtg/venv/lib/python3.5/site-packages/pyrogram/api/core/object.py", line 32, in read
    return Object.all[int.from_bytes(b.read(4), "little")].read(b, *args)
KeyError: 225735525
```

What did I do wrong?

**Comment by delivrance** [comment]
Hi there, you did nothing wrong, but I'm not able to reproduce this on my machine. To see what's going on update Pyrogram using `pip install --upgrade git+https://github.com/pyrogram/pyrogram.git@issue-12` and show me the full logs again. Also tell me where you are running it: OS, Python version.

**Comment by deadkrolik** [comment]
Ooops, may be it's our vpn+proxy:

```
>>> b'TTP/1.0 400 Bad Request\r\nServer: squid/2.6.STABLE21\r\nDate: Mon, 29 Jan 2018 10:49:53 GMT\r\nContent-Type: text/html\r\nContent-Length: 1162\r\nExpires: Mon, 29 Jan 2018 10:49:53 GMT\r\nX-Squid-Error: ERR_INVALID_REQ 0\r\nX-Cache: MISS from openvpn.serv\r\nX-Cache-Lookup: NONE from openvpn.serv:3121\r'
```

**Comment by delivrance** [comment]
Yep. I've extensively tested Pyrogram with proxies, but let me know if you think it should work by kindly opening a new issue. If it works with another proxy there's definitely something wrong with yours. Thanks.

**Comment by deadkrolik** [comment]
Do I have a possibility to change datacenter ip and port? Because I have recommended ip/port on telegram panel. When I changed in connection.py:

```python
self.address = (ipv4, 80)
```

to 

```python
self.address = ("149.154.167.50", 443)
```

I successfully logged. It's not a proxy like package expects, it's just transparent and caching proxy in our office. I can't bypass it without modifying source code.

**Comment by delivrance** [comment]
The recommended ip/port you see on your panel are only meaningful for client developers, the DC IP changes depending on where the user is located - Pyrogram automatically manages this. Port 80 and 443 offer the exact same service, but I found Telegram switching off port 443 rather often, that's why I'm using port 80. You don't really have to mess with this.

If you can confirm `self.address = (ipv4, 443)` works for you **without** changing the IP, then I might think of switching back to port 443 as default.

But again, I think is just your proxy misbehaving and we really should discuss this in another issue you can open.
