### ISSUE TITLE
Telegram says: [401 USER_DEACTIVATED_BAN] but it's not

### ISSUE THREAD

**Issue by budni** [pyrogram/pyrogram#1200]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When i try to log in into account via pyrogram I recieve 
pyrogram.errors.exceptions.unauthorized_401.UserDeactivatedBan: Telegram says: [401 USER_DEACTIVATED_BAN] - The user has been deleted/deactivated (caused by "updates.GetState")

But this account works on my phone and laptop. I've tried to log in via pyrogram from server and from local machine. Tested on 4 accounts

### Steps to reproduce

1. Create api_id/api_hash
2. Try to start app: app = await app.start()
3. recieve that your account is deleted

### Code example

```python
from pyrogram import Client
import asyncio

async def main():
    app = Client(api_id, api_hash, tel, proxy)
    app = await app.start()

asyncio.run(main())
```

### Logs

```shell
Traceback (most recent call last):
  File "/root/typer_bot/set_accs.py", line 99, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/typer_bot/set_accs.py", line 88, in main
    await get_tgs(sh, working_directory)
  File "/root/typer_bot/set_accs.py", line 34, in get_tgs
    name, username = await set_acc(app, line[tel_col], working_directory)
  File "/root/typer_bot/set_accs.py", line 51, in set_acc
    app = await app.start()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/utilities/start.py", line 68, in start
    await self.invoke(raw.functions.updates.GetState())
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.unauthorized_401.UserDeactivatedBan: Telegram says: [401 USER_DEACTIVATED_BAN] - The user has been deleted/deactivated (caused by "updates.GetState")
```

**Comment by delivrance** [comment]
This is a server behavior/decision, not a client library issue.

**Comment by budni** [comment]
> This is a server behavior/decision, not a client library issue.

It's not so, because it log in works fine with Telethon

**Comment by delivrance** [comment]
If you are really sure about that it might be a server issue (unlikely, but nonetheless possible). Definitely not a client issue since the error clearly says what it says and comes directly from the server.

**Comment by budni** [comment]
> If you are really sure about that it might be a server issue (unlikely, but nonetheless possible). Definitely not a client issue since the error clearly says what it says and comes directly from the server.

I understand what you're talking about, but this issue started to happen yesterday, I've just checked same accounts in telethon and it works. So Telethon recieve different answer from server? And at the end: this account works on my phone and laptop, it's not deleted/deactivated, it's not even limited

**Comment by budni** [comment]
Ok, I think I've solved this issue but I still don't understand how it works: I have a module which is written on telethon to change username and photo, I've changed them and then it started to log in. Use Pyrogram around 6 months already, didn't meet such before

Also helped the changing of username/photo by hands

**Comment by polyphia** [comment]
I am also experiencing this issue with pyrogram , difference being the account actually gets banned !

Pyrogram is the only client with such issues, i login normally with telethon and every other software I use, pyrogram = insta ban .

Something is terribly off in the way pyrogram works, idk if it's the flow of requests or what, but works with everything else .

**Comment by alihesamiz** [comment]
i had the same problem after wasting 2 hours 
changing bot name in Client() did help.

[aa.txt](https://github.com/pyrogram/pyrogram/files/12642732/aa.txt)

**Comment by alihesamiz** [comment]
`app = Client('my_bot2', api_id=api_id, api_hash=api_hash, bot_token=bot_token)

#change the str
`
