### ISSUE TITLE
Use Telegram Api Proxy instead of original website

### ISSUE THREAD

**Issue by PBhadoo** [pyrogram/pyrogram#1208]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

The telegam apis like api.telegram.org venus.web.telegram.org needs to connect to Telegram servers.

I'm asking this question.

Is there a way i can use proxy of Telegram api instead of original url in pyrogram.

My application has a need of this to save bandwidth in this manner. Please provide information if this can be achieved with Pyrogram.

**Comment by delivrance** [comment]
This is unrelated or otherwise unclear. Pyrogram only uses IP addresses which Telegram itself provides in order to connect to the server.

**Comment by PBhadoo** [comment]
> This is unrelated or otherwise unclear. Pyrogram only uses IP addresses which Telegram itself provides in order to connect to the server.

The ip address are someplace stored inside pyrogram to connect to. Or some library from which pyrogram gets the ips and connects to, I'll be very thankful if you can provide the link to the page.

Eg. Web.telegram.org uses
{ id: 1, host: 'pluto.web.telegram.org' },
    { id: 2, host: 'venus.web.telegram.org' },
    { id: 3, host: 'aurora.web.telegram.org' },
    { id: 4, host: 'vesta.web.telegram.org' },
    { id: 5, host: 'flora.web.telegram.org' }

What ip addresses and where it is in the repo mtproto connects to Telegram.

**Comment by delivrance** [comment]
See `pyrogram/session/internals/data_center.py` for Telegram's IP addresses Pyrogram connects to.
