### ISSUE TITLE
stream_media is broken

### ISSUE THREAD

**Issue by ingvar-lynn** [pyrogram/pyrogram#1209]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

stream_media (and download_media as far as i can tell) was broken somewhere between 2.0.51 and 2.0.97

### Steps to reproduce

1. have pyrogram 2.0.97
2. do 
```
        try:
            blobs = [chunk async for chunk in client.stream_media(ms)]
        except Exception as E:
            print(f'Exception raised {E}')
            quit()

        blob = b''.join(blobs)
```
in cycle

3. after 100k*50 = 5mb worth of images start getting empty blobs. **_NO EXCEPTIONS_** happens.
4. downgrade to  2.0.51 
5. restart, catch 420 FLOOD_WAIT_X exception, stop
6. wait mentioned number of seconds, restart
7. everything works fine now.

**Comment by delivrance** [comment]
This is likely a server issue or a behaviour change between schemas regarding rate limits rather than a client issue, the example is also not complete to reproduce any possibly related issue.

**Comment by ingvar-lynn** [comment]
it's a legit bug.

if you tired of support just stop opening issues tab completely or even better - wipe your project from pypi and archive the repo.

**Comment by frnkvieira** [comment]
I can confirm this bug, I'm also experiencing **random** empty files after upgrading to 2.0.97.

**Comment by delivrance** [comment]
Without a proper minimal, complete and consistently reproducible example that involves normal usages there's no way to confirm it's a client side bug. It could be a bug, but as I said already it's more likely to be a server side bug or a new server behavior that sends empty bytes on purpose rather than a client side issue.
