### ISSUE TITLE
bug in on_edited_message

### ISSUE THREAD

**Issue by m0hammadhossein** [pyrogram/pyrogram#1212]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

When using the ‍‍```on_edited_message``` , sometimes unedited messages are also checked in this handle.

example:

```
@ApiClient.on_edited_message(main_chat & filters.media & is_lock_media)
async def check_edit_media(_, msg: Message):
    if msg.media in (enums.MessageMediaType.PHOTO, enums.MessageMediaType.ANIMATION, enums.MessageMediaType.DOCUMENT):
        edited_msg = await msg.forward(SETTINGS['sup'])
        await msg.delete()
```
Sometimes it deletes unedited media messages after a while

**Comment by delivrance** [comment]
Wrong issue template. But from what you explained it's likely due to reactions on messages which trigger edits. This is a server behavior.

**Comment by m0hammadhossein** [comment]
How do I solve this problem?

**Comment by delivrance** [comment]
There currently appear to be no straightforward way to distinguish an actual edited message from an empty edited message triggered by a message reaction in all kind of chats except by doing a comparison of the new message content with the previously stored one. If the contents match it means there was an empty edited message triggered by a reaction (and therefore the event is to be discarded), if the contents differ it means there was an actual content edit to the message.

**Comment by m0hammadhossein** [comment]
Thank you
