### ISSUE TITLE
Infinite RAM usage

### ISSUE THREAD

**Issue by Dima752** [pyrogram/pyrogram#1213]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When using idle() I ran into a problem when the script starts to infinitely increase the ram usage. I even removed all the handlers for the test, except for the start of clients and idle nothing else happens, but the problem does not disappear.

### Steps to reproduce

1 use code

### Code example

```python
from pyrogram import Client, idle
from settings import *
for app in apps:
    app.start()
idle()
```

**Comment by delivrance** [comment]
The memory usage is supposed to grow until some point because of caching, it is a normal behavior.
Even without handlers, updates are being received underneath by default.

**Comment by Dima752** [comment]
You didn't understand, the memory is clogged to the limit until he is killed.

**Comment by delivrance** [comment]
That's because your machine doesn't have enough memory, which is not an issue of the library.

**Comment by ggjjjmbg** [comment]
> 

I tested on a VDS server with 2GB of operating memory and on my phone with 8, every minute the amount of memory used increases by 1-2 megabytes and it does not stop.

**Comment by ggjjjmbg** [comment]
Please help I've been suffering with this for a long time

**Comment by delivrance** [comment]
There's no memory issue with the library, it will use the amount of memory it needs depending on the usage one makes of it.
The issue report was incomplete and inadequate anyway.
