### ISSUE TITLE
I propose to add the Russian language for the documentation of pyrogram

### ISSUE THREAD

**Issue by imsLmaooo** [pyrogram/pyrogram#1214]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

I'm thinking of adding the Russian documentation language for pyrograms

**Comment by delivrance** [comment]
Thanks for the proposal, but I don't intend to have the documentation in any other language besides English.
