### ISSUE TITLE
in bug in close processing run bot

### ISSUE THREAD

**Issue by m3coder** [pyrogram/pyrogram#1217]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

when ending the bot when there is a listen or scheduled task running, errors are occurring, it would be interesting if also before closing the bot it closes only after finishing all the tasks called

### Steps to reproduce

from datetime import datetime
import asyncio, time

from pyrogram import Client, idle
from pyrogram.session import Session
from pyrogram.enums import ParseMode

from config import API_HASH, API_ID, BOT_TOKEN, WORKERS, GROUP_ID
from database import find, UserMongo
from hotmart import HOTMART
from apscheduler.schedulers.asyncio import AsyncIOScheduler

# Desativa a mensagem do Pyrogram no início.
Session.notice_displayed = True

client = Client(
    'bot',
    bot_token=BOT_TOKEN,
    api_id=API_ID,
    api_hash=API_HASH,
    workers=WORKERS,
    plugins={'root': 'plugins'},
    #parse_mode=ParseMode.HTML,
)

async def sweep_group():
    print('Varredura iniciada')

    members = await client.get_chat_members_count(GROUP_ID)
    send = await client.send_message(
        GROUP_ID, '✅ sweep in group is running'
    )

    count = 0
    last_percent = 0
    expires = 0

    responses = []

    start_sweep = datetime.now()
    async for verify_response in HOTMART.generator_clients():
        active = find({'email': verify_response.email})
        # if is active in database
        if active:
            responses.append(list(verify_response.__dict__.values()))

    async for member in client.get_chat_members(GROUP_ID):
        count += 1
        mongo_result = find({'usuario': str(member.user.id), 'ativo': '1'})
        if mongo_result:
            i = UserMongo(**mongo_result)
            try:
                if [True, i.email, None] in responses:
                    pass
                else:
                    text = f'''<b>Assinatura expirada</b>
user_id <code>{member.user.id}</code> : <code>{i.email}</code>\n
<code>/banir 123456 {member.user.id}</code>
'''
                    await client.send_message(user_id, text)
                    expires += 1
                
            except Exception as e:
                print(e, member.user.id)
                continue

        if time.time() - last_percent > 4:
            last_percent = time.time()
            msg = '\n'.join(
                [
                    f"<b>- Inicio em: </b><i>{start_sweep.strftime('%H :%M :%S')}</i>",
                    f'<b>- Verificando  ➞ </b>{(count / members) * 100:.2f}% concluído.',
                    f'<b>- verificados: </b>{count}',
                    f'<b>- expirados: </b>{expires}',
                    f'<b>- executando a: </b><i>{(datetime.now() - start_sweep).seconds}s</i>',
                ]
            )
            await send.edit_text(msg)

    msg = '\n'.join(
        [
            f"- <b>Inicio em: </b><i>{start_sweep.strftime('%H :%M :%S')}</i>",
            f'- <b>Verificação ➞ </b>{(100 / 100) * 100:.2f}% concluído.',
            f'- <b>verificados: </b>{count}',
            f'- <b>expirados: </b>{expires}',
            f'- <b>Tempo de execução:</b> <i>{(datetime.now() - start_sweep).seconds}s</i>',
            f'- <b>Finalizado em: </b><i>{datetime.now().strftime("%H :%M :%S")}</i>'
        ]
    )
    await send.edit_text(msg)

async def main():

    # Inicializa o cliente.
    await client.start()

    #scheduler = AsyncIOScheduler()

    #scheduler.add_job(sweep_group, 'interval', hours=5)
    #scheduler.start()

    print('Bot rodando...')
    client.me = await client.get_me()
    await sweep_group()

    await idle()
    await client.stop()

if __name__ == '__main__':
    asyncio.run(main())

any task scheduled there after the client.start() when it closes using ctrl + c it gives an error and does not close, locking the shell

### Code example

```python
from datetime import datetime
import asyncio, time

from pyrogram import Client, idle
from pyrogram.session import Session
from pyrogram.enums import ParseMode

from config import API_HASH, API_ID, BOT_TOKEN, WORKERS, GROUP_ID
from database import find, UserMongo
from hotmart import HOTMART
from apscheduler.schedulers.asyncio import AsyncIOScheduler


# Desativa a mensagem do Pyrogram no início.
Session.notice_displayed = True

client = Client(
    'bot',
    bot_token=BOT_TOKEN,
    api_id=API_ID,
    api_hash=API_HASH,
    workers=WORKERS,
    plugins={'root': 'plugins'},
    #parse_mode=ParseMode.HTML,
)


async def sweep_group():
    print('Varredura iniciada')

    members = await client.get_chat_members_count(GROUP_ID)
    send = await client.send_message(
        -1001425342949, '✅ sweep in group is running'
    )

    count = 0
    last_percent = 0
    expires = 0

    responses = []

    start_sweep = datetime.now()
    async for verify_response in HOTMART.generator_clients():
        active = find({'email': verify_response.email})
        # if is active in database
        if active:
            responses.append(list(verify_response.__dict__.values()))

    async for member in client.get_chat_members(GROUP_ID):
        count += 1
        mongo_result = find({'usuario': str(member.user.id), 'ativo': '1'})
        if mongo_result:
            i = UserMongo(**mongo_result)
            try:
                if [True, i.email, None] in responses:
                    pass
                else:
                    text = f'''<b>Assinatura expirada</b>
user_id <code>{member.user.id}</code> : <code>{i.email}</code>\n
<code>/banir 123456 {member.user.id}</code>
'''
                    await client.send_message(783805258, text)
                    expires += 1
                
            except Exception as e:
                print(e, member.user.id)
                continue


        if time.time() - last_percent > 4:
            last_percent = time.time()
            msg = '\n'.join(
                [
                    f"<b>- Inicio em: </b><i>{start_sweep.strftime('%H :%M :%S')}</i>",
                    f'<b>- Verificando  ➞ </b>{(count / members) * 100:.2f}% concluído.',
                    f'<b>- verificados: </b>{count}',
                    f'<b>- expirados: </b>{expires}',
                    f'<b>- executando a: </b><i>{(datetime.now() - start_sweep).seconds}s</i>',
                ]
            )
            await send.edit_text(msg)

    msg = '\n'.join(
        [
            f"- <b>Inicio em: </b><i>{start_sweep.strftime('%H :%M :%S')}</i>",
            f'- <b>Verificação ➞ </b>{(100 / 100) * 100:.2f}% concluído.',
            f'- <b>verificados: </b>{count}',
            f'- <b>expirados: </b>{expires}',
            f'- <b>Tempo de execução:</b> <i>{(datetime.now() - start_sweep).seconds}s</i>',
            f'- <b>Finalizado em: </b><i>{datetime.now().strftime("%H :%M :%S")}</i>'
        ]
    )
    await send.edit_text(msg)


async def main():

    # Inicializa o cliente.
    await client.start()

    #scheduler = AsyncIOScheduler()

    #scheduler.add_job(sweep_group, 'interval', hours=5)
    #scheduler.start()

    print('Bot rodando...')
    client.me = await client.get_me()
    await sweep_group()

    await idle()
    await client.stop()


if __name__ == '__main__':
    asyncio.run(main())
```

### Logs

```shell
RuntimeError: Task <Task pending name:' Task-31' running at /home/UeUzin/Årea de trabatho/nlka 
sungodbot/ . got Future <Future pending 
. at /home/UeUzin/Årea de trabatho/nikasungodbot/ . att 
ached to a different Loop
```

**Comment by delivrance** [comment]
See https://stackoverflow.com/help/minimal-reproducible-example.
