### ISSUE TITLE
Error sending photo or document

### ISSUE THREAD

**Issue by Randommist** [pyrogram/pyrogram#1218]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When calling the send_photo or send_document function, an error occurs in save_file.py line 131
https://docs.pyrogram.org/api/methods/send_photo

ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-32' coro=<Mailing() done, defined at /home/andrey/Projects/TelegramManagerSpamBot/main.py:74> exception=AttributeError("'AttributeError' object has no attribute 'message'")>
Traceback (most recent call last):
  File "/home/andrey/Projects/TelegramManagerSpamBot/main.py", line 92, in send
    await bots[user_bot_id].client.send_photo(bots[user_bot_id].Chats[chat_id].recipient, mes_choice.photo_path[0], caption=mes_choice.text)
  File "/home/andrey/.var/app/com.visualstudio.code-oss/data/python/lib/python3.10/site-packages/pyrogram/methods/messages/send_photo.py", line 153, in send_photo
    file = await self.save_file(photo, progress=progress, progress_args=progress_args)
  File "/home/andrey/.var/app/com.visualstudio.code-oss/data/python/lib/python3.10/site-packages/pyrogram/methods/advanced/save_file.py", line 131, in save_file
    file_size_limit_mib = 4000 if self.me.is_premium else 2000
AttributeError: 'NoneType' object has no attribute 'is_premium'

You can solve it by replacing line 131 with
file_size_limit_mib = 2000 #4000 if self.me.is_premium else 2000

### Steps to reproduce

call send_photo("local/path/img.jpg")

**Comment by delivrance** [comment]
#1106
