### ISSUE TITLE
FAQ is wrong

### ISSUE THREAD

**Issue by GodSaveTheDoge** [pyrogram/pyrogram#1221]
### Description

The `Code hangs when calling stop, restart, add/remove_handler` section incorrectly states that you should pass `block=False` to `add_handler` / `remove_handler`.

Those functions do not accept that kwarg.

### Steps to reproduce

1. Go to https://docs.pyrogram.org/faq/code-hangs-when-calling-stop-restart-add-remove-handler
2. Read

**Comment by delivrance** [comment]
FAQ updated.
