### ISSUE TITLE
Documentation for send_inline_bot_result is wrong

### ISSUE THREAD

**Issue by GodSaveTheDoge** [pyrogram/pyrogram#1222]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

The documentation for send_inline_bot_result says it returns a `pyrogram.types.Message`. 
This is wrong, it returns an instance of `pyrogram.raw.types.updates_t.Updates`

### Steps to reproduce

1. Execute the code below
2. Profit ???

### Code example

```python
from pyrogram import Client

c = Client(
    "foo",
    api_id=775622,
    api_hash="35c9ca3cc2db2747b34d73c67f10e3d6",
)
c.start()

res = c.get_inline_bot_results("pyrogrambot")
message = c.send_inline_bot_result("me", res.query_id, res.results[0].id)
print(message)
print(type(message))

c.stop()
```

### Logs

Sections of output are omitted for brevity.
```
{
    "_": "types.Updates",
    "updates": [
        {
            "_": "types.UpdateMessageID",
            ...
        },
        {
            "_": "types.UpdateNewMessage",
            "message": {
                "_": "types.Message",
                ...
            },
            ...
        },
        {
            "_": "types.UpdateReadHistoryInbox",
            ...
        }
    ],
    "users": [
        ...
    ],
    "chats": [],
    "date": 1677254774,
    "seq": 0
}
<class 'pyrogram.raw.types.updates_t.Updates'>
```

**Comment by delivrance** [comment]
Type hint updated.
