### ISSUE TITLE
send_media_group / reply_media_group fails to send multiple files

### ISSUE THREAD

**Issue by adontz** [pyrogram/pyrogram#1223]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

send_media_group fails to send multiple files. The same files can be successfully sent separately.

### Steps to reproduce

1. Prepare video files (any will do)
2. Run the provided code
3. Watch exception trace

### Code example

```python
from asyncio import run
from asyncio import sleep

from pyrogram import Client
from pyrogram import filters
from pyrogram.types import InputMediaVideo


async def main():
    telegram_client = Client('test', api_id='20349389', api_hash='ef9d39a0094336595deb20af959e84ff')
    @telegram_client.on_message(filters.private)
    async def hello(client, message):
        # This works
        await message.reply_video('test1-000.mp4', caption='Test 1')
        await message.reply_video('test2-000.mp4', caption='Test 2')
        await message.reply_video('test3-000.mp4', caption='Test 3')
        await message.reply_video('test4-000.mp4', caption='Test 4')

        # This also works
        await message.reply_media_group(
            [
                InputMediaVideo('test1-000.mp4', caption='Test'),
            ]
        )

        # This does NOT work, raises
        #   File ".venv/lib64/python3.9/site-packages/pyrogram/types/messages_and_media/message.py", line 1880, in reply_media_group
        #    return await self._client.send_media_group(
        #  File ".venv/lib64/python3.9/site-packages/pyrogram/methods/messages/send_media_group.py", line 393, in send_media_group
        #    r = await self.invoke(
        #  File ".venv/lib64/python3.9/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
        #    r = await self.session.invoke(
        #  File ".venv/lib64/python3.9/site-packages/pyrogram/session/session.py", line 389, in invoke
        #    return await self.send(query, timeout=timeout)
        #  File ".venv/lib64/python3.9/site-packages/pyrogram/session/session.py", line 357, in send
        #    RPCError.raise_it(result, type(data))
        #  File ".venv/lib64/python3.9/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
        #    raise getattr(
        #pyrogram.errors.exceptions.bad_request_400.MediaEmpty: Telegram says: [400 MEDIA_EMPTY] - The media you tried to send is invalid (caused by "messages.SendMultiMedia")
        await message.reply_media_group(
            [
                InputMediaVideo('test1-000.mp4', caption='Test'),
                InputMediaVideo('test2-000.mp4'),
                InputMediaVideo('test3-000.mp4'),
                InputMediaVideo('test4-000.mp4'),
            ]
        )


    try:
        await telegram_client.start()

        while True:
            await sleep(60)
    finally:
        await telegram_client.stop()


run(main())
```

### Logs

```shell
File ".venv/lib64/python3.9/site-packages/pyrogram/types/messages_and_media/message.py", line 1880, in reply_media_group
    return await self._client.send_media_group(
  File ".venv/lib64/python3.9/site-packages/pyrogram/methods/messages/send_media_group.py", line 393, in send_media_group
    r = await self.invoke(
  File ".venv/lib64/python3.9/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File ".venv/lib64/python3.9/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File ".venv/lib64/python3.9/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File ".venv/lib64/python3.9/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MediaEmpty: Telegram says: [400 MEDIA_EMPTY] - The media you tried to send is invalid (caused by "messages.SendMultiMedia")
```

**Comment by delivrance** [comment]
> Telegram says: [400 MEDIA_EMPTY] - The media you tried to send is invalid

The error is clear enough: one of the media is invalid for the method used.
It's also clear you need to try more combinations in order to figure out which is causing the issue exactly.

**Comment by adontz** [comment]
NO, it is not. I can successfully send my file separately. Please, actually read what I wrote before discarding

**Comment by adontz** [comment]
Also, files are valid, I can watch them on receiving side.

**Comment by delivrance** [comment]
Sending media separately involves a completely different method.

**Comment by adontz** [comment]
Yes, however all files are valid video files. I can watch them locally, I can watch them on receiving side. I can send them successfully with official client.

**Comment by adontz** [comment]
Clarification: I can send them as a media group with official client.

**Comment by delivrance** [comment]
As I already suggested here https://github.com/pyrogram/pyrogram/issues/1223#issuecomment-1445309011, you could start by figuring out which media exactly is causing the issue since the example is not complete and therefore it is inadequate because no one else would be able to reproduce the same issue with the given details. Also see https://stackoverflow.com/help/minimal-reproducible-example.

**Comment by adontz** [comment]
I believe, it is not about the files, since Telethon can send them just file.
```
    await telegram_client.send_file(chat,
    [
        'test1-000.mp4',
        'test2-000.mp4',
        'test3-000.mp4',
        'test4-000.mp4',
    ])
```
Nevertheless I can send you the files (~5mb) if you tell me how.

**Comment by delivrance** [comment]
I do believe it's about the test files you used because I already tried with other files and successfully sent them in a media group without any issue. One thing you could try is to pass `supports_streaming=False` to each `InputMediaVideo` constructors and see if that works.

**Comment by delivrance** [comment]
The audio stream will definitely affect the result since the media might be detected as animation (gif, video without sound) and therefore discarded by the server from being inserted into media groups. Not sure about other clients, official clients are very likely converting audio/video streams into compatible ones or adding the missing audio stream as silent sound before uploading in order for the media to be classified as video.

**Comment by tangyoha** [comment]
@adontz hi, Have you solved this problem?

**Comment by tangyoha** [comment]
```python

from moviepy.audio.io.AudioFileClip import AudioClip
from moviepy.video.io.VideoFileClip import VideoFileClip


def is_video_no_audio(path) -> bool:
    """is video not have audio"""
    videoclip = VideoFileClip(path)
    return videoclip.audio is None


def gif_to_video(path):
    """gif to video"""
    ext = os.path.splitext(path)[1] # 获取原文件名的扩展名
    tmp_path = os.path.splitext(path)[0] + "_tmp" + ext  

    videoclip = VideoFileClip(path)
    def make_frame(_):
        return 2 * [0.0]
    audioclip = AudioClip(make_frame, duration=videoclip.duration)
    final_clip = videoclip.set_audio(audioclip)
    final_clip.write_videofile(tmp_path, verbose=False, logger=None)   

    os.remove(path)
    os.rename(tmp_path, path)

    return path

def xxxx():
    if file_name and is_video_no_audio(file_name):
    gif_to_video(file_name)
```

**Comment by taimast** [comment]
> > Telegram says: [400 MEDIA_EMPTY] - The media you tried to send is invalid
> 
> The error is clear enough: one of the media is invalid for the method used. It's also clear you need to try more combinations in order to figure out which is causing the issue exactly.

Very often I observe in the issue that you come up with something in your head and answer yourself and close the issue, just try to read the question before making any conclusions
