### ISSUE TITLE
Can not download multiple files asynchronously

### ISSUE THREAD

**Issue by ali-safapour** [pyrogram/pyrogram#1225]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

This is a code to download files using a bot:

```
from pyrogram import Client, filters
from pyrogram.types import Message
import asyncio, random

app = Client( < Client info > )

async def progress(current, total, file_number):
    print(f"file number: {file_number}, {current * 100 / total:.1f}%")

@app.on_message(filters.private & (filters.document | filters.audio | filters.video))
async def download(c, m):
  global counter 
  file_number = random.randint(1, 1000)
  downloaded_file = await app.download_media(m, progress=progress, progress_args=(file_number,),

app.run()
```

The output when I forwarded two files together to the bot and one file randomly got 11 as it's file_id:

```
file number: 11, 0.9%
file number: 11, 1.1%
file number: 11, 1.4%
file number: 11, 1.7%
file number: 11, 2.0%
file number: 11, 2.3%
file number: 11, 2.6%
file number: 11, 2.9%
file number: 11, 3.2%
file number: 11, 3.4%
file number: 11, 3.7%
```

The problem is that when I forward multiple files at the same time to the bot, the bot downloads a file when downloading the previous file is finished. As you can see, there is no other files downloading except the file 11. I need to download files asynchronously. How can solve this issue?

My Pyrogram version is 2.0.100

### Steps to reproduce

Run the code that I provided and forward two big files together to the bot.

**Comment by delivrance** [comment]
This is not an issue, but an intended behavior. See Client's `max_concurrent_transmissions` parameter.

**Comment by ali-safapour** [comment]
Thanks.

**Comment by ali-safapour** [comment]
> This is not an issue, but an intended behavior. See Client's `max_concurrent_transmissions` parameter.

Thanks.
