### ISSUE TITLE
Telegram silently terminates all sessions after connect

### ISSUE THREAD

**Issue by dann1kid** [pyrogram/pyrogram#1236]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Telegram silently terminates all sessions after connect to account.

### Steps to reproduce

1 take new account
2 try to login
3 sometime later you have no access to yours account. Need to relogin in phone then in bot

### Code example

```python
from pyrogram import Client, filters

app = Client("my_account")

api_id = 123 # here my id
api_hash = "abc" # here my hash 


@app.on_message(filters.private)
async def hello(client, message):
    await message.reply("Hello from Pyrogram!")

app = Client("my_account", api_id=api_id, api_hash=api_hash)
app.run()
```

**Comment by delivrance** [comment]
This is not a client issue, but a server behavior, something that Telegram decides on its own for some reason and clients can't do anything about it.

**Comment by dann1kid** [comment]
> This is not a client issue, but a server behavior, something that Telegram decides on its own for some reason and clients can't do anything about it.

so why its can do it only with any telegram user lib?
its means to be useless if i cant use library at all

**Comment by rozha** [comment]
You have to use more gently, it works perfectly to me. Cost me a few hundred accounts to figure out though, but that was me being impatient.
