### ISSUE TITLE
How to check integrity of uploaded file?

### ISSUE THREAD

**Issue by divyam234** [pyrogram/pyrogram#1241]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I am uploading files through multiple connections to speed up the process but sometimes files are not fully uploaded so I want to check if uploaded file has same hash as original file.

### Steps to reproduce

None

**Comment by delivrance** [comment]
The issue section on GitHub is only for actual issues and useful enhancements in the library. You may ask questions on [StackOverflow](https://stackoverflow.com/questions/ask?tags=pyrogram).
