### ISSUE TITLE
401 USER_DEACTIVATED_BAN

### ISSUE THREAD

**Issue by polyphia** [pyrogram/pyrogram#1246]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

401 USER_DEACTIVATED_BAN - The user has been deleted / deactivated cause by (updates.getstate)

I know there is another open issue with this and author is arguing this is a telegram side thing, but it 100% isn't . 

Yes, it is a telegram spam trigger but that only happens due to something not being done properly in the flow of requests pyrogram uses , as I don't have such issues with any other client and every single time i try to login a fresh account with pyrogram I get an instant ban . 

So, the issue should be addressed instead of relegating this to telegram triggering spam protections, as a proper flow of requests would prevent it from happening . 

### Steps to reproduce

Create telegram account through software and then try to login using pyrogram with the OTP code .

**Comment by delivrance** [comment]
This is related to the actual use case one has when working with the library.
See https://docs.pyrogram.org/faq/the-account-has-been-limited-deactivated.

**Comment by polyphia** [comment]
You are wrong , it is related to the flow of requests being sent by the login process in pyrogram . 

Every single other client out there works properly and only when using Pyrogram this happens  with the exact same accounts that work everywhere else, so what you are saying makes no sense at all .

I think you are failing  to understand there is a certain flow of requests to be followed in the login process  and Telegram just happens to have updated very recently .

But it could be something else in the way you are performing the requests I am not sure , what I am sure is that the issue is on pyrogram side . 

For the sake of confirmation, I made a new pyrogram client from scratch . 

`from pyrogram import Client, emoji, filters

TARGET = -1824305169
api_id = 12599080
api_hash = "e6189f3078ba70d42b42c3f3f2b17ccd"

proxy = {
    "scheme": "http",  # "socks4", "socks5" and "http" are supported
    "hostname": "myproxy.com",
    "port": 10000
 }

app = Client("my_account", api_id=api_id, api_hash=api_hash, proxy=proxy)

@app.on_message(filters.chat(TARGET) & filters.new_chat_members)
async def welcome(client, message):
    new_members = [u.mention for u in message.new_chat_members]
    text = MESSAGE.format(emoji.SPARKLES, ", ".join(new_members))
    await message.reply_text(text, disable_web_page_preview=True)

app.run()`


The end result, as expected, is the same, the account instantly gets banned . 

The exact same procedure has 0 issues with pretty much every other client I have tried so far .

**Comment by polyphia** [comment]
Furthermore , I have tested this with over 10 identical accounts using the same proxies they were created with . 

5/5 - Telethon and other clients login without any issue

5/5 - Accounts are instantly banned when logging in with pyrogram

**Comment by delivrance** [comment]
I understand what you mean and your explanations are no news.
The library works well for intended usages and what you suggest falls outside the scope of this project.

**Comment by PLAKSHERiE** [comment]
similarly. After using any method of this library (the latest version) - just deletes the account

**Comment by PLAKSHERiE** [comment]
> I understand what you mean and your explanations are no news. The library works well for intended usages and what you suggest falls outside the scope of this project.

Do you even check to see if what you've updated is working? Go to your account from scratch and try uploading a video, for example.

**Comment by lizzardarcher** [comment]
Same issue. Checked lot of forums.
I got a little further adding some optional info (device_model="iPhone 13 Pro Max", system_version="14.8.1", app_version="8.4",).
It allows account to live for a bit longer. But not much. After 2-3 login it fails.

Think this framework is dead for me. Unfortunately
