### ISSUE TITLE
Missing RSA public keys for some CDN DCs

### ISSUE THREAD

**Issue by Cosangeles55** [pyrogram/pyrogram#1265]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When trying to download a file from popular channels, namely a popular file, a fatal error occurs:
ip = cls.PROD[dc_id]
KeyError: 203

While Pyrogram can get CDN listings:
print((await app.invoke(GetConfig())).dc_options)

And in the answer https://pastebin.com/gt0uwNHf there is this CDN, the pyrogram code does not fill in the cls.PROD object, the interlocutor "⎞ .·. ⎝" and I came to the conclusion that this is a flaw in the pyrogram code.

----------------
Many thanks to the interlocutor ⎞ .·. ⎝ from the chat!

https://t.me/pyrogramchat/553403

### Steps to reproduce

1) Reproduced only on specific users, with non-standard CDN in the profile (session).

2) try to download, for example this message https://t.me/school_network/586, via download_media()

### Code example

```python
app.download_media()
```

### Logs

```shell
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.10/site-packages/pyrogram/client.py", line 938, in get_file
backend  |     self, r.dc_id, await Auth(self, r.dc_id, await self.storage.test_mode()).create(),
backend  |   File "/usr/local/lib/python3.10/site-packages/pyrogram/session/auth.py", line 79, in create
backend  |     self.connection = Connection(self.dc_id, self.test_mode, self.ipv6, self.proxy)
backend  |   File "/usr/local/lib/python3.10/site-packages/pyrogram/connection/connection.py", line 39, in init
backend  |     self.address = DataCenter(dc_id, test_mode, ipv6, media)
backend  |   File "/usr/local/lib/python3.10/site-packages/pyrogram/session/internals/data_center.py", line 79, in new
backend  |     ip = cls.PROD[dc_id]
backend  | KeyError: 203


------------- await app.invoke(GetConfig())).dc_options

https://t.me/pyrogramchat/553403
```

**Comment by delivrance** [comment]
I cannot reproduce the issue since it's the server that decides whether to redirect or not to a CDN. However, I've added the missing DC IPs and RSA public keys, which should make the CDN redirect work for those DCs. You can update and try.

**Comment by Cosangeles55** [comment]
@delivrance 
Hooray! it works now. it only worries me that only one CDN has reached the pyrogram, I think there are many of them, which are unknown to us, if I meet again, I will definitely write

**Comment by Cosangeles55** [comment]
@delivrance hi, https://t.me/pyrogramchat/556101

**Comment by Cosangeles55** [comment]
Prishlos' otkatit'sya do versii Pyrogram==2.0.104, do doabvleniya 203 tsdn, inache v beskonechnom tsikle pytayetsya podklyuchit'sya k nemu i dzhango ppolnost'yu zavisayet
