### ISSUE TITLE
Button Click Request Timed Out Bug

### ISSUE THREAD

**Issue by Eikosa** [pyrogram/pyrogram#1276]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

![image](https://user-images.githubusercontent.com/20538090/236860464-b1352f24-78a9-499e-a0a2-e06064f3729e.png)
![image](https://user-images.githubusercontent.com/20538090/236860865-1d726c2d-5308-4c64-b483-eda1629e74a0.png)
When I want to click on a button belonging to a bot more than once with a user bot, it works when clicked first, but gives a "Request timed out" error afterward.

### Steps to reproduce

1. find a bot message with changing buttons
2. Click more than once on a button with the same message as the userbot
3. See Request timed out error

### Code example

```python
for i in range(10):
 await message.click(1)
 await asyncio.sleep(3)
```

### Logs

```shell
Request timed out
```

**Comment by delivrance** [comment]
This is not a bug and is also documented. See docs for `Message.click()`. The actual issue comes from the bot you are clicking buttons onto, which did not answer in time.
