### ISSUE TITLE
Use MTproto proxy in my pyrogram code

### ISSUE THREAD

**Issue by SepehrFakoori** [pyrogram/pyrogram#1279]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

I write a code with Pyrogram how can I add my MTProto proxy to the bot? I can add sock5 but I can't add MTproto, can you help me?

**Comment by delivrance** [comment]
Such feature is currently not supported.
