### ISSUE TITLE
Add Broadcast API call

### ISSUE THREAD

**Issue by bipinkrish** [pyrogram/pyrogram#1285]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

fetching the full list of users, chats and channels of a bot is not exactly possible from the current `get_members` due to 200 limit, but i have encountered [MadelineProto](https://github.com/danog/MadelineProto/) which is based on MTProto protocol and has the support for [Broadcast](https://docs.madelineproto.xyz/docs/BROADCAST.html)

**Comment by delivrance** [comment]
Thanks for the proposal. However, it's unlikely such a feature would find a place in this library.
