### ISSUE TITLE
Issue with Pyrogram - Inability to Identify Channel Dialogs

### ISSUE THREAD

**Issue by wollframe** [pyrogram/pyrogram#1293]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Hello,

I'm experiencing an issue with Pyrogram and would appreciate your assistance. Here's a description of the problem:

I'm trying to post images to my channels using Pyrogram. The program runs without errors, but the images are not getting published in the channels. I have checked my code and made sure that I have channels in my account. I used the app.get_dialogs() function to get a list of dialogs and checked the type of each dialog. However, despite having channels, the condition dialog.chat.type == "CHANNEL" is not being met, and the program doesn't enter that code block.

I have tried different variations of checking the chat type, such as "CHANNEL", "channel", "channels", but none of them work. This is very puzzling as the Pyrogram documentation states that the channel type should be "CHANNEL".

Please help me resolve this issue. I'm willing to provide additional information or code examples if needed.

Thank you for your attention, and I look forward to your assistance.

Sincerely,
Ivan

### Steps to reproduce

1. Run the ts.py file, which utilizes the Pyrogram library.
2. Establish a connection with my Telegram account.
3. Utilize the app.get_dialogs() function to retrieve a list of dialogs.
4. Check the type of each dialog using the dialog.chat.type attribute.
5. Expect the program to enter the code block if the dialog type is "CHANNEL."
6. However, the program fails to enter this code block even when there are channels present in my account.
7. Expected Result: The program should enter the code block for channels.
8. Actual Result: The program does not enter the code block for channels.

### Code example

```python
async def post_image_to_channels():
    async for dialog in app.get_dialogs():
        print(dialog.chat.type)
        if dialog.chat.type == "CHANNEL":
            print(dialog.chat.id)
```

### Logs

```shell
ChatType.CHANNEL
ChatType.CHANNEL
ChatType.CHANNEL
ChatType.CHANNEL
ChatType.CHANNEL
ChatType.BOT
ChatType.PRIVATE
ChatType.BOT
```

**Comment by wulan17** [comment]
Use pyrogram.enums
```python
from pyrogram import enums
async def post_image_to_channels():
    async for dialog in app.get_dialogs():
        print(dialog.chat.type)
        if dialog.chat.type == enums.ChatType.CHANNEL:
            print(dialog.chat.id)
```
