### ISSUE TITLE
"Official" Bot commands with trailing usernames don't work in groups

### ISSUE THREAD

**Issue by delivrance** [pyrogram/pyrogram#139]
**Example**:

`/start@pyrogrambot`

**Workaround**:

`Filters.command(["start", "start@pyrogrambot])`

Would be nice to have it automatically handled.

**Comment by fenilgandhi** [comment]
I would like to work on it.

**Comment by ColinTheShark** [comment]
I don't know if this would work, but would it make sense to just use regex?

`Filters.command("start", "/")` and in the background it creates the compiled regex:

`f"{prefix}{command}(@{username)?"` which would return `/start(@samplebot)?` and trigger on both with and without the `@samplebot` at the end.

**Comment by delivrance** [comment]
@ColinTheShark The issue is how to get the bot username to be used inside the filter, automatically. 

While we have the `message` instance available in the filter's callback, we can do `message._client.get_me().username`, or call `get_me()` somewhere in the client and store the username somewhere and then do `message._client.username` in the filter. Both solutions are ugly because they make use of non-public attributes (`_client`).

Maybe we can just match `(?i).+@\w+bot`?

**Comment by ColinTheShark** [comment]
Using such a generic Regex would possibly catch updates meant for other clients 🤔 

If my bot were `ColinSharkBot`, `/hi@AhoyBot` would also be caught by my bot and unintentionally react to it.

(Commenting here parallel to the [discussion in the chat](https://t.me/PyrogramChat/97715) to have it in the Issues, too)

**Comment by AVee** [comment]
Would it make sense to always call get_me() on Client.start() and make that info available? I guess there are more scenarios where that would be useful...

**Comment by tshipenchko** [comment]
I think that will work good 

`regex_patern = r'^\/(command)+(\@username_of_bot\w*(_\w+)*)?([ \f\n\r\t\v\u00A0\u2028\u2029].*)?$'`

https://gist.github.com/tshipenchko/42b81fb53bd52ca7034eb6f2b1b99799

Commands like that will handle
/command
/command arg1 arg2
/command@username_of_bot
/command@username_of_bot arg1 arg2

**Comment by pokurt** [comment]
Hi i have fixed it by modifying a filters.command()
https://nekobin.com/wilemoyepe.py

and example code for this will be
```
# import modified filters.command()
import command

@Client.on_message(command('start'))
async def func(_, message):
    print(message.command)
    await message.reply('hi')
```


but dan i suggest not to use this in pyrogram itself since it kinda slows the client down. this could be one of the few solutions for this

**Comment by murlakatamenka** [comment]
Thought that's already landed in the stable version of Pyrogram only to discover it actually hasn't yet :cry: 

That's an inconvenience, but not a huge issue though.
