### ISSUE TITLE
Missing Parameter in ban_member Method

### ISSUE THREAD

**Issue by sdmway** [pyrogram/pyrogram#1421]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Hello!
I stumbled upon an issue while using the `ban_member` method in your Python library. It seems that the `revoke_messages` parameter is missing. According to the expected functionality, setting this parameter to `True` should delete all messages authored by the member being banned.

### Steps to reproduce

1. Ban member

### Code example

```python
from pyrogram import Client, types, filters

app = Client("me", api_id, api_hash)

@app.on_message(filters.me & filters.reply & (filters.group | filters.chat) & filters.command(commands=["ban"], prefixes=['!', '/', '.'], case_sensitive=False))
async def ban_user(client, message: types.Message):
    try:
        await message.chat.ban_member(user_id=message.reply_to_message.from_user.id)
        await message.reply_to_message.delete()
        await message.edit_text(f"✅ Banned user: {message.reply_to_message.from_user.id}")
    except Exception as err:
        await message.reply(f"Couldn't ban user: {message.reply_to_message.from_user.id}\n\n{str(err)}")
        print(err)

app.run()
```

**Comment by SpEcHiDe** [comment]
> According to the expected functionality, setting this parameter to True should delete all messages authored by the member being banned.

Why?

**Comment by sdmway** [comment]
> > According to the expected functionality, setting this parameter to True should delete all messages authored by the member being banned.
> 
> Why?

Because when you try to ban user in Telegram, it allows you to delete all author messages 
<img width="329" alt="image" src="https://github.com/pyrogram/pyrogram/assets/97258586/435ae3ce-2085-4dc3-b068-5beed08f8638">

**Comment by SpEcHiDe** [comment]
This is a different vmethod called delete_user_history. Not ban_chat_member.

**Comment by sdmway** [comment]
> This is a different method called delete_user_history. Not ban_chat_member.
> 
> also, the screenshot is shown in official applications when you try to delete a message, not when ban user.

Thanks for the explanation! But wouldn't it be better just to add that parameter to ban_chat_member as well? I was looking at the Aiogram Docs and noticed they actually did that.
<img width="857" alt="image" src="https://github.com/pyrogram/pyrogram/assets/97258586/439fd248-e5b8-4134-8fc0-da9aa86b45f4">

**Comment by sdmway** [comment]
> delete_user_history

So actually this method has some disadvantages. It is not usable by bots, and allow deletions only in supergroups.

**Comment by SpEcHiDe** [comment]
The `revoke_messages` parameter in the **BOT API** library does not do the action that you mentioned in the previous screenshot.
