### ISSUE TITLE
Clarification related to how it upload more than 50mb?

### ISSUE THREAD

**Issue by Praveensenpai** [pyrogram/pyrogram#1428]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

How does Pyrogram manage to send files larger than Telegram's 50MB limit for bots? Does it upload them from user accounts and then forward them through the bot to the recipient?

**Comment by SpEcHiDe** [comment]
It is mentioned in the FAQ of documentation.

**Comment by Praveensenpai** [comment]
![Screenshot_1](https://github.com/pyrogram/pyrogram/assets/71966071/57d5e883-d698-4f4f-aeb3-445bbdefa5d2)
where?

> It is mentioned in the FAQ of documentation.

**Comment by Praveensenpai** [comment]
Understood tq
