### ISSUE TITLE
Add checks for file sizes when uploading

### ISSUE THREAD

**Issue by delivrance** [pyrogram/pyrogram#143]
File size limit is exactly 1500 MiB (1 MiB = 1024 KiB); if a bigger file is attempted to upload, a cryptic RPCError is shown. Let's make use of a nicer error instead.

**Comment by TolichP** [comment]
I am interested to do it, can I?

**Comment by delivrance** [comment]
Sure!

**Comment by delivrance** [comment]
Solved in #146
