### ISSUE TITLE
my code stopped working , maybe some telegram api changed?

### ISSUE THREAD

**Issue by doublep21** [pyrogram/pyrogram#1436]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 11 seconds is required (caused by "upload.SaveBigFilePart")
Telegram says: [420 FLOOD_WAIT_X] - A wait of 11 seconds is required (caused by "upload.SaveBigFilePart")
pyrogram.errors.exceptions.bad_request_400.FilePartMissing: Telegram says: [400 FILE_PART_X_MISSING] - Part 3 of the file is missing from storage (caused by "messages.UploadMedia")

### Steps to reproduce

mediafiles.append(InputMediaVideo(fl, thumb=thumb,width=videohw[0], height=videohw[1],duration=duration,supports_streaming=True))
up=app.send_media_group(int(l[1]),mediafiles)

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\x128b\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\methods\advanced\save_file.py", line 109, in worker
    await session.invoke(data)
  File "C:\Users\x128b\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\session\session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "C:\Users\x128b\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\session\session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\x128b\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 11 seconds is required (caused by "upload.SaveBigFilePart")
```

**Comment by pokzy** [comment]
The chat or group has a cooldown between messages.

**Comment by doublep21** [comment]
> The chat or group has a cooldown between messages.

actually no , the channel where i'm trying to upload it's mine

**Comment by doublep21** [comment]
was my mistake

**Comment by ndyanx** [comment]
How did you fix it?

**Comment by doublep21** [comment]
> How did you fix it?

https://github.com/pyrogram/pyrogram/issues/1306#issuecomment-2043484196
