### ISSUE TITLE
blockquote not worked

### ISSUE THREAD

**Issue by Yasin-Dev81** [pyrogram/pyrogram#1444]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When the blockquote tag is used, the text is displayed simply in Telegram

### Steps to reproduce

pass

**Comment by SpEcHiDe** [comment]
blockquote was introduced by Telegram in Layer 166. The repository is currently only at Layer 158.

You can try to use [a fork](https://telegramplayground.github.io/pyrogram/topics/text-formatting.html) at your own risk.

**Comment by Yasin-Dev81** [comment]
thanks
