### ISSUE TITLE
get_chat_history() doesn't start from offset_id

### ISSUE THREAD

**Issue by Sputchik** [pyrogram/pyrogram#1456]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Offset_id is treated as last message id to return instead of starting. Client doesn't use bot token

### Steps to reproduce

Change, make as argument 'min_id' in pyrogram.methods.messages.get_chat_history.get_chunk() method or make more human documentation if i'm wrong because that would be insane to who wrote this

### Code example

```python
async for message in client.get_chat_history(channel_id, limit = 0, offset_id = 444):
    msg_id = message.id
    print(msg_id)
    continue
```

### Logs

```shell
443
442
437
430
426
421
418
391
390
389
388
373
219
218
...
19
18
13
11
10
1
```

**Comment by SpEcHiDe** [comment]
The [documentation](https://docs.pyrogram.org/api/methods/get_chat_history) states:

`The messages are returned in reverse chronological order.`

` Identifier of the first message to be returned.`

**In my opinion, there isn't any bug here**.

**Comment by Sputchik** [comment]
🤡
