### ISSUE TITLE
TelegramGroup Problem

### ISSUE THREAD

**Issue by Padandish** [pyrogram/pyrogram#15]
Hi dears,
I joined to telegram group but haven't access?!

![capture](https://user-images.githubusercontent.com/26878830/35675602-dc9cc0e0-075d-11e8-9b78-e95b200f02ef.PNG)

**Comment by delivrance** [comment]
You are in Iran or some neighboring country, aren't you? Because supergroups are blocked there afaik.
If you want to join just contact me and I'll bring you in.
