### ISSUE TITLE
Instance of

### ISSUE THREAD

**Issue by applke** [pyrogram/pyrogram#151]
Hi, i am beginer in Python. Can u help me how to determine what is type of object.
` {
            "_": "telegram:ChannelAdminLogEvent",
            "id": 238701739760,
            "date": 1541018636,
            "user_id": 703213504,
            "action": {
                "_": "telegram:ChannelAdminLogEventActionParticipantJoin"
            }
        }`
I have this. In java i use if( a instance of Telegram.ChannelAdminLogEvent. How i can do it in python?

**Comment by delivrance** [comment]
@applke Hi, this is not the right place to ask python questions, but this is what you need: https://docs.python.org/3/library/functions.html#isinstance

Here in GitHub we should focus on asking questions about Pyrogram issues and features only.
For anything else that is still related you can join and ask our community in [@PyrogramChat](//t.me/pyrogramchat).
