### ISSUE TITLE
Floodwait on start client

### ISSUE THREAD

**Issue by Padandish** [pyrogram/pyrogram#16]
Hi dears,

When i call client.start(), program said:

> A wait of 74089 seconds is required

and waited on client.start() line without Error.
How can get error to handle my code flow?

Thanks

**Comment by delivrance** [comment]
By reading the documentation: https://docs.pyrogram.ml/resources/ErrorHandling/

**Comment by Padandish** [comment]
Thanks, I read documents, 

but program wait on client.start() line, without any Exception.
```

        try:
            if self.__client is not None:
                data['result'] = True
            else:
                session_path = self.__get_session_path()
                self.__client = Client(session_name=session_path,
                                       phone_number=str(self.__id),
                                       phone_code=phone_code_callback,
                                       password=self.__password)
                self.__client.start()

                me = self.__client.get_me()
                if hasattr(me, 'ID'):
                    self.__client_id = me.ID
                    data['result'] = True

        except FloodWait as ex:
            data['error'] = BadRequest.__name__
            data['error_log'] = ex
            pass
```

![capture](https://user-images.githubusercontent.com/26878830/35686929-bced6e14-0782-11e8-8460-5a91fc939a4b.PNG)

**Comment by delivrance** [comment]
``` python
try:
    ...  # Any interaction with the API
except FloodWait as e:
    time.sleep(e.x)  # e.x contains the amount of seconds you have to wait
```

**Comment by Padandish** [comment]
Yes, But "except FloodWait as e:" not called.

Please see video.
[2018-02-01_19-24-00.zip](https://github.com/pyrogram/pyrogram/files/1686172/2018-02-01_19-24-00.zip)

**Comment by delivrance** [comment]
Ok the video makes it clear now.
Your `except FloodWait as e` is not "called" because Pyrogram is blocking automatically, and it waits there for 71819 seconds and then automatically tries again to login.

**Comment by Padandish** [comment]
Can i handle blocking? when see this state, stop client and close program such as sys.exit()

**Comment by delivrance** [comment]
Sure, you are free to fork and make changes to the code.

**Comment by Padandish** [comment]
Thanks, i changed it.

I have suggestion, add callback to handle this state to future releases.

**Comment by i-Naji** [comment]
I have a client that has almost 500 group chats and about 3000 personal chats, I always get Floodwait because of get_dialogs when i call client.start() so I skipped this function during starting a client.
do you suggest any another solutions?

**Comment by delivrance** [comment]
@i-Naji I've wrapped the relevant method around a try..catch block. Now it is sleeping X seconds before continuing fetching the dialogs. Please try again using the master branch.
This is not a definitive solution, I'm planning in caching all the dialogs in the session file in order to speed the lib up.
