### ISSUE TITLE
How can I update unread mark of a message?

### ISSUE THREAD

**Issue by DrMartiner** [pyrogram/pyrogram#164]
Hello,

How can I update an unread mark of a message from ?

I try to do something:
```python
client = Client(...)
client.start()
for dialog in client.get_dialogs().dialogs:
    if not dialog.has_unread_messages:
        continue
    
    dialog_peer = client.resolve_peer(dialog.chat.id)
    for message in client.send(ReadHistory(dialog_peer, 3)):
        message_peer = client.resolve_peer(message.id)
        client.send(UpdateDialogUnreadMark(message_peer, True))
client.stop()
```

Best regards,
Aleksei

**Comment by delivrance** [comment]
@DrMartiner Hi, you tried to send a `type`, which you can't do in this way. You need 
[messages.MarkDialogUnread](https://docs.pyrogram.ml/functions/messages/MarkDialogUnread) instead.

For further questions about how to use the library I'll invite you to join [@PyrogramChat](//t.me/pyrogramchat). GitHub should be used for library issues and enhancement proposals. Thanks.
