### ISSUE TITLE
how to use with webhook mode

### ISSUE THREAD

**Issue by hossy13** [pyrogram/pyrogram#171]
hi
i want to use it on heroku service 
and use webhook for getting updates 
how i can do it?
i couldnt found anything in docs

**Comment by delivrance** [comment]
Pyrogram operates on a lower level by implementing the MTProto protocol which is built on top of TCP. There's no HTTP webhook involved, no polling whatsoever. All updates are automatically received via TCP socket from the server as soon as they are generated.

If you want webhooks you have to build something *on top* of Pyrogram itself.

**Comment by delivrance** [comment]
By the way, there are a bunch of people in [PyrogramChat]](//t.me/Pyrogramchat) who have successfully deployed Pyrogram applications on heroku. You can try asking there.
