### ISSUE TITLE
Allow to forward a copy of the message (without the forward header)

### ISSUE THREAD

**Issue by delivrance** [pyrogram/pyrogram#172]
Forwarded messages have headers on top of them telling from whom were originated. Telegram X and Plus Messenger have an option to forward a copy without the forward header.

**Comment by zeroone2numeral2** [comment]
How should this be handled, in your idea? A specific new method or a new `Client.forward_message()` argument (eg. `as_copy` that defaults to False?

**Comment by delivrance** [comment]
@zeroone2numeral2 Hi. An argument is what I thought initially and fits good imo; simply set it and the library does the job for you. I like ``as_copy``and looking at the apps another arg could be used to mimic the behaviour by removing media captions as well.

To implement this I think we must get_messages first (with the passed message IDs; calling the method is cheap enough) and re-send each one depending on the kind. Media messages can simply use the file_ids, where applicable. Text messages should obey to the original formatting options (bold, italic, ...).

**Comment by zeroone2numeral2** [comment]
Considering that atm there's anything that handles this many media types in pyrogram (maybe `Client.send_media_group()` only), what would be the correct approach?

The first thing that came to my mind was:

```py
def forward_message(chat_id, from_chat_id, message_id, disable_notification=False, as_copy=False, remove_caption=True):
  
  ...

  if as_copy:
    if message.text:
      self.send_message(chat_id, message.text.html, parse_mode=ParseMode.HTML)
    elif message.media:
      send = None  # will store the correct send_* method to use
      file_id = None
      caption = None
      parse_mode = None
      if message.document:
        send = self.send_document
        file_id = message.document.file_id
      elif message.audio:
        send = self.send_audio
        file_id = message.document.file_id
      elif message.sticker:
        send = self.send_sticker
        file_id = message.document.file_id
        remove_caption = True  # force this to True because stickers don't support captions
      ...

      if not remove_caption:
        caption = message.caption.html
        parse_mode = ParseMode.HTML

      send(chat_id, file_id, caption=caption, parse_mode=parse_mode)
```

But I don't think that storing the correct `client.send_*` method to use in a dedicated value would be a good thing to do. Maybe there would be some problems with send_audio/send_video, that accept a bunch of additional media properties like thumbnails or duration (shouldn't be the case because sending by file_id should preserve them)? The alternative would be to execute the `send_*` method directly in the "elif" branches. Not a fan of either these ways

**Comment by delivrance** [comment]
Your current proposal (`if`s) is the only good way to deal with this.

`Client.send_media_group()`, which is for albums and up to 10 photos/videos only, is out of any use here (even though we need to see what's the behaviour of forwarded albums; the method could be needed and would simply be in another `if` branch).

For each media branch we could simply call the relevant method and only store caption (I assume you chose HTML because Markdown is more problematic in terms of escaping characters).

```python
...
elif message.media:
    caption = None if remove_caption else message.caption.html
    parse_mode = ParseMode.HTML

    if message.document:
        self.send_document(chat_id, message.document.file_id, caption=caption, parse_mode=parse_mode)
    if message.sticker:
        self.send_sticker(chat_id, message.sticker.file_id)
    ...
```

We would also need to store each `send_*` result in a list to be able to return that to the user.

**Comment by delivrance** [comment]
I missed `disable_web_page_preview=not message.web_page`. Good catch, but I would add a brief `#TODO` near it to remind us we need to re-check this when the web_page feature will be reworked in the future.

Also, if you are going to implement this feel free to open a PR so that we can directly discuss and edit code in there.
