### ISSUE TITLE
Why use Telegram API key with bots?

### ISSUE THREAD

**Issue by qwez** [pyrogram/pyrogram#173]
According to official Telegram API doc, all you need for using a bot is a token. Why bot authorization proces wants API key? https://docs.pyrogram.ml/start/Setup#bot-authorization

I can make request `https://api.telegram.org/bot{bot_token}/sendMessage?chat_id={chat_id}&text={text}` without any api_id/api_hash

**Comment by delivrance** [comment]
Unpinning. There's now a dedicated FAQ: https://docs.pyrogram.org/faq#why-do-i-need-an-api-key-for-bots
