### ISSUE TITLE
The confirmation code has expired when another client in system is open

### ISSUE THREAD

**Issue by byehack** [pyrogram/pyrogram#186]
this https://github.com/LonamiWebs/Telethon/issues/799 is issue and you can see https://github.com/LonamiWebs/Telethon/commit/9445d2ba535ed7d214a7e6e68b85e7f3af1a690e for fix it.

you can also see more https://github.com/LonamiWebs/Telethon issues for update your project :]

**Comment by byehack** [comment]
> this [LonamiWebs/Telethon#799](https://github.com/LonamiWebs/Telethon/issues/799) is issue and you can see [LonamiWebs/Telethon@9445d2b](https://github.com/LonamiWebs/Telethon/commit/9445d2ba535ed7d214a7e6e68b85e7f3af1a690e) for fix it.
> 
> you can also see more https://github.com/LonamiWebs/Telethon issues for update your project :]

is it ok?

**Comment by delivrance** [comment]
First of all, that's an ancient issue and I'm not going to do anything unless you provide me some traceback logs and/or explaining to me *exactly* how to reproduce the issue.

**Comment by byehack** [comment]
> First of all, that's an ancient issue not even related to Pyrogram and I'm not going to do anything unless you provide me some traceback logs and/or explain to me _exactly_ how to reproduce the issue.

you can add phone_code_hash arg to Client class. and use it when sending phone_code

**Comment by delivrance** [comment]
The whole auth process is managed by the start() method. There's no need for the user to pass the phone code hash in the current implementation.

**Comment by byehack** [comment]
> The whole auth process is managed by the start() method. There's no need for the user to pass the phone code hash in the current implementation.

you can add phone_code_hash in session file

**Comment by delivrance** [comment]
> ...when this error raised...

[I still don't see any error ^^](https://github.com/pyrogram/pyrogram/issues/186#issuecomment-449977121).

**Comment by byehack** [comment]
add it to line 167:

phone_code_hash: str = None,

and it to 191:
self.phone_code_hash= phone_code_hash

and edit line 512 to:
phone_code_hash = self.phone_code_hash or r.phone_code_hash
