### ISSUE TITLE
Get Admin Log?

### ISSUE THREAD

**Issue by kernelpanic1** [pyrogram/pyrogram#187]
hey

**Comment by delivrance** [comment]
Hey

**Comment by delivrance** [comment]
![image](https://user-images.githubusercontent.com/14043624/50454480-2edc5e00-0948-11e9-9fab-1624b8e59446.png)

**Comment by delivrance** [comment]
@kernelpanic1 Ask in [@PyrogramChat](//t.me/pyrogramchat).

**Comment by byehack** [comment]
> @kernelpanic1 Ask in [@PyrogramChat](//t.me/pyrogramchat).

public group link doesnt work for me , can you give me your private gp link?

**Comment by ParsCoder** [comment]
> > @kernelpanic1 Ask in [@PyrogramChat](//t.me/pyrogramchat).
> 
> public group link doesnt work for me , can you give me your private gp link?

https://t.me/joinchat/F8VqcUbGxqwl4wimbrSnKA
