### ISSUE TITLE
fix documentation.

### ISSUE THREAD

**Issue by byehack** [pyrogram/pyrogram#194]
https://github.com/pyrogram/pyrogram/blob/develop/pyrogram/client/methods/messages/get_history.py  line 48 , forget ":" 😐

**Comment by delivrance** [comment]
Thanks, do want to open a PR for that?

**Comment by byehack** [comment]
no

> Thanks, do want to open a PR for that?

no

**Comment by byehack** [comment]
didnt fix!

**Comment by delivrance** [comment]
You didn't open a PR!

**Comment by byehack** [comment]
🐖🐖

**Comment by delivrance** [comment]
🐓🐓

**Comment by byehack** [comment]
dont fix😒

**Comment by byehack** [comment]
you know better than i, it is very big bug in somewhere😅😅
