### ISSUE TITLE
forget ":"

### ISSUE THREAD

**Issue by byehack** [pyrogram/pyrogram#195]
[get_history.py](https://github.com/pyrogram/pyrogram/blob/develop/pyrogram/client/methods/messages/get_history.py):48

**Comment by byehack** [comment]
[get_history.py](https://github.com/pyrogram/pyrogram/blob/develop/pyrogram/client/methods/messages/get_history.py):48

**Comment by delivrance** [comment]
You are one step away from getting blocked.
Stop open the same issue and send useless comments.
