### ISSUE TITLE
Error 400 with set_chat_photo and get_chat method

### ISSUE THREAD

**Issue by oscale05** [pyrogram/pyrogram#198]
I have tried to set a picture on a new private channel of which I am administrator.
Both with the set_chat_photo method and with the get_chat method I get the following error:

File "/usr/local/lib/python3.6/site-packages/pyrogram/client/methods/chats/get_chat.py", line 67, in get_chat
    peer = self.resolve_peer(chat_id)

 File "/usr/local/lib/python3.6/site-packages/pyrogram/client/methods/chats/set_chat_photo.py", line 54, in set_chat_photo
    peer = self.resolve_peer(chat_id)
 File "/usr/local/lib/python3.6/site-packages/pyrogram/client/client.py", line 1217, in resolve_peer
    raise PeerIdInvalid
I'm using >>> import pyrogram
>>> pyrogram.__version__
'0.10.4.develop'

thanks for your help

**Comment by delivrance** [comment]
@oscale05 Seems like you passed a wrong chat_id. You can get the right one with ``app.get_chat(<invite_link>)``

**Comment by oscale05** [comment]
@delivrance  thanx in advance for your answer. This is the result after execute functions.channels. CreateChannel:

"chats": [
        {
            "_": "telegram:Channel",
            "creator": true,
            "left": false,
            "editor": false,
            "broadcast": true,
            "verified": false,
            "megagroup": false,
            "restricted": false,
            "democracy": false,
            "signatures": false,
            "min": false,
            **"id": 1161463823**,
            "access_hash": 758067283413621027,
This is the id that I use with the set_chat_photo method and app.get.chat.
Is this correct?
Tnxs

**Comment by delivrance** [comment]
@oscale05 As I said, the correct id would be the one you find in the result coming from [get_chat](https://docs.pyrogram.ml/pyrogram/Client#pyrogram.Client.get_chat), which is **-1001161463823** in your case. More info: https://docs.pyrogram.ml/resources/AdvancedUsage#chat-ids.

**Comment by oscale05** [comment]
@delivrance  Prefect. It works.
Thanx a lot
