### ISSUE TITLE
Running pyrogram as a separate process.

### ISSUE THREAD

**Issue by oneprofittips** [pyrogram/pyrogram#200]
I want to run pyrogram as a separate process.
`
from pyrogram import Client, Filters
from multiprocessing import Process

path_to_file = 'my_account.session'
app = Client("my_account")

@app.on_message(Filters.chat(chats=-1001386552195))
def just_text(client, message):
    pass

if __name__ == "__main__":
    Process(target=app.run).start()
`
Does not start, gives an error. How can pyrogram be started by a separate process?
TypeError: can't pickle _thread.lock objects

**Comment by delivrance** [comment]
Hi. First of all, format your code. Make your issue look nice. Also, I can't see any traceback.

**Comment by delivrance** [comment]
Issue shifted to https://t.me/PyrogramChat/52359
Remember to always post the **full** traceback along with your non-working example next time.
