### ISSUE TITLE
Proposal for additional alternative to stop and continue update propagation

### ISSUE THREAD

**Issue by delivrance** [pyrogram/pyrogram#213]
We now have [.stop_propagation()](https://docs.pyrogram.ml/resources/MoreOnUpdates#stop-propagation) and [.continue_propagation()](https://docs.pyrogram.ml/resources/MoreOnUpdates#continue-propagation).
An additional way to set each behaviour as default was proposed:

```python
# Equivalent to calling message.stop_propagation()
@app.on_message(..., propagate=False)
def _(client, message):
    ...


# Equivalent to calling message.continue_propagation()
@app.on_message(..., propagate=True)
def _(client, message):
    ...


# Default behaviour, propagate=None
@app.on_message(...)
def _(client, message):
    ...
```

**Pro**: Nice usage of decorator parameters to change the default behaviour, saves you from calling the method or raising the exception explicitly inside function's body.

**Con**: You don't act on checks inside the function body, the dispatcher will continue propagating to the same group OR stop propagating to the other groups once the function finishes. Although, calling the method while also having `propagate` set will override the behaviour.

**Comment by JosXa** [comment]
I'd argue there should *never* be any checks inside a handler itself. Pyrogram's dispatcher system should clearly identify handlers that are applicable, or not. I would consider an early `if (...): return` in a callback an antipattern with regards to Pyrogram.

**Comment by delivrance** [comment]
@JosXa So, you are saying the *con* isn't really a con since you shouldn't be using any of such `if`s, right?

**Comment by JosXa** [comment]
Yes, that's my point. However I don't see a simple way to perform filter checks on properties that might (sometimes) require an `await` (and are cached afterwards so the filters still perform quickly).
