### ISSUE TITLE
Add convenience methods for entity counts

### ISSUE THREAD

**Issue by delivrance** [pyrogram/pyrogram#225]
We currently have [get_chat_members_count](https://docs.pyrogram.ml/pyrogram/Client#pyrogram.Client.get_chat_members_count) which returns a plain integer representing the total members count of a chat. Similar methods could be implemented for history (total messages count), dialogs (total dialogs count), and whatever else applies:

- [x] `get_history_count`
- [x] `get_dialogs_count`
- [x] `get_contacts_count`
- [x] `get_user_profile_photos_count`
...anything else?

Suggestions to alternative names are welcome!

**Comment by zeroone2numeral2** [comment]
Mmm, why has this been closed?

**Comment by delivrance** [comment]
@zeroone2numeral2 I implemented all the methods in the list, is there anything else to add?
