### ISSUE TITLE
Incorrect MIME type for images sent as documents

### ISSUE THREAD

**Issue by kdrag0n** [pyrogram/pyrogram#239]
All files sent as documents have been reported as ZIP files in the since commit 50cff068a071dac4cca352315f1462b229030f9e. This behavior can break some applications of `send_document` that rely on checking the MIME type of sent files.

For example, it is no longer possible to automate usage of the Stickers bot with Pyrogram. The bot expects PNG images sent as documents with the `image/png` MIME type, but Pyrogram now sends the `application/zip` MIME type which causes the bot to complain that the uploaded image is not a PNG image.

Reverting the `send_document.py` [changes](https://github.com/pyrogram/pyrogram/commit/50cff068a071dac4cca352315f1462b229030f9e#diff-061035e94dc9839167740e32d28648ed) from commit 50cff068a071dac4cca352315f1462b229030f9e fixes the issue.

**Comment by delivrance** [comment]
Thanks. Other people started to complain quite a bit as well. The main problem is that `mimetypes` is not good enough in my opinion; we need to gather some valid mime types (from official apps maybe) to make send_* methods work reliably and automatically.

Until we get there, maybe reverting that change and exposing `mime_type` as extra optional argument to each send_* method would be a better idea. What do you think?

**Comment by delivrance** [comment]
This looks like to be a great source of mime types: https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
