### ISSUE TITLE
Can you give an example of getting a channel's history messages ?

### ISSUE THREAD

**Issue by forever6** [pyrogram/pyrogram#242]
I have read the doc of https://docs.pyrogram.ml/functions/channels/GetChannels to get ID, but the result doesn't have an attribute of ID or something like that.
my life sucks , google and stack over flow can't help me out. the document that API is so simple, only some parameter need fill, but I have no idea of how to get the parameter like this:

Parameters: | id – List of either InputChannelEmpty or InputChannel

could you give me an example of get history message of a channel? ( know the channel' name and invite Link)

**Comment by zeroone2numeral2** [comment]
See [`Client.get_history()`](https://docs.pyrogram.ml/pyrogram/Client#pyrogram.Client.get_history)

**Comment by delivrance** [comment]
@forever6 Or better, iter_history(), in the examples folder: https://github.com/pyrogram/pyrogram/blob/develop/examples/history.py

Also worth reading: https://docs.pyrogram.ml/resources/AdvancedUsage
