### ISSUE TITLE
Telegram is deleting accounts

### ISSUE THREAD

**Issue by GooDeeJaY** [pyrogram/pyrogram#243]
I cannot sign in with pyrogram to telegram accounts. Actually, when I sign in, telegram is automatically banning(deactivating) an account. 
I don't know why! 
I've tried logging in multiple accounts using one api_id and api_hash, maybe that's why Telegram is deactivating accounts because only one account can be used for one api_id and api_hash???
I've tried changing system info (device_model, app_version, system_version) but it not helped...
Also, I've searched for socks5 proxies on the internet but all proxies that I found are not working at all. I don't wanna buy proxies... So, if someone knows the source of free proxies that work, let me know.

**Comment by delivrance** [comment]
@GooDeeJaY More extended information here https://github.com/pyrogram/pyrogram/issues/102 and here https://github.com/tdlib/td/issues/534.
