### ISSUE TITLE
A wait of 86400 seconds is required

### ISSUE THREAD

**Issue by LinArcX** [pyrogram/pyrogram#245]
Tor in my country is blocked by government. So i decide to use tor to connect to telegram. 
But when i want to use tor to identify, it give me this hint. i don't know what should i do to bypass this issue.
Any idea?

**Comment by delivrance** [comment]
@LinArcX You seem to be trying to log-in too often with the same phone number. Log-ins are quite expensive in terms of how many attempts you are allowed to in a day - I'm afraid you have to wait. Using a different api key might help.

**Comment by LinArcX** [comment]
Oh, i find the solution. actually tor try to change exit node ip frequently, so we can tell him to stop doing this for specific host/domains. by putting these two lines in the end of __torrc__ file, we don't get this hint any more:
```
TrackHostExits telegram.org
TrackHostExitsExpire 86400
```
