### ISSUE TITLE
Get recent actions

### ISSUE THREAD

**Issue by amirho3inf** [pyrogram/pyrogram#247]
hello
Is there a way to get recent actions of channel?

**Comment by delivrance** [comment]
@amirho3inf Of course, this is the method you need: https://docs.pyrogram.ml/functions/channels/GetAdminLog

**Comment by moein2016** [comment]
https://docs.pyrogram.org/telegram/types/channels/admin-log-results

**Comment by moein2016** [comment]
https://docs.pyrogram.org/telegram/functions/channels/get-admin-log#pyrogram.api.functions.channels.GetAdminLog

**Comment by amirho3inf** [comment]
> https://docs.pyrogram.org/telegram/functions/channels/get-admin-log#pyrogram.api.functions.channels.GetAdminLog

man this issue answered and closed 10 months ago stop commenting
