### ISSUE TITLE
how about "log_out"?

### ISSUE THREAD

**Issue by AidanDavis82** [pyrogram/pyrogram#249]
Now, i have a question about "log_out".
When i stop the program, i use "client.stop()" to end it.
But it does not terminate the session.
So how can i log out the session with pyrogram?

Thanks.

**Comment by delivrance** [comment]
Hi there, looks like you completely ignored the issue template. If you'd like to post a question, please move to https://stackoverflow.com or ask the Pyrogram community by joining the discussion at https://t.me/pyrogram.
