### ISSUE TITLE
Got 400 BOT_METHOD_INVALID after upgrade pyrogram

### ISSUE THREAD

**Issue by KunoiSayami** [pyrogram/pyrogram#250]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
Python version: `3.7.3`
I got `400 BOT_METHOD_INVALID` after upgrade pyrogram from `0.11.0` to `0.13.0` while using same session file.
Guess is session file missing `is_bot` member.

## Steps to Reproduce
Code for pyrogram `0.11.0`:

```python
# bot11.py
from pyrogram import Client

s = Client(
    bot_token, api_id, api_hash
)
s.start()
s.stop()
```

Then upgrade pyrogram version:

```bash
python3.7 -m pip install pyrogram --upgrade
```

Code for pyrogram  `0.13.0`:

```python
# bot13.py
from pyrogram import Client

s = Client(
    bot_token.split(':')[0], api_id, api_hash, bot_token = bot_token
)
s.start()
s.stop()
```

```bash
python3.7 bot11.py
python3.7 -m pip install pyrogram --upgrade
python3.7 bot13.py
```

Using `0.11.0` code to run `0.13.0` environment and change code to `0.13.0` version can avoid this problem.

## Traceback
```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    s.start()
  File "/usr/local/lib/python3.7/site-packages/pyrogram/client/client.py", line 321, in start
    raise e
  File "/usr/local/lib/python3.7/site-packages/pyrogram/client/client.py", line 314, in start
    self.send(functions.messages.GetPinnedDialogs(folder_id=0))
  File "/usr/local/lib/python3.7/site-packages/pyrogram/client/client.py", line 1039, in send
    r = self.session.send(data, retries, timeout)
  File "/usr/local/lib/python3.7/site-packages/pyrogram/session/session.py", line 429, in send
    return self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/pyrogram/session/session.py", line 416, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.7/site-packages/pyrogram/errors/rpc_error.py", line 71, in raise_it
    )(x=x)
pyrogram.errors.exceptions.bad_request_400.BotMethodInvalid: [400 BOT_METHOD_INVALID]: The method can't be used by bots
```

**Comment by KunoiSayami** [comment]
Traceback was generated under develop version

**Comment by delivrance** [comment]
@KunoiSayami Hi, thanks for the report. Your guess is right.

By using `bot_token.split(':')[0]`, you are actually bypassing the internal checks.
A possible fix for you it to run your client for once using the old code from v0.11.0 in the new version so that Pyrogram stores the new `is_bot` attribute in the session:

``` python
s = Client(bot_token, api_id, api_hash)
s.start()
s.stop()
```

Once you've done this, all the next runs plus your code using `bot_token.split(':')[0]` should work fine. You can also rename your session as `usernamebot.session` if you prefer, and use it as session_name, even without the bot token at all (bot tokens are only needed when creating a new session, pretty much like phone numbers).

```python
s = Client("usernamebot", api_id, api_hash)  # or bot_token.split(':')[0]
```
