### ISSUE TITLE
Custom file_name in messages.download method not working

### ISSUE THREAD

**Issue by JRafiei** [pyrogram/pyrogram#253]
## Checklist
- [ ] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [ ] I have searched in the issue tracker for similar bug reports, including closed ones.
reproduced the issue using the latest development version.

## Description
Previously, we could pass a file_name argument to the message.download method and the new downloaded file stored in that specified path. But now it is always ignored. The reason, as far as I understand, is the new changes in the following file:
_pyrogram/client/methods/messages/download_media.py_

In the download_media method, line 108 replaces the custom file_name with this value:
`file_name = getattr(media, "file_name", "")`
This value is then used in FileData object.
I think another name should be used to prevent changing the original file_name, something like data_file_name

**Comment by delivrance** [comment]
@JRafiei Hi, thanks for the report. This was fixed yesterday in https://github.com/pyrogram/pyrogram/commit/83af58258c2b6343f8684fb5bbaf80f05bf33a21.

To install the development version, follow the instructions here: https://docs.pyrogram.org/intro/install#bleeding-edge

**Comment by JRafiei** [comment]
Hi @delivrance, thats a good news! Thanks for  your efforts.
Does the asyncio branch get updated too?

**Comment by delivrance** [comment]
Yes, merged.

From time to time I keep the `asyncio` branch synced with the main develop branch.
