### ISSUE TITLE
add_contacts Error

### ISSUE THREAD

**Issue by mitya2back** [pyrogram/pyrogram#269]
Hello!
I want to add a contact by this method^
`from pyrogram import Client,InputPhoneContact`
`app = Client("test_ses",telegram_app_id,telegram_app_hash)`
`temp = InputPhoneContact(str(number), "str", str(number))`
`app.add_contacts(temp)`

    

But i see this

> builtins.TypeError:` getattr(): attribute name must be string

What i did not true?

**Comment by delivrance** [comment]
Hi, it seems like you ignored the template:

# Important
This place is for issues about Pyrogram, it's **not a forum**.

If you'd like to post a question, please move to https://stackoverflow.com or join the Telegram community at https://t.me/pyrogram. Useful information on how to ask good questions can be found here: https://stackoverflow.com/help/how-to-ask.

Thanks.
