### ISSUE TITLE
Add an easy method for updating profile pictures

### ISSUE THREAD

**Issue by i-paya** [pyrogram/pyrogram#27]
Hi , 
I want update my profile photo with this code 
```python3
client.send(
	functions.photos.UpdateProfilePhoto(types.InputPhoto(
			id=5798712647607234025,
			access_hash=-4552358589940473586)
	)
)
```
but it returns `"_": "types.UserProfilePhotoEmpty"` and removes current profile photo and does not change it .

**Comment by i-Naji** [comment]
I think you must use ```uploadProfilePhoto``` to update the user profile photo and then ```updateProfilePhoto``` to set previously uploaded photo as the profile photo.

**Comment by delivrance** [comment]
@i-paya Hi, you can't set the profile picture by using photos uploaded elsewhere (i.e. using only the id/hash pair), you have to upload a new photo each time you want to update. @i-Naji is correct, but you just use `photos.uploadProfilePhoto`. To get the needed `InputFile` you can use `file = client.save_file("path/to/photo.jpg")`

**Comment by delivrance** [comment]
Done. `set_user_profile_photo` will be available in the next version
