### ISSUE TITLE
Wrong DC2 IP

### ISSUE THREAD

**Issue by theunravelghoul** [pyrogram/pyrogram#280]
## Checklist
- [X] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [X] I have searched in the issue tracker for similar bug reports, including closed ones.
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
Looks like Telegram data centers IPs are incorrect.
My Telegram API app page says that DC2 IP is `149.154.167.50:443`, but Pyrogram uses  `149.154.167.51:443`. 
Also, though Telegram API app page says that my app should use DC2, Pyrogram tries to connect to DC1. 
So every time I'm trying to start the client it's bascially falls into endless "connecting - timed out - reconnecting" cycle.

## Steps to Reproduce
[A minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
```
client = Client("session_name", api_id, api_hash...)
client.start()
```

**Comment by delivrance** [comment]
Hi. I can't reproduce. I'm able to successfully connect to all five (actually four) DCs from my location, including DC1 and DC2; please make sure you are able to reach Telegram from your location too, you might need a proxy in case your ISP is trying to block Telegram.

Do not worry about IPs, they are correct even if they don't match with what you see from my.telegram.org. Pyrogram takes them from the server configuration through the dedicated MTProto API method, which holds the most up to date values.

The reason why Pyrogram tries to connect to DC1 first is that it doesn't know yet which DC your user is associated to until the server replies with the correct one in case of an error, so it guesses DC1 as first attempt.

**Comment by theunravelghoul** [comment]
Ok, got it. 
But still can’t understand why I can’t connect. 
Telegram Desktop client is running in my machine, so Telegam is definitely reachable from my network.

**Comment by theunravelghoul** [comment]
```
client = Client(
            session_name=self.phone_number,
            api_id=connection.telegram_app_id.api_id,
            api_hash=connection.telegram_app_id.api_hash,
            phone_number=self.phone_number,
        )
        client.run()
```

And

```
odoo_1           | 2019-07-14 11:26:14,655 1 INFO DEV pyrogram.session.auth: Start creating a new auth key on DC1 
odoo_1           | 2019-07-14 11:26:14,655 1 INFO DEV pyrogram.connection.connection: Connecting... 
odoo_1           | 2019-07-14 11:26:24,658 1 WARNING DEV pyrogram.connection.connection: timed out 
odoo_1           | 2019-07-14 11:26:25,660 1 INFO DEV pyrogram.connection.connection: Connecting... 
odoo_1           | 2019-07-14 11:26:35,668 1 WARNING DEV pyrogram.connection.connection: timed out 
odoo_1           | 2019-07-14 11:26:36,670 1 INFO DEV pyrogram.connection.connection: Connecting... 
odoo_1           | 2019-07-14 11:26:46,671 1 WARNING DEV pyrogram.connection.connection: timed out 
odoo_1           | 2019-07-14 11:26:47,673 1 WARNING DEV pyrogram.connection.connection: Connection failed! Trying again... 
odoo_1           | 2019-07-14 11:26:48,674 1 INFO DEV pyrogram.connection.connection: Disconnected 
odoo_1           | 2019-07-14 11:26:48,674 1 INFO DEV pyrogram.session.auth: Start creating a new auth key on DC1 
odoo_1           | 2019-07-14 11:26:48,674 1 INFO DEV pyrogram.connection.connection: Connecting... 
odoo_1           | 2019-07-14 11:26:58,684 1 WARNING DEV pyrogram.connection.connection: timed out 
odoo_1           | 2019-07-14 11:26:59,686 1 INFO DEV pyrogram.connection.connection: Connecting... 
```

**Comment by theunravelghoul** [comment]
Hm, I think I know where the problem is. 
Is this behaviour possible if session file can not be created?
My app is running in Docker container. I've just created small script outside the container and it works fine.

**Comment by theunravelghoul** [comment]
Is there a way to specify session files location?

**Comment by delivrance** [comment]
> Is this behaviour possible if session file can not be created?

Could be, what happens if you pass `:memory:` as session_name? This will create an in-memory session and nothing gets written on disk.
