### ISSUE TITLE
Support for in-memory file downloads

### ISSUE THREAD

**Issue by OctoNezd** [pyrogram/pyrogram#284]
## Checklist
- [ ] I believe the idea is awesome and would benefit the library.
- [ ] I have searched in the issue tracker for similar requests, including closed ones.
- [ ] Currently you can only download to file by path, not to BytesIO/anyotherIO or just bytes
- [ ] Feature parity with plain bot API libraries

## Description
An argument `out` for message.download, which is annotated by io.IOBase and downloads to specified file-like object. If both `file_name` and `out` are specified, throw exception

**Comment by Bibo-Joshi** [comment]
Hi. 1e8c981 linked above apparently added such functionality, but IISC 4a8e6fb855785588d79825f8ed6ade649fc1d6e8 removed it again. Are there any plans to bring this functionality back?

**Comment by gmankab** [comment]
still actual

**Comment by Bobronium** [comment]
@delivrance, can we get any comments regarding this feature? I think, motivation is clear. What's preventing it from being added to `pyrogram`?

**Comment by delivrance** [comment]
Hi. This feature will finally be available in the next major release.

**Comment by Bobronium** [comment]
Just to let you know, guys: it's available with latest release (2.0.0).

I'm sad it wasn't referenced here before and issue was closed prior to the release.
