### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by shamloo** [pyrogram/pyrogram#294]
Great Library.
I am using it and its ok.
in many times i get " sqlite3.OperationalError: database is locked " errors and it stops working.
in there any way to solve this?

**Comment by AyraHikari** [comment]
Make sure bot is not running.

If you're using Linux, make sure your work dir owner is your, if you logged in as user but workdir owner is root, it will not allow you to read database.
To change owner just type
`chown user workdir -R`

If you're using windows, try update to python 3.7, because python3.6.0 have bug at this.

Based on my experience

**Comment by shamloo** [comment]
Seems SQLite dose not support concurrent connection 
can we use another storage ?

**Comment by delivrance** [comment]
> Seems SQLite dose not support concurrent connection

SQLite does support multiple concurrent connections, but Pyrogram doesn't do anything to allow this nicely, on purpose. The error is a nice-to-have in order to protect the database integrity.

What do you need concurrent connections for? You should not mess with the session in any way, it's only an internal detail needed to cache peers and persist the session so that you don't have to login again when you restart the client.

If you want to run multiple client instances using the same account, please read this: https://docs.pyrogram.org/faq#can-i-use-multiple-clients-at-once-on-the-same-account

**Comment by shamloo** [comment]
Thank you for your good support.
but still problem

- OS :  CentOS release 6.10 (Final)
- python version : 3.6
- SQLite format 3
- Code struct:
```
app = Client(
                        session_name = client_name,
                        api_id=******,
                        api_hash="**************************",
                        bot_token=***********************,
                        no_updates = True
                )
app.start()
app.send_message(111111111, "Hi, it's me!")
app.stop()
```

**Comment by delivrance** [comment]
@shamloo Send the full traceback of the error and the full Python version (`python3.6 --version`).

**Comment by shamloo** [comment]
```
Traceback (most recent call last):
  File "/root/tdlib/td/py/pyrogram/client/ext/syncer.py", line 80, in sync
    client.storage.save()
  File "/root/tdlib/td/py/pyrogram/client/storage/memory_storage.py", line 91, in save
    self.date = int(time.time())
  File "/root/tdlib/td/py/pyrogram/client/storage/memory_storage.py", line 223, in date
    self._set(value)
  File "/root/tdlib/td/py/pyrogram/client/storage/memory_storage.py", line 190, in _set
    (value,)
sqlite3.OperationalError: database is locked
```


```
python3.6 --version
Python 3.6.6

```

**Comment by delivrance** [comment]
@shamloo with your authorized session, call `export_session_string` and use that to restart the client as explained here: https://docs.pyrogram.org/topics/storage-engines#session-strings

Tell me what happens.

**Comment by shamloo** [comment]
Code:
```
app = Client(
session_name = str(client_name),
api_id=********,
api_hash="****************",
bot_token="********:**************************",
no_updates = True
)
app.start()
app.send_message(chat_id, "Hi, it's me!")
with Client(":memory:") as app:
  print(app.export_session_string())
  f = open("my_bot", 'w')
  f.write(app.export_session_string())
  f.close()


app.stop()
```

output:
`Enter phone number: 
`

config.ini file also present:
```
[pyrogram]
api_id = *********
api_hash = "***************"
bot_token="**************:**********************"
no_updates = True
```

**Comment by shamloo** [comment]
@delivrance , Actually i want to use your library to complete my bot , due to lack of a method to delete other bots messages method in Bot API.
any simple and straight solution would be appreciated

**Comment by shamloo** [comment]
@delivrance 
I am looking forward to hearing from you

**Comment by delivrance** [comment]
> seems app.export_session_string() work for user mode , not bot login mode

It works, but you have to login first, then use the result from `export_session_string` as session name.

About this issue, I've added a new FAQ: https://docs.pyrogram.org/dev/faq#sqlite3-operationalerror-database-is-locked

**Comment by shamloo** [comment]
i logged in and then using memory method , its shown on sample code.
i am using different session name for each bot base of bot id

**Comment by delivrance** [comment]
@shamloo This place is not intended for questions, but for issues with the library. Please join our community and ask there instead: https://t.me/pyrogram

**Comment by uday5495pl** [comment]
first find running python3 process
sudo ps -a

==========
 8749 pts/1    00:00:00 screen
10093 pts/2    00:00:01 python3
10169 pts/2    00:00:00 sudo
10170 pts/2    00:00:00 ps
================

step 2
kill python3 

sudo kill -9 10093

**Comment by SergoZar** [comment]
This is because when you press ctrl + Z (or an error occurs) the script is disabled "aggressively" (or killed) and therefore the data exchanged by the script with the database is terminated. To avoid this, the script must be disabled with Ctrl + C.

p.s. I hope the translation is correct

**Comment by dshahrokhian** [comment]
For anyone facing the same issue 3 years later... just make sure you're using "with" statement with any client operations:

client = Client(ACC_NAME, api_id=API_ID, api_hash=API_HASH)

with client:
  # your methods using pyrogram client
