### ISSUE TITLE
400 AUTH_BYTES_INVALID error when downloads images

### ISSUE THREAD

**Issue by SCP-079-MIRROR** [pyrogram/pyrogram#299]
## Checklist
- [ ] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
Occasionally, this error occurs when downloading images, and only when I restart the program can I resume normal downloads.

## Traceback
```
ERROR - [400 Bad Request]: [400 AUTH_BYTES_INVALID] (caused by "auth.ImportAuthorization")
Traceback (most recent call last):
  File "/xxx/lib/python3.6/site-packages/pyrogram/client/client.py", line 834, in download_worker
    progress_args=progress_args
  File "/xxx/lib/python3.6/site-packages/pyrogram/client/client.py", line 1491, in get_file
    bytes=exported_auth.bytes
  File "/xxx/lib/python3.6/site-packages/pyrogram/session/session.py", line 437, in send
    return self._send(data, timeout=timeout)
  File "/xxx/lib/python3.6/site-packages/pyrogram/session/session.py", line 424, in _send
    RPCError.raise_it(result, type(data))
  File "/xxx/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 73, in raise_it
    is_unknown=True)
pyrogram.errors.exceptions.bad_request_400.BadRequest: [400 Bad Request]: [400 AUTH_BYTES_INVALID] (caused by "auth.ImportAuthorization")
```

**Comment by delivrance** [comment]
@SCP-079-MIRROR Hi. Thanks for the report.

Can you provide a minimal example that triggers the error so I can reproduce it myself?

**Comment by SCP-079-MIRROR** [comment]
This error is not generated only by certain images or stickers. 

A simple example (and also this program) is to download the images and stickers sent by users in groups. 

```python3
import logging
from os.path import exists
from random import choice
from string import ascii_letters, digits

from pyrogram import Client, Filters, Message

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.WARNING,
    filename='log',
    filemode='w'
)

logger = logging.getLogger(__name__)
app = Client(
    session_name="bot",
    bot_token="bla:bla"
)


@app.on_message(Filters.incoming & Filters.group & Filters.media)
def download(client: Client, message: Message):
    # Download images and stickers in groups
    try:
        if message.photo or message.sticker:
            if message.photo:
                file_id = message.photo.file_id
            else:
                file_id = message.sticker.file_id

            if file_id:
                file_path = get_new_path()
                client.download_media(message=file_id, file_name=file_path)
    except Exception as e:
        logger.warning(f"Download error: {e}", exc_info=True)


def get_new_path() -> str:
    # Get a new path in tmp directory
    result = ""
    try:
        file_path = random_str(8)
        while exists(f"tmp/{file_path}"):
            file_path = random_str(8)

        result = f"tmp/{file_path}"
    except Exception as e:
        logger.warning(f"Get new path error: {e}", exc_info=True)

    return result


def random_str(i: int) -> str:
    # Get a random string
    text = ""
    try:
        text = "".join(choice(ascii_letters + digits) for _ in range(i))
    except Exception as e:
        logger.warning(f"Random str error: {e}", exc_info=True)

    return text


app.run()
```

This program runs two copies on different machines (A and B), with the same bot token, so there are two sessions. 

Occasionally this error only occurs on a particular machine (A), but once this error occurs, any images (stickers) sent by users cannot be downloaded successfully (AUTH_BYTES_INVALID). Only when I restart this program on A, this error no longer appears for quite some time. 

I tried (several times) to delete the `bot.session` file on A and restarted the program, but after a period of time, the error still occurs occasionally, maybe once a day.

After I opened the issue, I deleted the `bot.session` file again and started the program. So far, this error has not occurred.

By the way, the two programs are restarted by `systemd` every day. The B machine restarts the program at 18:20 (for example) every day, and the A machine restarts the program at 18:30 (ten minutes later than B) every day.

**Comment by delivrance** [comment]
@SCP-079-MIRROR Thanks for the detailed answer, this is just an unlucky race condition between clients in machine A and B.

For `auth.ImportAuthorization` to succeed, the result from `auth.ExportAuthorization` must remain valid; any subsequent call would invalidate the previous result. In your case, both clients executed the export method at the same time and this lead to the generated auth bytes being invalidated server side for one of the clients, hence the error.

c1321a4c0115906814f687a5dab4cf91e094ee54 fixes this by narrowing the window in which this export & import process is done and also adds a retry mechanism.
