### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by JohnSmith2000** [pyrogram/pyrogram#30]
root@static:~/pybot/pyrogram# pip install --upgrade pyrogram
Collecting pyrogram
  Using cached Pyrogram-0.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ZKdZJV/pyrogram/setup.py", line 24, in <module>
        from compiler.api import compiler as api_compiler
      File "/tmp/pip-build-ZKdZJV/pyrogram/compiler/__init__.py", line 2
    SyntaxError: Non-ASCII character '\xc3' in file /tmp/pip-build-ZKdZJV/pyrogram/compiler/__init__.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ZKdZJV/pyrogram/

i cant install

**Comment by delivrance** [comment]
Use pip3 (Python 3)
