### ISSUE TITLE
get_chat - example

### ISSUE THREAD

**Issue by erichegit** [pyrogram/pyrogram#307]
I am trying to call get_chat, but have no success.

```
from pyrogram import Client

app = Client("my_account")
target = "-321075741"

#chat = app.get_chat("pyrogram")
#print(chat)

with app:
	for mychat in app.get_chat(target):
		print(str(mychat.chat.description))
```
Does`t matter if I provide an String with the Channel name or the ID, always I get

```
Traceback (most recent call last):
  File "/home/pi/telegram/getchat.py", line 12, in <module>
    for member in app.get_chat(target):
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/types/object.py", line 82, in __getitem__
    return getattr(self, item)
TypeError: getattr(): attribute name must be string
```

Sadly the in the code mentioned example fails too

```
        Example:
            .. code-block:: python
                chat = app.get_chat("pyrogram")
                print(chat)
```

thats why I am stuck :(

**Comment by delivrance** [comment]
@erichegit [Chat](https://docs.pyrogram.org/api/types#pyrogram.Chat) objects are not not iterable and most of the examples assume you have read some docs to set your application up, first. This is to keep them concise without useless noise. Read https://docs.pyrogram.org/start/invoking.

Furthermore, this place is for issues with the library code, not people's code. Such questions may go to https://stackoverflow.com or https://t.me/pyrogram.
