### ISSUE TITLE
Add live location

### ISSUE THREAD

**Issue by Sorrow2** [pyrogram/pyrogram#320]
Feature request:
Implement sending and editing live location to keep up with telegram api

**Comment by zeroone2numeral2** [comment]
Pyrogram already support live locations.

Live location updates are just edited messages updates you can handle with [`pyrogram.MessageHandler`](https://docs.pyrogram.org/api/handlers#pyrogram.MessageHandler) that tell you that a message containing a location has been edited.

You can update a location object you've previously sent with [`pyrogram.api.functions.messages.EditMessage`](https://docs.pyrogram.org/telegram/functions/messages/edit-message#pyrogram.api.functions.messages.EditMessage)

**Comment by GowthamSaminathan** [comment]
Hi i am new to this one , can you please explain me how to get the location update, i tried the below code but getting None in location .

`from pyrogram import Client
from pyrogram import filters

app = Client("my_account",api_id=API_ID,api_hash=API_HASH)

@app.on_message(filters.location)
async def location(client, message):
    print("Location received...")
    print(message.location)
app.run()`

**Comment by ColinTheShark** [comment]
Hi @GowthamSaminathan, this is not a Q&A Forum for how things work. If you don't have a bug report or feature request I advise you to join [@PyrogramChat](https://t.me/PyrogramChat) or the [Offtopic Lounge](https://t.me/PyrogramLounge). Also please do not necro old issues (Oct 2019) if yours isn't strictly related to the issue at hand.


<details><summary>Old Answer I had already written out before changing my mind to the above.</summary>

> from pyrogram import Client
> from pyrogram import filters
> 
> app = Client("my_account",api_id=API_ID,api_hash=API_HASH)
> 
> @app.on_message(filters.location)
> async def location(client, message):
> print("Location received...")
> print(message.location)
> app.run()

Your code would err with `IndentationError`s. Please indent your entire block of code with [four spaces on every line](https://i.imgur.com/4E49uHH.png) or wrap it in triple backticks.

    ```
    code here
    ```

----

Using this below handler yields the results as expected.

```python
@app.on_message(filters.location)
def print_location(_, m):
    print(m.location)
``` 

```python
{
    "_": "Location",
    "longitude": 10.00504840523306,
    "latitude": 53.55674938791926  
}
```
</details>
