### ISSUE TITLE
Plain 2FA password input

### ISSUE THREAD

**Issue by RadRussianRus** [pyrogram/pyrogram#328]
When entering 2FA password it is shown in plain text. This is because it uses `input`:

https://github.com/pyrogram/pyrogram/blob/945bc61262f3cad9fa15a441a3834e1819cedd39/pyrogram/client/client.py#L711-L712

I suggest to replacing it with with [getpass.getpass()](https://docs.python.org/3/library/getpass.html#getpass.getpass).

**Comment by zeroone2numeral2** [comment]
iirc `getpass` was causing some login issues when using pyrogram from Windows or some specific terminals, see [this](https://t.me/PyrogramChat/26228) and [this](https://t.me/PyrogramChat/37355) discussions in the chat

**Comment by delivrance** [comment]
Also, I'm not aware of any way of making `getpass` async.

**Comment by RadRussianRus** [comment]
It uses on login, and manual login process (where this is used) is not async anyway. Or I'm missing something?

Though problems on other terminals is more serious. I'd suggest to use escape codes, but I think problems will be the same.

**Comment by delivrance** [comment]
Partially fixed with `hide_password` Client parameter. getpass still misbehaves in some environments for some reason.
