### ISSUE TITLE
stop_poll() is broken

### ISSUE THREAD

**Issue by trenoduro** [pyrogram/pyrogram#338]
I have this little function that sends a poll when a specific command is submitted

    def on_command(client: Client, message: Message):

        poll = message.reply_poll('Question', ['opt1', 'opt2'])
        time.sleep(10)

        chat_id = poll.chat.id
        mess_id = poll.message_id

        client.stop_poll(chat_id, mess_id)

But the method stop_poll() raises an AttributeError Exception in the end

```
-------
  File "C:\Users\*****\.venv\lib\site-packages\pyrogram\api\core\primitives\int.py", line 32, in __new__
    return value.to_bytes(cls.SIZE, "little", signed=signed)
AttributeError: 'str' object has no attribute 'to_bytes'
```

**This is because the poll.poll.id (message.poll.id) is parsed as a string while it's expecting an int in the end**

**Comment by nocturn9x** [comment]
just do `int(message.poll.id)`

**Comment by ColinTheShark** [comment]
FYI: #339 

Someone already proposed changes to fix this error.
