### ISSUE TITLE
Retrying error

### ISSUE THREAD

**Issue by i-paya** [pyrogram/pyrogram#34]
Hi 
I ran my program 1 hour ago and now it shows retrying error and doesn't work .
How can I skip this error without crashing ?

**Comment by delivrance** [comment]
Please provide more information. Where exactly are you running your program (desktop, vps, raspberry pi, ...)? What's your internet speed? Are you using TgCrypto? Also show me the error you got.

**Comment by i-paya** [comment]
I run my program On ubuntu 16 and I also use TgCrypto.

**Comment by delivrance** [comment]
@i-paya That "error" means the response to a method call hasn't been received in time. This should never happen, but in the current implementation a slow net or machine can trigger this, and currently the solution would be to increase the WAIT_TIMEOUT to something higher than 10 seconds (which is what I'm gonna do now).

Can you post the warnings you got? I'd like to have a look at which method caused this.

**Comment by delivrance** [comment]
Closing due inactivity. You can reopen if you provide more info.
