### ISSUE TITLE
Strange behavior using numerical IDs for get_chat method

### ISSUE THREAD

**Issue by solipsy** [pyrogram/pyrogram#344]
## Checklist
- [ ] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [ ] I have searched in the issue tracker for similar bug reports, including closed ones.
- [ ] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
When requesting information about a chat with a numerical ID, Pyrogram sometimes does not return a response (throws PEER_ID_INVALID). If a string ID of same chat is known, the request returns a response. Then, using same numerical ID for another request, a response is returned. 

## Steps to Reproduce
app = Client("lrsrvr")
app.start()
try:
    res = app.get_chat("1001006503122")
    print(res)
except Exception as exc:
    print(exc)
try:
    res = app.get_chat("-1001006503122")
    print(res)
except Exception as exc:
    print(exc)

try:
    res = app.get_chat("durov")
    print(res)
except Exception as exc:
    print(exc)

try:
    res = app.get_chat("1001006503122")
    print(res)
except Exception as exc:
    print(exc)
try:
    res = app.get_chat("-1001006503122")
    print(res)
except Exception as exc:
    print(exc)

Returns:

[400 PEER_ID_INVALID]: The id/access_hash combination is invalid 
[400 PEER_ID_INVALID]: The id/access_hash combination is invalid 
{
    "_": "pyrogram.Chat",
    "id": -1001006503122,
    "type": "channel",
    "is_verified": true,
    "is_restricted": false,
    "is_scam": false,
    "title": "Durov's Channel",
    "username": "durov",
    "photo": {
        "_": "pyrogram.ChatPhoto",
        "small_file_id": "AQADAQATKaHSLwAEAgADLutc7xb____elyBsgWT1iX2jAAIWBA",
        "big_file_id": "AQADAQATKaHSLwAEAwADLutc7xb____elyBsgWT1iX-jAAIWBA"
    },
    "description": "This is where I post thoughts about Telegram in a slightly less formal and more direct way than in the official Telegram blog.",
    "can_set_sticker_set": false,
    "members_count": 332587
}
[400 PEER_ID_INVALID]: The id/access_hash combination is invalid 
{
    "_": "pyrogram.Chat",
    "id": -1001006503122,
    "type": "channel",
    "is_verified": true,
    "is_restricted": false,
    "is_scam": false,
    "title": "Durov's Channel",
    "username": "durov",
    "photo": {
        "_": "pyrogram.ChatPhoto",
        "small_file_id": "AQADAQATKaHSLwAEAgADLutc7xb____elyBsgWT1iX2jAAIWBA",
        "big_file_id": "AQADAQATKaHSLwAEAwADLutc7xb____elyBsgWT1iX-jAAIWBA"
    },
    "description": "This is where I post thoughts about Telegram in a slightly less formal and more direct way than in the official Telegram blog.",
    "can_set_sticker_set": false,
    "members_count": 332587
}

## Traceback

Traceback (most recent call last):
  File "/home/virostatiq/telegram-server/venv/lib/python3.6/site-packages/pyrogram/client/client.py", line 1659, in resolve_peer
    return self.storage.get_peer_by_id(peer_id)
  File "/home/virostatiq/telegram-server/venv/lib/python3.6/site-packages/pyrogram/client/storage/sqlite_storage.py", line 108, in get_peer_by_id
    raise KeyError("ID not found: {}".format(peer_id))
KeyError: 'ID not found: 1001006503122'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/virostatiq/telegram-server/venv/lib/python3.6/site-packages/pyrogram/client/client.py", line 1682, in resolve_peer
    return self.storage.get_peer_by_phone_number(peer_id)
  File "/home/virostatiq/telegram-server/venv/lib/python3.6/site-packages/pyrogram/client/storage/sqlite_storage.py", line 133, in get_peer_by_phone_number
    raise KeyError("Phone number not found: {}".format(phone_number))
KeyError: 'Phone number not found: 1001006503122'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/virostatiq/PycharmProjects/lang/telegram-server/test_history.py", line 175, in <module>
    res = app.get_chat("1001006503122")
  File "/home/virostatiq/telegram-server/venv/lib/python3.6/site-packages/pyrogram/client/methods/chats/get_chat.py", line 75, in get_chat
    peer = self.resolve_peer(chat_id)
  File "/home/virostatiq/telegram-server/venv/lib/python3.6/site-packages/pyrogram/client/client.py", line 1684, in resolve_peer
    raise PeerIdInvalid
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid

**Comment by ColinTheShark** [comment]
## Keep in mind:
Please make sure to tick off the fields `[ ]` -> `[x]` if you can confirm those to be True.

In addition to that, please format the Code and Traceback by intending the whole block by four (4) spaces, to make it a codeblock and easier to read.

## Now for your error:
You have passed only numerical IDs, as a string. Pyrogram tries to resolve those as a username, if it can't find those, it tries them as a phone number. If that still doesn't match, you get an error.

Try to use the method with an integer, as the IDs you tried, are integers.

    app.get_chat(-100123456789)
    >>> {
        "_": "pyrogram.Chat",
        "id": -100123456789,
        # For brevity sake I left the rest out
    }

**Comment by solipsy** [comment]
Is it possible that the problems with getting response from get_chat is somehow related to the OS, or maybe with Pyrogram storage, that could be related with permissions?

I'm testing on two computers: 

Ubuntu 18.04 (works as expected)
CentOS Linux release 7.6.1810 (Core) (does not work) 

Code:
```
def simple_test():
    app = Client("lrsrvr")
    app.start()
    print("resolve peer -1001097615402")
    print(app.resolve_peer(-1001097615402))
    print("get_chat, id: -1001097615402")
    res = app.get_chat(-1001097615402)
    print(res)
    return
```

Result on Ubuntu:

```
resolve peer -1001097615402
{
    "_": "types.InputPeerChannel",
    "channel_id": 1097615402,
    "access_hash": -387385235629597443
}
get_chat, id: -1001097615402
{
    "_": "pyrogram.Chat",
    "id": -1001097615402,
    "type": "channel",
    "is_verified": false,
    "is_restricted": false,
    "is_scam": false,
    "title": "Programmer_jokes",
    "username": "programmer_jokes",
    "photo": {
        "_": "pyrogram.ChatPhoto",
        "small_file_id": "AQADBAATjlH1GQAEAgAD1qfu6Rb____9HBE_Lruf-g-qAgABFgQ",
        "big_file_id": "AQADBAATjlH1GQAEAwAD1qfu6Rb____9HBE_Lruf-hGqAgABFgQ"
    },
    "description": "There are only 10 types of people in the world:\nThose who understand binary and\nthose who don't. ; )",
    "can_set_sticker_set": false,
    "members_count": 317
}

```

Result on CentOS:

```
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/pyrogram/client/client.py", line 1659, in resolve_peer
    return self.storage.get_peer_by_id(peer_id)
  File "/venv/lib/python3.6/site-packages/pyrogram/client/storage/sqlite_storage.py", line 108, in get_peer_by_id
    raise KeyError("ID not found: {}".format(peer_id))
KeyError: 'ID not found: -1001097615402'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_endpoints.py", line 129, in <module>
    simple_socket_test()
  File "test_endpoints.py", line 123, in simple_socket_test
    print("resolve peer", app.resolve_peer(-1001097615402))
  File "/venv/lib/python3.6/site-packages/pyrogram/client/client.py", line 1713, in resolve_peer
    access_hash=0
  File "/venv/lib/python3.6/site-packages/pyrogram/client/client.py", line 1381, in send
    r = self.session.send(data, retries, timeout)
  File "/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 436, in send
    return self._send(data, timeout=timeout)
  File "/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 423, in _send
    RPCError.raise_it(result, type(data))
  File "/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 84, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: [400 CHANNEL_INVALID]: The channel parameter is invalid (caused by "channels.GetChannels")
^CException ignored in: <module 'threading' from '/usr/lib64/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib64/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

```

I'll be very grateful for any indication to help resolve this problem.

Thanks!

**Comment by solipsy** [comment]
I'm repeating the main issue. To properly test it, the session file has to be deleted, and the client registered anew.

If chat info is requested with an integer ID, it fails. 
Then, if string alias is known, the request succeeds.
Finally, the request using the same integer ID succeeds.

Code:
```
def test_by_id(token=None):
    app = Client("a")
    app.start()
    print("\nRequesting get_chat with:", token)
    try:
        res = app.get_chat(token)
        print("Success!")
        print(res)
    except Exception as e:
        print("Error!")
        print(e)
    app.stop()
    return


test_by_id(token=-1001424046953)
test_by_id(token="slovenia_tips")
test_by_id(token=-1001424046953)
```

Returns this:
```
Requesting get_chat with: -1001424046953
Error!
[400 CHANNEL_INVALID]: The channel parameter is invalid (caused by "channels.GetChannels")

Requesting get_chat with: slovenia_tips
Success!
{
    "_": "pyrogram.Chat",
    "id": -1001424046953,
    "type": "channel",
    "is_verified": false,
    "is_restricted": false,
    "is_scam": false,
    "title": "Slovenia Tips",
    "username": "slovenia_tips",
    "photo": {
        "_": "pyrogram.ChatPhoto",
        "small_file_id": "AQADBAAT2gkfGwAEAgADl7R51hb___8b4Rj4jUST3pwjBwABFgQ",
        "big_file_id": "AQADBAAT2gkfGwAEAwADl7R51hb___8b4Rj4jUST3p4jBwABFgQ"
    },
    "can_set_sticker_set": false,
    "members_count": 59
}

Requesting get_chat with: -1001424046953
Success!
{
    "_": "pyrogram.Chat",
    "id": -1001424046953,
    "type": "channel",
    "is_verified": false,
    "is_restricted": false,
    "is_scam": false,
    "title": "Slovenia Tips",
    "username": "slovenia_tips",
    "photo": {
        "_": "pyrogram.ChatPhoto",
        "small_file_id": "AQADBAAT2gkfGwAEAgADl7R51hb___8b4Rj4jUST3pwjBwABFgQ",
        "big_file_id": "AQADBAAT2gkfGwAEAwADl7R51hb___8b4Rj4jUST3p4jBwABFgQ"
    },
    "can_set_sticker_set": false,
    "members_count": 59
}
```

The same thing happens in Telethon. I tested it because I wanted to be sure it's not a storage-related issue particular to Pyrogram.
This behaviour is not documented here: https://docs.pyrogram.org/api/methods/get_chat
 
I would like the integer ID to work in the first request. Is there anything I can do?

Thanks in advance!

**Comment by ColinTheShark** [comment]
There is nothing you can do.

Your Client has to "see" the chat_id before you can do anything with it. Receive any message from the chat, resolve the `@username` or join it. Only after "seeing" the Chat Pyrogram will cache the internal ID and access_hash. Those will then be used to handle the chat correctly if you pass the chat_id to `get_chat()`.

    >>> app.start()
    >>> app.get_chat("pyrogram")
    {
        "_": "pyrogram.Chat",
        "id": -1001292933413,
        ...
    }
    >>> app.get_chat(-1001292933413).title
    Pyrogram

As I've resolved the Username, Pyrogram stores the internal id and access_hash to the session file and caches them there. Afterwards the normal chat_id can be used to resolve the chat by its id alone.

**Comment by solipsy** [comment]
Thanks!

**Comment by abcdenis** [comment]
@solipsy 

Simple workaround is to iterate over all dialogs known for current account and get updated Pyrogram's "cache" which should handle get_chat() for your id correctly:
```
async with Client(account, api_id, api_hash) as client:
  async for dialog in client.get_dialogs():
    pass
  ...
```
