### ISSUE TITLE
User.access_hash / User.username occasionally null in message updates

### ISSUE THREAD

**Issue by EriHoss** [pyrogram/pyrogram#35]
User.access_hash / User.username is occasionally null during message updates from some users.

I am retrieving the user object this way:

```python

def update_handler(self, client, update, users, chats):
    if not isinstance(update, (types.UpdateNewChannelMessage, types.UpdateNewMessage)):
        return

    message = update.message

    if not isinstance(message, types.Message):
        return

    user = users[message.from_id]
    
    # Sometimes null..
    # user.access_hash

    # Sometimes null because of the above
    # user.username
```

Is the username not always expected to be available during an update?

affected users @username value is view-able in the default telegram client.

affected users do not gain a non null User.username in updates for the messages they send after any period of time.

**Comment by delivrance** [comment]
This is normal behaviour for big supergroups, in the sense that the server can decide to send just a minified version (user.min == True, access_hash not available) to save resources.

In order to "fix" this, clients should implement a mechanism for handling these special channel updates. In more details, pyrogram must make a call to `updates.GetChannelDifference`  with proper arguments somewhere down in the `updates_worker` code to extract the full version of that particular Update.

**Comment by EriHoss** [comment]
Ah I understand, thanks for the info

**Comment by delivrance** [comment]
Hi, I've pushed some changes to the `min` branch. Care to test it and report back? To install the branch version you can simply use `pip3 install --upgrade git+https://github.com/pyrogram/pyrogram.git@min`

**Comment by EriHoss** [comment]
I'm currently waiting out a 16 hour login flood-wait I accidentally encountered debugging 😀 

I tested this change a little bit on https://github.com/EriHoss/TGMiner/tree/pyrogram

I did not notice any absent info in the User entity immediately or other problems.

I'll wait until I can get back in and my supergroups have more chat volume to confirm with a longer test.

**Comment by delivrance** [comment]
Alright, I did some tests myself as well and it's behaving rather good.

**Comment by EriHoss** [comment]
I've been running this change for about 5 hours now and have not been able to spot anyone in my groups with missing info in the logs.

**Comment by delivrance** [comment]
Merging ^^ Thanks.
