### ISSUE TITLE
resolve_peer() gives invalid result for supergroups

### ISSUE THREAD

**Issue by Bibo-Joshi** [pyrogram/pyrogram#353]
## Checklist
- [ ] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
When passing the Chad ID of a supergroup to `resolve_peer()`, I can't use the result to perform raw function calls.
I'm new to MTProto and don't understand the behind the scenes well enough to be entirely sure that the issue is with pyrogram. Still, as a user, I'd expect `resolve_peer()` to do as it promises ;)
If I'm just using it wrong, I'm happy for feedback.

## Steps to Reproduce
Create a supergroup and get the `chat_id` (=-100...). Then run:
```
from pyrogram import Client
from pyrogram.api.functions.account import UpdateNotifySettings
from pyrogram.api.types import InputPeerNotifySettings
import time

api_id = XXX
api_hash = "YYY"


with Client("my_client", api_id, api_hash) as app:
    uns = UpdateNotifySettings(
        peer = app.resolve_peer(chat_id),
        settings = InputPeerNotifySettings(
            show_previews = False,
            mute_until =int(time.time() + 10),
        )
    )
    app.send(uns)
```

## Traceback

```
Traceback (most recent call last):
  File "script.py", line 28, in <module>
    app.send(uns)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1412, in send
    r = self.session.send(data, retries, timeout)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/session.py", line 436, in send
    return self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/session.py", line 423, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/errors/rpc_error.py", line 84, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid (caused by "account.UpdateNotifySettings")
```

**Comment by delivrance** [comment]
@Bibo-Joshi Hi, the issue is `UpdateNotifySettings` actually takes an `InputNotifyPeer` object as `peer` argument (which in turn takes an `InputPeer` object, that is, the resulting type of `resolve_peer`).

Try change it to this:
``` python
peer=types.InputNotifyPeer(
    peer=app.resolve_peer(chat_id)
)```

**Comment by Bibo-Joshi** [comment]
Okay, so I got it wrong. Thanks fro the clarification :) Works like a charm now!

**Comment by Crazy120** [comment]
Can any one please give example of DeleteHistory
Iam trying to reach peer id but it's not working help please
