### ISSUE TITLE
can i legally use pyrogram in a commercial, educational video?

### ISSUE THREAD

**Issue by codefather-labs** [pyrogram/pyrogram#361]
can i legally use pyrogram in a commercial, educational video?

**Comment by delivrance** [comment]
@codefather-labs Hi. Sure you can. Pyrogram is released under LGPLv3 which basically states you can do anything with it as long as you keep the library open source, including any changes you might make to it, and allow your users to obtain the source, license and copyright information for the library. Some more info here: https://docs.pyrogram.org/license
