### ISSUE TITLE
database is locked, create sessions for users with chat_id

### ISSUE THREAD

**Issue by khorammfar** [pyrogram/pyrogram#374]
How do I create a custom name for each session??
for example I can't figure out how to get the message sender before the chat id decorator `(@app.on_message())` and add in the name of the sessions in pyrogram?

**Comment by ColinTheShark** [comment]
>How do I create a custom name for each session??

To name the actual *.session file, use the `session_name` argument:
```python
app = Client(session_name="my_account")
bot = Client("userbot")  # or use positional arguments
```
[Relevant Documentation](https://docs.pyrogram.org/api/client#pyrogram.Client)

----

> for example I can't figure out how to get the message sender before the chat id decorator `(@app.on_message())` and add in the name of the sessions in pyrogram?

If you want to work with the `chat_id` of a message you received, you can just do that inside of your handler. The values simply don't exist outside of your handler and you can't decorate "_upwards_".

**Comment by khorammfar** [comment]
> 
> 
> > How do I create a custom name for each session??
> 
> To name the actual *.session file, use the `session_name` argument:
> 
> ```python
> app = Client(session_name="my_account")
> bot = Client("userbot")  # or use positional arguments
> ```
> 
> [Relevant Documentation](https://docs.pyrogram.org/api/client#pyrogram.Client)
> 
> > for example I can't figure out how to get the message sender before the chat id decorator `(@app.on_message())` and add in the name of the sessions in pyrogram?
> 
> If you want to work with the `chat_id` of a message you received, you can just do that inside of your handler. The values simply don't exist outside of your handler and you can't decorate "_upwards_".

Written in the library to avoid creating a file `:memory:`
it's true?
If I use this, the database won't be locked anymore?

**Comment by ColinTheShark** [comment]
> won't be locked anymore?

The "Database is locked" error might be resolved with using `:memory:` as a session name, do keep in mind that you don't get a session file by doing that. The Session will be created in memory, and is lost when you stop the client. To prevent that you could [`app.export_session_string()`](https://docs.pyrogram.org/api/methods/export_session_string#pyrogram.Client.export_session_string) to use that string as an authentication.

More about locked databases is [available here](https://docs.pyrogram.org/faq#sqlite3-operationalerror-database-is-locked).

**Comment by delivrance** [comment]
@khorammfar "database is locked" error is a wanted error and you should be glad it exists, why? because it exists to prevent corruptions from multiple instances writing to a single database.

If you get the error it means something else is still using the database, probably a script you detached from and forgot about it, and the correct way is to kill that process and only keep one and only one running, per session.
