### ISSUE TITLE
Bot Authentication - Steps Required

### ISSUE THREAD

**Issue by alavela** [pyrogram/pyrogram#377]
Hi,
I am trying to migrate my python bots from the **telepot** library (no longer maintained...) to **pyrogram**, also because of the opportunity to manage voip calls (with **tgvoip** so far and, hopefully soon, integrated in pyrogram).
After having read the docs, several posts and done some tests, I am not yet able to setup the client with this method:

```
from pyrogram import Client
app = Client(
    "my_bot",
    bot_token="123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
)
app.run()
```
I am only able to setup a client with _api_id_ and _api_hash_ generated with my phone number...so the bot is behind my account and with tgvoip I can't call myself, which is my target.
@delivrance, can you please detail the steps (for dummies...:-)) required to setup a bot with pyrogram? I already have a bot_token generated by the Bot Father, which are the steps required to use it?
Thanks a lot in advance for your help!

**Comment by delivrance** [comment]
@alavela Hi. I believe you missed the fact that you still need to provide api keys, even for bots, [here's why](https://docs.pyrogram.org/faq#why-do-i-need-an-api-key-for-bots).  Assuming you have read and understood [this](https://docs.pyrogram.org/start/auth#bot-authorization), you should now explain in details what does it mean when you say you are not able to setup the client. Do you get any error? Does the application start but nothing happens? Please explain.

**Comment by alavela** [comment]
Hi Dan, ok. As I said, my target is to have a bot that is able to call me on my mobile phone.
These are my trials:
1. I got the token 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11 from the Bot Father (which of course states that is valid for HTTP API...:-)) and used it. In this case, I used this code:
```
from pyrogram import Client
app = Client("my_bot", bot_token="123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11")
app.run()
```
and of course I got this error:
_AttributeError: No API Key found. More info: https://docs.pyrogram.org/intro/setup_

2. By means of https://my.telegram.org/auth?to=apps I generated an _api_id_ and _api_hash_ **with my phone number**. In this case, I used this code:
```
from pyrogram import Client
app = Client("newbot", api_id=723456, api_hash="WBC-DEF1234ghIkl-zyx57W2v1u123ew11")
app.run()
```
and I got:
_Enter phone number or bot token: 723456:WBC-DEF1234ghIkl-zyx57W2v1u123ew11
Is "723456:WBC-DEF1234ghIkl-zyx57W2v1u123ew11" correct? (y/N): y
The bot access token is invalid_

3. By means of https://my.telegram.org/auth?to=apps I generated an _api_id_ and _api_hash_ with **my wife's phone number**. In this case, I used this code:
```
from pyrogram import Client
app = Client("newbot2", api_id=823456, api_hash="YBC-DEF1234ghIkl-zyx57W2v1u123ew11")
app.run()
```
in this case, both the authentication and the voice call works fine but, of course, I get a voice call from my wife. So these are my questions:
A. How can I create a bot token similar to the one from the Bot Father, which is linked to my phone number but it is not my phone number client?
B. When I can use the following code?
```
from pyrogram import Client
app = Client("my_bot", bot_token="123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11")
app.run()
```
Thanks again for your help!

**Comment by LilianCruanes** [comment]
> Hi Dan, ok. As I said, my target is to have a bot that is able to call me on my mobile phone.
> These are my trials:
> 
>     1. I got the token 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11 from the Bot Father (which of course states that is valid for HTTP API...:-)) and used it. In this case, I used this code:
> 
> 
> ```
> from pyrogram import Client
> app = Client("my_bot", bot_token="123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11")
> app.run()
> ```
> 
> and of course I got this error:
> _AttributeError: No API Key found. More info: https://docs.pyrogram.org/intro/setup_
> 
>     1. By means of https://my.telegram.org/auth?to=apps I generated an _api_id_ and _api_hash_ **with my phone number**. In this case, I used this code:
> 
> 
> ```
> from pyrogram import Client
> app = Client("newbot", api_id=723456, api_hash="WBC-DEF1234ghIkl-zyx57W2v1u123ew11")
> app.run()
> ```
> 
> and I got:
> _Enter phone number or bot token: 723456:WBC-DEF1234ghIkl-zyx57W2v1u123ew11 Is "723456:WBC-DEF1234ghIkl-zyx57W2v1u123ew11" correct? (y/N): y The bot access token is invalid_
> 
>     1. By means of https://my.telegram.org/auth?to=apps I generated an _api_id_ and _api_hash_ with **my wife's phone number**. In this case, I used this code:
> 
> 
> ```
> from pyrogram import Client
> app = Client("newbot2", api_id=823456, api_hash="YBC-DEF1234ghIkl-zyx57W2v1u123ew11")
> app.run()
> ```
> 
> in this case, both the authentication and the voice call works fine but, of course, I get a voice call from my wife. So these are my questions:
> A. How can I create a bot token similar to the one from the Bot Father, which is linked to my phone number but it is not my phone number client?
> B. When I can use the following code?
> 
> ```
> from pyrogram import Client
> app = Client("my_bot", bot_token="123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11")
> app.run()
> ```
> 
> Thanks again for your help!

I also need to know it ! :)
Thanks !

**Comment by ColinTheShark** [comment]
From what I know _bot api_ bots cannot call anyway. You'd have to use a userbot which doesn't require a `bot_token`, but normal authentication with `api_id`, `api_hash` and a phone number.

**Comment by alavela** [comment]
@delivrance do you have any feedback for us?
Thanks!

**Comment by delivrance** [comment]
Bots as in normal bots created by botfather can't make phone calls as far as I know.

About the other questions:

A) Login once and generate a session string. More info here https://docs.pyrogram.org/topics/storage-engines#session-strings, but you probably don't need this since you can simply move your `account.session` file around.

B) I don't quite get what you are asking. That code uses the `bot_token` parameter and can thus be used to log bots in only.
