### ISSUE TITLE
Error loading contacts?

### ISSUE THREAD

**Issue by windx13** [pyrogram/pyrogram#38]
I'm trying to load a list of phone numbers into my account to check them afterwards: they are registered in Telegram or not. Here is my code:

```
list_contact = []
for number in list_item:
     list_contact.append(InputPhoneContact(phone=str(number), first_name=name_generate())
result = client.add_contacts(list_contact)
print(result)
```

The conclusion is this:

> {
>     "_": "types.contacts.ImportedContacts",
>     "users": [],
>     "popular_invites": [],
>     "retry_contacts": [
>         6535756451881337856,
>         6535756451881337860,
> 	...
>         6535756451881339844,
>         6535756451881339852
>     ],
>     "imported": []
> }

Further I carry out this code:

```
result = client.get_contacts()
print(result)
```

The conclusion is this:

> {
>     "_": "types.contacts.Contacts",
>     "users": [],
>     "contacts": [],
>     "saved_count": 83
> }

Method CheckPhone does not work for me, because with a large number of queries, I get an error FloodError. 

1. How can I check a large number of phone numbers?
2.  When using method client.add_contacts , does the error occur?

My goal: to upload a list of phone numbers to Telegram contacts. After that, get those phone numbers that are registered with Telegram.

**Comment by delivrance** [comment]
To troubleshoot this you can try using `client.add_contacts(...)` with a list of max 5 or 10 contacts and see what happens.

**Comment by windx13** [comment]
After 30 phone numbers downloaded in the account (in a cycle, 10 pieces each), the Telegram begins to return this:

Inquiry:

> {
>     "_": "types.contacts.ImportedContacts",
>     "users": [],
>     "imported": [],
>     "retry_contacts": [
>         6535766553982053376,
>         6535766553982053380,
>         6535766553982053384,
>         6535766553982053388,
>         6535766553982053392,
>         6535766553982053396,
>         6535766553982053400,
>         6535766553982053404,
>         6535766553982053408,
>         6535766553982053412
>     ],
>     "popular_invites": []
> }

answer:

> {
>     "_": "types.contacts.Contacts",
>     "users": [],
>     "saved_count": 79,
>     "contacts": []
> }

**Comment by delivrance** [comment]
@windx13 Okay, *maybe* your phone numbers are wrong, make sure you add the country code as well. Example: for Italy is 39, you need to prepend it to each number.

**Comment by windx13** [comment]
@delivrance All numbers are indicated properly, in an international format. Some of them I checked manually - they are registered in Telegrams. I understand that it may not be the library. I would like to know the cause of the error and how do I get what I want?

**Comment by delivrance** [comment]
@windx13 It is not a real error, you are not getting any exception raised. Pyrogram successfully calls the method with the given arguments, and the server replies correctly, but with something I've never seen before. I don't know exactly what that `retry_contacts` full of the client_ids means.

Does the method gives you the same result even with a single phone number?

You can also try to call `.add_contacts` **twice** using the same single phone number and see what happens.

**Comment by windx13** [comment]
@delivrance 
![552](https://user-images.githubusercontent.com/10945320/37782403-d7187a16-2e03-11e8-9bf6-36f399574975.jpg)

**Comment by delivrance** [comment]
Wow. I'm surprised this very obscure parameter was documented in their docs. I really couldn't think about looking there knowing how old they are.

**Comment by windx13** [comment]
@delivrance Previously, this was not. Phone numbers were successfully checked. And this month problems began. Is there anything you can do about this?

**Comment by delivrance** [comment]
@windx13 Well, no... As you can read is Telegram itself that's having problems importing contacts and is telling you to please try again later because of "system limitation".

**Comment by windx13** [comment]
@delivrance Got it. In this case, you will have to forget about checking telephone numbers. Thank you for the quick answers!

**Comment by delivrance** [comment]
@windx13 I wish many other parameters were documented like this. We probably could have not find a solution without reading that and we would have gone mad seeing it suddenly worked again ^^
