### ISSUE TITLE
Decorators use with class inhereted from pyrogram client

### ISSUE THREAD

**Issue by moonbaseDelta** [pyrogram/pyrogram#380]
Hello, I'm struggling with wrapping pyrogram client inside a class. The goal is make it a module inside larger project.

I can't figure out what is the way to use handlers decorators in that situation.

```
from pyrogram import Client
...

class MeApp(Client):
    def __init__(self):
        super().__init__( <data> )
        ...


    @<wut>.on_message(Filters.command([ ... ]))
    def any_handler(self, message):
        ...

```

**Comment by Tenount** [comment]
Maybe something like this will work

```
class MyApp:
    def __init__(self):
        self.client = Client(...)
        self._init()
        self.client.start()

    def _init(self):
        @self.client.on_message(Filters.incoming)
        def got_a_msg(client, message):
            print('A new msg from', message.chat.id)
```

**Comment by zeroone2numeral2** [comment]
@moonbaseDelta callback functions are registered in a client the moment the dispatcher is started - pyrogram will scan the plugins folder,  and import the plugins files. This is when `@client.add_handler()` is called and when the dispatcher is made aware of the existence of the handler. You should put your plugins in a separate file and load it as usual by passing the correct path to `plugins`, or use the classic `Client.add_handler()` and register your class methods as handlers when you initialize your class
