### ISSUE TITLE
using on_message method  for multi account in one program

### ISSUE THREAD

**Issue by sms7182** [pyrogram/pyrogram#384]
Question: i want using on_message for multi client account ,i am using dict for client but i want using 
on_message for these clients

**Comment by zeroone2numeral2** [comment]
As a workaround, you can use a `client`'s `add_handler` method:

```py
# assuming 'my_clients' is your dict of clients and (key: client name, value: Client object)
# and 'my_callback' is your handler callback function

for client_name, client in my_clients.items():
  client.add_handler(MessageHandler(my_callback), Filters.text)
```

More in the [docs](https://docs.pyrogram.org/start/updates#using-add-handler)
