### ISSUE TITLE
when using MessageHandler has exception but worked

### ISSUE THREAD

**Issue by sms7182** [pyrogram/pyrogram#385]
i am using from MessageHandler with same code:
  `app=Client('number',api_id,api_hash)  
   my_handler=MessageHandler(myfunction)
   app.add_handler(my_handler)
   app.run()
`
when app.run() has exception:ValueError('signal only works in main thread')
if i don't execute app.run() message handler not working 
thank you from your helping

**Comment by delivrance** [comment]
@sms7182 First, this is not the place for such questions, unless you are 100% sure it's a library issue and in that case you have to follow a template. Second, I dislike malformed issues and snippets. Make them nice and worth them reading.
