### ISSUE TITLE
AttributeError: 'MessageEntityBold' object has no attribute '__dict__' when printing a Message object

### ISSUE THREAD

**Issue by Ripeey** [pyrogram/pyrogram#386]
## Checklist
- [x]  I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
It happens only when I try to **print** the response after sending **reply_text** using **entities** (htnl or markdown in the text) with a **ReplyKeyboardRemove**, message goes perfectly fine, there is no error produced while printing the result when no entities (html or markdown) is used in the text.
## Steps to Reproduce
[A minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
```
# This throws error
@app.on_message(Filters.regex('test'))
def _(client, message):
    result = message.reply_text("<b>example</b>", reply_markup = ReplyKeyboardRemove())
    print(result)
# This works perfectly fine
@app.on_message(Filters.regex('test'))
def _(client, message):
    result = message.reply_text("example", reply_markup = ReplyKeyboardRemove())
    print(result)
``` 
## Traceback
The full traceback (if applicable).
```
'MessageEntityBold' object has no attribute 'dict'
Traceback (most recent call last):
  File "/home/ripe/.local/lib/python3.7/site-packages/pyrogram/client/ext/dispatcher.py", line 205, in update_worker
    handler.callback(self.client, *args)
  File "test.py", line 8, in _
    print(res)
  File "/home/ripe/.local/lib/python3.7/site-packages/pyrogram/client/types/object.py", line 68, in str
    return dumps(self, indent=4, default=Object.default, ensure_ascii=False)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.7/json/encoder.py", line 439, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/ripe/.local/lib/python3.7/site-packages/pyrogram/client/types/object.py", line 62, in default
    for attr in filter(lambda x: not x.startswith("_"), obj.dict)
AttributeError: 'MessageEntityBold' object has no attribute 'dict'
```

**Comment by usernein** [comment]
It's occurring in also in asyncio-dev 0.16 and even 0.17

**Comment by Sunda001** [comment]
It bugs i guess

**Comment by Sunda001** [comment]
![f](https://user-images.githubusercontent.com/32301831/79066701-4c237000-7ce4-11ea-9286-00abf8be0288.jpg)
![image](https://user-images.githubusercontent.com/32301831/79066710-5c3b4f80-7ce4-11ea-9657-0386dff32925.png)
it works fine on my machine btw

**Comment by delivrance** [comment]
@Ripeey Hi, let us tidy this up.

1) Your example is badly formatted. Make it nice for people to read. This is important.
2) Looks like there's not enough information to reproduce this issue consistently as I tried myself and I don't get any error.

**Comment by usernein** [comment]
@Sunda001 @delivrance it occurs when you try to 
**print**  the result of a send_message with html tags

**Comment by delivrance** [comment]
@usernein @Ripeey The issue happens in private chats, but not in groups and neither of you mentioned this. That was the missing piece of information needed for us to be able to reproduce the issue. Be more careful in future.

Moreover, the example not only was poorly formatted, but wasn't even minimal since `ReplyKeyboardRemove` had nothing to do with this issue.

**Comment by Ripeey** [comment]
@delivrance okay i wasnt aware that it was only issue for private chats (cause i tested it within bots private chat)
