### ISSUE TITLE
Timed out and connection failed

### ISSUE THREAD

**Issue by Wintreist** [pyrogram/pyrogram#390]
Hi, I'm trying to use your module, but I have an error, to start I'm trying as in the documentation:

import pyrogram as tg
api_id = (my id)
api_hash = (my hash key)
client = tg.Client('TAlarm' , api_id, api_hash)
client.run()

But it doesn't work for me.
![image](https://user-images.githubusercontent.com/49996562/79859415-aa81da00-83d9-11ea-9b4e-cb49825b0670.png)
![image](https://user-images.githubusercontent.com/49996562/79859429-b1105180-83d9-11ea-8eb7-91ef60ccd61a.png)

UPD: it looks like I chose the wrong Label, sorry

**Comment by delivrance** [comment]
@Wintreist It looks like Telegram is blocked in your country and Pyrogram can't connect. This is not an issue with the library.

**Comment by Wintreist** [comment]
The thing is that Telegram is available in my country, I can run telegram desktop freely and everything works

**Comment by maga726** [comment]
You may need proxy in your country, try follwing:

from pyrogram import Client
api_id = $$$$$$$$$$$
api_hash = "$$$$$$$$$$$$"
proxy1 = dict(scheme="socks5", hostname="127.0.0.1", port=10809)  # write correct type and port of proxy
with Client("my_account", api_id, api_hash,proxy=proxy1) as app:
    app.send_message("me", "Greetings from **Pyrogram**!")

**Comment by SmartManoj** [comment]
In India, failed to connect using Jio 4G but 5G. Same for https://github.com/rustdesk/rustdesk/discussions/5287

**Comment by Mister-Bugs** [comment]
use your proxy, change your hostname and port
```
import asyncio
from pyrogram import Client

api_id = 9830874
api_hash = "aafe6fbe5b572a19a18b3fb15489ba9b"

proxy1 = dict(scheme="socks5", hostname="127.0.0.1", port=7890)

async def main():
    async with Client("my_account", api_id, api_hash, proxy=proxy1) as app:
        await app.send_message("me", "Greetings from **Pyrogram**!")

asyncio.run(main())
```
