### ISSUE TITLE
app.start() with 0.17.1

### ISSUE THREAD

**Issue by petripanula** [pyrogram/pyrogram#394]
Hi,

With an earlier version of pyrogram I was able to use app.start() with my python code.  Now when I use app.start()  nothing is caught with @app.on_message() decorator. It works with app.run() but the code is "blocked" to that point. What I mean I want to run this pyrogram on "backgrund" and execute my own Python code.  How I do it with the current version of pyrogram? Or is this just some kind of bug?

``` python
import time
from pyrogram import Client

app = Client("my_account")

@app.on_message()
async def log(client, message):
    print(message)

app.start()
#app.run()

EXIT_CYCLE = False
while not EXIT_CYCLE:
    time.sleep(1)
    print("Hello")
```

Thanks
Pete

**Comment by delivrance** [comment]
I see you are using `async`, is that a typo? If not, `app.start()` needs to be awaited which means you need an async function for it to work. Can't reproduce the issue by removing `async`.

**Comment by petripanula** [comment]
Hi,

"app.start() needs to be awaited which means you need an async function for it to work. "

Are there any examples of how this should work?

Thanks for the fast reply!  :)
-Pete

**Comment by petripanula** [comment]
Even I remove the async I have the same problem. I have Python 3.5.6

**Comment by delivrance** [comment]
Might be some weird bug in 3.5 and I wouldn't be surprised. I suggest you update to the latest version or at least to python 3.6 and try again. 3.5 will soon be not supported anymore by pyrogram because of many annoyance of the sort.

**Comment by petripanula** [comment]
Thanks - I'll update my python! I'll be back to this then..

**Comment by petripanula** [comment]
Hi,

Installed Python 3.6.9 and now this started to work again :) So this can be closed!

**Comment by HertzHz** [comment]
Experiencing the same problem:

```python3

async def handler1(client, message) ...
async def handler2(client, message) ...

async def main():
    await app.start()
    await bot.start()

    try:
        while True:
            pass
    except KeyboardInterrupt:
        _writer.commit()
        _index.close()


if __name__ == '__main__':
    asyncio.run(main())
```
won't handle any.

Also tried delete all 'await 'async ' and replaced 'asyncio.run(main())' but didn't work

**Comment by delivrance** [comment]
You are blocking the main thread and that's something you must not do because pyrogram is an async library and relies on the event loop running in it. Use `pyrogram.idle()`.
