### ISSUE TITLE
Bug with emoji encoding?

### ISSUE THREAD

**Issue by tkossak** [pyrogram/pyrogram#396]
Hi, when I get text from telegram message that contains emoji, I can't index the message string properly. Here's sample code:

```python
    import pyrogram
    import emoji

    chat_id = <INSERT CHAT ID HERE>
    msg_id = <INSERT MESSAGE ID HERE>
    app = pyrogram.Client(<SETUP APP HERE>)
    app.start()

    em = emoji.EMOJI_ALIAS_UNICODE[':headphone:']
    new_text = f'a {em} a'

    try:
        app.edit_message_text(
            chat_id=chat_id,
            message_id=msg_id,
            text=new_text,
        )
    except pyrogram.errors.BadRequest as e:
        None  # bad request 400 - can't update when new text is the same as old

    msg = app.get_messages(
        chat_id=chat_id,
        message_ids=msg_id,
    )
    old_text = msg.text

    print([c for c in new_text])
    print(new_text[2])
    print([c for c in old_text])
    print(old_text[2])  # this line throws error
    app.stop()
```

Output is:
```
Pyrogram v0.17.1, Copyright (C) 2017-2020 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

['a', ' ', '🎧', ' ', 'a']
🎧
['a', ' ', '🎧', ' ', 'a']
Traceback (most recent call last):
  File "telegram_actions.py", line 345, in <module>
    test2()
  File "telegram_actions.py", line 49, in test2
    print(old_text[2])
  File "/home/kossak/.cache/pypoetry/virtualenvs/telegram-send-audiobook-H_xae_Ep-py3.8/lib/python3.8/site-packages/pyrogram/client/types/messages_and_media/message.py", line 58, in __getitem__
    return parser_utils.remove_surrogates(parser_utils.add_surrogates(self)[item])
  File "/home/kossak/.cache/pypoetry/virtualenvs/telegram-send-audiobook-H_xae_Ep-py3.8/lib/python3.8/site-packages/pyrogram/client/parser/utils.py", line 37, in remove_surrogates
    return text.encode("utf-16", "surrogatepass").decode("utf-16")
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 2-3: unexpected end of data
```
I use [emoji](https://github.com/carpedm20/emoji/) package for generating emojis, but the same error is thrown when pyrogram gets message sent directly from telegram app.

Is it a bug in the encoding of the message text? Am I doing something wrong?
I need to index the characters because I'm inserting the Message.entities as markdown links, so I can send the original links along with the updated message.

I know I can manually convert it using `old_text = str(msg.text)` (and then indexing works) but then `msg.entities` offsets are wrong.

Thank you in advance for any help.

I use:

- python 3.8.2
- pyrogram 0.17.1 (the same error is for 0.16)
- Linux Manjaro

**Comment by tkossak** [comment]
After debugging into pyrogram i found that I actually don't need indexing to insert links, I can use `msg.text.markdown` for it. But I leave this thread in case someone can confirm or deny that this indexing error on `msg.text` is actually a bug. I found out that the strange encoding is introduced in: 

https://github.com/pyrogram/pyrogram/blob/88e42ecc0d339ca9d9df8f50b305ec82a8567332/pyrogram/client/types/messages_and_media/message.py#L606-L610

Before this statement the `message.message` value works with indexing as expected in contrast to the new `text` attribute. The culprit seems to be `Str.__getitem__()` method:

https://github.com/pyrogram/pyrogram/blob/88e42ecc0d339ca9d9df8f50b305ec82a8567332/pyrogram/client/types/messages_and_media/message.py#L57-L58

but I didn't debug it further.

**Comment by Muhammadyusuf96** [comment]
Same issue on windows 10, with python 3.11 installed. I'm also using `emoji`
@delivrance what's wrong here?
