### ISSUE TITLE
PHONE_CODE_INVALID

### ISSUE THREAD

**Issue by adolfaka** [pyrogram/pyrogram#399]
When we want to log in step by step. We use:

**Step 1.**

```
from pyrogram import Client

app = Client("my_account")
app.connect()

phone_code_hash = app.send_code()

app.disconnect()
```

**Step 2.**

```
from pyrogram import (Client, TermsOfService)

app = Client("my_account")
app.connect()

signed_in = app.sign_in(phone_number=phone_number,
                                         phone_code_hash=phone_code_hash,
                                         phone_code=phone_code
                                         )
if isinstance(signed_in, TermsOfService):
    app.accept_terms_of_service(signed_in.id)

app.initialize()

telegram.stop()
```

When in the second step we execute the method `app.connect()`, the session is loaded [self.load_session()](https://github.com/pyrogram/pyrogram/blob/88e42ecc0d339ca9d9df8f50b305ec82a8567332/pyrogram/client/client.py#L261) and, as a result, the verification are values [user_id](https://github.com/pyrogram/pyrogram/blob/88e42ecc0d339ca9d9df8f50b305ec82a8567332/pyrogram/client/client.py#L1496) and [is_bot](https://github.com/pyrogram/pyrogram/blob/88e42ecc0d339ca9d9df8f50b305ec82a8567332/pyrogram/client/client.py#L1497) are None. Accordingly, both values are None, [session_empty](https://github.com/pyrogram/pyrogram/blob/88e42ecc0d339ca9d9df8f50b305ec82a8567332/pyrogram/client/client.py#L1500) is true, and we generate a new [auth_key](https://github.com/pyrogram/pyrogram/blob/88e42ecc0d339ca9d9df8f50b305ec82a8567332/pyrogram/client/client.py#L1505). Now the values of phone_code_hash and phone_code are not valid for us and we get an exception [PHONE_CODE_INVALID](https://docs.pyrogram.org/api/errors?highlight=phone_code_invalid#badrequest).

**Comment by delivrance** [comment]
Manually disconnecting while logging in breaks the login flow and makes the server not accept codes. Solution: don't disconnect until logged in.
