### ISSUE TITLE
Adding to_dict method for all types

### ISSUE THREAD

**Issue by m-hoseyny** [pyrogram/pyrogram#405]
Hi, 

I am using your library and this is great that you support both async and sync in python. I want to write an API by Pyrogram and I need to convert Pyrogram self-implemented types such as Message, Entries, and so on to JSON. So, it would be great that you add some methods in which I can get the dictionary type of all instances that I transfer data via HTTP.

Thanks

**Comment by delivrance** [comment]
You probably want this: https://docs.pyrogram.org/topics/serializing

**Comment by aentwist** [comment]
I wish that conversion to dict was handled and serialization was left to users. My web framework want to do the serialization itself and generate types and documentation from the dict.
