### ISSUE TITLE
New Features 🎊

### ISSUE THREAD

**Issue by josh8tg** [pyrogram/pyrogram#407]
## Checklist
- [ ✅ ] I believe the idea is awesome and would benefit the library.
- [ ✅ ] I have searched in the issue tracker for similar requests, including closed ones.

### 1️⃣ - Filters :

**1- For Animated Emojis :** 
>     - Filters.dice
>     - Filters.dart
>     - Filters.basket
>     - or Filters.emojis for all of it in one filter

**2- Filters.reply_to(user)**
**3- Filters.callback_regex()**
**4- Filters.inline_regex()**
**5- Filters.url()**

> or just make **Filters.regex()** support all types of updates

### 2️⃣ - Helpers :
**1- Rate Limit :** 
> Client.set_rate_limit(messages, seconds)
> @client.on_message(..., rate_limit=(3,1)) **# 3 messages per second**

**2- Conversation :** 
> Chat.listen **# wait for a reply from the user** you can see [pyromod](https://github.com/usernein/pyromod)
> Chat.ask **#same of above but sending a message before**

### 3️⃣ - Others : 
**1- Get info about the voters in polls**
**2- Complete support to channel posts**
**3- All Bot API's Inline Result types (and some more)**
**4- Refactored async core, so you can host thousands of bots using a single process without using a lot of resources**

[😆 Copyrights ](http://t.me/pyrogramlounge/250408)

**Comment by zeroone2numeral2** [comment]
Wouldn't it be better if all these suggestions had their own issues? It would be a mess to discuss each one opf them in the same github issue - plus also referencing them in pull requests/commits/other issues would be much cleaner
