### ISSUE TITLE
Pyrogram doesn't run when executing scripts outside the current directory

### ISSUE THREAD

**Issue by Onefivefournine** [pyrogram/pyrogram#41]
For example I have some boilerplate code with client initiation in a folder named `MyFancyPythonModule`, also I have `config.ini` in that folder, so that
```
root
- MyFancyPythonModule
- - app.py
- - config.ini
```
If I run it from root (`./MyFancyPythonModule/app.py`) it fails to initiate because there are no `config.ini` in root, but it tries to take it in `client.py` line 725
I suppose it's better to use something like `os.path.join(os.path.dirname(__file__), 'config.ini')`, or even make it configurable(passing a file path to read configs)

**Comment by delivrance** [comment]
Hi, don't name your project folder `pyrogram` in the first place, as it can cause some weird issues.
Rename it to something else and let me know if the problem persists.

**Comment by Onefivefournine** [comment]
@delivrance Well, I already use other name, just took it here as example

**Comment by delivrance** [comment]
@Onefivefournine Good, this is indeed some unwanted behaviour. Instead of `__file__` you probably want to look at `sys.argv` to extract the correct dir. Want to open a PR?

**Comment by Onefivefournine** [comment]
@delivrance Unfortunatetly, I'm not so good at python, so take it as a wish 😄
Also it would be great to have a configuration option of session file placement, because it has the same issue - it creates in execution root

**Comment by delivrance** [comment]
@Onefivefournine Noted. There is actually #4 open for that, but I'm still unsure how to make it nicer (without messing too much with Client parameters).

Regarding this issue, I'm labeling it as enhancement.

**Comment by delivrance** [comment]
As a temporary workaround for this you can use the *api_key* parameter instead: https://docs.pyrogram.ml/start/ProjectSetup#configuration
There is also a *proxy* parameter as well.
