### ISSUE TITLE
Lightweight comparaison with Telethon in FAQ

### ISSUE THREAD

**Issue by fgallaire** [pyrogram/pyrogram#415]
## Checklist
- [x] I believe the idea is awesome and would benefit the library.
- [x] I have searched in the issue tracker for similar requests, including closed ones.

## Description

As Telethon is the other (and older) Telegram MTProto API client python library, a lightweight comparaison in the Pyrogram FAQ (pros/cons, features or spirit differences) would be very useful for new users.

**Comment by JosXa** [comment]
I'll start. Pyrogram...

- is the most high-level of the available MTProto libraries
- aims to be similar in structure to the Bot API
- abstracts peers in a way that does not leak - It allows to use chat IDs, usernames, and complex objects interchangeably

**Comment by ZeeXxx** [comment]
Help me bro,how to export file contacts from file CSV to group Telegram
