### ISSUE TITLE
Add .raw attribute to high-level objects

### ISSUE THREAD

**Issue by delivrance** [pyrogram/pyrogram#418]
Similarly to `_client` (which is currently undocumented and used for internal purposes only), we can add a `raw` attribute to get each object's raw representation.

So far no real use case needs this, but could be nice to have. We need to look at the memory consumption too since raw objects are also kept around. Maybe save raw bytes instead and deserialize on the fly?

**Comment by JosXa** [comment]
Couldn't all custom objects' attributes become properties that read from `self.raw` instead? As far as I've seen (please correct me) a custom object always gets "copied" from raw ones including all attributes. If we save on that step and replace the copying with property access, then there's no memory overhead.
