### ISSUE TITLE
"Unknown media type" Random bad photo message formatting

### ISSUE THREAD

**Issue by fgallaire** [pyrogram/pyrogram#419]
## Description
I'm doing backup of channels with thousands photos and pdfs. I'm using ``message.forward(target, as_copy=True)`` each 2 sec not to flood.

Randomly, I have an ``Unknown media type`` exception on a normally well know media type (photo or pdf) which will be fine the next try, and another one will fail.

It's a very annoying bug, and the fact it's random really disturb me.

## Traceback

photo:
```
{
    "_": "pyrogram.Message",
    "message_id": 9558,
    "date": "2019-11-30 04:21:52",
    "chat": {
        "_": "pyrogram.Chat",
        "id": -100xxx,
        "type": "channel",
        "is_verified": false,
        "is_restricted": false,
        "is_creator": false,
        "is_scam": false,
        "title": "xxx",
        "photo": {
            "_": "pyrogram.ChatPhoto",
            "small_file_id": "AQADBAATmDagGgAEAgADNKY-4xb____u_ywllRcTNFOIBgABFgQ",
            "big_file_id": "AQADBAATmDagGgAEAwADNKY-4xb____u_ywllRcTNFWIBgABFgQ"
        }
    },
    "mentioned": false,
    "scheduled": false,
    "from_scheduled": false,
    "media": true,
    "caption": "L’equipe du Samedi 30 Novembre 2019",
    "views": 487,
    "outgoing": false
}
```

**Comment by delivrance** [comment]
Is what you pasted all you get when the error occurs? Those are not tracebacks.

As you can imagine, I need a way to easily reproduce the issue myself. You already have the chat and the message id of both suspected files, so I guess you can forward manually to a public channel, see if you still get the errors when forwarding `as_copy` and tell me so I can try myself and see what I get.

**Comment by fgallaire** [comment]
Hello what I pasted is the content of the message which is failing with the exception ``Unknown media type``

**Comment by fgallaire** [comment]
@delivrance the problem is that there's no problem: all the messages fail randomly, they where ok the prev try and will be ok the next.

**Comment by fgallaire** [comment]
hello, my first message example was not good (from an other error), so I removed it.

**Comment by fgallaire** [comment]
So the problem is only for ``media`` message of type ``photo``. It seems sometimes the ``photo`` messages are wrongly formatted with ``photo`` field inside ``chat`` instead of being at the top level.

**Comment by fgallaire** [comment]
The well formed version of the message, the ``photo`` field is here:

```
{
    "_": "pyrogram.Message",
    "message_id": 9558,
    "date": "2019-11-30 04:21:52",
    "chat": {
        "_": "pyrogram.Chat",
        "id": -1001209813452,
        "type": "channel",
        "is_verified": false,
        "is_restricted": false,
        "is_creator": false,
        "is_scam": false,
        "title": "Journaux.fr",
        "photo": {
            "_": "pyrogram.ChatPhoto",
            "small_file_id": "AQADBAATmDagGgAEAgADNKY-4xb___-sAAEds4TlLFpTiAYAARYE",
            "big_file_id": "AQADBAATmDagGgAEAwADNKY-4xb___-sAAEds4TlLFpViAYAARYE"
        }
    },
    "mentioned": false,
    "scheduled": false,
    "from_scheduled": false,
    "media": true,
    "photo": {
        "_": "pyrogram.Photo",
        "file_id": "AgADBAAD57ExG_5sEVN3wHImo6VEs0BlqBsABAEAAwIAA3kAA7OwBAABFgQ",
        "file_ref": "AkgcScwAACVWXukoBl6fhl8bYctpHK_EZEmq0Yc",
        "width": 816,
        "height": 1056,
        "file_size": 185399,
        "date": "2019-11-30 04:21:52",
        "thumbs": [
            {
                "_": "pyrogram.Thumbnail",
                "file_id": "AgADBAAD57ExG_5sEVN3wHImo6VEs0BlqBsABAEAAwIAA20AA7WwBAABFgQ",
                "width": 247,
                "height": 320,
                "file_size": 33780
            },
            {
                "_": "pyrogram.Thumbnail",
                "file_id": "AgADBAAD57ExG_5sEVN3wHImo6VEs0BlqBsABAEAAwIAA3gAA7awBAABFgQ",
                "width": 618,
                "height": 800,
                "file_size": 140714
            }
        ]
    },
    "caption": "L’equipe du Samedi 30 Novembre 2019",
    "views": 487,
    "outgoing": false
}
```

**Comment by delivrance** [comment]
We shifted the discussion to Telegram and we concluded that there is something wrong in Pyrogram's code dedicated on fetching the history of a chat in the reverse order. Fetching from new-to-old (no reverse) should work fine. More tests needed

**Comment by delivrance** [comment]
After more tests we understood that there's a server issue regarding those bad photo messages, but Pyrogram's `iter_history` when `reverse=True` is buggy and could skip some messages (there's no issue when not using "reverse").
