### ISSUE TITLE
not able to get all groups and participants

### ISSUE THREAD

**Issue by darkknight2206** [pyrogram/pyrogram#42]
I have to get data from all groups but I am not able to. Please help me.

**Comment by delivrance** [comment]
Post what you've tried so far.

**Comment by delivrance** [comment]
You seem to be a bit confused if you've tried all those combinations (the semantically correct one is number 4).

Anyway, here's an example on how to get participants, given a `target` supergroup: https://github.com/pyrogram/pyrogram/blob/master/examples/get_participants2.py
You need at least a username, a chat_id or a joinchat link of the supergroup/channel.

**Comment by darkknight2206** [comment]
is their any way to get all target names from api?

**Comment by delivrance** [comment]
Yes, [messages.GetDialogs](https://docs.pyrogram.ml/functions/messages/GetDialogs).

**Comment by darkknight2206** [comment]
Sir, what should be the offset_id and also what should be the format of offset_date and what should we do to get all information from starting

**Comment by delivrance** [comment]
Look at how get_dialogs() is implemented, in particular: https://github.com/pyrogram/pyrogram/blob/master/pyrogram/client/client.py#L891-L915

If you just want to get the IDs of all your dialogs you can get them from `client.peers_by_id`. Pyrogram already fetches all the dialogs when it starts.

**Comment by darkknight2206** [comment]
Thanks sir, I will test it and give you the update

**Comment by delivrance** [comment]
@darkknight2206 Maybe you want to join the group for such questions and discuss there instead: [@PyrogramChat](https://t.me/pyrogramchat)

**Comment by musharrafz** [comment]
How can I create groups whose users have subscribed to in pyrogram?

**Comment by musharrafz** [comment]
How can I create groups whose users have subscribed to in pyrogram?

**Comment by musharrafz** [comment]
@delivrance I would be very happy if you could provide information on this question
