### ISSUE TITLE
pyinstaller compatibility

### ISSUE THREAD

**Issue by BouncyMaster** [pyrogram/pyrogram#424]
## Checklist
- [ ] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

Source file:
`from pyrogram import Client`

Output of [pyinstaller tgImport.py](https://github.com/pyrogram/pyrogram/files/4799046/bundle.txt)
Output when [running executable](https://github.com/pyrogram/pyrogram/files/4799058/run.txt)

[Here](https://github.com/pyrogram/pyrogram/blob/develop/pyrogram/client/ext/base_client.py#L80) usually the file is expected to be in the global folder `site-packages`, but when freezing it changes to the executable folder, which doesn't have pyrogram folder. I think the `mime.types` file should be in the actual executable, but as I don't really know how pyinstaller works, i don't know how to fix this.

**Comment by delivrance** [comment]
This should fix it: add `pyrogram/client/ext/mime.types` to the bundle (https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-files-to-the-bundle).

**Comment by BouncyMaster** [comment]
For anyone else having this problem, here is the full command:
```
pyinstaller tgImport.py --add-data /usr/lib/python3.8/site-packages/pyrogram/client/ext/mime.types:pyrogram/client/ext
```
