### ISSUE TITLE
TimeoutError when downloading media (except photos)

### ISSUE THREAD

**Issue by schw4rzlicht** [pyrogram/pyrogram#431]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
I have serious timeout issues when downloading anything else but photos. It also only occurs when running the code on a cloud server. I can download any media locally.

I suspected that Telegram blocked AWS subnets (as suggested in #109) but why would photos work then?

Additionally it seems I cannot catch the `TimeoutError` to handle it, is that intended?

## Steps to Reproduce

Not really reproducible since it works locally. But this is an excerpt from the actual code I'm using:

```python
message = telegram.get_messages(chat_id=raw_message["chat"]["id"],
                                message_ids=raw_message["message_id"],
                                replies=0)

try:
    raw_filename = telegram.download_media(message=message,
                                           file_name="/tmp/")
except TimeoutError:
    print("TIMEOUT ERROR!")
else:
    # do stuff
```

## Traceback
```
[WARNING] 2020-06-26T00:17:11.301Z xx [5] Retrying functions.upload.GetFile due to 
[ERROR]   2020-06-26T00:17:27.461Z xx Traceback (most recent call last):
  File "/var/task/pyrogram/client/client.py", line 1994, in get_file
    r = session.send(
  File "/var/task/pyrogram/session/session.py", line 450, in send
    return self.send(data, retries - 1, timeout)
  File "/var/task/pyrogram/session/session.py", line 450, in send
    return self.send(data, retries - 1, timeout)
  File "/var/task/pyrogram/session/session.py", line 450, in send
    return self.send(data, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "/var/task/pyrogram/session/session.py", line 442, in send
    raise e from None
  File "/var/task/pyrogram/session/session.py", line 439, in send
    return self._send(data, timeout=timeout)
  File "/var/task/pyrogram/session/session.py", line 421, in _send
    raise TimeoutError
TimeoutError
```

**Comment by BouncyMaster** [comment]
This was fixed in the `develop` branch, now pyrogram sleeps automatically when it gets a TimeoutError.

**Comment by schw4rzlicht** [comment]
How does sleep help with that?

**Comment by delivrance** [comment]
@schw4rzlicht have you tried installing tgcrypto to improve pyrogram's performance? (`pip install tgcrypto`). such timeout errors are sign of a slow network.

**Comment by schw4rzlicht** [comment]
I just just realized that I actually did not install tgcrypto. I just recently changed things in my CI build to make installing of tgcrypto possible but then forgot to actually install it.

I changed that and will report back if that helped :)

**Comment by schw4rzlicht** [comment]
> have you tried installing tgcrypto to improve pyrogram's performance?

It seems that tgcrypto indeed fixed my issues. Thanks a log!

**Comment by dsaw** [comment]
I am having the same issues when downloading video. Just curious to know how using `tgcrypto` solves the issue..since `TimeoutError` usually means a slow network as you mentioned.
