### ISSUE TITLE
New file size limit

### ISSUE THREAD

**Issue by Encryptize** [pyrogram/pyrogram#438]
## Checklist
- [x] I believe the idea is awesome and would benefit the library.
- [x] I have searched in the issue tracker for similar requests, including closed ones.

## Description
Telegram is change file limit size from 1.5GB to 2GB and Pyrogram is blocking sending file over 1.5GB. Source: https://t.me/tginfo/2656

**Comment by delivrance** [comment]
@Encryptize Already updated, 3 days ago in https://github.com/pyrogram/pyrogram/commit/c196b90c9d1f73cbd72615131a97d0d703ef814b.
