### ISSUE TITLE
inviteToChannel doesn't work correctly 

### ISSUE THREAD

**Issue by RomanGorbatko** [pyrogram/pyrogram#44]
Hi guys,
Have one issue, who can help me – welcome 🙂

So, I'm using InviteToChannel to multiple invites in my channel.
But this function doesn't work correctly as I think. 
I want an invite 1000 users, but function invited just 30 or 40 users. 
I check SpamBot for my account – its ok. 
What the problem? Maybe this function has a limit to users or any restrictions?

My code: https://gist.github.com/RomanGorbatko/dff4db59785d9403bdceff70cf6a2ab4

**Comment by delivrance** [comment]
I'm closing this, since we discussed in the group.
The answer was: use a smaller chunk of maximum 20 users per API call, but the method call could fail in case a single user has group invitations blocked, you can then try inviting users one by one.
