### ISSUE TITLE
Hosting on heroku

### ISSUE THREAD

**Issue by arydevy** [pyrogram/pyrogram#441]
Hi i made a telegram bot with pyrogram and i want to host it on keroku source code here https://github.com/websitdev/tbot 
but we dont know how to do it we tryed and we cant host it no erors but the bot dosent run

**Comment by jacobshilitz** [comment]
why you committed your API keys.

**Comment by arydevy** [comment]
> why you committed your API keys.

i will regenerate them 
also i commit the files to heroku from thr github repo

**Comment by fgallaire** [comment]
@arydevy Heroku is a Cloud hosting service i.e. it uses HTTP protocol and is not compatible with TCP sockets.

**Comment by delivrance** [comment]
@fgallaire I never tried heroku, but that's not true. Some people managed to make Pyrogram work with heroku, even on a free tier.

@arydevy and all, Github's issues section is for actual issues with the library, not for questions. Join the Telegram [community](https://t.me/pyrogram) and ask in the offtopic group or try on [stackoverflow](https://stackoverflow.com/questions/ask).

**Comment by fgallaire** [comment]
Maybe this could help:
https://elements.heroku.com/buttons/spechide/pyrogram-userbot

**Comment by fgallaire** [comment]
A Pyrogram bot sample working on Heroku:
https://github.com/fgallaire/Pyroku
