### ISSUE TITLE
Is it possible to change a public group URL?

### ISSUE THREAD

**Issue by skhaz** [pyrogram/pyrogram#444]
I want to know if using Pyrogram if it possible to change the group public link, this one:

<img width="690" alt="Screen Shot 2020-07-22 at 12 54 51" src="https://user-images.githubusercontent.com/46259/88199156-de5bde00-cc1a-11ea-85ef-e1b6a5e1db99.png">

**Comment by delivrance** [comment]
Yes, https://docs.pyrogram.org/api/methods/update_chat_username.
