### ISSUE TITLE
Html parser removing html tags

### ISSUE THREAD

**Issue by GodSaveTheDoge** [pyrogram/pyrogram#445]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
The parser truncates trailing tags if following a character that gets truncated (like \n)

## Steps to Reproduce
```python
from pyrogram import Client 

bot = Client("Issue_445")
bot.start()
bot.send_message("self", "<code>This is not monospace\n</code>")
bot.stop()
```

## Expected behaviour 
`This is not monospace` sent in monospace

## Actual behaviour
`This is not monospace` sent not formatted

**Comment by delivrance** [comment]
Can't reproduce with `develop`. All is working fine as intended.
