### ISSUE TITLE
wait for user to send a message

### ISSUE THREAD

**Issue by AmirHosein-Gharaati** [pyrogram/pyrogram#450]
After executing a command, how can I wait for user to send a message that relates to the last command?

**Comment by ColinTheShark** [comment]
What you're looking for is generally referred to as a conversation handler.

> A conversation-like feature is not available yet in the lib. One way to do that is saving states into a dictionary using user IDs as keys. Check the dictionary before taking actions so that you know in which step your users are and update it once they successfully go past one action

See https://t.me/pyrogramchat/213488
