### ISSUE TITLE
Quiz forwarding

### ISSUE THREAD

**Issue by P2LOVE** [pyrogram/pyrogram#462]
Steps to reproduce:

1. Make an poll in channel with type = quiz.
2. Try to forward it to user, using method forward_messages()

ER: Forwarded quiz from channel in user PM
AR: Quiz appears in PM like new poll, not forwarded

Screenshot - https://imgur.com/a/1kSt1jh

Screenshot explaining - First message in a chat - forwarded using pyrogram, second message - manual forwarded quiz
And difference between it is missing title at the top of the message "Forwarded from chatname"

**Comment by GodSaveTheDoge** [comment]
can't reproduce.
I sent a quiz in a channel and did `Client.forward_messages("afriend", "achannel", 69420)`

https://i.imgur.com/NAPFwYc.png

**Comment by himynameisulpa** [comment]
It also didn't work for me.

**Comment by viper-adnan** [comment]
> can't reproduce.
> I sent a quiz in a channel and did `Client.forward_messages("afriend", "achannel", 69420)`
> 
> https://i.imgur.com/NAPFwYc.png

Your pyrogram version ?

**I got this error too.**

**Comment by viperadnan-git** [comment]
> can't reproduce.
> I sent a quiz in a channel and did `Client.forward_messages("afriend", "achannel", 69420)`
> 
> https://i.imgur.com/NAPFwYc.png

Try forwarding from a channel to a channel. Or from a group to another.
I got when forwarding from one group to another.

**Comment by delivrance** [comment]
Can't reproduce with the given info.
Quiz created in a channel successfully forwards everywhere as intended (user, group, other channel).

**Comment by viper-adnan** [comment]
https://t.me/pyrogramlounge/508818

I still getting this.....
