### ISSUE TITLE
AssertionError at use message.download function

### ISSUE THREAD

**Issue by snow922841** [pyrogram/pyrogram#463]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
A clear and concise description of the problem.
use message.download function AssertionError
## Steps to Reproduce
[A minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
 ```
chat_id = "@qsxiaowu"
file_save_path = 'F:\\tmp'
 for message in app.iter_history(chat_id=chat_id, offset_id=0):
       if message.media:
            file_name = message.document.file_name
            message.download(file_name=os.path.join(file_save_path, file_name))
```
## Traceback
The full traceback (if applicable).
Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\pyrogram\session\session.py", line 281, in net_worker
    data = self.unpack(BytesIO(packet))
  File "D:\Python38\lib\site-packages\pyrogram\session\session.py", line 262, in unpack
    assert msg_key == sha256(self.auth_key[96:96 + 32] + data.getvalue()).digest()[8:24]
AssertionError

**Comment by delivrance** [comment]
@snow922841 Thanks for the report. You need to provide a minimal example that is able to reproduce the issue consistently. Yours is not minimal enough since it features a loop in which you download multiple files and the error is not clear where could come from.
