### ISSUE TITLE
Syntax error in chosen_inline_result.py in line 81  ERROR

### ISSUE THREAD

**Issue by MarcosRandulfeGarrido** [pyrogram/pyrogram#465]
Hi!

I found a syntax bug in pyrogram/client/types/inline_mode/chosen_inline_result.py on line 81 there are a come to remove.
Is easy to correct if someone can give me privileges to contribute i can correct the error my self

**Comment by ColinTheShark** [comment]
> Is easy to correct if someone can give me privileges to contribute i can correct the error my self

1. [Make a fork](https://github.com/pyrogram/pyrogram/fork)
2. Make your changes
3. [Make a PR](https://github.com/pyrogram/pyrogram/pulls)
