### ISSUE TITLE
Pyrogram doesn't return user permissions in chat

### ISSUE THREAD

**Issue by Daniel3k00** [pyrogram/pyrogram#466]
When I try `app.get_chat_member()`, Pyrogram returns:
`{
    "_": "pyrogram.ChatMember",
    "user": {
        "_": "pyrogram.User",
        "id": ****,
        "is_self": false,
        "is_contact": true,
        "is_mutual_contact": false,
        "is_deleted": false,
        "is_bot": false,
        "is_verified": false,
        "is_restricted": false,
        "is_scam": false,
        "is_support": false,
        "first_name": "Daniel",
        "status": "online",
        "next_offline_date": "2020-08-20 14:44:39",
        "dc_id": 2,
        "phone_number": "***********",
        "photo": {
            "_": "pyrogram.ChatPhoto",
            "small_file_id": "****",
            "big_file_id": "****"
        }
    },
    "status": "creator",
    "title": "****"
}`
**There isn't user permissions!**

But VSC show me this:
![image](https://user-images.githubusercontent.com/38838770/90765770-2d1c9680-e2f3-11ea-8878-e0530eb289b7.png)

Help me :(

(Sorry for my english, I'm from Russia)

**Comment by ColinTheShark** [comment]
>`"status": "creator",`

The user is the creator of the chat and have all permissions. All other permissions say who can have them. (eg "Administrators only").

Please see https://docs.pyrogram.org/api/types/ChatMember for more info.
