### ISSUE TITLE
what is the correct way to get channel/chat/user name of forwarded message?

### ISSUE THREAD

**Issue by AmirMahmood** [pyrogram/pyrogram#47]
what is the correct way to get channel/chat/user name  and title of forwarded message?

p.s : I have the same question as https://github.com/LonamiWebs/Telethon/issues/335

**Comment by AmirMahmood** [comment]
I have the same question as https://github.com/LonamiWebs/Telethon/issues/335

**Comment by delivrance** [comment]
From https://docs.pyrogram.ml/pyrogram/Client#pyrogram.Client.set_update_handler

> **chats** (`dict`) – Dictionary of all Chat and Channel mentioned in the update. You can access extra info about the chat (such as title, participants_count, etc…) by using the IDs you find in the update argument (e.g.: chats[1701277281]).
