### ISSUE TITLE
AttributeError: 'MessageEmpty' object has no attribute 'to_id'

### ISSUE THREAD

**Issue by Tenount** [pyrogram/pyrogram#478]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [ ] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
File `pyrogram\client\methods\chats\get_dialogs.py`
In `get_dialogs `function:
```
...
for message in r.messages:
    to_id = message.to_id
...
```
[MessageEmpty ](https://core.telegram.org/constructor/messageEmpty)type is ignored here.

It should be something like this::
```
...
for message in r.messages:
    if isinstance(message, types.MessageEmpty):
        continue

    to_id = message.to_id
...
```

## Traceback
```
Traceback (most recent call last):
  File "main.py", line 28, in main
    for dialog in app.iter_dialogs():
  File "C:\Python36\site-packages\pyrogram\client\methods\chats\iter_dialogs.py", line 75, in iter_dialogs
    limit=limit
  File "C:\Python36\site-packages\pyrogram\client\methods\chats\get_dialogs.py", line 87, in get_dialogs
    to_id = message.to_id
AttributeError: 'MessageEmpty' object has no attribute 'to_id'
```

**Comment by delivrance** [comment]
This should be fixed in the latest version. Closing.
