### ISSUE TITLE
Can't get messages via get_messages (using bot token)

### ISSUE THREAD

**Issue by kostyakoz** [pyrogram/pyrogram#479]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
I'm trying to retrieve messages with `get_messages` using bot as client.

## Steps to Reproduce
```python
custom_app = Client(<bot_id>, <API_ID>, <API_HASH>, bot_token=<bot_token>, workdir='sessions')
custom_app.start()
try: 
    data = custom_app.get_messages('all_or_nothing', [1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763])
except: 
    print(traceback.format_exc())
```

## Traceback
```
Traceback (most recent call last):
  File "...", line 68, in custom_get_messages
    data = custom_app.get_messages(channel, ids)
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/sync.py", line 51, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/methods/messages/get_messages.py", line 116, in get_messages
    messages = await utils.parse_messages(self, r, replies=replies)
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/utils.py", line 171, in parse_messages
    parsed_messages[0].chat.id,
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by delivrance** [comment]
@kostyakoz Hi. Can you provide an example with the single message that fails?

**Comment by ehsanonline** [comment]
Telegram Bots can not get messages by ID (only clients can). Bots can get messages only by update. There is no `get_message` or `get_messages` method in [Bots API](https://core.telegram.org/bots/api).

**Comment by kostyakoz** [comment]
@delivrance hi! Just try `[1746, 1747, 1748, 1749]` and you'll get error, but everything works fine when you try any ID from this list separately (like `[1746]`). I really can't get it.

@ehsanonline no, with Pyrogram (client ID and secret) and Bot token I can retrieve messages by IDs (check out bottom of https://core.telegram.org/method/messages.getMessages).
