### ISSUE TITLE
RuntimeError: Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by Tenount** [pyrogram/pyrogram#482]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I want to create an interface for managing a pyrogram client. Since the library has become asynchronous, I'm trying to work with [asyncqt](https://github.com/gmarull/asyncqt). But it looks like pyrogram doesn't provide the required capabilities.
Is it possible to do as in the aiohttp example? [link](https://github.com/gmarull/asyncqt/blob/master/examples/aiohttp_fetch.py)

## Steps to Reproduce
```python
from pyrogram import Client
from pyrogram.handlers import RawUpdateHandler

import sys
import asyncio

from asyncqt import QEventLoop, asyncSlot, asyncClose

from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QPushButton, QVBoxLayout


class MainWindow(QWidget):
    def __init__(self):
        super().__init__()

        self.setLayout(QVBoxLayout())

        self.lblStatus = QLabel('Idle', self)
        self.layout().addWidget(self.lblStatus)

        self.btnFetch = QPushButton('Fetch', self)
        self.btnFetch.clicked.connect(self.on_btnFetch_clicked)
        self.layout().addWidget(self.btnFetch)

        # self.session = aiohttp.ClientSession(
        #     loop=asyncio.get_event_loop(),
        #     timeout=aiohttp.ClientTimeout(total=self._SESSION_TIMEOUT))
        self.client = Client(
            "user",
        )

        self.client.add_handler(
            RawUpdateHandler(
                self.func
            )
        )
        self.client.start()

    async def func(*a):
        print('test')

    @asyncClose
    async def closeEvent(self, event):
        await self.client.stop()

    @asyncSlot()
    async def on_btnFetch_clicked(self):
        self.btnFetch.setEnabled(False)
        self.lblStatus.setText('Fetching...')
        try:
            async with self.client:
                await self.client.send_message("me", "Hi!")
        except Exception as exc:
            self.lblStatus.setText('Error: {}'.format(exc))
        else:
            self.lblStatus.setText('Finished!')
        finally:
            self.btnFetch.setEnabled(True)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    loop = QEventLoop(app)
    asyncio.set_event_loop(loop)

    mainWindow = MainWindow()
    mainWindow.show()

    with loop:
        sys.exit(loop.run_forever())

```

## Traceback
```
Task exception was never retrieved
future: <Task finished coro=<closeEvent() done, defined at test.py:42> exception=RuntimeError('Cannot run the event loop while another loop is running',)>
Traceback (most recent call last):
  File "test.py", line 44, in closeEvent
    await self.client.stop()
  File "C:\Python36\site-packages\pyrogram\sync.py", line 51, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Python36\Lib\asyncio\base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "C:\Python36\Lib\asyncio\base_events.py", line 428, in run_forever
    'Cannot run the event loop while another loop is running')
RuntimeError: Cannot run the event loop while another loop is running
```

**Comment by delivrance** [comment]
@Tenount A *full* traceback would be helpful.

**Comment by Tenount** [comment]
> @Tenount A _full_ traceback would be helpful.

Added.

**Comment by delivrance** [comment]
Pyrogram currently relies on the main event loop Python creates and you are setting a new one from QT. I'm not sure how to make both libraries work together when each want to use a different loop.

**Comment by Tenount** [comment]
I want to use the modified Qt loop from acyncqt so that they work together like in the aiohttp example. But it looks like pyrogram doesn't let ещ set another loop and creates its own.

**Comment by delivrance** [comment]
@Tenount Try installing Pyrogram with `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and see if you can still reproduce the issue. One problem in your code: you are using `async with` inside `on_btnFetch_clicked ` which will fail because the context manager will start the client again, and you are already starting it inside `__init__`.

**Comment by Tenount** [comment]
@delivrance It seems this completely solves my problem. Thank you!
