### ISSUE TITLE
caption shows "None" instead nothing

### ISSUE THREAD

**Issue by fgallaire** [pyrogram/pyrogram#486]
When I'm using ```caption=message.caption``` with ```send_document()``` I have ```"None"``` as caption instead nothing when ```message.caption``` is ```None```, i.e there's no caption (not tested the other methods but it's probably a global wrong beahaviour)

**Comment by ColinTheShark** [comment]
I'd you're passing `"None"` you obviously have the string "None" show up. Try passing just `None` instead.
