### ISSUE TITLE
Code lock when running transfer inside a thread other than the main one

### ISSUE THREAD

**Issue by BouncyMaster** [pyrogram/pyrogram#488]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Code
```python
from pyrogram import Client
import threading
from time import sleep

def progress(current, total):
    print("{} / {}".format(current, total))

def uploadFile():
    api_id = xxxxxx
    api_hash = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

    app = Client("a1", api_id, api_hash) 

    with app:
        app.send_document("me", "test500M", progress=progress)

transferJob = threading.Thread(target=uploadFile, daemon=True)
transferJob.start()

a = 1
while True:
    sleep(1)
    print("{} seconds passed".format(a))
    a += 1
```

## Info
* After some debugging i found out that the program reaches [here](https://github.com/pyrogram/pyrogram/blob/master/pyrogram/methods/messages/send_document.py#L160), but calling `save_file()` doesn't really call it as the breakpoint isn't getting hit at the start of the function. So the program freezes somewhere inbetween these 2 points.
* The same code works with `pyrogram 0.18.0`.

**Comment by delivrance** [comment]
Don't mix sync and async unless you really know what you are doing. Pyrogram is an async framework with some convenience to make it work with sync callbacks. You never want to block the main thread when using async libraries (you are blocking it with that sleep call inside an infinite loop).
