### ISSUE TITLE
socks5 proxy

### ISSUE THREAD

**Issue by 1pyxa1** [pyrogram/pyrogram#5]
good day!
could you please explain how to use pyrogram with socks5 proxy? tried [PySocks](https://github.com/Anorov/PySocks) but no luck unfortunately. add 
`socks.set_default_proxy(socks.SOCKS5, "localhost")`
`socket.socket = socks.socksocket`
to ./pyrogram/connection/transport/tcp/tcp.py and got repeating "Connecting..." status. 
would be grateful for any advice.

**Comment by delivrance** [comment]
Hi there! I'm not quite experienced with proxies, but will have a look at PySocks and how to set it up correctly. I will keep this issue open for further updates and for everyone else who want to participate.

**Comment by 1pyxa1** [comment]
thanks for your reply! for a temporally solution used [redsocks](https://github.com/darkk/redsocks) plus iptables on my Ubuntu. works fine so far.

**Comment by delivrance** [comment]
Hi! I've added SOCKS5 proxy support. Changes are not merged into master yet, but you can test by upgrading Pyrogram using:

``` sh
pip install --upgrade git+https://github.com/pyrogram/pyrogram@proxy
```

Then you must append the following to your `config.ini` file:

``` ini
[proxy]
enabled = True
hostname = 123.234.123.234
port = 443
username = <your_username>
password = <your_password>
```

You can omit username and password if your proxy doesn't require authorization.

Let me know if something doesn't work as expected.

**Comment by 1pyxa1** [comment]
Hi! I've tested pyrogram@proxy. Everything works good. Thanks a lot!
