### ISSUE TITLE
Question: get_messages || GetChats

### ISSUE THREAD

**Issue by sviat9440** [pyrogram/pyrogram#50]
In what format to specify the id of the chat?

    pycli.get_messages(chat_id=-1001004766182, message_ids=list(range(100)))
    pycli.resolve_peer(-1001004766182)
    # pyrogram.api.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid

    pycli.send(
        functions.messages.GetChats([-1001004766182])
    )
    # OverflowError: int too big to convert
    
    pycli.get_messages(chat_id=pycli.resolve_peer("coding_ru"), message_ids=list(range(141180, 141280)))
    # TypeError: unhashable type: 'InputPeerChannel'

    

(Bot API)

**Comment by delivrance** [comment]
@sviat9440 Hi, any bot API id starting with -100 is considered a channel or a supergroup, hence you can't use messages.GetChats, you need channels.GetChannels.

**Comment by sviat9440** [comment]
`print(pycli.resolve_peer(1004766182))` # -1001004766182
pyrogram.api.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid

**Comment by delivrance** [comment]
I can now see your problem.

You are logging in as Bot, right? Because this is a work in progress, you can install the latest development version: https://docs.pyrogram.ml/start/QuickInstallation#bleeding-edge,
restart your bot using this version and while is online, kick it and add it again to your channel/supergroup. Now resolve_peer with the id should work.

**Comment by sviat9440** [comment]
Ok, thats works. All users needs to kick and add bot again?

Then, `pycli.get_messages(chat_id=pycli.resolve_peer(1004766182), message_ids=list(range(141180, 141280)))` returns:
`TypeError: unhashable type: 'InputPeerChannel'`

**Comment by sviat9440** [comment]
pycli.send(
        functions.channels.GetMessages(pycli.resolve_peer(1004766182), list(range(141180, 141280)))
    )

returns:
AttributeError: 'int' object has no attribute 'write'

**Comment by delivrance** [comment]
> Ok, thats works. All users needs to kick and add bot again?

No, is just the bot that wasn't aware of the channel/supergroup.

For the other errors, you are passing wrong values. Please read the docs, in particular read what kind of values you must pass: https://docs.pyrogram.ml/pyrogram/Client?highlight=get_messages#pyrogram.Client.get_messages

This is high-level convenience method, and accepts IDs as simple integers (it will automatically call resolve_peer for you). For any other **raw** methods not listed in the Client class you must use resolve_peer.

**Comment by sviat9440** [comment]
> No, is just the bot that wasn't aware of the channel/supergroup.
That is, the client must always be running when you add the bot to the group?

> For the other errors, you are passing wrong values.
tnx!

**Comment by sviat9440** [comment]
print(pycli.resolve_peer(258239875))

> Traceback (most recent call last):
...
KeyError: -100258239875
During handling of the above exception, another exception occurred:
Traceback (most recent call last):


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    print(pycli.resolve_peer(258239875))
  File "C:\Users\sviat-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\pyrogram\client\client.py", line 983, in resolve_peer
    raise PeerIdInvalid
pyrogram.api.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid

**Comment by delivrance** [comment]
> That is, the client must always be running when you add the bot to the group?

Currently, providing you are using the latest development version, it must be online only when you are adding it again, then pyrogram will remember the id (it is stored in the session file).

> -258239875 -> simple private group

I think this is just the same problem, have you kicked and added it again?

Anyway, I flagged this issue as enhancement, some code needs to be added in order to make bots be aware of groups they are part of, even without the need of kicking them.

**Comment by sviat9440** [comment]
> I think this is just the same problem, have you kicked and added it again?

Yes. I use method messages.GetMessages(id), but i cant set chat_id param.

**Comment by delivrance** [comment]
This is because basic groups are stored *inside* your account. This means that each member of a basic group have his own copy of the messages stored inside their own account (that's why you can't get old mesages in case you leave and delete the group). The method doesn't accept a chat_id for basic groups because message ids for them are shared with private messages ids.

In other words, any personal message id can be a message of either a private message or a basic group. Channels and Supergroups have their own message id space

**Comment by sviat9440** [comment]
rgr, tnx

**Comment by delivrance** [comment]
To summarize: if you want messages from private chats or basic groups, you use messages.GetMessages (and pass only the message id). If you want messages from channels or supergroups, you use channels.GetMessages.

Yhe convenience method `.get_messages()` is able to get messages for both entities. If you look at how's implemented you'll see that it'll use both raw function, and will use channels.GetMessages in case the provided chat_id belongs to a channel/supergroup.

**Comment by sviat9440** [comment]
> Anyway, I flagged this issue as enhancement, some code needs to be added in order to make bots be aware of groups they are part of, even without the need of kicking them.

Please tell when you implemented it

**Comment by Pilllo** [comment]
Kings

**Comment by sviat9440** [comment]
> .get_messages() is able to get messages for both entities. 

line 2954 client.py raise exception if I try get messages from private chats\simple groups

**Comment by delivrance** [comment]
> Please tell when you implemented it

All changes live in the github repo. For new releases I write release notes which summarize what's been changed.

> line 2954 client.py raise exception if I try get messages from private chats\simple groups

Well, what exception exactly? That's important...

**Comment by sviat9440** [comment]
Hi again. I have the same problem, but now, user is not bot:

    app.resolve_peer("https://t.me/joinchat/AlC8dVFxvk5kSqSkO8T9WQ")

```pyrogram.api.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid```

**Comment by delivrance** [comment]
Closing. [Client.get_chat](https://docs.pyrogram.ml/pyrogram/Client#pyrogram.Client.get_chat) has been added.
