### ISSUE TITLE
How can I set the start point of the video to Client().set_profile_photo()

### ISSUE THREAD

**Issue by batiscuff** [pyrogram/pyrogram#504]
I need the video I’m uploading to the profile to start with the fourth second. How can I do that?

**Comment by M-Smits** [comment]
I don't think it is possible at the moment to achieve this with the API.
If the cropping of the video only needs to be done once, you can crop the video by other means (websites, programs, ...).

**Comment by ColinTheShark** [comment]
Hi @batiscuff, this is not a Q&A forum, but for bug reports and feature requests. If you have a "how do I use x" question, please join the [Pyrogram Inn](https://t.me/PyrogramChat) or if your message is more broad (which yours is) the [Pyrogram Lounge](https://t.me/PyrogramLounge).
