### ISSUE TITLE
how to log in not through the console, thanks for the answer!

### ISSUE THREAD

**Issue by artem-webdev** [pyrogram/pyrogram#520]
how to log in not through the console, thanks for the answer!

**Comment by ColinTheShark** [comment]
Okay, so you've managed to post the issue with the title that is prefilled by the template, that tells you to read the template body, which in turn tells you to not ask questions here.

How did you manage to still ask a question then??

This is NOT a Q&A forum. Join [@PyrogramChat](https://t.me/pyrogramchat) and ask your questions there.
