### ISSUE TITLE
Download_media corrupt some files

### ISSUE THREAD

**Issue by mrb0098** [pyrogram/pyrogram#531]
Hi
i use [this version](https://github.com/pyrogram/pyrogram/tree/ccbe9b498a3f07a1157f44f0de535051e1d825d6) on python 3.7 to run my bot .

i am store files in my server using  **bot.download_media** and when i try to extract files in my system i see this errors :
checksum error . . . . the archive is corrupt
![06af3071-b60c-4e3f-baad-45a73f205336](https://user-images.githubusercontent.com/20848653/97798517-099f9180-1c3c-11eb-9432-e385805817cc.jpg)
![1c34cdb6-bf82-413d-a433-b19e68ce95fb](https://user-images.githubusercontent.com/20848653/97798519-0c9a8200-1c3c-11eb-814c-bb23317f5935.jpg)

**Comment by delivrance** [comment]
Hi. Do not ignore the bug report issue template.
