### ISSUE TITLE
How to run pyrogram on background?

### ISSUE THREAD

**Issue by petripanula** [pyrogram/pyrogram#542]
I have been away maybe a year or something and upgraded pyrogram and python.
Now:  
Python version 3.7.9 
Pyrogram v1.0.7

I want to run my program the same time in that "while loop" and pyrogram to handle messages at the same time.
app.run() just blocks the thread and app.start() only doesn't work and when I add that idle() it blocks again...

```python
import threading
import time
import sys
from pyrogram import Client
#from pyrogram import filters
from pyrogram import idle

app = Client("my_account")

@app.on_message()
async def my_handler(client, message):
    print(message)
    #await message.reply_text("Hello, async world!")

print("Python version")
print (sys.version)

#app.run()
app.start()
#idle()

#while loop - my program runs here....
i = 0
while(True):
    print("looping...")
    time.sleep(2)
    i = i + 1
    if i > 5:
        break
```

Any clue what's wrong?

Thanks
-Pete

**Comment by delivrance** [comment]
Hi. The issue section on GitHub is for actual issues with the library, it's not a forum for questions.
If you'd like to ask a question, do so at [StackOverflow](https://stackoverflow.com/questions/ask) or join the [community](https://t.me/pyrogram).

**Comment by petripanula** [comment]
So I change this a bug?

**Comment by delivrance** [comment]
Questions/help requests are not bug reports. If you want to file a bug report, follow the provided guidelines. Regards.
