### ISSUE TITLE
Pyrogram v1.0.7: [400 BOT_METHOD_INVALID] messages.GetHistory

### ISSUE THREAD

**Issue by Sylva1n** [pyrogram/pyrogram#544]
Hello,

I try to code a delete all messages bot based on such [example](https://stackoverflow.com/questions/63563328/how-can-i-delete-all-chat-history-using-telegram-bot).

Unfortunately, this error message is returned:

```
  File "/usr/local/lib/python3.9/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.BotMethodInvalid: [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")
```

I can't figure out why such a method can't be used by bots.

What is my misunderstanding?

Regards,

Sylvain

-------
Pyrogram v1.0.7
Python 3.9.0
macOs 11.0.1

**Comment by Tenount** [comment]
You are trying to use a bot-restricted method "messages.GetHistory".  Read carefully the first two paragraphs in your example. So you need to know the chat id and message id in advance to delete them.

**Comment by ColinTheShark** [comment]
As Tenount said, `messages.GetHistory` is a method that cannot be used by bots (made with `@BotFather`). If you want to fetch messages retroactively (after they've been sent), you'll need to use a user account.

**Comment by Sylva1n** [comment]
Ok. Thank you.

**Comment by fgallaire** [comment]
Hello, how to know which are the methods not allowed to token bots ? I don't see this information in the pyrogram documentation

**Comment by dcbtc88** [comment]
Send message see
