### ISSUE TITLE
How can i use phone_code parameter

### ISSUE THREAD

**Issue by jabert74** [pyrogram/pyrogram#546]
Pass the phone code as string to avoid entering it manually.
How can i do it?
please give me an example!

**Comment by ColinTheShark** [comment]
Hi @jabert74 , this is not a Q&A forum, but for bug reports and feature requests. If you have a "how do I use x" question, please join the [Pyrogram Inn](https://t.me/pyrogramchat) and ask there.

**Comment by petripanula** [comment]
I tried to join that Pyrogram Inn Telegram Chat - but missed the "captha" below.. What is the missing 6th emoij? I have found all other than hedgehog...


 

![image](https://user-images.githubusercontent.com/14090741/99914575-ec278a00-2d06-11eb-9d9d-dd9e3e7c5ae1.png)
