### ISSUE TITLE
Pyrogram Inn Telegram group?

### ISSUE THREAD

**Issue by petripanula** [pyrogram/pyrogram#547]
Not really related to Pyrogram App but anyway... I couldn't join that Telegram Group.. Can you tell me the answer for this :)

![image](https://user-images.githubusercontent.com/14090741/99914655-8d164500-2d07-11eb-921c-a95eff1b3c70.png)

**Comment by delivrance** [comment]
It seems you failed the captcha already (https://t.me/pyrogramchat/268503). You basically have issues missing emojis in your OS. Is that picture coming from web.telegram.org?
