### ISSUE TITLE
update handling in accounts with many chats

### ISSUE THREAD

**Issue by CrisMystik** [pyrogram/pyrogram#548]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Currently Pyrogram, for each update received, calls different methods to provide some additional information. However, in accounts with many active chats, and therefore many messages received, it is easy for this to lead to floodwait of these methods, particularly GetMessages.

## Proposed solution
A `get_additional_info` parameter in the Client object, which is True by default, and if set to False disables obtaining additional information by calling methods when receiving updates

**Comment by delivrance** [comment]
Related to #264 and #265.

**Comment by CrisMystik** [comment]
> Related to #264 and #265.

but this would not solve the problem completely, bots using pyrogram would still be at risk of ceasing to function for some time in the event of GetMessages floodwait in particular, and would be vulnerable to attacks that take advantage of this
