### ISSUE TITLE
Iter_history is not able to fetch all messages in a supergroup

### ISSUE THREAD

**Issue by guenter-r** [pyrogram/pyrogram#549]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.
- [x] Tried to debug this myself ( iter_history() - could not fix .. ) -> still true.

## Description
When iterating over the messages through iter_history() the program stops proceeding at message with message_id=1. This is not the message that was sent earliest. 
Under the below link (gist) the message (changed Id) is listed. This message (timestamp as orientation), cannot be found in the chat at all (checked on phone, tablet and web client). When setting the offset date to an earlier date, the function returns nothing as it is not able to bypass this "broken" (?) and unavailable entry.

Last available message (missing data like sent_from..): [here](https://gist.github.com/guenter-r/3aab84f9cca04736ea3c34c66bb45f4e).  (The whole "from_user" block is missing)

## Steps to Reproduce
Re-run iter_history
last message is again the one mentioned

**Comment by guenter-r** [comment]
I was able to clear related messages, still the program stops iterating. I will further look into this.

**Comment by delivrance** [comment]
Your supergroup has been upgraded from a normal group at some point and messages prior to this event live in another chat (official apps might hide this and make it transparent to user). You need to look at `migrate_from_chat_id` in the very first message and redo `iter_history` in that chat to get all the messages prior the upgrade.
