### ISSUE TITLE
imperfect parse_channel_chat

### ISSUE THREAD

**Issue by i-Naji** [pyrogram/pyrogram#56]
Hi
Thank you for your great project.
a small change in parse_channel_chat to support ```ChannelForbidden``` type of channel:
```py
def parse_channel_chat(channel: types.Channel) -> pyrogram.Chat:
    return pyrogram.Chat(
        id=int("-100" + str(channel.id)),
        type="supergroup" if channel.megagroup else "channel",
        title=channel.title,
        username=getattr(channel, "username", None),
        photo=parse_chat_photo(getattr(channel, "photo", None))
    )

**Comment by delivrance** [comment]
Nice. Wanna open a pull request instead? This way you'll appear in the contributors' list.

And thank you for the appreciation!

**Comment by i-Naji** [comment]
```chatForbidden``` type of chat needs support too. and about **pull request**, I think you have a better plan for these cases...

**Comment by delivrance** [comment]
> I think you have a better plan for these cases...

The idea of a pull request is to propose some changes, and you did exactly that, by providing a possible solution which is also correct. I was only insisting so that you could appear in the contributors' list.

> chatForbidden type of chat needs support too

Yep.
