### ISSUE TITLE
For Q&A purposes, please read this template body

### ISSUE THREAD

**Issue by EnxGitHub** [pyrogram/pyrogram#563]
How can I make a download of a file faster?

**Comment by ColinTheShark** [comment]
You did not read the template body.

> # Important
> This place is for issues about Pyrogram, it's **not a forum**.
> If you'd like to post a question, please move to https://stackoverflow.com or join the Telegram community at https://t.me/pyrogram. Useful information on how to ask good questions can be found here: https://stackoverflow.com/help/how-to-ask.
