### ISSUE TITLE
limits of iter_chat_members()

### ISSUE THREAD

**Issue by kiberzoid** [pyrogram/pyrogram#577]
Hi, I have a channel with 300+ members. Meanwhile there is the server's limit with 200 members when using 
iter_chat_members()
What is the properly way to use this function, if I want to get more than 200 members

**Comment by Tenount** [comment]
Maybe you're doing something wrong. Need a minimal, reproducible example.

This works fine for me:
```
In [4]: members = app.iter_chat_members("pyrogramchat")

In [5]: len(members)
Out[5]: 3535
```

**Comment by pokurt** [comment]
by server's limitation of 200 chat members i dont think there is a way. but as for @Tenount said using len() in members dict will be the just an option to get member count. but there is already a valid method for it explained here: https://docs.pyrogram.org/api/methods/get_chat_members_count

**Comment by kiberzoid** [comment]
From pyrogram's doc for iter_chat_members():
"Server limit: on supergroups, you can get up to 10,000 members for a **single** query and up to **200 members on channels**"
it's Telegram's limit, right? and if i did first query for get first 200 members, how i can do the second query for get next 200 members?
