### ISSUE TITLE
Bad workers number on Heroku (and probably other containerized hosting providers)

### ISSUE THREAD

**Issue by fgallaire** [pyrogram/pyrogram#578]
I use a free dyno from Heroku, its specs are 1 CPU core and 512 Mo of RAM.
The server where run the dyno has a 8 cores Intel(R) Xeon(R) CPU E5-2670 v2.

The workers default number is **12**: min(32, os.cpu_count() + 4) = min(32, 8 + 4) = 12
But should be **5**: min(32, os.cpu_count() + 4) = min(32, 1 + 4) = 5

`os.cpu_count()` seems not relevant in a containerized context.

**Comment by jonatan1609** [comment]
It's up to you then, pass workers=N to pyrogram.Client
