### ISSUE TITLE
Send a message when the user is online (Schedule)

### ISSUE THREAD

**Issue by foremtehan** [pyrogram/pyrogram#590]
Excuse me which method sends a message when the user is online ? some sort of scheduling a message

**Comment by ColinShark** [comment]
From the Issue Template you had to read when creating this issue:

> This place is for issues about Pyrogram, it's **not a forum**.
> If you'd like to post a question, please move to https://stackoverflow.com or join the Telegram community at https://t.me/pyrogram. Useful information on how to ask good questions can be found here: https://stackoverflow.com/help/how-to-ask.
