### ISSUE TITLE
Get channel id by channel name or invite hash

### ISSUE THREAD

**Issue by ksanderer** [pyrogram/pyrogram#6]
Hi! Is it possible to retrieve chat_id and access_hash by t.me channe/invite links?

https://t.me/joinchat/GG4BlQwm19czcBGOewv40Q   
or   
https://t.me/asdaasd

**Comment by delivrance** [comment]
Hi there! Nope, is not possible to get the id/hash pair for **private** chats or channels via the joinchat link without joining first, all you can do is using [messages.CheckChatInvite](https://docs.pyrogram.ml/functions/messages/CheckChatInvite/) to get a brief description. You have to pass only the link hash as argument, which is `GG4BlQwm19czcBGOewv40Q` in your example.

However, if the chat/channel is **public** (i.e., you have its public username), you can get the id/hash pair by using [contacts.ResolveUsername](https://docs.pyrogram.ml/functions/contacts/ResolveUsername/).

**Comment by ksanderer** [comment]
Thanks! Will try!

Telethon has sugar method `get_entity` that is quite handy for the current case.

http://telethon.readthedocs.io/en/latest/extra/basic/entities.html?highlight=get_entity#getting-entities

**Comment by delivrance** [comment]
@ksanderer Thanks. New features/ideas are surely welcome and being Pyrogram pretty young there's a lot of room for improvements.

**Comment by Morrigan-Ship** [comment]
i 

> Hi there! Nope, is not possible to get the id/hash pair for **private** chats or channels via the joinchat link without joining first

bot joined
how can i do it via custom invite link?
