### ISSUE TITLE
Data invalid when answering bot query

### ISSUE THREAD

**Issue by AckslD** [pyrogram/pyrogram#609]
I'm trying to reply to a button from a query from a bot. In the template here it said to ask questions on the telegram community (Pyrogram News) but it I don't see how to ask a question there. Sorry if this is not the right place to ask this question.

I tried using the answer from #81 but I get
```
pyrogram.errors.exceptions.bad_request_400.DataInvalid: [400 DATA_INVALID]: The encrypted data is invalid (caused by "messages.GetBotCallbackAnswer")
```
I'm calling as follows:
```python
client.send(
    raw.functions.messages.GetBotCallbackAnswer(
        client.resolve_peer(bot_name),
        msg_id=message_id,
        data=button.encode(),
    )
)
```
where `button="Offer Help"` and the message with the given `message_id` has the following `reply_markup` field:
```python
reply_markup=pyrogram.types.InlineKeyboardMarkup(inline_keyboard=[[
    pyrogram.types.InlineKeyboardButton(
        text='Request Help',
        callback_data='request_help',
    ),
    pyrogram.types.InlineKeyboardButton(
        text='Offer Help',
        callback_data='offer_help',
    ),
]])
```

**Comment by delivrance** [comment]
Your `reply_markup` looks ok. When people press buttons in your bot they generate a so called "callback query" which is handled by `on_callback_query` as shown here: https://docs.pyrogram.org/start/examples/callback_queries.

To answer to those queries simply use the bound method `callback_query.answer(...)` (more convenient) or `client.answer_callback_query(...)`, there's no need for raw methods here.

**Comment by delivrance** [comment]
By the way, "Pyrogram News" is the channel, which has a linked group.

**Comment by AckslD** [comment]
@delivrance, thanks a lot for your reply! If I understood you correctly what I want is the other way around, i.e. write a client which presses the buttons of a bot (this is for testing a bots behaviour)

**Comment by delivrance** [comment]
Buttons are attached to messages, obtain the one you need to interact with and use [message.click](https://docs.pyrogram.org/api/bound-methods/Message.click). This is the most convenient way.

**Comment by AckslD** [comment]
Thanks! That makes a lot of sense :) Also got some help from the Pyrogram Inn channel :+1:
