### ISSUE TITLE
 FloodWait error in message_parser

### ISSUE THREAD

**Issue by i-Naji** [pyrogram/pyrogram#61]
https://github.com/pyrogram/pyrogram/blob/debc45968614b3c9891afcb809e48bc3c79a4f93/pyrogram/client/message_parser.py#L183

set default to **0** to avoid FloodWait

**Comment by delivrance** [comment]
@i-Naji Thanks for reporting this, I've also noticed it when people spam many messages that are also a reply to another message.

Setting replies to 0 is not the right way though, because we would miss any information regarding the replied message.
