### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Voron14Artl** [pyrogram/pyrogram#612]
![image](https://user-images.githubusercontent.com/59573562/106388986-027e5000-63f2-11eb-8230-6e97dde6d4d5.png)

I found a typo in class pyrogram.types.InputMediaAudio. The title accept int value. XD:)

**Comment by code-rgb** [comment]
Lol

**Comment by ColinShark** [comment]
Next time please either [make a quick PR](https://github.com/pyrogram/pyrogram/compare)* yourself, or at least make your Issue title more useful than just "typo". 

\* [How do I contribute?](https://github.com/MarcDiethelm/contributing/blob/master/README.md#contributing)
