### ISSUE TITLE
No update event from big channel

### ISSUE THREAD

**Issue by vellrya** [pyrogram/pyrogram#613]
Hello, I switched to Pyrogram 1.1.13 from other library because updates from large channels (500-1500 people) stopped coming, although updates from small groups and channels worked correctly - only restarting the application helped.

Pyrogram was working correctly for a few days after the update, but now I have the same problem - my account is subscribed to 15 channels, but updates from them stop coming after a while, restarting also helps. What can be done in this situation?

**Comment by ColinShark** [comment]
Hi @vellrya, please read the templates before submitting them.
You can join and ask your questions at [@PyrogramChat](https://t.me/PyrogramChat).

> This place is for issues about Pyrogram, it's **not a forum**.
> If you'd like to post a question, please move to https://stackoverflow.com or join the Telegram community at https://t.me/pyrogram. Useful information on how to ask good questions can be found here: https://stackoverflow.com/help/how-to-ask.
