### ISSUE TITLE
sqlite3.OperationalError: no such column: number

### ISSUE THREAD

**Issue by RomanSafe** [pyrogram/pyrogram#622]
## Checklist
- [v] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [v] I have searched in the issue tracker for similar bug reports, including closed ones.
- [v] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I'm trying to send a message to a bot and search it. As the result I'm getting an exception `sqlite3.OperationalError: no such column: number`.

## Steps to Reproduce (my source code)
```python
import asyncio

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)

async def send_test(text):
    from pyrogram import Client
    
    bot_username = "@Eng_vocabulary_bot"
    app = Client("my_account", api_id=my_api_id, api_hash=my_api_hash)
    async with app:
        await app.send_message(bot_username, text)
        async for message in app.search_messages(bot_username, limit=1):
            print(message.text)


loop.run_until_complete(send_test("TEST"))
loop.close()
```

## Traceback
```
Traceback (most recent call last):
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/Telegram_bot_for_english_learners/stage1/telegram_bot/simple_bot.py", line 17, in <module>
    loop.run_until_complete(send_test("TEST"))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/Telegram_bot_for_english_learners/stage1/telegram_bot/simple_bot.py", line 11, in send_test
    async with app:
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/client.py", line 258, in __aenter__
    return await self.start()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 53, in start
    is_authorized = await self.connect()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect
    await self.load_session()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/client.py", line 668, in load_session
    await self.storage.open()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/storage/file_storage.py", line 112, in open
    self.update()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/storage/file_storage.py", line 71, in update
    version = self.version()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/storage/sqlite_storage.py", line 215, in version
    return self.conn.execute(
sqlite3.OperationalError: no such column: number

Process finished with exit code 1
```
I've taken a look at files `sqlite_storage.py` and `file_storage.py`, but I don't have any idea about the reason of this exception.
Do you have any thoughts about this issue? How can I fix it?

**Comment by ColinShark** [comment]
I don't see how creating a `new_event_loop` is necessary or even useful.
Can you try with just this below?

```python
from pyrogram import Client

app = Client("my_account")

with app:
    message = app.send_message("Eng_vocabulary_bot", "TEST")
    print(message.text)
```

Since the sent message is returned by the method `send_message`, we can simply assign it to a variable and print it, no need to search it again with another method call.

**Comment by delivrance** [comment]
It seems like you tried to load something that is not a Pyrogram session. Delete the file and restart your application, it will ask you to login again.

**Comment by RomanSafe** [comment]
@delivrance 
> It seems like you tried to load something that is not a Pyrogram session. Delete the file and restart your application, it will ask you to login again.

This suggestion solved the issue. Thanks a lot!!!

**Comment by Nachos25** [comment]
import sqlite3
from telethon.sync import TelegramClient, events
import time
from datetime import datetime, date


api_id = ''  # Отримайте це на my.telegram.org
api_hash = ''  # Отримайте це на my.telegram.org
bot_token = ''  # Отримайте це від BotFather
admin_chat_id =  # Ідентифікатор чату адміністратора

# Підключення до бази даних SQLite
conn = sqlite3.connect('phone_numbers.db')
cursor = conn.cursor()

conn.commit()

# Створення таблиці для зберігання часу останньої розсилки
cursor.execute('''
    CREATE TABLE IF NOT EXISTS sent_history (
        id INTEGER PRIMARY KEY,
        account_id INTEGER,
        username TEXT,
        sent_count INTEGER,
        last_sent_time REAL,
        last_broadcast_time REAL,
        recipients_count INTEGER
    )
''')

# Створення таблиці для зберігання імен користувачів
cursor.execute('''
    CREATE TABLE IF NOT EXISTS usernames (
        id INTEGER PRIMARY KEY,
        username TEXT,
        added_by INTEGER,
        account_id INTEGER
    )
''')

try:
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS phone_numbers (
            id INTEGER PRIMARY KEY,
            phone TEXT,
            account_id INTEGER,
            last_broadcast_time REAL,
            added_by INTEGER,
            recipients_count INTEGER
        )
    ''')
    conn.commit()
except sqlite3.OperationalError:
    pass

conn.commit()

# Перевіряємо, чи стовпець last_broadcast_time і recipients_count існують в таблиці phone_numbers
columns = [row[1] for row in cursor.execute('PRAGMA table_info(phone_numbers)').fetchall()]
if 'last_broadcast_time' in columns and 'recipients_count' in columns:
    print("Стовпці існують в таблиці.")
else:
    print("Стовпці відсутні в таблиці.")

def column_exists(cursor, column_name):
    cursor.execute("PRAGMA table_info(phone_numbers)")
    columns = [col[1] for col in cursor.fetchall()]
    return column_name in columns


client = TelegramClient('bot_session', int(api_id), str(api_hash)).start(bot_token=bot_token)

@client.on(events.NewMessage())
async def handle_message(event):
    if event.is_private and event.sender_id == admin_chat_id:
        # Отримуємо ID користувача, щоб використовувати його для збереження часу останньої розсилки
        user_id = event.sender_id

        # Отримуємо час останньої розсилки для цього користувача з бази даних
        db_last_broadcast_time = cursor.execute('SELECT last_broadcast_time FROM phone_numbers WHERE id = ?',
                                             (user_id,)).fetchone()

        today_date = date.today().strftime('%Y-%m-%d')  # Поточна дата в форматі 'Рік-Місяць-День'

        # Отримуємо час останньої розсилки та кількість користувачів, які отримали розсилку сьогодні
        result = cursor.execute(
            'SELECT last_broadcast_time, recipients_count FROM phone_numbers WHERE id = ?',
            (user_id,)).fetchone()

        if result is not None:
            db_last_broadcast_time_result, db_recipients_count = result
        else:
            db_last_broadcast_time_result, db_recipients_count = None, None

        # Використовуйте змінні last_broadcast_time і recipients_count далі в коді
        # Наприклад:
        if db_last_broadcast_time is not None and time.time() - db_last_broadcast_time < 24 * 60 * 60:
            await event.respond("Ви вже здійснили розсилку менше 24 годин тому. Будь ласка, зачекайте.")
            return
        message = event.message.message
        if message.startswith("/addaccount"):
            account_id = int(message[11:].strip())
            cursor.execute('INSERT INTO phone_numbers (account_id, added_by) VALUES (?, ?)', (account_id, user_id))
            conn.commit()
            await event.respond(f'ID аккаунта {account_id} додано для розсилки.')

        elif message.startswith("/sendtousers"):
            parts = message.split(' ', 1)
            if len(parts) < 2:
                await event.respond("Некоректна команда. Використовуйте /sendtousers список_користувачів.txt")
                return

            file_name = parts[1]

            try:
                with open(file_name, 'r') as file:
                    usernames = file.readlines()

                    for username in usernames:
                        username = username.strip()

                        cursor.execute('INSERT INTO usernames (username, account_id) VALUES (?, ?)',
                                       (username, event.sender_id))

                        conn.commit()

                    await event.respond(f'@username зі списку додано до бази даних.')
            except FileNotFoundError:
                await event.respond(f'Файл {file_name} не знайдено.')

        elif message.startswith("/sendmessages"):
            parts = message.split(' ', 1)
            if len(parts) < 2:
                await event.respond("Некоректна команда. Використовуйте /sendmessages Повідомлення")
                return

            msg_to_send = parts[1]
            entries = cursor.execute(
                'SELECT account_id FROM phone_numbers WHERE account_id IS NOT NULL AND added_by = ?',
                (user_id,)).fetchall()

            for entry in entries:
                account_id = entry[0]
                await client.send_message(account_id, f'Розсилка: {msg_to_send}')

            await event.respond(f'Розсилка надіслана користувачам.')


            # Додайте цей блок для обробки повідомлень від доданих аккаунтів
        elif message.startswith("/broadcast"):
            broadcast_message = message[11:]  # Видаляємо "/broadcast "
            phones = cursor.execute('SELECT phone FROM phone_numbers WHERE account_id = ?', (event.sender_id,)).fetchall()
            for phone in phones:
                await client.send_message(phone[0], broadcast_message)
        elif message.startswith("/recipientscount"):
            await event.respond(
                f'Кількість отримувачів розсилки сьогодні: {db_recipients_count if db_recipients_count is not None else 0}')



        else:

            account_id = event.sender_id

            phones = cursor.execute('SELECT phone FROM phone_numbers WHERE account_id = ?', (account_id,)).fetchall()

            sent_recipients = set()  # Множина для зберігання вже відправлених отримувачів

            for phone in phones:

                recipient_username = cursor.execute(

                    'SELECT username FROM usernames WHERE phone = ?',

                    (phone[0],)).fetchone()

                if recipient_username is not None and recipient_username[0] not in sent_recipients:

                    # Перевіряємо, скільки повідомлень було вже відправлено цьому @username з цього ID аккаунта

                    sent_count = cursor.execute(

                        'SELECT sent_count, last_sent_time FROM sent_history WHERE account_id = ? AND username = ?',

                        (user_id, recipient_username[0])).fetchone()

                    if sent_count is None or (
                            sent_count[0] < 35 and today_date != datetime.fromtimestamp(sent_count[1]).strftime(
                            '%Y-%m-%d')):

                        await client.send_message(phone[0], event.message)

                        sent_recipients.add(recipient_username[0])  # Додаємо @username до множини

                        # Оновлюємо історію відправки

                        if sent_count is None or today_date != datetime.fromtimestamp(sent_count[1]).strftime(
                                '%Y-%m-%d'):

                            cursor.execute(
                                'INSERT OR REPLACE INTO sent_history (account_id, username, sent_count, last_sent_time) VALUES (?, ?, ?, ?)',

                                (user_id, recipient_username[0], 1, time.time()))

                        else:

                            cursor.execute(
                                'UPDATE sent_history SET sent_count = ?, last_sent_time = ? WHERE account_id = ? AND username = ?',

                                (sent_count[0] + 1, time.time(), user_id, recipient_username[0]))

            # Оновлюємо лічильник отримувачів

            if db_recipients_count is None:

                db_recipients_count = len(sent_recipients)

            else:

                db_recipients_count += len(sent_recipients)

            cursor.execute('UPDATE phone_numbers SET last_broadcast_time = ?, recipients_count = ? WHERE id = ?',

                           (time.time(),db_recipients_count, user_id))

            conn.commit()

if __name__ == '__main__':
    conn = sqlite3.connect('phone_numbers.db')
    cursor = conn.cursor()

    print("Бот запущений. Натисніть Ctrl+C для зупинки.")
    client.run_until_disconnected()
    print("Бот вимкнено.")
I have similar error whith added_by 
Unhandled exception on handle_message
Traceback (most recent call last):
  File "D:\lib\site-packages\telethon\client\updates.py", line 570, in _dispatch_update
    await callback(event)
  File "C:\Users\Asus\PycharmProjects\Work\main.py", line 138, in handle_message
    entries = cursor.execute(
sqlite3.OperationalError: no such column: added_by
Pls help me.
