### ISSUE TITLE
My bot getting error after your Pyro update

### ISSUE THREAD

**Issue by Technical-Jigar** [pyrogram/pyrogram#625]
After your pyrogram update my bot getting this error app[worker.1]:     from pyrogram import Client, Message, MessageHandler, Filters, CallbackQueryHandler
2021-02-13T15:42:31.067239+00:00 app[worker.1]: ImportError: cannot import name 'Message' from 'pyrogram' 

So can u tell me which version should I use?

**Comment by delivrance** [comment]
Hi. Release notes exist.

**Comment by delivrance** [comment]
https://docs.pyrogram.org/releases/v1.0.0

**Comment by Technical-Jigar** [comment]
> https://docs.pyrogram.org/releases/v1.0.0

Ok

**Comment by Technical-Jigar** [comment]
> https://docs.pyrogram.org/releases/v1.0.0

I tried most of all versions getting error 

Yesterday I only used https://github.com/pyrogram/pyrogram/archive/asyncio.zip this and my app works file but now getting error 404 in this link
