### ISSUE TITLE
Problem to get linked_chat from iter_dialogs dialog.

### ISSUE THREAD

**Issue by Gor1194** [pyrogram/pyrogram#629]
## Checklist
- [ ] I am sure the error is coming from Pyrogram's code and not elsewhere.

## Description
In the first example of traceback, linked_chat returns None, but dialog has linked chat.
In second example, when trying to get chat, after that chat.linked_chat is normally returned.

## Traceback
1) 
```
for dialog in app.iter_dialogs():
    if dialog.chat.type == 'channel':
        print(dialog.chat.linked_chat)
```

2) 
```
for dialog in app.iter_dialogs():
    if dialog.chat.type == 'channel':
        chat = app.get_chat(dialog.chat.username)
        print(chat.linked_chat)
```

**Comment by delivrance** [comment]
Server limitation plus docs not mentioning that extra info such as `linked_chat` are available via `get_chat` only.
