### ISSUE TITLE
BadServerSalt raise nothing!

### ISSUE THREAD

**Issue by i-Naji** [pyrogram/pyrogram#63]
https://github.com/pyrogram/pyrogram/blob/debc45968614b3c9891afcb809e48bc3c79a4f93/pyrogram/session/session.py#L394

```py
elif isinstance(result, (types.BadMsgNotification, types.BadServerSalt)): 
```

**Comment by delivrance** [comment]
Are you reporting issues or giving opinions on how things should be done? This and #62 contain no real value. You must provide more info and, in case of an error, the full traceback or the unhandled exception you get.

**Comment by i-Naji** [comment]
my bad, sorry!
```
ERROR:pyrogram.client.dispatcher.dispatcher:'BadServerSalt' object has no attribute 'set'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/dispatcher/dispatcher.py", line 132, in update_worker
    chats
   "/usr/local/lib/python3.5/dist-packages/pyrogram/client/parse_mode.py", line 402, in parse_message
AttributeError: 'BadServerSalt' object has no attribute 'set'
```

**Comment by delivrance** [comment]
Thanks, but I'm afraid is not enough. You need to show me the steps on how to reproduce it.

**Comment by delivrance** [comment]
Related to https://github.com/pyrogram/pyrogram/issues/62#issuecomment-385173984
Closing.
