### ISSUE TITLE
Can't use progress in download_media()

### ISSUE THREAD

**Issue by rahmansharifi** [pyrogram/pyrogram#636]
Hi everybody. I have problem downloading media. I cannot define progress. Checkout my code:

**plugin_file**:
```
from pyrogram import Client, filters

def progress(current,total):
    print(f"{current * 100 / total:.1f}%")

@Client.on_message(filters.text, group=10)
def Process(Client, message):
    try:
        Photo = message.reply_to_message.from_user.photo.big_file_id
        Client.download_media(Photo,progress=progress)
    except AttributeError:
        message.reply_text('You have to reply on sb.',quote=True)
```
An error division by zero is returned. I am sure that account has profile photo. If you see any other problem, let me know. thanks.

![image](https://user-images.githubusercontent.com/21124569/110851783-bf53ae80-82c6-11eb-9baf-5590bc9cb5f9.png)

**Comment by delivrance** [comment]
The issue here is that, when downloading with a `file_id` instead of a media object, the total size is unknown and Pyrogram reports 0.

**Comment by rahmansharifi** [comment]
Thanks for your service.
