### ISSUE TITLE
Exit from script on Control+C||Z

### ISSUE THREAD

**Issue by sviat9440** [pyrogram/pyrogram#64]
Why dosn't work ctrl+c||z?

**Comment by delivrance** [comment]
You need to use [idle()](https://docs.pyrogram.ml/pyrogram/Client#pyrogram.Client.idle)?

**Comment by sviat9440** [comment]
Hm. tnx)

**Comment by delivrance** [comment]
Here's an example: https://github.com/pyrogram/pyrogram/blob/master/examples/welcome_bot.py

**Comment by LeonardoRick** [comment]
could you update this example?

**Comment by delivrance** [comment]
Examples can now be found in the documentation: https://docs.pyrogram.org/start/examples/welcomebot
