### ISSUE TITLE
Data files are written to an unexpected location by default

### ISSUE THREAD

**Issue by Equidamoid** [pyrogram/pyrogram#649]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ~~ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and~~ reproduced the issue using the latest development version.

## Description
The default handling of relative file paths is confusing.
For example, I try to use the `Client.download_media` method. I see `file_name: str = DEFAULT_DOWNLOAD_DIR,`, where `DEFAULT_DOWNLOAD_DIR = "downloads/"`. This leads to an assumption that the files will be written to `$PWD/downloads`, which is not the case. 
When you provide a relative path it still writes to the code directory: `download_media(..., 'test.png')` results in an attempt to write the data a place like`$project_root/bin/downloads/test.png` instead of `./test.png` as one may expect.

Similar problem exists for the session names: the database is written to the code directory, as opposed to the current working directory.

## Steps to Reproduce
Create a client, download a file.
Expected:
 - library uses the current working directory for all the data it writes by default

Actual:
 - library creates data files in an inappropriate place (source directory/`bin` of a virtualenv/etc., depending on the setup)

**Comment by ehsanonline** [comment]
duplicated of #330
