### ISSUE TITLE
Ability To Edit Inline Media With File Path / Client.save_file().

### ISSUE THREAD

**Issue by StarkGang** [pyrogram/pyrogram#652]
## Checklist
- [x] I believe the idea is awesome and would benefit the library.
- [x] I have searched in the issue tracker for similar requests, including closed ones.

## Description
A detailed description of the request.

I Wanted To Request Ability To Edit Media With Just File Path Or Client.save_file() Method.
This Will Make Editing inline Media Simpler and Better.
SomeTimes Its Hard To Edit Media With File ID. I Don't Think Its Impossible Because I Have Tried This With Other Libs (Ex. Telethon).

**Comment by delivrance** [comment]
This seems to be already possible: [edit_message_media](https://docs.pyrogram.org/api/methods/edit_message_media) accepts an [InputMedia](https://docs.pyrogram.org/api/types/InputMedia) type in its `media` argument. All `InputMedia` sub-types have a `media` argument that can accept a local path as well, as explained in docs.

**Comment by StarkGang** [comment]
But it gives some error.

**Comment by StarkGang** [comment]
I am Talking About Inline Media's Btw.

i am getting this error : https://nekobin.com/hemihafije | while editing inline media. the file exists, and i am able to upload it normally but unable to edit inline message media.
