### ISSUE TITLE
"video" filters need to search in file_name for search_messages fn:

### ISSUE THREAD

**Issue by m4mallu** [pyrogram/pyrogram#655]
To get more efficient results in search_messages fn, video filters need to be searched in file_name than in caption. Most of the video files doesn't have a caption text, but effectively having a good file_name. So it will be good to add the feature.

**Comment by delivrance** [comment]
`search_messages` is a wrapper for the raw method available in the full Telegram API. No local search is done, what you get is what the server sends.

**Comment by m4mallu** [comment]
Yeah.. I know! This is a common issue when using the fn. Hope, telegram will fix this in the future.
