### ISSUE TITLE
Group filter required undocumented 'm' argument

### ISSUE THREAD

**Issue by moonbaseDelta** [pyrogram/pyrogram#659]
Hi, I've tried to run group filter for `on_message()` decorator, but it don't want to be created without that argument. The purpose of that I don't know, `None` value fixed it well though. 
Same happens for arrays of group-names and for a single name.

```
@app.on_message(filters.group([..., ...], m=None))
def from_pyrogramgroup(client, message):
    # code
```

**Comment by moonbaseDelta** [comment]
But now it don't filter groups at all.

**Comment by AndrielFR** [comment]
I at this time: 🤔😳

**Comment by jonatan1609** [comment]
>  Hi, I've tried to run group filter for `on_message()` decorator, but it don't want to be created without that argument. The purpose of that I don't know, `None` value fixed it well though. 
> 
> Same happens for arrays of group-names and for a single name.
> 
> 
> 
> ```
> 
> @app.on_message(filters.group([..., ...], m=None))
> 
> def from_pyrogramgroup(client, message):
> 
>     # code
> 
> ```

As far as I remember you should not do filters.group(GROUPS) but filters.chat(GROUPS), and if you don't want a specific list of groups but any group just pass filters.group, correct me if I'm wrong
