### ISSUE TITLE
Cannot demote chat member using m.promote_member or c.promote_member

### ISSUE THREAD

**Issue by Divkix** [pyrogram/pyrogram#661]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Not able to demote user, whenever teying to demote, the bot just removes all the admin permissions and user still remians admin without any permission,
![photo_2021-04-03_23-43-47](https://user-images.githubusercontent.com/23524935/113515429-1b41e800-9592-11eb-827f-c268f0483281.jpg)

## Steps to Reproduce
```
from pyrogram import Client

api_id = 123456
api_hash = '123456789'
bot_token = '1234:abcd'
app = Client(
    "my_bot",
    bot_token=bot_token,
    api_id=api_id,
    api_hash=api_hash
)

@app.on_message()
async def demote_member(c,m):
    user_id = m.reply_to_message.from_user.id
    await m.chat.promote_member(
            user_id=user_id,
            can_change_info=False,
            can_delete_messages=False,
            can_restrict_members=False,
            can_invite_users=False,
            can_pin_messages=False,
            can_manage_voice_chats=False,
        )

@app.on_message()
async def demoet_chat_member(c,m):
    user_id = m.reply_to_message.from_user.id
    await c.promote_chat_memberte_member(
            user_id=user_id,
            chat_id=m.chat.id,
            can_change_info=False,
            can_delete_messages=False,
            can_restrict_members=False,
            can_invite_users=False,
            can_pin_messages=False,
            can_manage_voice_chats=False,
        )
```

## Traceback
None

**Comment by zeroone2numeral2** [comment]
I believe it's because since a few layer, Telegram introduced a new admin permission `can_manage_chat`, which you have to revoke in order to remove someone from the admins ([docs](https://docs.pyrogram.org/api/methods/promote_chat_member#pyrogram.Client.promote_chat_member))

**Comment by delivrance** [comment]
No issue in the library. `app.promote_chat_member(..., ..., can_manage_chat=False)` is enough to demote a chat member.
