### ISSUE TITLE
Client calls "freeze" when not called in the main thread

### ISSUE THREAD

**Issue by brun0-matheus** [pyrogram/pyrogram#667]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
When I call client.send_code('464541') in another thread rather than the main, the method freezes. It does not return anything and does not raise anything. When I call it in the main thread, it runs perfectly (in order to check this, uncomment the "run()" line and comment the thread and sleep stuff).

## Steps to Reproduce
``` python
import asyncio

import pyrogram
from threading import Thread


API_ID = API_ID
API_HASH = 'API_HASH'
finished = False


def run():
    global finished

    client = pyrogram.Client(':memory:', API_ID, API_HASH)

    print('Connecting...')
    client.connect()
    print('Connected. Sending code...')

    try:
        client.send_code('464541')
        print('Code sent.')
    except pyrogram.errors.PhoneNumberInvalid:
        print('Invalid phone number')

    finished = True


# run()  # Uncomment here in order to test calling the send_code in the main thread

# Comment from here to the end of the code in order to stop testing calling send_code in a different thread
th = Thread(target=run, daemon=True)
th.start()

while not finished:
    asyncio.run(asyncio.sleep(0.5))
```

## Traceback
The full traceback (if applicable).
No traceback, but the console of when the code freezes is:
```
Connecting...
Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Connected. Sending code...
```

**Comment by delivrance** [comment]
Hi, Pyrogram is an async library and therefore you need to use asyncio tasks instead of threads.
