### ISSUE TITLE
Allow parsing binary data directly to Client.save_file()

### ISSUE THREAD

**Issue by panos** [pyrogram/pyrogram#671]
## Checklist
- [x] I believe the idea is awesome and would benefit the library.
- [x] I have searched in the issue tracker for similar requests, including closed ones.

## Description

Hi, I'm a person trying to do away with I/O for my own project, as the edge cases would be a huge burden on me maintenance-wise, as I work on a project called [OnionSproutsBot](https://gitlab.torproject.org/tpo/anti-censorship/gettor-project/onionsproutsbot) [(GitHub)](https://github.com/panos/OnionSproutsBot) as a way to both help people and in order for me to learn how to use Pyrogram and interact with the Telegram platform.

I'd love to be able to use a variable assigned to the object returned by `requests.get()` with `Client.save_file()`, rather than having to store the file on my drive and then telling `Client.save_file()` where the file is using the `path` parameter. Right now, the bot developer is basically forced to act as a middleman. That way, I won't have to:

- Store files in folder, check whether the file was successfully downloaded, deal with doing this asynchronously, remove old files periodically, then upload the document to Telegram and save its `file_id`. I'd be able to skip through the entire hassle and just upload the file straight from the web, instantly on Telegram and be done with it, rather than maintaining a possibly huge local repository and having to manage that on my end.
- Check for file conflicts and deal with each occasion accordingly, possibly by blocking out a request or by wasting more disk space and Telegram's storage space, should multiple people request the same exact file at the same time.
- Use BytesIO as a huge hack/workaround, as the max amount of file size that can be uploaded at any given moment is approximately 144 gigabytes at once (since I'm mirroring software that's available for many different platforms in a considerable amount of locales).

The only real problem that would be left is having to store `file_id`s in an external database in my case, which would apply in either of these situations. I'll emphasize that I'm talking about why this would be useful to me as a manner of illustrating how much time this addition would save on the end of the maintainer that's dealing with similar situations in general by providing a real-world example. I think that it would add a considerable amount of flexibility to the project and lift a lot of weight from the end of bot developers, myself included.

**Comment by panos** [comment]
One could do away with this by simply using `client.send_document()` and using an HTTP link, but that may not be available if e.g. you're using a local SFTP server that Telegram's backend cannot reasonably access or if you're storing a recording taken from an audio buffer. Or basically any situation where the bot itself has to act as some sort of a middleman in some situations. This, unfortunately, also applies to my situation and for some of the future use cases that I have planned out.

**Comment by delivrance** [comment]
`save_file` is a low-level method used when you work with the full raw Telegram API. You can use `app.send_document` by passing a BytesIO instance wrapping your bytes. The maximum amount per file is 2 GB, this is a server limit.

Example:

``` python
f = BytesIO(b)
f.name = "valid name with extension.zip"
app.send_document(chat_id, f)
```

**Comment by panos** [comment]
> `save_file` is a low-level method used when you work with the full raw Telegram API. You can use `app.send_document` by passing a BytesIO instance wrapping your bytes. The maximum amount per file is 2 GB, this is a server limit.

In my case, BytesIO streams may possibly kill the bot, Each upload of a file is 80 megabytes, but there's more than 150 different variations of the same file that gets updated regularly. That would mean that a malicious person could make a lot of requests and have the bot run out of resources. I expect dozens all the way up to possibly thousands to use the bot concurrently.
 
`save_file` cannot work with web servers that falsely report their `Content-Type` as `Content-Type: text/plain` instead of `Content-Type: application/octet-stream`.

**Comment by delivrance** [comment]
> Wait, can you already use BytesIO with save_file and the documentation just doesn't mention it?

Correct. There's an issue in the documentation not mentioning BytesIO is allowed there. Thanks for finding that out.

> save_file cannot work with web servers that falsely report their Content-Type as Content-Type: text/plain instead of Content-Type: application/octet-stream.

This is not a Pyrogram issue. The mime type at the Pyrogram side is derived from the file name extension (see example above). This should not be a problem if you use `send_document` so that all media will be generic documents.

**Comment by panos** [comment]
> This is not a Pyrogram issue. The mime type at the Pyrogram side is derived from the file name extension (see example above). This should not be a problem if you use `send_document` so that all media will be generic documents.

I'm just explaining my case scenario as to why I cannot directly use the HTTP URL and `save_file()` and have to parse the bytes with BytesIO instead. This is indeed the fault of the Telegram backend.

I'm just saying that this will only work at a massive scale out of sheer luck and there's a ton of case scenarios where you may need to be able to send specific data to Telegram in scenarios with limited memory but relatively faster bandwidth, some of which are planned side-projects of mine, where storing everything in the much more limited memory with `BytesIO` cannot do the trick. `send_document()` won't do either for that matter. Either way, if I use BytesIO instead of streaming different chunks, there's a decent chance that the bot will break.

**Comment by panos** [comment]
For one, I thought of using the Telegram backend for IoT devices (e.g. use a Raspberry Pi Zero W in order to implement a camera feed that films the past 30 seconds when an event happens (e.g. sensor tripped), as well as with video calling functionality or a cosmetic, faux cassette recorder with similar restrictions). It'd probably a good idea to use something else in either of these situations, but the integration with the Telegram ecosystem is what makes these sorts of concepts interesting in my head.

Writing on SD cards persistently is expensive and the memory on those things is extremely limited, especially when video's involved, so the inability to send files in chunks in an efficient, easy manner is a bit of a blocker. That's what I'm sort of trying to illustrate through so many of these examples, and I'm not sure that I'll be the only one with those sorts of problems.

**Comment by panos** [comment]
Either way, if that doesn't sound convincing enough, I should probably close this issue so that neither of us spend any more time on debating back and forth.
