### ISSUE TITLE
filters.command adds trailing username to message's command attribute

### ISSUE THREAD

**Issue by L3Nya** [pyrogram/pyrogram#676]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
`filters.command` filter matches command in message and sets `command` field to `Message`.
But after that `Message.command` contains also trailing username of command if it was used.
## Steps to Reproduce
1. run this code
```python
from pyrogram import filters, Client
API_ID = 12345
API_HASH = ""
client = Client("pyrogram", API_ID, API_HASH)

@client.command("test")
def test(client, message):
    message.reply_text(f'args you sent: {message.command}')

client.run()    
```
2. Send `/test@your_username` to your account
3. It'll answer `args you sent: ['test', '@your_username']`

**Comment by L3Nya** [comment]
I don't know whether I should create a new issue or not, but they're related.

### Description
`filters.command` adds second argument, that is a command with trailing username if there's a trailing username, to `Message.command` if there's actually no arguments. 

### Steps to Reproduce
1. run this code
```python
from pyrogram import filters, Client
API_ID = 12345
API_HASH = ""
client = Client("pyrogram", API_ID, API_HASH)

@client.on_message(filters.command("start"))
def test(_, message):
    message.reply_text(f'args you sent: {message.command}')

client.run()
```
2. send `/start` to your account. it will answer `args you sent: ['start', 'start']`
   it isn't right.
3. send `/start@username` to your account. it will answer `args you sent: ['start', 'start@username']`
   it isn't right too.
4. send `/start argument` to your account. it will answer `args you sent: ['start', 'argument']`
   and it's right.

**Comment by delivrance** [comment]
@L3Nya It's ok. Thanks for reporting again! Fixed.
