### ISSUE TITLE
Error parsing HTML entities

### ISSUE THREAD

**Issue by MStudioBuildInc** [pyrogram/pyrogram#682]
The message may contain errors (Translated from Russian)

In the code of the parser for HTML entities, there is a removal of extra spaces and other line breaks, but it does not work correctly.
We are talking about this [function](https://github.com/pyrogram/pyrogram/blob/aef0cce8d973ffb3a7a5c7e1970fe714214a34f7/pyrogram/parser/html.py#L112)

`text = re.sub(r"\s+(</[\w\W]*>)\s*$", r"\1", text)`

This line of code can remove line breaks enclosed in HTML tags.
For example, if we received a message with HTML markup:

```
Any text ...
⚠️ <code> Any text


</code> ⚠️ <code> Any text </code>
```

Then after circumcision, it will turn into:

```
Any text ...
⚠️ <code> Any text </code> ⚠️ <code> Any text </code>
```

Because of this, the formatting breaks when sending

**Comment by delivrance** [comment]
The issue should now be fixed. You can install Pyrogram with the latest changes by following the steps here: https://docs.pyrogram.org/intro/install#bleeding-edge.

**Comment by MStudioBuildInc** [comment]
> The issue should now be fixed. You can install Pyrogram with the latest changes by following the steps here: https://docs.pyrogram.org/intro/install#bleeding-edge.

Thanks for the quick fix
