### ISSUE TITLE
Userbot on telegram crashing

### ISSUE THREAD

**Issue by Rawana07** [pyrogram/pyrogram#691]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
A **clear** and **concise** description of the problem. Code snippets must be
[minimal, reproducible](https://stackoverflow.com/help/minimal-reproducible-example) and properly formatted.
Below mentioned traceback is from heroku of an telegram userbot.. I'm not able to understood this and don't know how to fix I tried changing string session multiple times but it didn't worked.

``` python
from pyrogram import Client
...
```

## Traceback
The full traceback (if applicable).
pyrogram.errors.exceptions.not_acceptable_406.AuthKeyDuplicated: [406 AUTH_KEY_DUPLICATED]: The same authorization key (session file) was used in more than one place simultaneously. You must delete your session file and log in again with your phone number or bot token (caused by "InvokeWithLayer") 

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
```

**Comment by delivrance** [comment]
The error is clear. This is not a library issue
