### ISSUE TITLE
GitHub tags

### ISSUE THREAD

**Issue by dotlambda** [pyrogram/pyrogram#696]
Why are there discrepancies between the releases on https://pypi.org/project/Pyrogram/#history and the tags on https://github.com/pyrogram/pyrogram/releases?

**Comment by alissonlauffer** [comment]
Currently only the major releases are tagged in the repo, which is bad when someone wants to create a distro package from the library (which I think is your case).

@delivrance can you start tagging minor releases on GitHub?

**Comment by dotlambda** [comment]
ping @delivrance

**Comment by dotlambda** [comment]
ping @delivrance

**Comment by delivrance** [comment]
Hi. Starting from v2 (already released) I'm also tagging patch versions.

**Comment by dotlambda** [comment]
Thank you! The tag for 2.0.14 is missing though.

**Comment by delivrance** [comment]
Added.
