### ISSUE TITLE
Message Object

### ISSUE THREAD

**Issue by AYMENJD** [pyrogram/pyrogram#708]
Hi, i have a bot with high load ```100 update``` per second
And i want to rebulid my bot to use pyrogram and i make sample pyrogram code:
```
x = 0
@Client.on_message()
def start(client, message):
	global x
	print("\r"+str(x),end="")
	x += 1
```
is just simple code that print a number when receiving an update but when it reach 10k update it stops and printing 
```Server sent "-429"``` after 10 sec everything back normal . this thing repeat tons of times

i know that telegram will not include user first_name and last_name but in pyrogram Message Object it include first_name and last_name and that means pyrogram will make a requset to telegarm to get user information on each update right?.

i think that is the problem

**Comment by jonatan1609** [comment]
Yes, it's been a known issue about caching

**Comment by delivrance** [comment]
Related to 264 and #265.
