### ISSUE TITLE
on_deleted_messages bug

### ISSUE THREAD

**Issue by Dangeres** [pyrogram/pyrogram#709]
doesnt support filters.user and filters.user and filters.bot because on handling all income deleted messages, they are doesnt have chat if message has been deleted from user or bot.

if i delete message from any account and try to handle that, incoming data will be:
`'[\n    {\n        "_": "Message",\n        "message_id": 547808\n    }\n]'`

with channels that's work fine.

version pyro is 1.2.9 official
version tgcrypto is 1.2.2

**Comment by Dangeres** [comment]
Also an error with link of message:

```
pyrogram\types\messages_and_media\message.py", line 732, in link
    if self.chat.type in ("group", "supergroup", "channel") and self.chat.username:
AttributeError: 'NoneType' object has no attribute 'type'
```

**Comment by ColinShark** [comment]
Besides not filling out any issue templates making this issue inside, `on_deleted_message()` doesn't take any filters, since it's only to inform clients to no longer display the message with that id. There is no chat or content associated to filter against.

**Comment by Dangeres** [comment]
Well, how can i get chat id with deleted message?

**Comment by ColinShark** [comment]
Again, you don't.

> There is no chat or content associated to filter against.

**Comment by Dangeres** [comment]
Why? Telegram doesnt give you that info or smth else?

**Comment by ColinShark** [comment]
> Why? Telegram doesnt give you that info or smth else?

You literally printed the entire update you get from the Server. You have a `message_id`, that's it.
