### ISSUE TITLE
Multi line <pre> tag not working

### ISSUE THREAD

**Issue by kishorv06** [pyrogram/pyrogram#71]
I was testing the pre tag to send some text content, but it doesn't seem to work for multiple lines. I have to add each line with pre tag and it also fails if the string contains "/".

**Comment by delivrance** [comment]
Hi, care to post some examples I can test against?

**Comment by kishorv06** [comment]
`cmd = Popen("ls", shell=True, stdout=PIPE, stderr=PIPE, stdin=PIPE,universal_newlines=True)
 output_bytes = cmd.stdout.read()
 response = '<pre>' +output_bytes+'</pre>'
 client.send_message(chat_id,response,parse_mode=ParseMode.HTML)`

I am not sure what prevents the message from being sent. All tags are removed from the message, but the formatting will be gone.

**Comment by delivrance** [comment]
> If i send the same text by copy pasting as string, it works.

Well, then it's certainly something wrong in your script and nothing to do with the library itself ^^
Just `print(output_bytes)` and see how it looks like, first of all.
