### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'set_bot_commands'

### ISSUE THREAD

**Issue by MrBotDeveloper** [pyrogram/pyrogram#714]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Sir, I am trying to set Bot commands. My code is as follows

``` python
from pyrogram import Client

Client.set_bot_commands([
    BotCommand("start","Start the bot")
])
...
```
But it shows the following error.

## Traceback
The full traceback (if applicable).

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  Client.set_bot_commands([
  AttributeError: 'Client' object has no attribute 'set_bot_commands'
```

**Comment by jonatan1609** [comment]
You are supposed to use it with a `Client` object, not with the class itself but with an object.

**Comment by jonatan1609** [comment]
The same code works for me (except importing pyrogram.types for BotCommand). Try to re-install it and make sure you install it to the same environment you ran the code with.

**Comment by MrBotDeveloper** [comment]
Can you share it's sample code for better understanding ????

**Comment by jonatan1609** [comment]
> Can you share it's sample code for better understanding ???? 

Try to re-run the pip install command, and try again. You probably didn't install it to the correct interpreter.
Try it out:

python -m pip install https://... etc
python script.py

If needed, use python3 instead of python.

**Comment by MrBotDeveloper** [comment]
Ok sir thanks a lot ......
