### ISSUE TITLE
Bot Accepting Commands as Text

### ISSUE THREAD

**Issue by MrBotDeveloper** [pyrogram/pyrogram#721]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Sir, when I have filtered the reply messages but I am replying even a defined command to a file or text. It is taking it under the ```filter.reply``` category

``` python
from pyrogram import Client, filters

@Client.on_message(filters.reply & filters.text)
async def replied(client, cmd):
    msg = cmd.reply_to_message.text
    if "x" in msg:
        await msg.reply_text("Work 👍", quote=True)

@Client.on_message(filters.command("send"))
async def help(client, cmd):
    msg=cmd.reply_to_message
    if msg is None:
        await cmd.reply_text("Reply to a message.", quote=True)
        return
    await msg.reply_text("Thanks a lot", quote=True)
    return
...
```

## Traceback
The full traceback.

```log.txt
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/main.py", line 6, in replied
    if "x" in msg:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by delivrance** [comment]
The error is not arising from the library itself, hence it is not a Pyrogram issue.

**Comment by MrBotDeveloper** [comment]
Sir if If it is not Pyrogram issue then why it is accepting commands in text and replied issue please help

**Comment by delivrance** [comment]
Because `filters.text` checks the current message only, not the replied-to message, which was not a text in your case. It needs to be checked as well, either via custom filters or an extra `if`.

**Comment by MrBotDeveloper** [comment]
Sir but when I am replying my command ```/send``` to a document it is taking it under the 

```python
@Client.on_message(filters.reply & filters.text)
```

**Comment by MrBotDeveloper** [comment]
And giving this error in the log only when I reply /send to a document and if I simply sent /send command then the client is sending the if condition statement

**Comment by MrBotDeveloper** [comment]
**Sir please help me to clear my doubt....**

**Comment by delivrance** [comment]
The issue section on GitHub is only for actual issues with the library, it's not a forum for questions, albeit you were given an answer already. If you'd like to ask a question, do so at [StackOverflow](https://stackoverflow.com/questions/ask) or join the [community](https://t.me/pyrogram).

**Comment by MrBotDeveloper** [comment]
Ok sir thanks a lot for suggestion

**Comment by MrBotDeveloper** [comment]
Sir but GitHub also provide Discussions option for the questing and asking something but you haven't enabled it in the repo so please kindly enable it for the clearification of the doubts
