### ISSUE TITLE
Question:How do I use pyrogram to complete registration

### ISSUE THREAD

**Issue by u6chen** [pyrogram/pyrogram#723]
## Checklist
- [x] I believe the idea is awesome and would benefit the library.
- [x] I have searched in the issue tracker for similar requests, including closed ones.

## Description
How do you register using pyrogram?i tried to manipulate it but it kept getting an error,Looking forward to the answers. Thanks

**Comment by delivrance** [comment]
Hi. The issue section on GitHub is for actual issues with the library, it's not a forum for questions.
If you'd like to ask a question, do so at [StackOverflow](https://stackoverflow.com/questions/ask) or join the [community](https://t.me/pyrogram).
