### ISSUE TITLE
PYROGRAM WITH THREAD

### ISSUE THREAD

**Issue by An0nimia** [pyrogram/pyrogram#725]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I was trying to call a pyrogram function inside a Threaded function, but it doesn't work, why? Thanks in advice :)

``` python
from pyrogram import Client
...
#!/usr/bin/python3

from pyrogram import Client
from threading import Thread

api_id = "xxxx"
api_hash = 'xxxx'

client = Client('my_account', api_id, api_hash)
client.start()

def get_client():
	client.send_message("me", "ciao")

Thread(
	target = get_client,
	daemon = True
).start()

```

**Comment by jonatan1609** [comment]
Define "doesn't work". Any error?

**Comment by An0nimia** [comment]
> Define "doesn't work". Any error?

No it just remains stuck try execute it by yourself you will see.

**Comment by 12inchpianist** [comment]
I can confirm this behavior as I observed the same. Running pyrogram in threads doesn't work, it just gets stuck without throwing any errors. Same code, but using multiprocessing instead of multithreading works.

I guess that using threads somehow causes conflicts with the async framework that pyrogram uses internally.

**Comment by rking32** [comment]
@An0nimia have you tried adding `idle()` to the end (main thread) ?

**Comment by An0nimia** [comment]
> @An0nimia have you tried adding `idle()` to the end (main thread) ?

Yes, if I am not wrong and this will create another problem because idle would stop the code execution, but I need to execute an while to check some things.

**Comment by rking32** [comment]
> I need to execute a while loop to check some things.

Don't use blocking while loops in main thread. Since pyrogram is fully asynchronous it will block the event loop and your bot won't work. Also make sure that event loop is running in main thread. Since `idle()` basically do this you can place your while loop inside the event loop. but don't block it, you can give long sleeps.

```python
import asyncio

async def main():
    while True:
        # do your work
        await asyncio.sleep(60)

client.run(main())
```

**Comment by An0nimia** [comment]
> > I need to execute a while loop to check some things.
> 
> Don't use blocking while loops in main thread. Since pyrogram is fully asynchronous it will block the event loop and your bot won't work. Also make sure that event loop is running in main thread. Since `idle()` basically do this you can place your while loop inside the event loop. but don't block it, you can give long sleeps.
> 
> ```python
> import asyncio
> 
> async def main():
>     while True:
>         # do your work
>         await asyncio.sleep(60)
> 
> client.run(main())
> ```
> 

Okay but still persists the problems with threads because I have to start a thread which start something for downloading and uploading content and I have to be able to stop that thread anytime and in the thread I need pyrogram api for uploading content.

**Comment by rking32** [comment]
Are you calling `thread.join()` in main thread or can you share code of main thread ?

**Comment by delivrance** [comment]
Latest changes have improved usages with threads and possibly fixed the issues described here.

**Comment by An0nimia** [comment]
No, it didn't fixed, maybe the only thing which is changed but I am not 100% sure, is the fact that if I call the function Thread set with daemon = True, when it comes to the line ``` app.send_message('me', 'ciao')```  it stops the script.
P.S. No the message 'ciao' isn't sent.

**Comment by An0nimia** [comment]
> Latest changes have improved usages with threads and possibly fixed the issues described here.



> Latest changes have improved usages with threads and possibly fixed the issues described here.

No, it didn't fixed, maybe the only thing which is changed but I am not 100% sure, is the fact that if I call the function Thread set with daemon = True, when it comes to the line app.send_message('me', 'ciao') it stops the script.
P.S. No the message 'ciao' isn't sent. Anyway thanks for trying :)

**Comment by An0nimia** [comment]
This solved with last version thanks a lot.

```
from pyrogram import Client, idle
from threading import Thread

client = Client(...)
client.start()


def get_client():
    client.send_message("me", "ciao")


Thread(target=get_client, daemon=True).start()
idle()
```
