### ISSUE TITLE
Bug when deleting profile photos

### ISSUE THREAD

**Issue by Danipulok** [pyrogram/pyrogram#726]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
`ValueError: Unknown constructor found: 0xXXXXXXX` while deleting profile photos.
Both async and 'sync' way.
Result: in both ways the profile photos are deleted, but we still get the error.

## Code
Async code - [here](https://nekobin.com/falodisede.py)
Sync code - [here](https://nekobin.com/vapajoyedo.py)

## Traceback
Async traceback - [here](https://nekobin.com/qisocaxayo.py)
Sync traceback - [here](https://nekobin.com/wupamigucu.py)

**Comment by delivrance** [comment]
Duplicate issue. You didn't really search for a similar issue, neither you did install the latest development version (or in case you did, you were not running that).
