### ISSUE TITLE
Bot Authorization without api id not work but should

### ISSUE THREAD

**Issue by gzivdo** [pyrogram/pyrogram#74]
the config.ini consist only of proxy settings.
```
Traceback (most recent call last):
  File "./1.py", line 6, in <module>
    app.start()
  File "/usr/local/lib/python3.4/dist-packages/pyrogram/client/client.py", line 179, in start
    self.load_config()
  File "/usr/local/lib/python3.4/dist-packages/pyrogram/client/client.py", line 824, in load_config
    "No API Key found. "
AttributeError: No API Key found. More info: https://docs.pyrogram.ml/start/ProjectSetup#configuration

```
For the other libs and the raw api  only token is sufficient to send message to chat via chat_id.
Also i tried to put into config.ini newly created api_id and api_hash and created client by bot token and tried to send to chat and got:
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pyrogram/client/client.py", line 976, in resolve_peer
    return self.peers_by_id[peer_id]
KeyError: -<mychatid>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pyrogram/client/client.py", line 979, in resolve_peer
    return self.peers_by_id[-peer_id]
KeyError: <mychatid>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pyrogram/client/client.py", line 982, in resolve_peer
    return self.peers_by_id[int("-100" + str(peer_id))]
ValueError: invalid literal for int() with base 10: '-100-<mychatid>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./1.py", line 8, in <module>
    app.send_message(-<my chat id>, "Hi there! I'm using Pyrogram")
  File "/usr/local/lib/python3.4/dist-packages/pyrogram/client/methods/messages/send_message.py", line 74, in send_message
    peer=self.resolve_peer(chat_id),
  File "/usr/local/lib/python3.4/dist-packages/pyrogram/client/client.py", line 984, in resolve_peer
    raise PeerIdInvalid
pyrogram.api.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid
```

**Comment by delivrance** [comment]
Hi.

> For the other libs and the raw api only token is sufficient to send message to chat via chat_id.

This can't be true, other libs might use some default API key allowing you to just pass your bot token, but you always need one when dealing with the MTProto API, for both Users and Bots, there's no exception.

For your other problem, currently you need to keep your bot online with pyrogram and kick and invite it back from your chat. Done that, you'll then be able to send messages using chat ids.  For public groups (using usernames) you don't need to re-invite the bot.

**Comment by gzivdo** [comment]
Possibly telegram_send not use mtproto api. Anyway, I followed your recommendations and still getting 
`pyrogram.api.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid
`
But this work fine and without api_id/api_hash, just bot token.
curl -X POST "https://api.telegram.org/botXXX:YYYY/sendMessage" -d "chat_id=-zzzzzzzzzz&text=my sample text"

**Comment by delivrance** [comment]
@gzivdo Hi, you need to understand that Pyrogram (in your case, as you are login with a bot identity) acts like a self-hosted bot API backend. I can assure you that the official bot API at [api.telegram.org](api.telegram.org) is built on top of MTProto too and needs an API key (api_id + api_hash) for itself, but this is not a requirement for end users/developers and is hidden server side.

Pyrogram, being written entirely from scratch, follows Telegram specifications and requirements and one of them is that you always need an API key in order to authorize both users and bots. We can't do otherwise.

About your recurrent issue: Can you please show a snippet of your code that triggers that exception?

**Comment by gzivdo** [comment]
```
#!/usr/bin/python3
from pyrogram import Client

app = Client("4668xxxx6:AAENxlTnXcdm1VlcxR5SqzLYJJ......")
app.start()
app.send_message(-1001144015619, "test1")
app.stop()

```
When it was started (just app.start()) i kicked bot from chat and added again.

**Comment by delivrance** [comment]
Running that code won't make it work! The bot will start and stop immediately with an error (PEER_ID_INVALID).

Run this instead:

``` python
from pyrogram import Client

app = Client("4668xxxx6:AAENxlTnXcdm1VlcxR5SqzLYJJ......")
app.start()
app.idle()
```

`.idle()` will block there and keep the bot online. While the script is running, re-invite the bot and then press <kbd>CTRL+C</kbd> to stop it. The chat_id is now saved in your `4668xxxx6:.session` file and `app.send_message(-100xxxx5619, "test1")` should work.

**Comment by gzivdo** [comment]
Thanks, working now.
Can i just use while True cycle without app.idle() or I need to create own thread for my logic flow?

**Comment by delivrance** [comment]
Yes, idle() exists for convenience and is optional. Just make sure you call app.stop() before exiting your script.
