### ISSUE TITLE
[bug] Multiple media are not handled correctly

### ISSUE THREAD

**Issue by sam01101** [pyrogram/pyrogram#740]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Pyrogram can't parse multiple/batch media as shown in following picture
![image](https://user-images.githubusercontent.com/25792361/128611110-468e4b0a-9bf2-434c-9919-f3eab403dd32.png)
Any types of media more than two will encounter this problem.
|
|
The funny is, when replying to a batch media, `reply_to_message` will show first media as `Document` type, whatever the type it is.
![image](https://user-images.githubusercontent.com/25792361/128611285-2752e53d-ff40-445b-99d7-d0673c26111f.png)
![image](https://user-images.githubusercontent.com/25792361/128611261-6346b6f6-b148-4ed2-8a45-97d1b368881d.png)
^ Other are skipped and not shown
|
|
I've checked the code and I found out Pyrogram only parse **one** media each message, that cause the problem.

## Code snippets
_Code snippets are not available due to internal code issue_

## Traceback
_No traceback available due to internal code issue_

**Comment by ColinShark** [comment]
Each media is its own message. Each of those messages share a `media_group_id` attribute. That id identifies an album.
You could use [`app.get_media_group()`][1] to get a list of all messages that share an album.

[1]: https://docs.pyrogram.org/api/methods/get_media_group

**Comment by sam01101** [comment]
> Each media is its own message. Each of those messages share a `media_group_id` attribute. That id identifies an album.
> You could use [`app.get_media_group()`](https://docs.pyrogram.org/api/methods/get_media_group) to get a list of all messages that share an album.

Got it, thank you.
