### ISSUE TITLE
How to handle if an account is deleted/deactivated?

### ISSUE THREAD

**Issue by i-paya** [pyrogram/pyrogram#75]
Hi ,
How can I handle an deleted account and stop the program ?

I wrote this code but it doesn't work .
```python3 
try:
    client.start()
except Exception as e :
    sys.exit()
```
It just returns this and doesn't close the program .
`[401 USER_DEACTIVATED]: The user has been deleted/deactivated
pyrogram.api.errors.exceptions.unauthorized_401.UserDeactivated: [401 USER_DEACTIVATED]: The user has been deleted/deactivated`

**Comment by delivrance** [comment]
You must call ```client.stop()``` before exiting your script.

To specifically handle `[401 USER_DEACTIVATED]` you can do:

``` python
from pyrogram.api.errors import UserDeactivated

try:
    client.start()
except UserDeactivated:
    client.stop()
```
