### ISSUE TITLE
__init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by buzz3rs** [pyrogram/pyrogram#753]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I am trying to write a script that destroys sessions in a telegram account via ResetAuthorization.
I noticed with some accounts it works just fine but some accounts will get this error

``` python
from pyrogram import Client, idle
from pyrogram.raw import functions
from config import API_ID, API_HASH
import traceback
accountsession = "TEST"
client = Client(accountsession, API_ID, API_HASH, workdir="sessions")

AccountSessions = await client.send(   
        functions.account.GetAuthorizations()
)
for session in AccountSessions.authorizations:
        if session.current is not True:                                        
                try:
                        await client.send(   
                                functions.account.ResetAuthorization(
                                        int(session.hash)
                                 )
                         )
                except Exception as e:
                        print(f"{type(e).__name__ } : {e}")
                        traceback.print_tb(e.__traceback__)
```

## Traceback
```
TypeError : __init__() takes 1 positional argument but 2 were given
  File "main.py", line 507, in update_accounts
    int(session.hash)
```

**Comment by ColinShark** [comment]
Raw Methods require you to 
> [..] fill them in with the correct values using named arguments.

2nd Paragraph: https://docs.pyrogram.org/topics/advanced-usage#invoking-functions
