### ISSUE TITLE
How can I get telegram channels id

### ISSUE THREAD

**Issue by ErtepBerke** [pyrogram/pyrogram#755]
Hi I saw a function named "getchannels" and it says it can give channels id but I don't know how to use it how can I use It or do u know another method for getting id of a channel

**Comment by ColinShark** [comment]
This is not a question an answer forum. The issues tab on GitHub is only for bug reports an feature requests.
If you want to inquire on how methods work, please use either the [Pyrogram tag on StackOverflow][1], or [ask in the Telegram Chat][2].

[1]: https://stackoverflow.com/questions/tagged/pyrogram
[2]: https://t.me/PyrogramChat
