### ISSUE TITLE
Repeated dialogs when running iter_dialogs(...)

### ISSUE THREAD

**Issue by User087** [pyrogram/pyrogram#756]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
When trying to get around the seemingly never-ending floodwaits mentioned in #749, I encountered another issue. When I run `count = client.get_dialogs_count()`, I expect I should be able to retrieve all the dialogs with `client.iter_dialogs(count)`. Instead, some were missing. In my case, `count` was equal to 521 whereas I had to make the argument of `client.iter_dialogs(...)` at least 526 for all the dialogs to be retrieved. It turned out that every 100 dialogs, a dialog was being repeated, as if the last dialog of the previous GetDialogs request was then the first dialog retrieved in the next GetDialogs request. You can test using the code below (change the argument of `client.iter_dialogs(...)` as appropriate).

``` python
from pyrogram import Client
client = Client(...)
client.start()
count = client.get_dialogs_count()
print(count)
l = []
for x in client.iter_dialogs(526):
    print(x.chat.id)
    l.append(x.chat.id)
print(len(l))
```

When I increased the argument of `client.iter_dialogs(...)` beyond 526, the final dialog just kept on repeating itself.

I found that when I change [line 81 of iter_dialogs.py](https://github.com/pyrogram/pyrogram/blob/fdbab8cc87ea6363e1c3358647abd758b5717e90/pyrogram/methods/chats/iter_dialogs.py#L81) from `offset_date = dialogs[-1].top_message.date` to `offset_date = dialogs[-1].top_message.date-1`, the issue seems to be fixed. No dialogs are repeated, and all the dialogs are retrieved with `client.iter_dialogs(count)`.
This also seems to have been sufficient to fix the never-ending floodwaits mentioned in #749. I could now run `client.iter_dialogs()` with no argument and it returns all the dialogs without repeats or floodwaits.

Consider merging #750.

**Comment by User087** [comment]
Until this gets fixed, a possible workaround is to use `client.iter_dialogs(count+(count//100))` instead of `client.iter_dialogs()` (where `count = client.get_dialogs_count()`).

**Comment by delivrance** [comment]
This issue should be now fixed with latest changes.
