### ISSUE TITLE
When registering an account with a new phone number,  the mobile phone fails to receive SMS code?

### ISSUE THREAD

**Issue by hipitt** [pyrogram/pyrogram#761]
When registering an account with a new phone number, send_code(phone_number) is executed successfully, but the mobile phone does not receive the SMS code. using TelegramClient's send_code_request triggers a SMS, it can be received. How can I handle it?

`
# send sms code for registering an account
           res = app.send_code(phone_number)
           if (res and res.type != "sms") or force_sms:
                res = app.resend_code(phone_number, res.phone_code_hash)

           #.....
           signed_in = app.sign_in(phone_number, phone_code_hash=phone_code_hash, phone_code=verify_code)
           #.....
           signed_up = app.sign_up(phone_number, phone_code_hash, first_name="TG{}".format(phone_number[-4]))
`
#sign_up,send_code

**Comment by hipitt** [comment]
@delivrance please help me

**Comment by delivrance** [comment]
Hi. The issue section on GitHub is for actual issues with the library, it's not a forum for questions.
If you'd like to ask a question, do so at [StackOverflow](https://stackoverflow.com/questions/ask).
