### ISSUE TITLE
how to create two threads with one phone number?

### ISSUE THREAD

**Issue by mohsenamoon1160417237** [pyrogram/pyrogram#773]
Hello assume I have a phone number and I want to create 2 threads with this number. how can I do this?

like this:

app = Client(api_id=API_ID, api_hash=API_HASH, phone_number=PHONE_NUMBER)
def do_sth():
   app.start()
   print("hello")
   app.stop()

t1 = threading.Thread(target=do_sth)
t1.start()
t1.join()
t2 = threading.Thread(target=do_sth)
t2.start()

but it does not work.

**Comment by delivrance** [comment]
Hi. The issue section on GitHub is for actual issues with the library, it's not a forum for questions. If you'd like to ask a question, do so at [StackOverflow](https://stackoverflow.com/questions/ask).
