### ISSUE TITLE
Open photos automatically

### ISSUE THREAD

**Issue by prashanth742** [pyrogram/pyrogram#78]
How  to open upcoming photos from telegram channel automatically?

**Comment by delivrance** [comment]
@prashanth742 Hi, there's nothing that lets you "open photos automatically", you need to download the photo of a media message first and then do whatever you like with it.

To achieve this you set up a MessageHandler, filter the channel and use download_media(). Example:

 python
@app.on_message(Filters.chat(<channel id or username>)
def _(client, message):
    client.download_media(message)


This handler will automatically download every new media posted in that specific channel. To only allow photos you can combine your filter with Filters.photos.

More info: https://docs.pyrogram.ml/resources/UpdateHandling#combining-filters
