### ISSUE TITLE
Add Multiple

### ISSUE THREAD

**Issue by Cyber56** [pyrogram/pyrogram#782]
Hello i'm begginer how to add multiple chat id in

TARGET_CHAT =

Always showing the "sqlite3.interfaceerror error binding parameter 0 - probably unsupported type" 
If i try to make like this
TARGET_CHAT = ["@id", "@id"]

**Comment by ColinShark** [comment]
This is not a Q&A Forum. The Issues are only for suggestions or bugs in the Library itself.

For questions, please join the [Telegram Group](https://t.me/PyrogramChat) instead.
