### ISSUE TITLE
KeyError: ID not found

### ISSUE THREAD

**Issue by asarubbo** [pyrogram/pyrogram#786]
## Checklist
- [ ] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [ ] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I'm using pyrogram-1.2.0 with python3.8. I have correctly obtained api_id and api_hash and I can send message to myself. I can't send message to others. I found the RECEIVER_ID via @userinfobot (https://github.com/nadam/userinfobot), I tried also the phone number with the international prefix, but every time I got the attached stacktrace.
MY_API_ID - MY_API_HASH - RECEIVER_ID have been replaced in the attachments.

``` python
from pyrogram import Client
app = Client("bot", api_id="MY_API_ID", api_hash="MY_API_HASH")

app.start()
app.send_message("RECEIVER_ID", "test")
app.stop()
```

## Traceback
The full traceback (if applicable).

```
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/tgcrypto
Pyrogram v1.2.0, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 60, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/usr/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 147, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: RECEIVER_ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 83, in resolve_peer
    return await self.storage.get_peer_by_phone_number(peer_id)
  File "/usr/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 172, in get_peer_by_phone_number
    raise KeyError(f"Phone number not found: {phone_number}")
KeyError: 'Phone number not found: RECEIVER_ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "send_m.py", line 6, in <module>
    app.send_message("RECEIVER_ID", "test")
  File "/usr/lib/python3.8/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/pyrogram/methods/messages/send_message.py", line 127, in send_message
    peer=await self.resolve_peer(chat_id),
  File "/usr/lib/python3.8/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 85, in resolve_peer
    raise PeerIdInvalid
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it
```

**Comment by ColinShark** [comment]
The session you're trying to send a message from hasn't met the user the id belongs to yet, and thus cannot resolve it. You need to use either the `@username`, or their phone number if they're a contact of yours. Meet the user first by receiving a message from them, or use a method like `app.iter_dialogs()` to "meet" all dialogs and have their IDs cached in your session file.

**Comment by asarubbo** [comment]
Thanks for the response.

This contact does not have an username so I can't use '@'. It is a contact of mine and I received a lot of message. It does not work for me if I use the phone number (as stated in the first comment)

**Comment by asarubbo** [comment]
For anyone that hits this issue:

- If you have the username, there are no problems,
- If the contact does not have an username, you need to find the numeric ID of the chat, you can do it via telegram web for example, after that you need to run the code in this way:

```
from pyrogram import Client
app = Client("bot", api_id="MY_API_ID", api_hash="MY_API_HASH")

receiver = 123456789

app.start()
app.get_chat(receiver)
app.send_message(receiver, "test")
app.stop()
```

@ColinShark I really suggest to explain that in the documentation because it isn't clear at all.

**Comment by delivrance** [comment]
Even if you have the id, [this FAQ](https://docs.pyrogram.org/faq#i-keep-getting-peer-id-invalid-error) applies.
