### ISSUE TITLE
How can I send a URL BUTTON  to group

### ISSUE THREAD

**Issue by wz343450860** [pyrogram/pyrogram#79]
Hi, 
    I want to use @toolkitbot to send URL BUTTON to some group,  does the Pyrogram support the method?  If it it not supported  how should I do to realize the purpose?

**Comment by delivrance** [comment]
Hi, I've answered you in the group: https://t.me/PyrogramChat/19479

> Hi, yes. You can do that with Pyrogram, check this example https://github.com/pyrogram/pyrogram/blob/develop/examples/send_bot_keyboards.py
