### ISSUE TITLE
Pyrogram v1.2.9 auth not working. [406 Not Acceptable]: [406 UPDATE_APP_TO_LOGIN] 

### ISSUE THREAD

**Issue by charindithjaindu** [pyrogram/pyrogram#794]
## Checklist
- [✔️ ] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [ ✔️] I have searched in the issue tracker for similar bug reports, including closed ones.
- [ ✔️] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I tried to get session string for my music bot. Then this happened

``` python
from pyrogram import Client

with Client("Jaindu", api_id=api_id, api_hash=api_hash) as bot_:
    first_name = (bot_.get_me()).first_name
    string_session_ = f"<b>String Session For {first_name}</b>\n<code>{bot_.export_session_string()}</code>"
    bot_.send_message("me", string_session_, parse_mode="html")
    print(f"String Has Been Sent To Your Saved Message : {first_name}")
```

## Traceback

```
Traceback (most recent call last):
  File "sesgen.py", line 65, in <module>
    api_hash=input("Enter API HASH: ")) as pyrogram:
  File "/home/jaindu2015/.local/lib/python3.7/site-packages/pyrogram/client.py", line 249, in __enter__
    return self.start()
  File "/home/jaindu2015/.local/lib/python3.7/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/jaindu2015/.local/lib/python3.7/site-packages/pyrogram/methods/utilities/start.py", line 57, in start
    await self.authorize()
  File "/home/jaindu2015/.local/lib/python3.7/site-packages/pyrogram/client.py", line 303, in authorize
    sent_code = await self.send_code(self.phone_number)
  File "/home/jaindu2015/.local/lib/python3.7/site-packages/pyrogram/methods/auth/send_code.py", line 54, in send_code
    settings=raw.types.CodeSettings()
  File "/home/jaindu2015/.local/lib/python3.7/site-packages/pyrogram/methods/advanced/send.py", line 81, in send
    else self.sleep_threshold)
  File "/home/jaindu2015/.local/lib/python3.7/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/jaindu2015/.local/lib/python3.7/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/jaindu2015/.local/lib/python3.7/site-packages/pyrogram/errors/rpc_error.py", line 73, in raise_it
    is_unknown=True)
pyrogram.errors.exceptions.not_acceptable_406.NotAcceptable: [406 Not Acceptable]: [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SendCode")
```

**Comment by MdHazrat8361** [comment]
Same Problem Bro.. 😥

**Comment by Feelini** [comment]
Me too

**Comment by Malladoi** [comment]
same trouble

**Comment by A9FM** [comment]
try to change the name of the variables in which the input

**Comment by Malladoi** [comment]
> try to change the name of the variables in which the input

`with Client("my_cli", api_id=apiid, api_hash=apihash) as bot_:`

doesn't work

**Comment by Malladoi** [comment]
I found some comment with "maybe" solution in https://github.com/alexander-akhmetov/python-telegram/issues/227

**Comment by charindithjaindu** [comment]
Telegram made a server side change today morning. 

so new sign_in / sign_up (from old clients) are affected.

**Comment by Malladoi** [comment]
This issue is global. Reason explained here https://github.com/LonamiWebs/Telethon/issues/3215#issuecomment-983368827

**Comment by dashezup** [comment]
Just for the record, today some people including me received the message from Telegram

<details>
  <summary>Click to expand!</summary>

> [Forwarded from Telegram]
>
> Dear developer, 
>
> Telegram continues to grow worldwide, in part thanks to your third-party app. If your app is built from your own code, you'll need to make two changes so your users can keep chatting. If you are using the up-to-date open source code for one of our apps, these changes have already been made. 
>
> Support for int64 IDs
> With its rapid growth, Telegram is moving from 32-bit to 64-bit IDs so that users can continue creating billions of groups, channels and bots. Your app will need to support these new IDs as soon as possible to ensure users aren't interrupted. 
>
> To do so, make sure your app supports this API layer: https://core.telegram.org/api/layers#layer-133
>
> Sponsored Messages
> To cover its growing infrastructure costs, Telegram added sponsored messages (https://promote.telegram.org/) – a paid, privacy-friendly way to promote bots and channels. We are happy to see support for this has already been added across the majority of third-party apps.
>
> We ask that you make sure that these sponsored messages are supported and properly displayed in your app by January 1, 2022. Unfortunately, Telegram cannot financially sustain apps that support Telegram Channels but do not display official sponsored messages – such apps will have to be disconnected. 
>
> The necessary methods for this change are available here: https://core.telegram.org/api/sponsored-messages
>
> You can read more about sponsored messages here: https://t.me/durov/172
>
> Telegram's API usage will continue to be free of charge for all developers. We're counting on your understanding and support so that Telegram and your app can continue to offer private, secure messaging to people around the world. 
>
> The Telegram Team
</details>

And I experienced the login issue on new session login as well

`pyrogram.errors.exceptions.not_acceptable_406.NotAcceptable: [406 Not Acceptable]: [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SendCode")`

Not being able to login on new session is somehow critical for me. I hope this issue could be fixed soon.

Out of curious, this requires updated wheel which include newer version of TDLib and corresponding code changes in Pyrogram? is it hard to be done?

**Comment by zeroone2numeral2** [comment]
@dashezup pyrogram doesn't use tdlib, it's a native python MTProto client. No idea what needs to be done, but it's entirely up to pyrogram

**Comment by Malladoi** [comment]
> Out of curious, this requires updated wheel which include newer version of TDLib and corresponding code changes in Pyrogram? is it hard to be done?

IDK. I'm first-day-user of this lib, need more time to explore source. Maybe later.

Interesting big question is: will tg ban userbots on this type of libs, because we have a new condition about sponsored messages.

**Comment by loverboyXD** [comment]
Getting this in both telethon also🧐🍂 
I hope Dan will fix it soon🙇 Please Fix this String Problem soooon

**Comment by delivrance** [comment]
This issue has been fixed. You can upgrade with the usual command `pip install -U pyrogram`.

**Comment by Ghost-147** [comment]
> 

how can i get this to work. using what comand?

**Comment by Ghost-147** [comment]
> This issue has been fixed. You can upgrade with the usual command `pip install -U pyrogram`.

telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: UPDATE_APP_TO_LOGIN

same error message

**Comment by ColinShark** [comment]
> telethon.errors.rpcbaseerrors.AuthKeyError

That's a Telethon error, not Pyrogram. If you keep getting errors, consult with Telethon's Issues.

**Comment by loverboyXD** [comment]
> > telethon.errors.rpcbaseerrors.AuthKeyError
> 
> That's a Telethon error, not Pyrogram. If you keep getting errors, consult with Telethon's Issues.

Ok thanks.. i have fixed this :) just upgraded my PyroGram

**Comment by Ghost-147** [comment]
> > > telethon.errors.rpcbaseerrors.AuthKeyError
> > 
> > 
> > That's a Telethon error, not Pyrogram. If you keep getting errors, consult with Telethon's Issues.
> 
> Ok thanks.. i have fixed this :) just upgraded my PyroGram

I used this command pip install -U pyrogram and it downloaded  but still brings same errror message. How did you fix yours and are you able to login telegrams on python?. Please i need help urgently.

**Comment by loverboyXD** [comment]
> > > > telethon.errors.rpcbaseerrors.AuthKeyError
> > > 
> > > 
> > > That's a Telethon error, not Pyrogram. If you keep getting errors, consult with Telethon's Issues.
> > 
> > 
> > Ok thanks.. i have fixed this :) just upgraded my PyroGram
> 
> I used this command pip install -U pyrogram and it downloaded but still brings same errror message. How did you fix yours and are you able to login telegrams on python?. Please i need help urgently.

Okkk i will help dm me in telegram https://t.me/Alone_loverboy

**Comment by joaopedrolourencoaffonso** [comment]
> This issue has been fixed. You can upgrade with the usual command `pip install -U pyrogram`.

How? Telethon is still trying to fix it.

**Comment by BramGamingNL** [comment]
> This issue has been fixed. You can upgrade with the usual command `pip install -U pyrogram`.

nope does not work

**Comment by Autorua** [comment]
> 

Not work 
![image](https://user-images.githubusercontent.com/88741033/144485667-72527e25-8667-4d66-b223-367a916ea315.png)

**Comment by Autorua** [comment]
> > > Эта проблема исправлена. Вы можете обновиться с помощью обычной команды `pip install -U pyrogram`.
> > 
> > 
> > нет не работает
> 
> Работает ... обновить библиотеку пирограмм

Not work

**Comment by Autorua** [comment]
> > > Эта проблема исправлена. Вы можете обновиться с помощью обычной команды `pip install -U pyrogram`.
> > 
> > 
> > нет не работает
> 
> Работает ... обновить библиотеку пирограмм

Not work. Pyrogram 1.2.11 
![image](https://user-images.githubusercontent.com/88741033/144486091-916f8412-4d82-4658-a1af-db93179f482d.png)

**Comment by asarubbo** [comment]
> This issue has been fixed. You can upgrade with the usual command `pip install -U pyrogram`.

I don't see a new release, would you mind to make a new one? You will be loved by other packagers

**Comment by TamunRa** [comment]
Same error, after upgrade the library still not work. 
Has anyone solved the problem?

**Comment by asarubbo** [comment]
> Same error, after upgrade the library still not work. Has anyone solved the problem?

I can confirm that the error is solved with the master version.

**Comment by premnathdey** [comment]
I am still getting the error. I update pyrogram to v1.3.1 but still the same error.

**Comment by bwithai** [comment]
Hello @ all I fixed this using `pip install -U Telethon `
