### ISSUE TITLE
Auth Problem [406 UPDATE_APP_TO_LOGIN]

### ISSUE THREAD

**Issue by MdHazrat8361** [pyrogram/pyrogram#795]
406 UPDATE_APP_TO_LOGIN
when i try to create a new session , i face this except .

**Comment by RememberTheAir** [comment]
Duplicate of  #794

**Comment by theadbothostpro** [comment]
How to solve this error?

**Comment by joaopedrolourencoaffonso** [comment]
We at Telethon are having the [same](https://github.com/LonamiWebs/Telethon/issues/3215) problem.
