### ISSUE TITLE
CODE_SEND not work

### ISSUE THREAD

**Issue by mike335** [pyrogram/pyrogram#798]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

``` python
result = self.client.send_code(self.number)
...
```

## Traceback
When I call send_code I have this response and code not receive. I need change type to app.

```
Traceback (most recent call last):
{
    "_": "SentCode",
    "type": "sms",
    "phone_code_hash": "ee5280ea19a30fab4c",
    "next_type": "call",
    "timeout": 180
}
```

**Comment by ColinShark** [comment]
Telegram decides where the update is sent to, the client cannot force this to change.
If you need, you can use `resend_code()` after 2 minutes to ask Telegram to send a new code out. You'll receive another `SendCode` update telling you where/how it was sent.

**Comment by mike335** [comment]
To date, the telegram by default sent the code to the app. In the documentation it is written that by default the code comes to the app. even if the SMS does not come. And from another device everything works correctly.
