### ISSUE TITLE
Can't work app.add_chat_members(group_id, member)

### ISSUE THREAD

**Issue by MdHazrat8361** [pyrogram/pyrogram#800]
i am try ti add chat member in group . but Can't work app.add_chat_members(group_id, member) and there is no error face .

**Comment by ColinShark** [comment]
The Issues tab is for Feature Suggestions and Bug Reports. This is not a Q&A Forum.

If you have general questions or have need help with specific methods, please join the [Telegram Community](https://t.me/pyrogramchat) or use the `pyrogram` tag on [StackOverflow](https://stackoverflow.com/questions/tagged/pyrogram).
