### ISSUE TITLE
Can't work app.add_chat_members

### ISSUE THREAD

**Issue by MdHazrat8361** [pyrogram/pyrogram#801]
Can't work app.add_chat_members

**Comment by RememberTheAir** [comment]
lol

**Comment by ColinShark** [comment]
To quote myself...
> The Issues tab is for Feature Suggestions and Bug Reports. This is not a Q&A Forum.
> 
> If you have general questions or have need help with specific methods, please join the [Telegram Community](https://t.me/pyrogramchat) or use the `pyrogram` tag on [StackOverflow](https://stackoverflow.com/questions/tagged/pyrogram).
