### ISSUE TITLE
getSponsoredMessages 

### ISSUE THREAD

**Issue by fagci** [pyrogram/pyrogram#803]
## Checklist
- [x] I believe the idea is awesome and would benefit the library.
- [x] I have searched in the issue tracker for similar requests, including closed ones.

## Description

Each time the user opens a channel, channels.getSponsoredMessages should be called to receive sponsored messages available for this channel. The result should be cached for 5 minutes.

[getSponsoredMessages](https://core.telegram.org/api/sponsored-messages)

**Comment by A9FM** [comment]
а нахуя? только засорять библиотеку...

**Comment by fagci** [comment]
@A9FM поддержки этого требует сам Телеграм, или я не прав?
На стороне настройки приложения версия API не указывается.

**Comment by fagci** [comment]
До 1 января 2022 мы просим Вас убедиться, что Ваше приложение поддерживает и корректно отображает рекламные сообщения. К сожалению, Telegram не сможет взять на себя расходы по поддержке приложений, в которых не отображаются рекламные сообщения, и будет вынужден отключить таким приложениям доступ к API.

Please update your app to the latest version. The version you are using is out of date and will stop working soon.


Или это про что-то другое? В полном сообщении приводится ссылка на этот метод апи.
