### ISSUE TITLE
Some update should be enchance in Pyrogram

### ISSUE THREAD

**Issue by sam01101** [pyrogram/pyrogram#808]
## Checklist
- [x] I believe the idea is awesome and would benefit the library.
- [x] I have searched in the issue tracker for similar requests, including closed ones.

## Description
- [x] Telegram has released a new version of bot api https://core.telegram.org/bots/api#december-7-2021
\
This update should be added in

- [ ] Thus, `view_message` field is missing in [chatBannedRights](https://core.telegram.org/constructor/chatBannedRights), Pyrogram's API should add this field.

- [x] And there are some undocumented APIs that is listed in [here](https://core.telegram.org/contest/android-2021-11-api), I think it would be nice if Pyrogram would add those API in.

For example I had already tested out some of them by forking another project [telethon](https://github.com/sam01101/Telethon).

- [x] Another, the new `Send as channel peer` seems to be broken in Pyrogram's `Message` object, it would be ignored and cause bot can't identify the channel peer's data.
This made me had to use raw functions and types in my project (Example file: [message_handler.py](https://github.com/sam01101/TelegramChannelBlockerBot/blob/master/plugins/handlers/message_handler.py))

Thank you for watching my feature request.

**Comment by BraveSail** [comment]
Also need `is_automatic_forward` filed in class Message, it seems that `filters.linked_channel` can not distinguish between linked channel and users with channel identity.

**Comment by sam01101** [comment]
> Also need `is_automatic_forward` filed in class Message, it seems that `filters.linked_channel` can not distinguish between linked channel and users with channel identity.

Unfortunately, `is_automatic_forward` is a bot exclusive parameter that only visible in `Bot HTTP API`.
The `td_api.tl` doesn't provide this parameter in anywhere, yet.

However, this can be simulated by this condition: `message.fwd_from and message.fwd_from.saved_from_peer == message.fwd_from.from_id == message.from_id`
This condition was originally from [message_handler.py](https://github.com/sam01101/TelegramChannelBlockerBot/blob/d011580dcbf99be2c2228ce219dac76e3d8fc2f0/plugins/handlers/message_handler.py#L32)

**Comment by BraveSail** [comment]
@sam01101 Thanks. It works.

**Comment by sam01101** [comment]
> @sam01101 Thanks. It works.
> 
> Edit: I use this to do that:
> 
> ```
> @bot.on_raw_update()
> async def bot_handle_new_message(client: Client, update: base.Update, _, chats: dict):
>     if isinstance(update, types.UpdateNewChannelMessage):
>         message = update.message
>         if (isinstance(message.from_id, types.PeerChannel) and message.peer_id.channel_id == {CHANNEL_ID} and
>         not message.out and message.peer_id != message.from_id and message.fwd_from and
>         message.fwd_from.saved_from_peer == message.fwd_from.from_id == message.from_id and 
>         message.fwd_from.saved_from_peer.channel_id == {GROUP_ID}):
>             print(f'catched: {message}')
> 			···
> ```
> 
> Now it's fine even if user forward message from linked channel by using linked channel's identity to group. But it would be good to use `filters.linked_channel` if it's not broken.

The filter `filters.linked_channel` is broken is because the `Chat` object is not always a full (complete) object (`ChatFull`)

If you need an example of creating your own `linked_channel` filter, here is some references:

```py3
linked_chat_id = await database.get_linked_group(
    channel_peer=chat_peer
)
```

The function [get_linked_group](https://github.com/sam01101/TelegramChannelBlockerBot/blob/d011580dcbf99be2c2228ce219dac76e3d8fc2f0/plugins/functions/database.py#L16-L89) is located in [database.py](https://github.com/sam01101/TelegramChannelBlockerBot/blob/d011580dcbf99be2c2228ce219dac76e3d8fc2f0/plugins/functions/database.py)
Please note that I used [`asyncio.Lock`](https://docs.python.org/3.8/library/asyncio-sync.html#asyncio.Lock) to do write operation

I'm using sqlite3 to cache my `linked_channel` `chat_id`, you can find the sql table in [create_link_channel_table.sql](https://github.com/sam01101/TelegramChannelBlockerBot/blob/d011580dcbf99be2c2228ce219dac76e3d8fc2f0/plugins/sqls/create_link_channel_table.sql)

The database initialize logic is located in [main.py](https://github.com/sam01101/TelegramChannelBlockerBot/blob/d011580dcbf99be2c2228ce219dac76e3d8fc2f0/main.py#L15-L23) and the variable is in [glovar.py](https://github.com/sam01101/TelegramChannelBlockerBot/blob/d011580dcbf99be2c2228ce219dac76e3d8fc2f0/plugins/glovar.py#L11)

**Comment by sam01101** [comment]
Fixed
