### ISSUE TITLE
how to use the program to press an InlineKeyboardButton

### ISSUE THREAD

**Issue by wz343450860** [pyrogram/pyrogram#81]
Hi , I received some InlineKeyboardButtons from somebody, how can I press someone with the pyrogram?

**Comment by delivrance** [comment]
Hi, the current way is to invoke [messages.GetBotCallbackAnswer](https://docs.pyrogram.ml/functions/messages/GetBotCallbackAnswer). Here's an example:

``` python
r = client.send(
    functions.messages.GetBotCallbackAnswer(
        peer=client.resolve_peer("bot_username"),
        msg_id=1234567,
        data=b"inline_button_data"
    )
)

print(r)
```

You need the bot username (or id) to be used with `resolve_peer`, the message id the keyboard is attached on and the data, which is stored inside the keyboard button you receive and you want to press (note the `b""` which means you have to pass a `bytes` array).

**Comment by drxvmrz** [comment]
Hello! I know that several years have passed, but if it relevant yet:

For example there's a clicking on "PFD"-button in a message recieved from any TG-bot.

How it looks like in TG-chat:
![image](https://github.com/pyrogram/pyrogram/assets/138060212/f874c098-5df8-4eba-9d32-4ee700c79605)

Imagine you want to click on "PDF" button with all recieved messages:
```python
async def main():
    async with Client("Client", api_id, api_hash) as app:
        chat_history = app.get_chat_history(tg_bot_username_or_chatid)
      
        async for message in chat_history:
            if message.outgoing is False and message.reply_markup is not None:
            print(f"{message.id} first key: {message.reply_markup.inline_keyboard[0][0]}")
            await message.click(0,0)

asyncio.run(main())
```

If recieved message have inlinekeyboard it has not ```Null``` atribute ```reply_markup```.
In this turn it has an attribute ```inline_keyboard``` contains a list of buttons. The countdown starts from the top and to the right. PDF-button has the coordinates (0, 0).
