### ISSUE TITLE
Hide 2 step verification password like sudo does

### ISSUE THREAD

**Issue by D4v1dH03** [pyrogram/pyrogram#813]
## Checklist
- [x] I believe the idea is awesome and would benefit the library.
- [x] I have searched in the issue tracker for similar requests, including closed ones.

## Description
A detailed description of the request.

Currently the two step verification password input prompt echos the password in CLEAR TEXT

it is not very secure

Better hide it with '*' or doesn't echo it at all

**Comment by delivrance** [comment]
https://docs.pyrogram.org/api/client?highlight=hide_password
