### ISSUE TITLE
[Question] Multiple different sessions in one app?

### ISSUE THREAD

**Issue by HIMix** [pyrogram/pyrogram#82]
**Question:** Is there a way to handle multiple different sessions in one app?
**Explanation:** I'm working on a web client based on django. And I want my users to be able to log in to multiple Telegram accounts at the same time and use one control panel to operate 'em (e.g. send a message from multiple accounts at the same time).
First idea was to run separate instances of _"pyrogram based script"_ for separate Telegram accounts and create some kind of inner API so those scripts could interact with main django process and UI. But not sure I want it to work this way. So... here's my question appeared.
Will appreciate any answer.

Thanks.

**Small update:** What I'm thinking right now is threading but maybe you have some better ideas.

**Comment by HIMix** [comment]
What I'm thinking right now is threading but maybe you have some better ideas?

**Comment by delivrance** [comment]
@HIMix Pyrogram, being a library, exposes the `Client` class whose instance handle a **single** user/bot account; if you want to handle **multiple** accounts at once, simply create other Clients and use their `.start()` and `.stop()` methods to control their lifecycles.

Currently, there's no "easy" way to handle all these multiple clients automatically, is up to the application (you) to build something on top of them. I.e.: nothing stops you from having a "global" `clients` dictionary or list in your app and use something line `clients[some_app_user_id].send_message(...)`.

About `how` to implement this to handle async requests, my advice is to dive into Python's `asyncio`. which can save you lots of threads (everything runs in a single thread), but is more complex to use. Threading and/or multiprocessing is the other way. Multiprocessing is useful if you want to fully leverage your CPU cores.

**Comment by HIMix** [comment]
Thank you for a good answer.
I already implemented my code using _threading_. Everything works pretty well.
But I'll check _asyncio_ maybe it could be useful for my case. Anyway new knowledge/experience is always good 👍 

Thanks one more time.

**Comment by khorammfar** [comment]
> 
> 
> @HIMix Pyrogram, being a library, exposes the `Client` class whose instance handle a **single** user/bot account; if you want to handle **multiple** accounts at once, simply create other Clients and use their `.start()` and `.stop()` methods to control their lifecycles.
> 
> Currently, there's no "easy" way to handle all these multiple clients automatically, is up to the application (you) to build something on top of them. I.e.: nothing stops you from having a "global" `clients` dictionary or list in your app and use something line `clients[some_app_user_id].send_message(...)`.
> 
> About `how` to implement this to handle async requests, my advice is to dive into Python's `asyncio`. which can save you lots of threads (everything runs in a single thread), but is more complex to use. Threading and/or multiprocessing is the other way. Multiprocessing is useful if you want to fully leverage your CPU cores.

### I use this method
There is no problem when my robot uses the first account
But when you start with the second account, you run into problems
And it fails

**i have this error :**
`pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid`

### But peerid is not a problem

**Comment by ColinTheShark** [comment]
@khorammfar If you run into problems, please make a new issue instead of hijacking other ones (And use the Issue Template, while you're at it).

**Comment by AKHACKER-program4hack** [comment]
> Thank you for a good answer. I already implemented my code using _threading_. Everything works pretty well. But I'll check _asyncio_ maybe it could be useful for my case. Anyway new knowledge/experience is always good +1
> 
> Thanks one more time.

can you please share the code with me because i not able to run userbot using threads
