### ISSUE TITLE
Add documentation about `CHAT_FORWARDS_RESTRICTED`

### ISSUE THREAD

**Issue by D4v1dH03** [pyrogram/pyrogram#820]
## Checklist
- [X] I believe the idea is awesome and would benefit the library.
- [X] I have searched in the issue tracker for similar requests, including closed ones.

## Description
A detailed description of the request.

Telegram has added a new feature about restrict saving content in groups. We should document it in 400 Bad request section of 'API Errors'

**Comment by delivrance** [comment]
You can open a PR to add newly found RPC errors
