### ISSUE TITLE
RuntimeError: Task cannot await on itself

### ISSUE THREAD

**Issue by scrazzz** [pyrogram/pyrogram#824]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [ ] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I'm getting an error when I try to terminate the bot.

Minimal code:
```py
@bot.on_message(filters.command('restart') & filters.private)
async def restart(bot, ctx):
    await ctx.reply('restarting...')
    await bot.terminate()
    await asyncio.sleep(4)
    await bot.initialize()
    await ctx.reply('Done!')
```

## Traceback
The full traceback (if applicable).

```
Task cannot await on itself: <Task pending name='Task-29' coro=<Dispatcher.handler_worker() running at /usr/lib/python3.10/site-packages/pyrogram/dispatcher.py:217>>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/gh/bot/bot.py", line 48, in restart
    await bot.terminate()
  File "/usr/lib/python3.10/site-packages/pyrogram/methods/auth/terminate.py", line 46, in terminate
    await self.dispatcher.stop()
  File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 139, in stop
    await i
RuntimeError: Task cannot await on itself: <Task pending name='Task-29' coro=<Dispatcher.handler_worker() running at /usr/lib/python3.10/site-packages/pyrogram/dispatcher.py:217>>
```

**Comment by delivrance** [comment]
Weird usage (xyproblem?) also see https://docs.pyrogram.org/faq#code-hangs-when-i-stop-restart-add-remove-handler and don't use .terminate/.initialize unless you know what you are doing, use .start/.stop instead. Also, always try with the up to date branch first since issues could have been fixed there already.
