### ISSUE TITLE
Multiple downloads at the same time?

### ISSUE THREAD

**Issue by lluiscab** [pyrogram/pyrogram#83]
Even tho I've set `Block` to `False` on `download_media`, my script is only downloading one file at a time. Is there any way to fix this?

My code
```client.download_media(message, fileName, False, callback, (prevTime, prevSize, (message.document.file_name)))```

**Comment by delivrance** [comment]
@lluiscab Hi, the reason is that by default only **one** download worker is running. There's no nice way to change this currently; you have to manually set the desired amount like this, for example: 

``` python
app = Client(...)
app.DOWNLOAD_WORKERS = 4

app.start()
```

**Comment by lluiscab** [comment]
Thanks! That worked perfectly, any way to list the pending / ongoing downloads?

**Comment by delivrance** [comment]
Hmm, I think you can hack something with the progress callback. While `current` is not equal to `total` the download is still in progress. You keep track of each of them in a list/dict or something and pop out as soon as `current` equals `total`, which means all bytes have been downloaded. If you have any idea how can this be embedded nicely to the lib let me know!

**Comment by qfewzz** [comment]
I've done what you said, but still downloading one file at a time.
I'm downloading profiles photos actually.

python`
photos = await generator_to_list2(client.get_chat_photos(chat_member.user.id))
photos: list[pyrogram.types.Photo]
tasks = []
for index, photo in enumerate(photos):
    tasks.append(asyncio.create_task(
        client.download_media(
            message=photo.file_id,
            file_name=f'{path}/files/photos/{index}.jpg'
        )
    ))
print('done! now waiting...')
for task in tasks:
    await task
print('fully done!')`

**Comment by qfewzz** [comment]
I found the answer.
In the new version of Pyrogram, we we should also  set `max_concurrent_transmissions ` when creating client.
