### ISSUE TITLE
unpack requires a buffer of 263 bytes 

### ISSUE THREAD

**Issue by anylayer** [pyrogram/pyrogram#831]
File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyrogram/methods/utilities/start.py", line 53, in start
    is_authorized = await self.connect()
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect
    await self.load_session()
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyrogram/client.py", line 669, in load_session
    await self.storage.open()
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyrogram/storage/memory_storage.py", line 41, in open
    self.name + "=" * (-len(self.name) % 4)
struct.error: unpack requires a buffer of 263 bytes

**Comment by AKHACKER-program4hack** [comment]
> File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyrogram/methods/utilities/start.py", line 53, in start is_authorized = await self.connect() File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect await self.load_session() File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyrogram/client.py", line 669, in load_session await self.storage.open() File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyrogram/storage/memory_storage.py", line 41, in open self.name + "=" * (-len(self.name) % 4) struct.error: unpack requires a buffer of 263 bytes

I am also getting the same error

**Comment by Soebb** [comment]
Pass the special session name ":memory:" to the session_name parameter of pyrogram.Client()

https://github.com/pyrogram/pyrogram/blob/4f585c156c1a2c6707793a8ad7f2f111515ca23b/docs/source/topics/storage-engines.rst#memory-storage

**Comment by AKHACKER-program4hack** [comment]
No the error is fixed by updating the pyrogram from GitHub
