### ISSUE TITLE
progress - division by zero

### ISSUE THREAD

**Issue by smm993** [pyrogram/pyrogram#835]
## Checklist
- [ x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [ x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [ x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
A **clear** and **concise** description of the problem. Code snippets must be
[minimal, reproducible](https://stackoverflow.com/help/minimal-reproducible-example) and properly formatted.

``` python
from pyrogram import Client
import time

app = Client(
    "iBot",
    bot_token="bot_token"
)

app.start()

def progress(current, total):
    print(f"{current * 100 / total:.1f}%")

app.download_media('CQACAgQAAxkBAAIHEWHF58CWRlwM65huiz6SAjcADwJ3AA1LCQACOknoUgaBohGR59kwzh4E', progress=progress)

app.stop
```

## Traceback
The full traceback (if applicable).

```
division by zero
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.6/site-packages/pyrogram/client.py", line 936, in get_file
    await self.loop.run_in_executor(self.executor, func)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "t.py", line 12, in progress
    print(f"{current * 100 / total:.1f}%")
ZeroDivisionError: division by zero
```

**Comment by delivrance** [comment]
There can't be a progress handler in case you download by file id because the file size is unknown in this case. You have to use `app.download_media(message)` if you want to keep the progress handler.
