### ISSUE TITLE
how can I get the phone_code Get your code programmatically

### ISSUE THREAD

**Issue by wz343450860** [pyrogram/pyrogram#84]
Hi , 
   If I want get the phone_code via a callback function,  I write a function as the callback, it will sleep some seconds to wait the phone code received, but when I pass the function as  a parameter to phone_code, when I start the client it not work well, could you give me a demo to let me know how the phone_code callback function work?

thanks

**Comment by VarunChilukuri** [comment]
Did you ever find a solution?
