### ISSUE TITLE
BadServerSalt error

### ISSUE THREAD

**Issue by MStudioBuildInc** [pyrogram/pyrogram#851]
## Checklist
- [+] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [+] I have searched in the issue tracker for similar bug reports, including closed ones.
- [+] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

I have 7 servers in Europe and 1 in Russia, all of them reproduce the same problem. The bottom line is that some time after launch, bots receive an error:

```
[LINE: 235] # ERROR [pyrogram.dispatcher] [2022-01-04 20: 59: 20,524] 'BadServerSalt' object has no attribute 'updates'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback (self.client, * args)
  File "/home/FollowBot/bot_manager.py", line 1441, in __start_command
    await message.reply_text (f'T ({v}) 'if') 'not in v else v, reply_markup = markup)
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/types/messages_and_media/message.py", line 909, in reply_text
    return await self._client.send_message (
  File "/home/FollowBot/bot_manager.py", line 11327, in wrapper
    m = await func (* args, ** kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/messages/send_message.py", line 166, in send_message
    for i in r.updates:
AttributeError: 'BadServerSalt' object has no attribute 'updates'
```

This is one example. In fact, the error occurs arbitrarily when calling any method. After that, the connection with the telegram is closed (as I understand it, connection.close is called somewhere inside the library). Next comes the error
```
[LINE: 911] # WARNING [asyncio] [2022-01-04 23: 23: 49,972] socket.send () raised exception.
(Attempting to write to a closed socket)
```

After that, the bot either stops working altogether, or reconnects, receives unprocessed updates, processes them again and reconnects again. Because of which the same update is processed endlessly (The record at the moment is 1000 times)

I would be glad if someone could help me solve this problem

**Comment by MStudioBuildInc** [comment]
In general, I experimented and came to this solution: You need to change the connection mode from 3 to 0 here
https://github.com/pyrogram/pyrogram/blob/00c91120d82b5ae3b23961e60b5edb5f2eaadde4/pyrogram/connection/connection.py#L40

**Comment by MStudioBuildInc** [comment]
> ## Checklist
> * [+] I am sure the error is coming from Pyrogram's code and not elsewhere.
> * [+] I have searched in the issue tracker for similar bug reports, including closed ones.
> * [+] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.
> 
> I have 7 servers in Europe and 1 in Russia, all of them reproduce the same problem. The bottom line is that some time after launch, bots receive an error:
> 
> ```
> [LINE: 235] # ERROR [pyrogram.dispatcher] [2022-01-04 20: 59: 20,524] 'BadServerSalt' object has no attribute 'updates'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/pyrogram/dispatcher.py", line 222, in handler_worker
>     await handler.callback (self.client, * args)
>   File "/home/FollowBot/bot_manager.py", line 1441, in __start_command
>     await message.reply_text (f'T ({v}) 'if') 'not in v else v, reply_markup = markup)
>   File "/usr/local/lib/python3.9/dist-packages/pyrogram/types/messages_and_media/message.py", line 909, in reply_text
>     return await self._client.send_message (
>   File "/home/FollowBot/bot_manager.py", line 11327, in wrapper
>     m = await func (* args, ** kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/messages/send_message.py", line 166, in send_message
>     for i in r.updates:
> AttributeError: 'BadServerSalt' object has no attribute 'updates'
> ```
> 
> This is one example. In fact, the error occurs arbitrarily when calling any method. After that, the connection with the telegram is closed (as I understand it, connection.close is called somewhere inside the library). Next comes the error
> 
> ```
> [LINE: 911] # WARNING [asyncio] [2022-01-04 23: 23: 49,972] socket.send () raised exception.
> (Attempting to write to a closed socket)
> ```
> 
> After that, the bot either stops working altogether, or reconnects, receives unprocessed updates, processes them again and reconnects again. Because of which the same update is processed endlessly (The record at the moment is 1000 times)
> 
> I would be glad if someone could help me solve this problem

**Comment by MStudioBuildInc** [comment]
> ## Checklist
> * [+] I am sure the error is coming from Pyrogram's code and not elsewhere.
> * [+] I have searched in the issue tracker for similar bug reports, including closed ones.
> * [+] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.
> 
> I have 7 servers in Europe and 1 in Russia, all of them reproduce the same problem. The bottom line is that some time after launch, bots receive an error:
> 
> ```
> [LINE: 235] # ERROR [pyrogram.dispatcher] [2022-01-04 20: 59: 20,524] 'BadServerSalt' object has no attribute 'updates'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/pyrogram/dispatcher.py", line 222, in handler_worker
>     await handler.callback (self.client, * args)
>   File "/home/FollowBot/bot_manager.py", line 1441, in __start_command
>     await message.reply_text (f'T ({v}) 'if') 'not in v else v, reply_markup = markup)
>   File "/usr/local/lib/python3.9/dist-packages/pyrogram/types/messages_and_media/message.py", line 909, in reply_text
>     return await self._client.send_message (
>   File "/home/FollowBot/bot_manager.py", line 11327, in wrapper
>     m = await func (* args, ** kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/messages/send_message.py", line 166, in send_message
>     for i in r.updates:
> AttributeError: 'BadServerSalt' object has no attribute 'updates'
> ```
> 
> This is one example. In fact, the error occurs arbitrarily when calling any method. After that, the connection with the telegram is closed (as I understand it, connection.close is called somewhere inside the library). Next comes the error
> 
> ```
> [LINE: 911] # WARNING [asyncio] [2022-01-04 23: 23: 49,972] socket.send () raised exception.
> (Attempting to write to a closed socket)
> ```
> 
> After that, the bot either stops working altogether, or reconnects, receives unprocessed updates, processes them again and reconnects again. Because of which the same update is processed endlessly (The record at the moment is 1000 times)
> 
> I would be glad if someone could help me solve this problem

**Comment by slaid908** [comment]
I have the same problem when sending messages to the chat. The same code in pyrogram 1.2.20 does not cause this problem.

**Comment by slaid908** [comment]
> In general, I experimented and came to this solution: You need to change the connection mode from 3 to 0 here
> 
> https://github.com/pyrogram/pyrogram/blob/00c91120d82b5ae3b23961e60b5edb5f2eaadde4/pyrogram/connection/connection.py#L40

This fix didn't help me get rid of the error

**Comment by Devanagaraj** [comment]
I too facing the same issue...

**Comment by delivrance** [comment]
Hi. This issue has been addressed; you can update with `pip install -U pyrogram`.
