### ISSUE TITLE
Access to messages on protected channels

### ISSUE THREAD

**Issue by nkuznetsow** [pyrogram/pyrogram#855]
## Checklist
- [ +] I believe the idea is awesome and would benefit the library.
- [ +] I have searched in the issue tracker for similar requests, including closed ones.

## Description
In December 2021 Telegram introduces content protection on channels. Admins could block ability to forward content. 
In start of January, Pyrogram stoped to get text of messages in channels like that. 

Now instead of the message there is a list of restrictions inside the message which contains message: 

`The admins of this channel have restricted saving content. Please update your app to open this chat.`

I think some changes in Pyrogram are required to access protected channels messages.

**Comment by Slhdono** [comment]
Any updates? I need this one too

**Comment by delivrance** [comment]
Pyrogram has been updated
