### ISSUE TITLE
`chat_id` and `channel_id` are different then telegram

### ISSUE THREAD

**Issue by kai3341** [pyrogram/pyrogram#858]
## Checklist
- [x] I believe the idea is awesome and would benefit the framework.
- [x] I have searched in the issue tracker for similar requests, including closed ones.

## Description
Telegram IDs are distorted. This is root of integration problem.
I have to change this behavior via refactoring Client and Storage. But after data model changing backward compatibility will be broken. Yes, we can migrate all SQLiteStorage data, but when Pyrogram users store data anywhere else there are will be some problems

So, the question is would you create branch 1.3.x and accept PR? Is it OK? Should I start this work?
Also I want to break backward compatibility of `proxy` behavior to solve #90

**Comment by delivrance** [comment]
Ids are not "distorted", you probably mixed Pyrogram's conventional ids with raw ids. More info here https://docs.pyrogram.org/topics/advanced-usage#chat-ids.

**Comment by kai3341** [comment]
@delivrance OK, I'm sorry. I told with many people and got this behavior is OK.
I thought it's not ok because my previous projects were about electrical meters and financial, where data mutation is not allowed
