### ISSUE TITLE
Allow defining custom device_model, system_version and app_version

### ISSUE THREAD

**Issue by Liiion911** [pyrogram/pyrogram#86]
Hi!

How i can change VERSION. APP_VERSION, DEVICE_MODEL and SYSTEM_VERSION ?

**Comment by delivrance** [comment]
Hi, you must manually edit these lines: 
https://github.com/pyrogram/pyrogram/blob/develop/pyrogram/session/session.py#L50-L61

**Comment by delivrance** [comment]
Hm, I should allow defining custom strings more easily. Maybe via some extra arguments to pass when creating a new Client.

**Comment by Liiion911** [comment]
Yes, custom properties - good idea.
Thx for answer!

**Comment by mnb3000** [comment]
Just 3 extra optional args for Client constructor would solve the problem

**Comment by delivrance** [comment]
Here it is. All `app_version`, `device_model`, `system_version`, `system_lang_code`, `lang_code` parameters can be set by using the *config.ini* file (inside the `[pyrogram]` section) as well as on the Client itself, when creating a new one (if using the latter, any value in the *config.ini* file will be ignored).

**Comment by Liiion911** [comment]
thx for implementation in 0.7.5!
Best Telegram MTProto lib ♥️
