### ISSUE TITLE
Current get_dialogs() implementation can't be used by library users as it's intended for internal usages only

### ISSUE THREAD

**Issue by gabiruh** [pyrogram/pyrogram#87]
`get_dialogs()` does an useless loop. And besides fetching the first dialogs twice, it returns `None`.

https://github.com/pyrogram/pyrogram/blob/develop/pyrogram/client/client.py#L932

**Comment by delivrance** [comment]
@gabiruh It's normal behaviour.

`get_dialogs()`, which is undocumented, is intended for internal usage only and not for library's users (yet).
If you want to get your dialogs you need to manually invoke `messages.GetDialogs` for now. An example is shown here: https://github.com/pyrogram/pyrogram/blob/develop/pyrogram/client/client.py#L919-L924

I'm labeling this as enhancement until a proper and documented get_dialogs method is added!

**Comment by delivrance** [comment]
Closing. [Client.get_dialogs](https://docs.pyrogram.ml/pyrogram/Client#pyrogram.Client.get_dialogs) has been added.
