### ISSUE TITLE
Bot not working in new accounts.Only work in old accounts. "-": "types.UpdatesTooLong"

### ISSUE THREAD

**Issue by fatihesergg** [pyrogram/pyrogram#873]
## Checklist
- [ ] I Lastest Pyrogram version.
- [ ] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description

Old account has no problem.But in new accounts, bot terminated in about 10 second.After terminated in console have no log just says types.UpdateTooLong.

``` Here is the repo 
https://github.com/TeamDerUntergang/Telegram-SedenUserBot
...
```

## Traceback
https://ibb.co/r0VYHt0

```
```

**Comment by delivrance** [comment]
The server ended the session for some reason. This looks like an issue with your bot/account rather than library's.
