### ISSUE TITLE
protect_content problem

### ISSUE THREAD

**Issue by RSR-TG-Info** [pyrogram/pyrogram#880]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
A **clear** and **concise** description of the problem. Code snippets must be
[minimal, reproducible](https://stackoverflow.com/help/minimal-reproducible-example) and properly formatted.

``` python
from pyrogram import Client

await client.send_document(
                    chat_id=query.from_user.id,
                    document=file_id,
                    caption=cappy,
                    protect_content=True,
                    reply_markup=InlineKeyboardMarkup(button1)
                    )
...
```

My Bot can protect for forwarding, but can't protect for saving, Document say "protect_content=True " can protect for forwarding and saving.

**Comment by delivrance** [comment]
The description applies to the user end using official clients.
