### ISSUE TITLE
Passing user-defined arguments to message handlers 

### ISSUE THREAD

**Issue by djnotes** [pyrogram/pyrogram#882]
## Checklist
- [X] I believe the idea is awesome and would benefit the framework.
- [ ] I have searched in the issue tracker for similar requests, including closed ones.

## Description
Earlier today, I was trying to make my message handler code more testable by passing some dependencies to it in addition to Client and Message. Normally the callable that is used in MessageHandler is like this: 
```
def handle_bot(client: Client, message: Message):
  # do stuff  with client and message
```
However, I needed to inject a db connection as well as a second client object. Something like this: 
```
def new_handle_bot(client:Client, message: Message, user_client: Client, db: Connection):
   # Trying to do stuff with all four params, but user_client and db are None
```
The problem is I can't find a way to pass extra parameters beyond `client` and `message` to the handler callable. 
I tried subclassing MessageHandler like this: 
```
class MyMessageHandler(MessageHandler):
    def __init__(self, callback: callable, filters=None, user_client: Client = None, db: Connection = None):
        super().__init__(callback, filters)
        self.user_client = user_client
        self.db = db
```
and I set my handler with an instance of it: 

```

bot_client.add_handler(
    MyMessageHandler(handle_bot, 
        filters.command(["add", "help", "start", "getusers"]),
        user_client= user_client, 
        db = db
    )
)

```
but, inside the handle_bot function, both the extra parameters have a value of None. 
I'm not a Python vet, so not sure if that is technically possible. So, in short, can Pyrogram add support for handler callables taking arbitrary params?

**Comment by delivrance** [comment]
The current way of dealing with this is to create a new class that inherits from Pyrogram's Client, store your data in there and use instances of the new class so that your data becomes available in handlers through the client instance argument.

**Comment by dxm1337** [comment]
I don’t know how this problem is still relevant and how pythonic it is, but I implemented `pool` forwarding for the database like this:
```python
from functools import partial
.....
async def handle_message(client: Client, message: types.Message, db_pool)
.....
partial_handle_message = partial(handle_message, db_pool=pool)
message_handler = MessageHandler(partial_handle_message, filters.chat(chat_id))
app.add_handler(message_handler)
.....
```

Maybe this will save someone time (I hope so) 😸
