### ISSUE TITLE
Issues with repeatedly being force-disconnected and reconnecting.

### ISSUE THREAD

**Issue by righteon** [pyrogram/pyrogram#883]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
There seems to be a bug that was either introduced in the latest versions - and/or something related to a new telegram update.
because the error appeared - without modifying any code (only updating to latest master) - about one week ago. 
I suspect it could have something to do with salts, vectors, etc but Im not the expert. 

What happens?
The client gets force-disconnected and then tries to reconnect - MANY, many times. This happens more or less randomly so it is not clear how to reproduce it. But I have seen other people having the same issue.

The following shows the console output. One is from myself and the other is from another user that reported the same problem:
![bug2](https://user-images.githubusercontent.com/17290590/151372296-4f557245-6fe6-4e4c-a301-40767cc3a17c.jpg)
![bug1](https://user-images.githubusercontent.com/17290590/151372348-13ea3dde-1ccf-4bb4-958e-626eb4ab0dd2.jpg)

This wouldnt be so bad because often the client finally reconnects - but what happens for me is that the on_message handler gets called  - sometimes up to 50 times with the same message when this issue occurs.

**Comment by delivrance** [comment]
Reconnections are normal, they can happen at anytime and are handled internally. What you described are two different scenarios: one is downloading files and new connections are to be expected, the other is showing consistent reconnections of one reconnection every 60 minutes. The actual issue you are having looks unrelated and could be because of this: https://docs.pyrogram.org/faq/why-is-the-event-handler-triggered-twice-or-more.

**Comment by righteon** [comment]
Happened again today...absolutely flooded my application with over 1000 same messages (with no attachement or edit) over and over. 

Just a few points here that would make me - as a programmer - think that this COULD be an issue and not something to be "expected":

1) The described issue appeared abruptly, after one YEAR of running multiple pyrogram bots without this issue.
2) The described issue appeared last week and since then has occured multiple times. (Upgraded to the latest master last week)
3) The described issue has not occured on a bot running an older version of the library. That one has been running for months without issue while the upgraded ones show this problem.
5) The described issue is NOT related to edited messages because:
     A) I am handling message edits in my application specifically. Those repeated messages are NOT edited.
     B) No one edits messages **1179 times** over the course of a few minutes...
6) when the bot gets stuck in those re-connection loops, not even Ctrl+C is able to close them



![image](https://user-images.githubusercontent.com/17290590/151720146-619ec06c-5797-443c-afa7-fccc1b30a82b.png)
![image](https://user-images.githubusercontent.com/17290590/151720280-47490970-d6f4-4678-b253-22fe4efa55f7.png)

**Comment by delivrance** [comment]
Either something changed server side that needs to be handled differently after a schema update or a specific commit about something else introduced the alleged bug and you could pinpoint which one.

**Comment by righteon** [comment]
I will downgrade to 1.3.1 and let it run for a week to check. And gradually downgrade to hopefully pin down when the issue began. It occurs irregularly and I cant see a pattern to it yet. I will update if I get any new information.

**Comment by delivrance** [comment]
I eventually identified what was causing messages to be replayed, the fix is now available in the latest version. However, I believe that the many reconnections you experience remain a separate issue and likely depend on your machine/network.

**Comment by righteon** [comment]
I cant fully rule out connection problems on the network (although would be a bit odd) - but even if it happens, the application will not be flooded now - thanks for the quick fix!
