### ISSUE TITLE
Executing functions twice

### ISSUE THREAD

**Issue by user88372** [pyrogram/pyrogram#887]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Once the functions gets called by the command sent to the bot, there is a chance that it will repeat without interaction after some random amount of time (between 2 minutes and 1 hour).
I already mitigated edited messages from all the functions.
Using python 3.8.2 and latest master.

``` python
@Client.on_message(filters.private & ~filters.edited & filters.command(["start"], prefixes=["/"]))
async def mystartcommand(client, msg):
	chatid = msg.from_user.id
	await client.send_message(chatid, "pong")
	return
```

## Traceback
The full traceback (if applicable).

No traceback

**Comment by delivrance** [comment]
Fixed in the latest version.
