### ISSUE TITLE
Service message empty

### ISSUE THREAD

**Issue by mike335** [pyrogram/pyrogram#889]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Some times service field in message object is missing. Changes may be made to the api pyrogram, but no changes have been reported. In log message obj is nothing about the service message but there is in the doc Pyrogram. 

### Steps to reproduce

1.run iter_history
2. get message object 
3. service field is missing

### Logs

{
    "_": "Message",
    "message_id": 128001,
    "from_user": {
        "_": "User",
        "id": 342907413,
        "is_self": false,
        "is_contact": true,
        "is_mutual_contact": true,
        "is_deleted": false,
        "is_bot": false,
        "is_verified": false,
        "is_restricted": false,
        "is_scam": false,
        "is_fake": false,
        "is_support": false,
        "first_name": "Name",
        "last_name": "Second",
        "status": "recently",
        "username": "name_c",
        "phone_number": "*********"
    },
    "date": "2021-12-24 14:28:54",
    "chat": {
        "_": "Chat",
        "id": 342907413,
        "type": "private",
        "is_verified": false,
        "is_restricted": false,
        "is_scam": false,
        "is_fake": false,
        "is_support": false,
        "username": "name_c",
        "first_name": "Name",
        "last_name": "Second"
    }
}

**Comment by delivrance** [comment]
You must provide precise steps on how to reproduce the specific issue (e.g. what service message exactly are you expecting and seeing in official clients and how to get one to reproduce the issue).
