### ISSUE TITLE
Migrate to different data center

### ISSUE THREAD

**Issue by prashanth742** [pyrogram/pyrogram#89]
Hi How can I connect to different data center. I am on dc1. I want to migrate to dc4. Can you provide a  pythonscript to that?

Thanks,

**Comment by delivrance** [comment]
@prashanth742 Not possible, the public API doesn't offer such functions. This is something Telegram does automatically when it sees you are connecting frequently from another country and decides it's better for your account to be relocated in a different DC for good.
