### ISSUE TITLE
Pyrogram Version 1.4.0 Can't Work Properly

### ISSUE THREAD

**Issue by MdHazrat8361** [pyrogram/pyrogram#891]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

In Pyrogram version 1.4.0, when I use the Add_Chat_Members method, it does not work and the ID is banned.

### Steps to reproduce

1. In Pyrogram version 1.4.0, when I use the Add_Chat_Members method, it does not work and the ID is banned.

**Comment by delivrance** [comment]
This is not a library's issue. Read the FAQ https://docs.pyrogram.org/faq.
