### ISSUE TITLE
[Bug] Pyrogram Chat Forward Restricted for media types 400 

### ISSUE THREAD

**Issue by RafayGhafoor** [pyrogram/pyrogram#893]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

On restricted chats, Media files can't be copied but text is working  through message.copy.

The message gets printed fine, we can see the caption of the image, the photo id but seems like they are being forwarded with header set to None, instead of being copied.

Error: Telegram says: [400 CHAT_FORWARDS_RESTRICTED] - The chat restricts forwarding content (caused by "messages.SendMedia")

### Steps to reproduce

Create two test channels with restrict saving content enabled and test the following code.

### Code example

```python
from pyrogram import Client
import re

app = Client("my_account", 'id', 'hash')

# source and destination pair of channels/groups
chat_mapping = {
    'publicTestChannel1':'publicTestChannel2',
}

@app.on_message()
def my_handler(client, message):
    if str(message.chat.username) not in chat_mapping: return
    print(message)

    if message.text: # Prints text of message
        print(message.text)

    # Copies message in the destination
    message.copy((chat_mapping.get(str(message.chat.username))))

app.run()
```
```


### Logs

_No response_

**Comment by delivrance** [comment]
> Error: **Telegram says**: [400 CHAT_FORWARDS_RESTRICTED]

This is not a library's issue. It's a server-side restriction.

**Comment by RafayGhafoor** [comment]
Content types of text seems to work fine. Downloading media files and attaching them without using file_id seems to work as a workaround. Can we have a utility function which allows us to bypass this restricted method by downloading the media attached; uploading it using the file path and deleting it after using.
