### ISSUE TITLE
Is Pyrogram serverless-ready

### ISSUE THREAD

**Issue by timbuckanowski** [pyrogram/pyrogram#908]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

Hi, I'm at the early stages of prototyping a service (a bot actually) with Pyrogram that heavily relies on callback data from `InlineKeyboardButton`. 

The deployment opportunity is AWS Lambda, given Pyrogram does support a synchronous execution model. Yet, I discovered a couple of things that ask for clarification for me, and possibly a lot of people in future.

1. If a webhook is set with a different framework beforehand, will Pyrogram based bot be capable of receiving those updates by any means possible?
1. Given, Pyrogram uses direct TCP connections to Telegram's DCs  how does the bot gets missed user interactions (like button presses) when server push isn't available (meaning how the update model works for Pyrogram based bots)? To be more specific will the `CallbackQueryHandler` be invoked once the the killed process gets restarted.

**Comment by timbuckanowski** [comment]
@delivrance hope you'll clear this out. Coz right now I feel Pyrogram is too low-levelish for serverless deployments of that sort.

**Comment by delivrance** [comment]
Pyrogram's and any MTProto client's (like the one running behind the bot api) means of receiving updates is by server pushes on a persistent connection or by explicitly asking for previously missed events via some dedicated methods.
Combining it with bot api wehbooks should work fine, so you could use Pyrogram in a serverless context by having something else trigger any Pyrogram function you would like to invoke, but this has nothing to do with handling updates by itself.

**Comment by timbuckanowski** [comment]
@delivrance thanks for a quick reply.

The solution I went with ended up being quite trivial. 

1. Set the webhook URL. Point it to AWS API gateway. 
`https://api.telegram.org/bot{my_bot_token}/setWebhook?url={url_to_send_updates_to}`

2.  API gateway event triggers the lambda.
Run Pyrogram as a lambda func in sync mode, providing the payload from API Gateway.

I didn't try to catch the event with `CallbackQueryHandler`, can't say if it's gonna wrap the event or not. But either way it's possible to work with incoming JSON messages directly.

**Comment by fenestron** [comment]
Hi @timbuckanowski
Can you please provide a minimal example how did you run pyrogram in lambda?

**Comment by fenestron** [comment]
In addition, I can say that the session file should be created in the `/tmp` folder.
For example, like this:
```
app = Client(
    '/tmp/' + client_name,
    api_id=api_id,
    api_hash=api_hash,
    bot_token=bot_token
)
```

**Comment by timbuckanowski** [comment]
Russkies clearly can't read the API docs and think they outsmart everyone. Go stop the war, enough with your useless advises. 

[Pyrogram supports session strings](https://docs.pyrogram.org/topics/storage-engines?highlight=session%20string#session-strings) that do not require any interaction with persistence at all.



```
from pyrogram import Client

app = Client("my_account")

with app:
    print(app.export_session_string())
```

Exports the session as a string.



Next time, you provide as an argument to `Client` instance and you're good to go.

```from pyrogram import Client

session_string = "...ZnUIFD8jsjXTb8g_vpxx48k1zkov9sapD-tzjz-S4WZv70M..."

with Client(session_string) as app:
    print(app.get_me())
```

**Comment by timbuckanowski** [comment]
![image](https://user-images.githubusercontent.com/83173418/156608594-76e10dfe-7ba2-4a7c-88bb-f49ede45d234.png)
Hey boy, why do you remove the messages like it never happened.
Fkn braindead propaganda minion.
