### ISSUE TITLE
Fails to save session properly

### ISSUE THREAD

**Issue by marvic2409** [pyrogram/pyrogram#909]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Whenever I try to restart my pyrogram program that uses a user account, it fails to load in the session and gives the error code: ```pyrogram.errors.exceptions.unauthorized_401.AuthKeyUnregistered: Telegram says: [401 AUTH_KEY_UNREGISTERED] - The key is not registered in the system. Delete your session file and login again (caused by "updates.GetState")
```

### Steps to reproduce

Login to user account, restart program

### Code example

```python
from pyrogram import Client, filters
app = Client('bot')

app.run()
```

### Logs

```shell
Traceback (most recent call last):
  File "main.py", line 158, in <module>
    app.run()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/utilities/run.py", line 58, in run
    self.start()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/sync.py", line 51, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/utilities/start.py", line 62, in start
    await self.send(raw.functions.updates.GetState())
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 360, in send
    return await self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 330, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.unauthorized_401.AuthKeyUnregistered: Telegram says: [401 AUTH_KEY_UNREGISTERED] - The key is not registered in the system. Delete your session file and login again (caused by "updates.GetState")
```

**Comment by delivrance** [comment]
> Telegram says: [401 AUTH_KEY_UNREGISTERED] - The key is not registered in the system. Delete your session file and login again

> Delete your session file and login again

**Comment by Azizbekdevn1** [comment]
Telegram says: [401 AUTH_KEY_UNREGISTERED] - The key is not registered in the system. Delete your session file and login again

Delete your session file and login again

**Comment by Johnny3951** [comment]
Dear friends, I have exactly the same error but I don't know how to delete  the session file. Can you help me? Please...

**Comment by rainskin** [comment]
> Dear friends, I have exactly the same error but I don't know how to delete the session file. Can you help me? Please...

 This file is creating in your project. 
 pyrogram.Client has a parameter that is responsible for this 
 
 **workdir** (``str``, *optional*):
            _Define a custom working directory.
            The working directory is the location in the filesystem where Pyrogram will store the session files.
            Defaults to the parent directory of the main script._
