### ISSUE TITLE
AttributeError: No API Key found.

### ISSUE THREAD

**Issue by perssBest** [pyrogram/pyrogram#910]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

hello, I started developing my project in telegram, and ran into a problem. At some point, the bot stopped logging in to the API, and in the console it displays an error about an unspecified token. The token is correct, I tried to recreate it - it did not help. I don't understand what could be wrong? If I use your library with a self user (my_account), then everything works fine, and there are no errors about incorrect api id, or hash.

### Steps to reproduce

Take the code from the documentation
Insert your telegram bot token
run it.

### Code example

```python
from pyrogram import Client, filters

client = Client("my_bot", bot_token="521xxxxx8:AAEuexxxxxxxxxxxxxxxxxv2UW8MU")

client.run()
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\nyansterowo\Desktop\tg\src\Client.py", line 6, in <module>
    client.run()
  File "C:\Users\nyansterowo\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\utilities\run.py", line 58, in run
    self.start()
    return loop.run_until_complete(coroutine)
  File "C:\Users\nyansterowo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\nyansterowo\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\utilities\start.py", line 52, in start
    is_authorized = await self.connect()
  File "C:\Users\nyansterowo\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\auth\connect.py", line 38, in connect
    self.load_config()
  File "C:\Users\nyansterowo\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\client.py", line 619, in load_config
    raise AttributeError("No API Key found. More info: https://docs.pyrogram.org/intro/setup")
AttributeError: No API Key found. More info: https://docs.pyrogram.org/intro/setup
```

**Comment by delivrance** [comment]
The error mentioned a specific documentation page you need to read as it explains everything about it.

**Comment by perssBest** [comment]
The specified documentation uses userbot (and I remind you that I have no problems with it), it stops seeing the token when I want to start the bot (my_bot)

**Comment by perssBest** [comment]
although the token is correct and it is specified directly in the code (not even in the config)

**Comment by delivrance** [comment]
It's not about the token, you still need the api key even for bots. Also see https://docs.pyrogram.org/start/auth#bot-authorization.

**Comment by perssBest** [comment]
I threw the code from above, and everything is correct there, which is why I opened this issues.  There can't be an error, working token received from @BotFather
