### ISSUE TITLE
Add Explanation in send_poll mathod

### ISSUE THREAD

**Issue by kinshusharma0412** [pyrogram/pyrogram#915]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

Add explanation so we can send explanation with tha poll...

**Comment by aditya-yadav-27** [comment]
What kind of explanation?

**Comment by kinshusharma0412** [comment]
Like this Explanation so our user can see hint of poll question

**Comment by aditya-yadav-27** [comment]
The feature has already been requested see #850, consider closing this issue
