### ISSUE TITLE
Pyrogram will not receive updates after a while.

### ISSUE THREAD

**Issue by khorammfar** [pyrogram/pyrogram#916]
### Checklist

- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I have a program with several clients
1 client and 3 API robots
After one to three days, the client is deactivated and does not receive any updates, but the robots are well online and active.

### Steps to reproduce

this app just gets the updates

### Code example

```python
from pyrogram import Client, idle

cli = Client("session_name1", api_id, api_hash)
bot1 = Client("session_name2", api_id, api_hash)
bot2 = Client("session_name3", api_id, api_hash)
bot3 = Client("session_name4", api_id, api_hash)

@cli.on_message()
def myhandler(client, message):
    print(message)
 
# doing something with bots that not related with client

# start all Clients
idle()
# and stop ..
```

**Comment by delivrance** [comment]
> After one to three days, the client is deactivated and does not receive any updates, but the robots are well online and active.

This is likely the server deciding to stop sending updates to inactive clients after some while. Bots on the other hand are designed to be online h24 and might not be affected by this.

**Comment by AlexLiuSheng** [comment]
hello，I am using pyrogram user bot  to receive updates. Everything works fine at first, but I can not receive anymore updates  after about 1 day (usually after a night) . It works again only if i reboot client. How to keep client always activate?

**Comment by FanaticExplorer** [comment]
Same. I also have this problem a lot. And even rebooting/resigning doesn't work

**Comment by ZwickVitaly** [comment]
Any caveeats? Same trouble

**Comment by khorammfar** [comment]
This problem was solved by switching to **telethon**, if you don't want to switch to **telethon**, test the pyrogram **fork**s.
