### ISSUE TITLE
file_name attribute missing

### ISSUE THREAD

**Issue by stefanodvx** [pyrogram/pyrogram#919]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Some videos have no file_name attribute

### Steps to reproduce

I dont really know how to reproduce that, you could just print Messagge object of this video and see yourself: https://t.me/pyrogramlounge/571142

**Comment by delivrance** [comment]
`file_name` is optional and seems like the uploader didn't set it.
