### ISSUE TITLE
Got `RuntimeError` after `await Client.stop()`

### ISSUE THREAD

**Issue by KunoiSayami** [pyrogram/pyrogram#921]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Python: 3.10.2
Linux: `5.16.11-arch1-2 #1 SMP PREEMPT Mon, 28 Feb 2022 10:17:30 +0000 x86_64 GNU/Linux`

After start client, calling `Client.stop` will got Runtime error. But it seems works on python version 3.8.2

### Steps to reproduce

Just start and stop client.
But if we specify client argument `no_updates=True`, it work properly.

### Code example

```python
import asyncio
import pyrogram

async def test():
    app = pyrogram.Client(
            'client',
            'api_id',
            'api_hash',
        )
    await app.start()
    await app.stop()

asyncio.run(test())
```

### Logs

```shell
[asyncio] ERROR Task exception was never retrieved (logging output)
future: <Task finished name='Task-2518' coro=<Stop.stop() done, defined at /some/where/.local/lib/python3.10/site-packages/pyrogram/methods/utilities/stop.py:23> exception=RuntimeError("Task <Task pending name='Task-2518' coro=<Stop.stop() running at /some/where/.local/lib/python3.10/site-packages/pyrogram/methods/utilities/stop.py:58> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.10/asyncio/tasks.py:475]> got Future <Task pending name='Task-80' coro=<Dispatcher.handler_worker() running at /some/where/.local/lib/python3.10/site-packages/pyrogram/dispatcher.py:184>> attached to a different loop")>
Traceback (most recent call last):
  File "/some/where/.local/lib/python3.10/site-packages/pyrogram/methods/utilities/stop.py", line 58, in stop
    await do_it()
  File "/some/where/.local/lib/python3.10/site-packages/pyrogram/methods/utilities/stop.py", line 54, in do_it
    await self.terminate()
  File "/some/where/.local/lib/python3.10/site-packages/pyrogram/methods/auth/terminate.py", line 46, in terminate
    await self.dispatcher.stop()
  File "/some/where/.local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 144, in stop
    await i
RuntimeError: Task <Task pending name='Task-2518' coro=<Stop.stop() running at /some/where/.local/lib/python3.10/site-packages/pyrogram/methods/utilities/stop.py:58> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.10/asyncio/tasks.py:475]> got Future <Task pending name='Task-80' coro=<Dispatcher.handler_worker() running at /some/where/.local/lib/python3.10/site-packages/pyrogram/dispatcher.py:184>> attached to a different loop
```

**Comment by delivrance** [comment]
Can't reproduce any issue with the code provided as it works fine with the mentioned Python version. I saw you correctly put the instance creation inside the async function as it should be, not doing so will produce the error shown, so I guess your error comes from a different example that has the instance creation outside of the async function.

**Comment by KunoiSayami** [comment]
Ok, I realize this issue is the same as #391 . I thought this issue was fixed, move `pyrogram.Client` inside function can fix this problem.

**Comment by dshahrokhian** [comment]
For anyone doing a Django integration, using `async with client` instead of `with client` resolved the issue for me.
