### ISSUE TITLE
Forwarding Every new messages of a public channel

### ISSUE THREAD

**Issue by alisaqi** [pyrogram/pyrogram#923]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

Hi, 

I want to write a bot with a program that forwards every single new message of a public channel to me. 

For example, channel "A" posts a new message (this message can be varied on its types), and then my bot should immediately forward this new message to me.

I really appreciate it if you can comment any code sample for this issue.

**Comment by delivrance** [comment]
Hi. This kind of questions are better asked on [StackOverflow](https://stackoverflow.com/questions/ask).
