### ISSUE TITLE
Bots don't need API ID and Hash, but pyrogram doesn't start without them

### ISSUE THREAD

**Issue by malemburg** [pyrogram/pyrogram#927]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Bots only need a bot_token to be set in order to work with the Telegram API, but the current logic in client.load_config() unconditionally requires .api_id and .api_hash to be set and true:

https://github.com/pyrogram/pyrogram/blob/master/pyrogram/client.py#L619

As a work-around, .api_id and .api_hash can be set to "123", but that's not an ideal solution. It would be better to accept only setting the .bot_token.

### Steps to reproduce

Try starting a pyrogram app with only  the bot_token set.

**Comment by delivrance** [comment]
Hi. The API key is a requirement, see https://docs.pyrogram.org/faq/why-is-the-api-key-needed-for-bots.

**Comment by malemburg** [comment]
Hi Dan, have you tried using api_id = 123 and api_hash = '123', together with a valid bot_token ? It works just fine.

**Comment by malemburg** [comment]
Oh, wait... perhaps the .session SQLite database is causing this.
Yup, that still had valid credentials from a session where the API ID and Hash were set.

**Comment by malemburg** [comment]
BTW: Thanks for the great package !

**Comment by delivrance** [comment]
The api_id and api_hash among with the bot token are all required to be valid during new authorizations only. Afterwards, only the api_id is formally required - even though its value seems to be not relevant anymore for the server - and for this reason Pyrogram's current logic keeps asking for the API key (but not the bot token, which can be omitted).

**Comment by malemburg** [comment]
On 05.03.2022 19:07, Dan wrote:> The api_id and api_hash among with the bot
token are all required to be valid
> during new authorizations only. Afterwards, only the api_id is formally required
> - even though its value seems to be not relevant anymore for the server - and
> for this reason Pyrogram's current logic keeps asking for the API key (but not
> the bot token, which can be omitted).

So it's basically enough to just do one run of a bot, have this create
the session database and then stop passing in the details ?

I'm trying to find a way not to put the API key on the server directly.
It would be good to just run the bot to initialize during installation
and then only leave the session database on the server.

-- 
Marc-Andre Lemburg
http://www.malemburg.com/

**Comment by delivrance** [comment]
Yes. Once the session file has been created you can use the workaround you mentioned, for now.

**Comment by malemburg** [comment]
On 05.03.2022 23:05, Dan wrote:
> Yes. Once the session file has been created you can use the workaround you
> mentioned, for now.

Great, that's good to know. Thanks.

-- 
Marc-Andre Lemburg
http://www.malemburg.com/

**Comment by Karl-Han** [comment]
> Yes. Once the session file has been created you can use the workaround you mentioned, for now.

I think it is worthwhile to mention this thread in the Documentation [Authorization](https://docs.pyrogram.org/start/auth) to clarify what does it mean to be: 
> You can now remove the api_id and api_hash values from the code as they are not needed anymore.
