### ISSUE TITLE
 Cannot operate on a closed database.

### ISSUE THREAD

**Issue by AliRezaBeigy** [pyrogram/pyrogram#933]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I config logging with following line:
```python
logging.basicConfig(
			level=logging.WARNING,
			format='%(name)s - %(message)s - %(funcName)s:%(filename)s'
		)
```
and most of the time I get following error
```
asyncio - Task exception was never retrieved
future: <Task finished name='Task-282604' coro=<Client.handle_updates() done, defined at /usr/local/lib/python3.10/site-packages/pyrogram/client.py:528> exception=ProgrammingError('Cannot operate on a closed database.')> - default_exception_handler:base_events.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/client.py", line 530, in handle_updates
    is_min = (await self.fetch_peers(updates.users)) or (await self.fetch_peers(updates.chats))
  File "/usr/local/lib/python3.10/site-packages/pyrogram/client.py", line 496, in fetch_peers
    await self.storage.update_peers(parsed_peers)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/storage/sqlite_storage.py", line 134, in update_peers
    self.conn.executemany(
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

### Steps to reproduce

1. config logging
2. run the bot for a day
3. see what's the output

**Comment by A9FM** [comment]
delete session, and recreate

**Comment by AliRezaBeigy** [comment]
> delete session, and recreate

this solution is wired, developer can't delete session and recreate it on server automatically
