### ISSUE TITLE
Make multiple lines in InlineKeyboardMarkup possible

### ISSUE THREAD

**Issue by n0toose** [pyrogram/pyrogram#935]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

It's not possible to add more than 4-8 buttons on a single "row"/line of an inline keyboard. I'd like to propose the option to break `InlineKeyboardMarkup`s into new lines, especially because `ReplyKeyboardMarkup`s do not have the fine-tuned callback-related capabilities that inline keyboards do.

**Comment by zeroone2numeral2** [comment]
Doesn't this work?

```py
buttons = [
  [  # first row
    InlineKeyboardButton(), InlineKeyboardButton()
  ],
  [  # second row
    InlineKeyboardButton(), InlineKeyboardButton()
  ],
  [  # third row
    InlineKeyboardButton(), InlineKeyboardButton()
  ],
]
reply_markup = InlineKeyboardMarkup(buttons)
```

**Comment by n0toose** [comment]
I most probably messed something up in my code, I'm preemptively closing the issue until I investigate further and I may send in a patch to improve the docs later.
