### ISSUE TITLE
Make it so it would be possible to have image kwargs accept bytes and image url

### ISSUE THREAD

**Issue by lvlahraam** [pyrogram/pyrogram#939]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

image kwargs like the media kwarg in ImageInput
and thumb kwarg in reply_audio

not accepting image urls or bytes, is a weird thing that is not available

please add it, it would be very helpful

**Comment by lvlahraam** [comment]
Bro, even in the docs, for send_audio, it says it accepts bytesio, but when you try it with that, you still get an error and you have to pass a file path...

**Comment by delivrance** [comment]
This wouldn't benefit the library.
Uploading with in-memory files is already supported.

**Comment by lvlahraam** [comment]
It would be easier to use a image without really having to donwloat it bruh... Just BRUH

**Comment by lvlahraam** [comment]
And the other weird thing is, some other methods already accept image urls or even bytes... again why just not make every method that needs an image accept image url or byes, BRUH
