### ISSUE TITLE
Message handler doesn't work when starting bot with asyncio

### ISSUE THREAD

**Issue by tropicoo** [pyrogram/pyrogram#940]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Running pyrogram through asyncio doesn't trigger message handler function.

### Steps to reproduce

1. Run echo-bot example with `main` function in `asyncio` and check logs that handler tasks started.
2. Send some message in the Telegram client and get no response.
3. Run program with `app.run()` instead of `asyncio.run(main())` and check that sent message is echoed back.

### Code example

```python
# Doesn't work
import asyncio
import logging

from pyrogram import Client, filters, idle
from pyrogram.types import Message

log_format = '%(asctime)s - [%(levelname)s] - [%(name)s:%(lineno)s] - %(message)s'
logging.basicConfig(format=log_format)
logging.getLogger().setLevel('INFO')

app = Client(session_name="my_account2", api_id=xxx, api_hash=xxx, bot_token=xxx)


@app.on_message(filters.text & filters.private)
async def echo(client: Client, message: Message) -> None:
    await message.reply(message.text)


async def main():
    await app.start()
    await idle()


asyncio.run(main())

##########################################################################
# This Works
@app.on_message(filters.text & filters.private)
async def echo(client: Client, message: Message) -> None:
    await message.reply(message.text)

app.run()
```
```


### Logs

2022-03-18 20:29:52,083 - [INFO] - [pyrogram.connection.connection:56] - Connecting...
2022-03-18 20:29:52,143 - [INFO] - [pyrogram.connection.connection:63] - Connected! Production DC2 - IPv4 - TCPAbridgedO
2022-03-18 20:29:52,145 - [INFO] - [pyrogram.session.session:272] - NetworkTask started
2022-03-18 20:29:52,317 - [INFO] - [pyrogram.session.internals.msg_id:45] - Time synced: 2022-03-18 18:29:52.121263 UTC
2022-03-18 20:29:52,461 - [INFO] - [pyrogram.session.session:131] - Session initialized: Layer 138
2022-03-18 20:29:52,461 - [INFO] - [pyrogram.session.session:132] - Device: CPython 3.9.10 - Pyrogram 1.4.8
2022-03-18 20:29:52,461 - [INFO] - [pyrogram.session.session:133] - System: Windows 10 (EN)
2022-03-18 20:29:52,461 - [INFO] - [pyrogram.session.session:148] - Session started
2022-03-18 20:29:52,466 - [INFO] - [pyrogram.session.session:250] - PingTask started
2022-03-18 20:29:52,537 - [INFO] - [pyrogram.dispatcher:136] - Started 8 HandlerTasks
```

**Comment by delivrance** [comment]
The usage is wrong, see https://docs.pyrogram.org/start/invoking#using-asyncio-run.

**Comment by tropicoo** [comment]
@delivrance Your example not even working

```python
@app.on_message(filters.text & filters.private)
async def echo(client: Client, message: Message) -> None:
    await message.reply(message.text)


async def main():
    async with app:
        await app.send_message(chat_id=xxx, text="Hi!")


asyncio.run(main())
```
Leads to error:
```shell
RuntimeError: Task <Task pending name='Task-2' coro=<main() running at C:\Users\xxx\bot\tmp2.py:26> cb=[_run_until_complete_cb() at C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py:184]> got Future <Task pending name='Task-24' coro=<Dispatcher.handler_worker() running at C:\Users\xxx\bot\virtualenv\lib\site-packages\pyrogram\dispatcher.py:184>> attached to a different loop
```

**Comment by delivrance** [comment]
You are not following the docs, which are very clear about how things needs to be done when using `asyncio.run`.

**Comment by tropicoo** [comment]
@delivrance I do not see any example in the docs where I can run the program using asyncio and Message Handlers (your example doesn't work - it sends message and crashes, that's not what I need). Please point me how can I run the `Client` instance with bot token which can use Message Handlers.

**Comment by delivrance** [comment]
The examples in the docs work fine, but if you believe there's something not right you can open a specific issue with steps on how to reproduce the problem.

The docs also mention the following:

> ...you can use Python’s asyncio.run() to execute the main function, with one little caveat: the Client instance (and possibly other asyncio resources you are going to use) must be instantiated inside the main function.

You are not instantiating a client inside the main function as described, hence the issues.
Once you do that, you can define and decorate your callback functions inside the main function as well.

**Comment by tropicoo** [comment]
@delivrance Okay, my bad with understanding what was written. Now it works. Thank you for your time and patience.
