### ISSUE TITLE
client.download_media is returning a coroutine not a str or none as the doc says

### ISSUE THREAD

**Issue by ThallyssonKlein** [pyrogram/pyrogram#941]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I'm trying to download a media from a message and getting it path with the following code:

```python
path = client.download_media(message)
```
The doc says this method will return a str or None, but it's returning a coroutine object DownloadMedia.download_media

### Steps to reproduce

1. Install the latest version of the module
2. Try to download the media from a message like this:

```python
@app.on_message()
async def hello(client, message):
    if message.photo:
        path = client.download_media(message)
        print(path)

### Code example

_No response_

### Logs

_No response_

**Comment by delivrance** [comment]
You are not awaiting the coroutine. This is Python/async knowledge, not a library issue.

**Comment by ThallyssonKlein** [comment]
@delivrance wait method was the first thing i tried, and it doesn't change anything
