### ISSUE TITLE
Task error in multi sessions!

### ISSUE THREAD

**Issue by shayanfh** [pyrogram/pyrogram#948]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I have problem in multi sessions , when i call other sessions in the handler, I will have a task error , I think its for async fuctions...

Actually , I am using sync functions!

### Steps to reproduce

When i call other sessions in the handler

### Code example

```python
from pyrogram import Client, filters as Filters, idle

bot = Client(
    session_name='bot'
)

def Handler(client, message):
   accounts=["+989123456789","+989123456787"]
   for account in accounts:
        phone_number = account
        print(phone_number)
    
        app = Client(
            session_name=phone_number,
            phone_number=phone_number,
            api_id=int(config['KEYS']['api_id']),
            api_hash=config['KEYS']['api_hash'],
        )
    
        try:
            app.start()
            app.stop()
        except Exception as e:
            print(e)
            continue


bot.start()
   
my_handler = MessageHandler(
    Handler, Filters.text)
bot.add_handler(my_handler)

idle()
bot.stop()
```

### Logs

```shell
Task <Task pending name='Task-5565' coro=<Stop.stop() running at /usr/local/lib/python3.9/site-packages/pyrogram/methods/utilities/stop.py:58> cb=[_chain_future.<locals>._call_set_state() at /usr/local/lib/python3.9/asyncio/futures.py:391]> got Future <Task pending name='Task-5530' coro=<Dispatcher.handler_worker() running at /usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py:184>> attached to a different loop
```

**Comment by delivrance** [comment]
Hi. The issue section on GitHub is for issues with the library. This is not an issue with the library, but rather an issue with your usage. If you want to ask Pyrogram related questions you can do so on [StackOverflow](https://stackoverflow.com/questions/ask?tags=pyrogram).
