### ISSUE TITLE
When using a proxy, the code does not pass

### ISSUE THREAD

**Issue by izykatsman** [pyrogram/pyrogram#954]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

The code does not come when authorization via the Socks5 proxy is used, the following proxies were used:
- 2gXJH8:BZ853t7s4d:45.139.177.120:3001
- c1G0P2:5gNabH34vR:2.59.50.80:3001
- 4WorQX:zzMdIxm6tW:45.151.145.221:3001

When you delete the proxy login, the code starts coming.

### Steps to reproduce

- Create a client with proxy login.
- Create a connection
- Request a code

### Code example

```python
client = Client(
                session_name=str(phone),
                api_hash="",
                api_id="",
                device_model="1",
                system_version="6.12.0",
                app_version="10 P (28)",
                proxy=dict(
                    hostname=IPpr,
                    port=int(portpr),
                    username=loginpr,
                    password=paspr
                )
            )
await client.connect()
pyro_code = await client.send_code(phone)
await client.sign_in(phone_number=phone, phone_code_hash=hash, phone_code=codes)
```

**Comment by AliRezaBeigy** [comment]
I faced this issue too, when i config proxy app doesn't work anymore

exception:
```  
File "\lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
  File "\lib\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
    await self.load_session()
  File "\lib\site-packages\pyrogram\client.py", line 584, in load_session
    await Auth(
  File "\lib\site-packages\pyrogram\session\auth.py", line 261, in create
    self.connection.close()
  File "\lib\site-packages\pyrogram\connection\connection.py", line 76, in close
    self.protocol.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by Code-Dramatist** [comment]
Happened to me too, man! What a headache!

**Comment by xiaojipi** [comment]
I know how to solve it,you should add a new attribute in proxy dict.
`proxy=dict(scheme="socks5",  hostname=ip, port=port)`

**Comment by delivrance** [comment]
This is a Telegram server behaviour.
