### ISSUE TITLE
edit_date field does not return ISO 8601 string

### ISSUE THREAD

**Issue by bking23** [pyrogram/pyrogram#956]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Currently the Pyrogram API contains a field called `edit_date`. This value contains a date string similar to this one '2021-12-29 15:22:41'.  This date string is not ISO 8601 compliant resulting in incompatibility with third party applications such as Apache Solr. The `edit_date` field needs to be updated to contain a valid ISO 8601 date string.

### Steps to reproduce

1. Search a valid Telegram channel (i.e. client.search_messages() )
2. Print the results
3. Inspect the data to find the `edit_date` field
4. Compare the `edit_date` date string with a valid ISO 8601 date string

**Comment by delivrance** [comment]
Hi. Any date field in Pyrogram's API currently contains an integer unix timestamp as docs explain, which gets rendered in a human-friendly format when printed out. In the next major version this behavior will change and all date fields will be turned into `datetime` objects for a more convenient usage.
