### ISSUE TITLE
add_contacts

### ISSUE THREAD

**Issue by mitya2back** [pyrogram/pyrogram#96]
I try to add contact to my telegram phone book, but  i see that

**TypeError: add_contacts() takes 2 positional arguments but 4 were given**

my code there 
from pyrogram import Client
from pyrogram.api.errors import FloodWait
app = Client(
    "my_account",
    api_id=1***,
    api_hash="*****"
)
phone = '+***'

print(app.add_contacts(phone,'firstname','second name'));

**Comment by delivrance** [comment]
Hi, make sure you [read the docs](https://docs.pyrogram.ml/pyrogram/Client#pyrogram.Client.add_contacts).
