### ISSUE TITLE
What can I do if I just want to listen to the permission change of a group?

### ISSUE THREAD

**Issue by mokeLiu** [pyrogram/pyrogram#963]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

I want to listen to the permission change of a group and send message immediately. But I searched all methods and funcitons in pyrogram. I didn't find a good way to finish it. I tried use the app.get_chat(), but it has a 10s to wait, Can you tell me a way to realize it? Or do I have a alternative way to do so.

**Comment by MrBotDeveloper** [comment]
You can try checking the chat permissions in an fixed interval of time. 

**Like :**

```python
from pyrogram import Client

app = Client() # Set and start your client

chat_id = -100 #Chat Id whom you want to check permissions
permissions = app.get_chat(chat_id).permissions
print(permissions)

# Do what ever you want to do with the permissions
```

**Comment by AlbertEinsteinTG** [comment]
> You can try checking the chat permissions in an fixed interval of time.
> 
> **Like :**
> 
> ```python
> from pyrogram import Client
> 
> app = Client() # Set and start your client
> 
> chat_id = -100 #Chat Id whom you want to check permissions
> permissions = app.get_chat(chat_id).permissions
> print(permissions)
> 
> # Do what ever you want to do with the permissions
> ```

This doesn't help with the problem. The objective was to listen to the permission change in a group. But there aren't any visible service message for that, like that for when a person joins a chat, atleast I think so.

**Comment by MrBotDeveloper** [comment]
> > You can try checking the chat permissions in an fixed interval of time.
> > **Like :**
> > ```python
> > from pyrogram import Client
> > 
> > app = Client() # Set and start your client
> > 
> > chat_id = -100 #Chat Id whom you want to check permissions
> > permissions = app.get_chat(chat_id).permissions
> > print(permissions)
> > 
> > # Do what ever you want to do with the permissions
> > ```
> 
> This doesn't help with the problem. The objective was to listen to the permission change in a group. But there aren't any visible service message for that, like that for when a person joins a chat, atleast I think so.

Yes, no such listener is present in **Pyrogram** (in Telegram also as far as I think) so, my view I think that is the only and best way to do all.

**Comment by mokeLiu** [comment]
> > > You can try checking the chat permissions in an fixed interval of time.
> > > **Like :**
> > > ```python
> > > from pyrogram import Client
> > > 
> > > app = Client() # Set and start your client
> > > 
> > > chat_id = -100 #Chat Id whom you want to check permissions
> > > permissions = app.get_chat(chat_id).permissions
> > > print(permissions)
> > > 
> > > # Do what ever you want to do with the permissions
> > > ```
> > 
> > 
> > This doesn't help with the problem. The objective was to listen to the permission change in a group. But there aren't any visible service message for that, like that for when a person joins a chat, atleast I think so.
> 
> Yes, no such listener is present in **Pyrogram** (in Telegram also as far as I think) so, my view I think that is the only and best way to do all.

I think you are right. I've searched for it for several days. And I think your method is the best way for now. But biggest problem is that the get_app() method has 10s to wait when run it every time. That cause a delay in response. orz...

**Comment by mokeLiu** [comment]
> > > > > You can try checking the chat permissions in an fixed interval of time.
> > > > > **Like :**
> > > > > ```python
> > > > > from pyrogram import Client
> > > > > 
> > > > > app = Client() # Set and start your client
> > > > > 
> > > > > chat_id = -100 #Chat Id whom you want to check permissions
> > > > > permissions = app.get_chat(chat_id).permissions
> > > > > print(permissions)
> > > > > 
> > > > > # Do what ever you want to do with the permissions
> > > > > ```
> > > > 
> > > > 
> > > > This doesn't help with the problem. The objective was to listen to the permission change in a group. But there aren't any visible service message for that, like that for when a person joins a chat, atleast I think so.
> > > 
> > > 
> > > Yes, no such listener is present in **Pyrogram** (in Telegram also as far as I think) so, my view I think that is the only and best way to do all.
> > 
> > 
> > I think you are right. I've searched for it for several days. And I think your method is the best way for now. But biggest problem is that the get_app() method has 10s to wait when run it every time. That cause a delay in response. orz...
> 
> Or you could just listen to some regular Message(s) and check the chat permission by Message.chat.permissions. This way you won't need to use get_chat() everytime.
> 
> ```
> async def listen_msg(_, m: Message):
>     permissions = m.chat.permissions
>     print(permissions)
> ```

good idea. I'll have a try. Thanks.

**Comment by MrBotDeveloper** [comment]
> > > > > You can try checking the chat permissions in an fixed interval of time.
> > > > > **Like :**
> > > > > ```python
> > > > > from pyrogram import Client
> > > > > 
> > > > > app = Client() # Set and start your client
> > > > > 
> > > > > chat_id = -100 #Chat Id whom you want to check permissions
> > > > > permissions = app.get_chat(chat_id).permissions
> > > > > print(permissions)
> > > > > 
> > > > > # Do what ever you want to do with the permissions
> > > > > ```
> > > > 
> > > > 
> > > > This doesn't help with the problem. The objective was to listen to the permission change in a group. But there aren't any visible service message for that, like that for when a person joins a chat, atleast I think so.
> > > 
> > > 
> > > Yes, no such listener is present in **Pyrogram** (in Telegram also as far as I think) so, my view I think that is the only and best way to do all.
> > 
> > 
> > I think you are right. I've searched for it for several days. And I think your method is the best way for now. But biggest problem is that the get_app() method has 10s to wait when run it every time. That cause a delay in response. orz...
> 
> Or you could just listen to some regular Message(s) and check the chat permission by Message.chat.permissions. This way you won't need to use get_chat() everytime.
> 
> ```
> async def listen_msg(_, m: Message):
>     permissions = m.chat.permissions
>     print(permissions)
> ```

Nice way 👍 but will not work if no new messages in the chat...

**Comment by MrBotDeveloper** [comment]
> > > > > You can try checking the chat permissions in an fixed interval of time.
> > > > > **Like :**
> > > > > ```python
> > > > > from pyrogram import Client
> > > > > 
> > > > > app = Client() # Set and start your client
> > > > > 
> > > > > chat_id = -100 #Chat Id whom you want to check permissions
> > > > > permissions = app.get_chat(chat_id).permissions
> > > > > print(permissions)
> > > > > 
> > > > > # Do what ever you want to do with the permissions
> > > > > ```
> > > > 
> > > > 
> > > > This doesn't help with the problem. The objective was to listen to the permission change in a group. But there aren't any visible service message for that, like that for when a person joins a chat, atleast I think so.
> > > 
> > > 
> > > Yes, no such listener is present in **Pyrogram** (in Telegram also as far as I think) so, my view I think that is the only and best way to do all.
> > 
> > 
> > I think you are right. I've searched for it for several days. And I think your method is the best way for now. But biggest problem is that the get_app() method has 10s to wait when run it every time. That cause a delay in response. orz...
> 
> Or you could just listen to some regular Message(s) and check the chat permission by Message.chat.permissions. This way you won't need to use get_chat() everytime.
> 
> ```
> async def listen_msg(_, m: Message):
>     permissions = m.chat.permissions
>     print(permissions)
> ```

Nice 👍 idea
