### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by gabiruh** [pyrogram/pyrogram#97]
```
2018-07-19 16:01:55,109 'utf-16-le' codec can't decode bytes in position 206-207: illegal UTF-16 surrogate
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/client/dispatcher/dispatcher.py", line 148, in update_worker
    chats
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/client/ext/utils.py", line 586, in parse_messages
    m.text.markdown = client.markdown.unparse(*args)
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/client/style/markdown.py", line 141, in unparse
    return utils.remove_surrogates(message)
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/client/style/utils.py", line 37, in remove_surrogates
    return text.encode("utf-16", "surrogatepass").decode("utf-16")
```

**Comment by delivrance** [comment]
@gabiruh Hi, can you give me instructions on how to reproduce this?

**Comment by Too-Naive** [comment]
Same error in Too-Naive/Things-Forward-telegram#2
I think you can add a parameter `errors='ignore'` when calling `.decode()`.
Or setting an option allows the user to choose how to handle it in this case.

**Comment by Too-Naive** [comment]
I have the wrong function at `pyrogram.client.types.bots.InlineKeyboardButton`
I solved this problem with the following steps:
Make a copy of  `pyrogram.client.types.bots.InlineKeyboardButton.read` function, like this:
```py
def read(b, *args):
	if isinstance(b, KeyboardButtonUrl):
		return InlineKeyboardButton(
			text=b.text,
			url=b.url
		)

	if isinstance(b, KeyboardButtonCallback):
		return InlineKeyboardButton(
			text=b.text,
			callback_data=b.data.decode(errors='ignore')
		)

	if isinstance(b, KeyboardButtonSwitchInline):
		if b.same_peer:
			return InlineKeyboardButton(
				text=b.text,
				switch_inline_query_current_chat=b.query
			)
		else:
			return InlineKeyboardButton(
				text=b.text,
				switch_inline_query=b.query
			)
```
Then in main function, after import `pyrogram`, Add the following line:
```py
import pyrogram.client.types.bots
setattr(pyrogram.client.types.bots.InlineKeyboardButton, 'read', read)
```
It works for me.

**Comment by delivrance** [comment]
Hi @Too-Naive. Your error is similar, but you are actually receiving it in a different place. @gabiruh's error is coming from a text message (or media caption) while yours is from an inline button callback data.

I'd like to test this myself, so any info on how to reproduce the issue is welcome. Ignoring decoding errors in callbacks data might not be an ideal solution because you are actually losing some info this way.

**Comment by delivrance** [comment]
@gabiruh Feel free to open again once you have some examples showing how to reproduce this.
