### ISSUE TITLE
pyrogram sample

### ISSUE THREAD

**Issue by xiberman** [pyrogram/pyrogram#98]
hi all, i'm newbie  in python.
this documentation about pyrogram is poor(https://docs.pyrogram.ml/)
where  can i found samples about using function and types of this api?
for example how can i get channel list and channel information in this api.
thanks.

**Comment by Dangeres** [comment]
in first - check examples(https://github.com/pyrogram/pyrogram/tree/develop/examples)
in second - check this link(https://docs.pyrogram.ml/functions/)

**Comment by xiberman** [comment]
Dear Dangeres, 
but i read that docs and however seems good but it can't help me. 
thanks

**Comment by delivrance** [comment]
> where can i found samples about using function and types of this api?

Do also check this: https://docs.pyrogram.ml/start/Usage#raw-functions
