### ISSUE TITLE
`message.reactions` behaves in a strange way

### ISSUE THREAD

**Issue by evgfilim1** [pyrogram/pyrogram#983]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones: #924 might be related
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I'm trying to get all reactions of the message, but they're either not updated or updated only once I first try to get message reactions. Reproducible in ~~1.4 and~~ 2.0.

![image](https://user-images.githubusercontent.com/17182159/166150752-c9e38b12-819b-460a-a3fa-1dd3afd307d2.png)

### Steps to reproduce

1. Send `.reactions` in reply to any message;
2. React to that message;
3. Send `.reactions` in reply to that message.

### Code example

```python
from pyrogram import Client, filters
from pyrogram.handlers import MessageHandler
from pyrogram.types import Message

# Put your own creds here
API_ID = 0
API_HASH = ''

async def get_reactions(_: Client, message: Message) -> None:
    rs = message.reply_to_message.reactions
    if not rs:
        await message.edit("<i>No reactions</i>")
        return
    await message.edit("\n".join(f"<code>{r.emoji}</code>: {r.count}" for r in rs))

def main():
    app = Client("account", API_ID, API_HASH)
    app.add_handler(MessageHandler(get_reactions, filters.command("reactions", prefixes=".")))
    app.run()

if __name__ == "__main__":
    main()
```

### Logs

_Not applicable_

**Comment by aditya-yadav-27** [comment]
Ah man, I have also been puzzled for a day and now figured out that you are checking reaction for the message you sent, not for the message you replied lmao 😂 and you get no reactions bcoz the message you sent isnt reacted

**Comment by evgfilim1** [comment]
> Ah man, I had also been puzzled for a day and now figured out that you are checking reaction for the message you sent, not for the message you replied lmao joy and you get no reactions bcoz the message you sent isnt reacted, consider closing this :D

@aditya-yadav-27 Sorry, code mistype in MRE, I had this issue in my userbot, let me re-check and edit issue description.

**Comment by aditya-yadav-27** [comment]
sorry I can't reproduce this

**Comment by delivrance** [comment]
This is a server behavior, not a library issue. See https://docs.pyrogram.org/telegram/functions/messages/get-messages-reactions and https://docs.pyrogram.org/telegram/functions/messages/get-message-reactions-list for ways to get the reactions of one or more messages.

**Comment by evgfilim1** [comment]
@delivrance Thanks for the answer, I'm already doing this in my userbot, it really helps.

**Comment by hykilpikonna** [comment]
> This is a server behavior, not a library issue. See https://docs.pyrogram.org/telegram/functions/messages/get-messages-reactions and https://docs.pyrogram.org/telegram/functions/messages/get-message-reactions-list for ways to get the reactions of one or more messages.

How should I call this? `GetMessageReactions` seems like a class, and the only reaction-related function in `Client` is `send_reaction`...

**Comment by delivrance** [comment]
Those are raw API methods and have their own way of invocation, see https://docs.pyrogram.org/topics/advanced-usage.

**Comment by hykilpikonna** [comment]
> Those are raw API methods and have their own way of invocation, see https://docs.pyrogram.org/topics/advanced-usage.

Works, thanks!
