### ISSUE TITLE
Path return after cancelling download 

### ISSUE THREAD

**Issue by anasty17** [pyrogram/pyrogram#987]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [ ] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

hi hope everything is well 
There is a bug in cancelling download. As we know on success the download return the path of the downloaded file and if cancelled using stop_transmisson in progress it will return None. But now after update it returns the path on both success and cancel

### Steps to reproduce

Cancel video download and check return

**Comment by delivrance** [comment]
Fixed.
