### ISSUE TITLE
Inf while

### ISSUE THREAD

**Issue by Dangeres** [pyrogram/pyrogram#99]
If i will write code like that i will be inside infinity circle and i cant see line after running.
How to solve that problem(im stupid)?

```
from pyrogram import Client

app = Client(
    session_name="example",
    api_id = #,
    api_hash = '#',
    proxy=dict(
        hostname="192.169.232.12",
        port=49980,
    )
)

print('start auth')
app.run()

print('okay')
app.send_message("me", "Hi there! I'm using **Pyrogram**")
```

**Comment by Dangeres** [comment]
i got shitty proxy, but problem is stable. 
![image](https://user-images.githubusercontent.com/5412293/43023830-d9fd4ebc-8c74-11e8-966b-befac68f5063.png)

**Comment by Dangeres** [comment]
@delivrance, help please.

**Comment by delivrance** [comment]
@Dangeres Hi, looks like `app.run()` confuses you a bit.

`app.run()` is used when you deal with [updates](https://docs.pyrogram.ml/resources/UpdateHandling) only and you don't need to execute any procedural action in your script. If you want to do something and then stop you have to wrap your code inside `app.start()` and `app.stop()`.

Example using your snippet:

``` python
from pyrogram import Client

app = Client(
    session_name="example",
    api_id = #,
    api_hash = '#',
    proxy=dict(
        hostname="192.169.232.12",
        port=49980,
    )
)

print('start auth')

app.start()

print('okay')
app.send_message("me", "Hi there! I'm using **Pyrogram**")

app.stop()
```

**Comment by Dangeres** [comment]
Can i use run and start together? If it's possible - can you get me an example? As example i want upset bot that will print "hello world" to someone and in that program need to get history messages. And i have a question about raw function. What does it mean param "q" (https://docs.pyrogram.ml/functions/channels/GetAdminLog)?

**Comment by delivrance** [comment]
**Next time, for different questions [open new Issues](new). Or better, you can join [@PyrogramChat](https://t.me/pyrogramchat) and ask our community.**

---

It doesn't make any sense to use `run()` and `start()` together, simply because `run()` is just a shortcut for `start()` and `idle()`:

https://github.com/pyrogram/pyrogram/blob/0c96fa8b7cd4a7f22bceacf12c85d5f68770db98/pyrogram/client/client.py#L324-L332

`q` stands for "query", and is a search term. You want something like this:

``` python
from pyrogram import Client
from pyrogram.api import functions, types

app = Client(...)

app.start()

app.send_message("username", "hello world")

r = app.send(
    functions.channels.GetAdminLog(
        channel=app.resolve_peer("username"),
        q="",
        events_filter=types.ChannelAdminLogEventsFilter(),
        max_id=0,
        min_id=0,
        limit=10
    )
)

print(r)

app.stop()
```
