### ISSUE TITLE
Client object has no attribute 'set_username' 

### ISSUE THREAD

**Issue by md5hash16** [pyrogram/pyrogram#996]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

i am using pyrogram 2.0.24 all methods set photo, delete photo got no Attribute

### Steps to reproduce

connect client
set username

### Code example

```python
app = Client(....).start()

with app:
  app.set_username('new username")
```

### Logs

```shell
'Client' object has no attribute 'set_username'
```

**Comment by OxMohsen** [comment]
I use the following code and it's working without any problem:
```python
import asyncio
from pyrogram import Client

async def main():
    async with Client("oxmohsen") as app:
        await app.set_username("RandomString")


asyncio.run(main())

```

**Comment by delivrance** [comment]
You are running a different version.
